force-app/main/default/objects/Application_Log__c.object
<CustomObject>
    <fields>
        <fullName>Integration_Name__c</fullName>
        <label>Integration Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Upsert</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Application Log</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_BuyingPerformanceDailyTOP__c.object
<CustomObject>
    <description>TOP Daily Buying Performance</description>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <formula>Customer__r.AccountNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingDate__c</fullName>
        <description>Billing Date</description>
        <label>Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BillingType__c</fullName>
        <label>Billing Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BillingType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BillingYearMonth__c</fullName>
        <label>Billing Date (Year-Month)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractLineItemReport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Line Item Report</label>
        <referenceTo>C360_ContractLineItemReport__c</referenceTo>
        <relationshipLabel>Daily Buying Performance</relationshipLabel>
        <relationshipName>Daily_Buying_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company Name</description>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>TOP_Daily_Buying_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DistributionChannel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>C360_Product__c</referenceTo>
        <relationshipName>TOP_Daily_Buying_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuantityMT__c</fullName>
        <label>Quantity (MT)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <description>Sales Organization</description>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Salesunit__c</fullName>
        <label>Sales unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit</valueSetName>
        </valueSet>
    </fields>
    <label>Daily Buying Performance</label>
    <nameField>
        <displayFormat>BPD{00000000}</displayFormat>
        <label>Daily Buying Performance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_Contract__c.object
<CustomObject>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SalesOrganization__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DistributionChannel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MasterContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Contract</label>
        <referenceTo>C360_Contract__c</referenceTo>
        <relationshipLabel>Contract</relationshipLabel>
        <relationshipName>Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SoldTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold-To Party</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sold To</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Ship To</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contract (Sold-To Party)</relationshipLabel>
        <relationshipName>Contract1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>SFCT{0000000}</displayFormat>
        <label>SF Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_ContractLineItem__c.object
<CustomObject>
    <fields>
        <fullName>ContractVolumeUOM__c</fullName>
        <label>Contract Volume UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContractVolume__c</fullName>
        <label>Contract Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>C360_Contract__c</referenceTo>
        <relationshipLabel>Contract Line Item</relationshipLabel>
        <relationshipName>Contract_Line_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <formula>Text(Contract__r.DistributionChannel__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Distribution Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <externalId>true</externalId>
        <label>Key</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>C360_Product__c.DeletionMark__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>C360_Product__c</referenceTo>
        <relationshipLabel>Contract Line Item</relationshipLabel>
        <relationshipName>Contract_Line_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesUnit__c</fullName>
        <label>Sales Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>VolumeAllocationMTConversion__c</fullName>
        <description>Use for TPX Labix report</description>
        <label>Volume Allocation (MT) Conversion</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VolumeLiftingMTReport__c</fullName>
        <description>Use only in TPX Labix report</description>
        <label>Volume Lifting (MT)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <displayFormat>SFCTI{0000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_ContractLineItemReport__c.object
<CustomObject>
    <fields>
        <fullName>BillingDateMonthYearReport__c</fullName>
        <description>Defualt Date as 1st date of every month use in Report TPX/LAbix</description>
        <label>Billing Date (Month/Year)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BillingYearMonth__c</fullName>
        <description>Billing Date  group(Year-Month)</description>
        <label>Billing Date (Year-Month)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractStartDate__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractVolumeUOM__c</fullName>
        <label>Contract Volume UOM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContractVolume__c</fullName>
        <label>Contract Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DistributionChannel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <externalId>true</externalId>
        <label>Key</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>C360_Product__c</referenceTo>
        <relationshipLabel>Contract Line Item Report</relationshipLabel>
        <relationshipName>Contract_Line_Item_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SoldTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold-To Party</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contract Line Item Report</relationshipLabel>
        <relationshipName>Contract_Line_Item_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VolumeAllocationMTConversion__c</fullName>
        <label>Volume Allocation (MT) Conversion</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VolumeLiftingMTReport__c</fullName>
        <label>Volume Lifting (MT)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Contract Line Item Report</label>
    <nameField>
        <displayFormat>SFCTIR{0000000}</displayFormat>
        <label>Contract Line Item Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_Product__c.object
<CustomObject>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <externalId>true</externalId>
        <label>Material Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C360Integration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Yesterday__c</fullName>
        <description>For migration</description>
        <label>Yesterday</label>
        <type>DateTime</type>
    </fields>
    <label>C360Integration</label>
</CustomObject>

force-app/main/default/globalValueSets/DistributionChannel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>10-Domestic Major Oil</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11-Domestic Third Party</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12-Domestic TOP Group</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>13-Domestic Other</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>14-Domestic User/Blnder</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>15-Domestic Trade/Resel</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>16-Domestic</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>17-Free Tax Zone</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20-Export Direct</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>21-Export Indirect</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>22-Export Free Zone</label>
    </customValue>
    <customValue>
        <fullName>23</fullName>
        <label>23-Exp Direct Trading</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>24-Exp Indirect Trading</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>25-Export</label>
    </customValue>
    <customValue>
        <fullName>26</fullName>
        <label>26-Export Direct Broker</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>30-Import (VAT)</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>31-Import Indirect(VAT)</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>32-Import (Non-VAT)</label>
    </customValue>
    <customValue>
        <fullName>33</fullName>
        <label>33-Import Indirect(NonV</label>
    </customValue>
    <customValue>
        <fullName>IC</fullName>
        <label>IC-Intra-comp. Transfer</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <isActive>false</isActive>
        <label>01</label>
    </customValue>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SalesOrganization.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1100</fullName>
        <label>1100-Thai Oil</label>
    </customValue>
    <customValue>
        <fullName>1300</fullName>
        <label>1300-Thai Paraxylene</label>
    </customValue>
    <customValue>
        <fullName>1400</fullName>
        <label>1400-Thai Lube Base</label>
    </customValue>
    <customValue>
        <fullName>1700</fullName>
        <label>1700-LABIX</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <label>2000-TOP NEXT International Company Limited</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <label>9100-TOP SOLVENT VIETNAM</label>
    </customValue>
    <customValue>
        <fullName>9200</fullName>
        <label>9200-PT.TIRTA SURYA RAYA</label>
    </customValue>
    <customValue>
        <fullName>9300</fullName>
        <label>9300-JSKem Pte Ltd</label>
    </customValue>
    <customValue>
        <fullName>9400</fullName>
        <label>9400-TSChem</label>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
        <isActive>false</isActive>
        <label>0001</label>
    </customValue>
    <masterLabel>Sales Organization</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/C360_ReportBuyingDailySummary.cls
public class C360_ReportBuyingDailySummary {
 	public static void sumBuyingDailyMonthYear(){
        integer whMonth;
        integer whYear;
        DateTime yesterday;
        C360Integration__c c360Integration = C360Integration__c.getInstance();
        yesterday = (c360Integration.Yesterday__c != null)? c360Integration.Yesterday__c : System.Today().addDays(-1);
        if(c360Integration.Yesterday__c != null){
            whMonth = yesterday.month();
            whYear = yesterday.Year();
        }else{    
            whMonth =Date.Today().Month();
            whYear = Date.Today().Year();
        }
 //1.create Mapping ContractLineItem Summary by:sum(ContractVolume__c) ============================================================================= =============== =============== 
        List<string> SelectItemMonthYear = new List<string>(); 
        SelectItemMonthYear.add('Contract__r.SalesOrganization__c');
        SelectItemMonthYear.add('Contract__r.DistributionChannel__c');
        SelectItemMonthYear.add('Contract__r.SoldTo__r.AccountNumber__c');
        SelectItemMonthYear.add('Product__c');
        SelectItemMonthYear.add('Product__r.MaterialCode__c');
        SelectItemMonthYear.add('calendar_month(Contract__r.ContractStartDate__c) StartMonth');
        SelectItemMonthYear.add('calendar_year(Contract__r.ContractStartDate__c) StartYear');
        SelectItemMonthYear.add('sum(ContractVolume__c) ContractVolume');
        SelectItemMonthYear.add('ContractVolumeUOM__c');
        String WhereConditionMonthYear ='Where Contract__r.SalesOrganization__c in(\'1300\' ,\'1700\') and Contract__r.DistributionChannel__c <>\'\' and Product__c<>null and Contract__r.ContractStartDate__c<>null and calendar_month(Contract__r.ContractStartDate__c)='+whMonth+' and calendar_year(Contract__r.ContractStartDate__c)='+whYear; 
        String groupbyMonthYear =' group by Contract__r.SalesOrganization__c, Contract__r.DistributionChannel__c,Contract__r.SoldTo__r.AccountNumber__c,Product__c,Product__r.MaterialCode__c,ContractVolumeUOM__c,calendar_month(Contract__r.ContractStartDate__c),calendar_year(Contract__r.ContractStartDate__c)';
        String queryMonthYear ='Select '+ string.join(SelectItemMonthYear,',') +' From C360_ContractLineItem__c '+WhereConditionMonthYear + groupbyMonthYear;    
        List<sObject> sobjcontractItemSummaryListMonthYear = Database.query(queryMonthYear);
        string contractStartDate ='';
        string KeyMap ='';
        map<String,decimal>contractVolumeMap = new map<String,decimal>();
        if(sobjcontractItemSummaryListMonthYear.size()>0){        
            for(sObject conItemMY : sobjcontractItemSummaryListMonthYear){ 
                KeyMap =String.valueOf(conItemMY.get('SalesOrganization__c'))+'_'+String.valueOf(conItemMY.get('DistributionChannel__c'))+'_'+String.valueOf(conItemMY.get('AccountNumber__c'))+'_'+String.valueOf(conItemMY.get('MaterialCode__c'))+'_'+String.valueOf(conItemMY.get('ContractVolumeUOM__c'))+'_'+String.valueOf(conItemMY.get('StartYear'))+'-'+String.valueOf(conItemMY.get('StartMonth')); 
                if(String.isNotBlank(String.valueOf(conItemMY.get('ContractVolume')))){
                    contractVolumeMap.put(KeyMap, decimal.valueof(String.valueOf(conItemMY.get('ContractVolume'))));
                }
            }
        }     
//2.Summary BuyingPerformanceDaily แล้วเอาไป  upsert muj object contractLineItemReport โดยจะ mapping เอาค่า sum(contract volume ) จากข้อ1มาinsertด้วย=============================================================================    
       	List<string> SelectItem = new List<string>(); 
         SelectItem.add('SalesOrganization__c');
         SelectItem.add('DistributionChannel__c');
         SelectItem.add('Customer__c');
         SelectItem.add('Customer__r.AccountNumber__c');
         SelectItem.add('Product__c');
         SelectItem.add('Product__r.MaterialCode__c');
         SelectItem.add('calendar_month(BillingDate__c) BillingStartMonth');
         SelectItem.add('calendar_year(BillingDate__c) BillingStartYear');
         SelectItem.add('Salesunit__c');
         SelectItem.add('sum(QuantityMT__c) sumQuantityMT ');
        String groupBy =' group by SalesOrganization__c, DistributionChannel__c,Customer__c,Customer__r.AccountNumber__c,calendar_month(BillingDate__c),calendar_year(BillingDate__c),Product__c,Product__r.MaterialCode__c,Salesunit__c';
  		String whereCon ='where  calendar_month(BillingDate__c)='+whMonth+' and calendar_year(BillingDate__c)='+whYear+' and SalesOrganization__c in(\'1300\',\'1700\') and BillingType__c<>\'Z2C1\' and BillingType__c<>\'Z6C1\' and BillingDate__c <> null and Customer__c <> null and Product__c<> null and Salesunit__c <> null';
       	String query ='Select '+ string.join(SelectItem,',') +' from C360_BuyingPerformanceDailyTOP__c ' + whereCon + groupBy;
         List<C360_ContractLineItemReport__c>upsertContractLineItemReport = new List<C360_ContractLineItemReport__c>();
         List<sObject> objBuyingDailyList = Database.query(query);
         if(objBuyingDailyList.size()>0){
            for(sObject obdaily : objBuyingDailyList){
                C360_ContractLineItemReport__c objContItemRpt = new C360_ContractLineItemReport__c();
                String KeyRecord ='';
                KeyRecord = String.valueOf(obdaily.get('SalesOrganization__c'))+'_'+String.valueOf(obdaily.get('DistributionChannel__c'))+'_'+String.valueOf(obdaily.get('AccountNumber__c'))+'_'+String.valueOf(obdaily.get('MaterialCode__c'))+'_'+String.valueOf(obdaily.get('Salesunit__c'))+'_'+String.valueOf(obdaily.get('BillingStartYear')) +'-'+String.valueOf(obdaily.get('BillingStartMonth'));
                objContItemRpt.Key__c =	KeyRecord;
                objContItemRpt.BillingYearMonth__c = String.valueOf(obdaily.get('BillingStartMonth'))=='10'||String.valueOf(obdaily.get('BillingStartMonth'))=='11'|| String.valueOf(obdaily.get('BillingStartMonth'))=='12'? String.valueOf(obdaily.get('BillingStartYear')) +'-'+String.valueOf(obdaily.get('BillingStartMonth')) : String.valueOf(obdaily.get('BillingStartYear')) +'-0'+String.valueOf(obdaily.get('BillingStartMonth'));    
                objContItemRpt.BillingDateMonthYearReport__c = date.valueOf(String.valueOf(obdaily.get('BillingStartYear')) +'-'+String.valueOf(obdaily.get('BillingStartMonth'))+'-1');
                objContItemRpt.SalesOrganization__c =  String.isNotBlank(String.valueOf(obdaily.get('SalesOrganization__c')))? String.valueOf(obdaily.get('SalesOrganization__c')) : '';
                objContItemRpt.DistributionChannel__c = String.isNotBlank(String.valueOf(obdaily.get('DistributionChannel__c')))? String.valueOf(obdaily.get('DistributionChannel__c')) : '';
                objContItemRpt.SoldTo__c =String.isNotBlank(String.valueOf(obdaily.get('Customer__c')))? String.valueOf(obdaily.get('Customer__c')) : '';
                objContItemRpt.Product__c = String.isNotBlank(String.valueOf(obdaily.get('Product__c')))? String.valueOf(obdaily.get('Product__c')) : '';
                objContItemRpt.VolumeLiftingMTReport__c = String.isNotBlank(String.valueOf(obdaily.get('sumQuantityMT')))? decimal.valueOf(String.valueOf(obdaily.get('sumQuantityMT'))) : 0 ;
                objContItemRpt.ContractVolumeUOM__c= String.isNotBlank(String.valueOf(obdaily.get('Salesunit__c')))? String.valueOf(obdaily.get('Salesunit__c')) : '';
                if(String.isNotBlank(String.valueOf(contractVolumeMap.get(KeyRecord)))){
                    objContItemRpt.ContractVolume__c = contractVolumeMap.get(KeyRecord);
                }else{
                    objContItemRpt.ContractVolume__c = 0;
                    objContItemRpt.VolumeAllocationMTConversion__c = 0;
                }	
              upsertContractLineItemReport.add(objContItemRpt);
            }  
         } 
         List <Database.upsertResult>acc_resultList = new List<Database.upsertResult>(); 
        if(upsertContractLineItemReport.size()> 0){         
            Schema.SObjectField ContractLineItemReportKey = C360_ContractLineItemReport__c.Fields.Key__c;
            acc_resultList= Database.upsert(upsertContractLineItemReport, ContractLineItemReportKey, false); 
            if(acc_resultList.size() > 0)
            {
                List<String>accIdList_suc = new List<String>();
                List<String>acc_errorMsg_List = new List<String>();
                map<String,List<String>>acc_errorMap = new map<String,List<String>>();
                
                for (Integer idx = 0; idx < acc_resultList.size(); idx++) 
                {
                    if (acc_resultList[idx].isSuccess()){
                        accIdList_suc.add(acc_resultList[idx].getId()); 
                    }else{
                        acc_errorMsg_List = new List<String>();
                        for(Database.Error err : acc_resultList[idx].getErrors()){
                            acc_errorMsg_List.add('Field:'+err.getFields()+': '+err.getMessage());
                        }
                        acc_errorMap.put(acc_resultList[idx].getId(),acc_errorMsg_List);
                    }
                }
                if(acc_errorMsg_List.size() > 0){
                    Application_Log__c log = new Application_Log__c();
                    log.Method__c = 'Upsert';
                    log.Integration_Name__c = 'Replicated ContractLineItemReport';
                    log.Log_Type__c = 'Error';
                    log.Message_Type__c = 'Fail';
                    log.OwnerId = UserInfo.getUserId();
                }else{
                    //3.จะMapping ContractLineItemRepor with Perfomance daily = และ update BuyingPerfomancedaily object next step========================================================================
                    //====ถ้า Insert  จะมา  update Perfomance daily next step============================================================================================================                      
                    List<String> KeyReportList = new List<String>();
                    map<String,String>BuyingDailyMapIDcontract = getConcractID();
                    string keyConcractID = '';
                    List<C360_BuyingPerformanceDailyTOP__c>updateBuyingDailyList = new List<C360_BuyingPerformanceDailyTOP__c>();
                    list<C360_BuyingPerformanceDailyTOP__c>selectBuyingDailyList = [select id,KeyReport__c,BillingDate__c from C360_BuyingPerformanceDailyTOP__c                                                        where  SalesOrganization__c in('1300','1700') and BillingDate__c <> null and ContractLineItemReport__c = null  and calendar_year(BillingDate__c)=:whYear and calendar_month(BillingDate__c)=:whMonth ];
                    for(C360_BuyingPerformanceDailyTOP__c BuyingDailyItem :selectBuyingDailyList){
                        keyConcractID = BuyingDailyItem.KeyReport__c +'_'+ String.valueOf(BuyingDailyItem.BillingDate__c).substring(0,4)+'-'+BuyingDailyItem.BillingDate__c.month();
                        KeyReportList.add(BuyingDailyItem.KeyReport__c);
                        C360_BuyingPerformanceDailyTOP__c objBuyingPerformanceDaily = new C360_BuyingPerformanceDailyTOP__c();
                        objBuyingPerformanceDaily.BillingYearMonth__c= String.valueOf(BuyingDailyItem.BillingDate__c.month())=='10'||String.valueOf(BuyingDailyItem.BillingDate__c.month())=='11'||String.valueOf(BuyingDailyItem.BillingDate__c.month())=='12'? String.valueOf(BuyingDailyItem.BillingDate__c).substring(0,4)+'-'+BuyingDailyItem.BillingDate__c.month() : String.valueOf(BuyingDailyItem.BillingDate__c).substring(0,4)+'-0'+BuyingDailyItem.BillingDate__c.month();
                        objBuyingPerformanceDaily.ContractLineItemReport__c = String.isNotBlank(String.valueOf(BuyingDailyMapIDcontract.get(keyConcractID)))? BuyingDailyMapIDcontract.get(keyConcractID) : '';  
                        objBuyingPerformanceDaily.id = BuyingDailyItem.id;//BuyingDailyMapID.get(String.valueOf(sobjcontractRpt.get('KeyReport__c')));
                        updateBuyingDailyList.add(objBuyingPerformanceDaily); 
                    }
                    if(updateBuyingDailyList.size() > 0){  
                        update updateBuyingDailyList;
                    } /**/
                    //====ถ้า Insert  จะมา  update Perfomance daily next step============================================================================================================ 
                }
            }
        }
     }   
    
    public static Map<string,string> getConcractID(){
        string ConcractID = '';  
        map<String,String>ConcractIDMap = new map<String,String>();
        List<C360_ContractLineItemReport__c> queryContractRtp =[Select id, Key__c,KeyReport__c From C360_ContractLineItemReport__c]; 
        for(C360_ContractLineItemReport__c sobjcontractRpt :queryContractRtp){
            ConcractIDMap.put(sobjcontractRpt.Key__c , sobjcontractRpt.id);
        } 
        return ConcractIDMap;
    }  
}