force-app/main/default/objects/Application_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>- Job UID; SAP Integration</inlineHelpText>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Integration_Name__c</fullName>
        <label>Integration Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message_Type__c</fullName>
        <label>Message Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Upsert</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Response_Body__c</fullName>
        <label>SAP Response Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Application Log</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_FinancialInfo__c.object
<CustomObject>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <formula>CompanyName__r.AccountNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyCode__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CompanyCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CompanyName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Info</relationshipLabel>
        <relationshipName>Financial_Info</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CreditBalance__c</fullName>
        <label>Credit Balance (Not Use)</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CreditControlArea__c</fullName>
        <label>Credit Control Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CreditControlArea</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CreditLimit__c</fullName>
        <label>Credit Limit</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Currency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <externalId>true</externalId>
        <label>Key</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Outstanding__c</fullName>
        <label>Outstanding (credit exposure)</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Financial Info</label>
    <nameField>
        <displayFormat>FI-{0000000}</displayFormat>
        <label>Financial Info Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/CompanyCode.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1100</fullName>
        <label>Thai Oil Public Co.,Ltd (1100)</label>
    </customValue>
    <customValue>
        <fullName>1200</fullName>
        <label>Thaioil Power Co.,Ltd (1200)</label>
    </customValue>
    <customValue>
        <fullName>1300</fullName>
        <label>Thai Paraxylene Co.,Ltd. (1300)</label>
    </customValue>
    <customValue>
        <fullName>1400</fullName>
        <label>Thai Lube Base PLC. (1400)</label>
    </customValue>
    <customValue>
        <fullName>1500</fullName>
        <label>Independent Power Co.,Ltd (1500)</label>
    </customValue>
    <customValue>
        <fullName>1600</fullName>
        <label>Thaioil Energy Services (1600)</label>
    </customValue>
    <customValue>
        <fullName>1700</fullName>
        <label>LABIX Company Limited (1700)</label>
    </customValue>
    <customValue>
        <fullName>1800</fullName>
        <label>TOP SPP Company Limited (1800)</label>
    </customValue>
    <customValue>
        <fullName>1900</fullName>
        <label>Thaioil Marine Co.,Ltd. (1900)</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <label>TOP NEXT International Company Limited (2000)</label>
    </customValue>
    <customValue>
        <fullName>2100</fullName>
        <label>Thaioil Treasury Center (2100)</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <label>TOP Solvent Vietnam (9100)</label>
    </customValue>
    <customValue>
        <fullName>9200</fullName>
        <label>PT.TIRTA SURYA RAYA (9200)</label>
    </customValue>
    <customValue>
        <fullName>9300</fullName>
        <label>JSKem Pte Ltd (9300)</label>
    </customValue>
    <customValue>
        <fullName>9400</fullName>
        <label>TSChem (9400)</label>
    </customValue>
    <masterLabel>Company Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/C360_BApiFinancialInfoHelper.cls
public with sharing class C360_BApiFinancialInfoHelper{
    class FinancialInfoToSAP {
        String KUNNR;//Account Number
        String BUKRS;//Company Code
        String KKBER;//Credit Control Area
        Decimal KLIMK;//Credit Limit
        Decimal ABSBT;//Credit Balance
        Decimal OBLIG;//Outstanding
        String CASHC;//Currency__c
        String CRBLB;//Indicator__c
    }
    public class dto_response extends WebServiceExtend.dto_response{
        public Result result {get;set;}
    }
    public static dto_response parse(String json){
        return (dto_response) System.JSON.deserialize(json, dto_response.class);
    }
    public static dto_response execute(String endpoint, Map<String, Object> result){
        dto_response responseDTO = new dto_response();
        Application_Log__c applog = new Application_Log__c(
            External_ID__c = String.valueOf(result.get('gateway_id')),
            Integration_Name__c = 'BAPI_FINANCIAL_INFO',
            Method__c = 'Create',
            Message_Type__c = 'Success',
            SAP_Response_Body__c = JSON.serialize(result).abbreviate(90000)
        );
        try{
            String requestBody = String.valueOf(JSON.serialize(result.get('results')));
            List<object> FinancialInfoList = (List<Object>)JSON.deserializeUntyped(requestBody);
            List<FinancialInfoToSAP> ResultList = new List <FinancialInfoToSAP>();
            for(Object obj : FinancialInfoList){
                String jsonSTR = JSON.serialize(obj);
                Map<String,Object> temp = (Map<String,Object>)JSON.deserializeUntyped(jsonSTR);
                FinancialInfoToSAP TempResult = new FinancialInfoToSAP();
                TempResult.KUNNR = removeLeadingZeros((string)temp.get('KUNNR'));
                TempResult.BUKRS = (string)temp.get('BUKRS');
                TempResult.KKBER = (string)temp.get('KKBER');
                TempResult.KLIMK = Decimal.valueOf((string)temp.get('KLIMK'));
                TempResult.ABSBT = Decimal.valueOf((string)temp.get('ABSBT'));
                TempResult.OBLIG = Decimal.valueOf((string)temp.get('OBLIG'));
                TempResult.CASHC = (string)temp.get('CASHC');
                TempResult.CRBLB = (string)temp.get('CRBLB');
                ResultList.add(TempResult);
            }
            list<String> accSAP = new List <string>();
            for(FinancialInfoToSAP iFinancialinfo : ResultList){
                accSAP.add(iFinancialinfo.KUNNR);
            }
            list<Account>AccList = [select id,AccountNumber__c from Account where AccountNumber__c in :accSAP];
            Map<String, string> accSFId = new Map<String, string>();
            for(Account iAcc : AccList){
                accSFId.put(iAcc.AccountNumber__c, iAcc.id);
            }
            List<C360_FinancialInfo__c> FinanceInfoList = new List<C360_FinancialInfo__c>();
            for(FinancialInfoToSAP iFinancialInfoToSAP : ResultList){
                C360_FinancialInfo__c thisFinanceInfo = new C360_FinancialInfo__c();
                if(iFinancialInfoToSAP.BUKRS.substring(0, 2)==iFinancialInfoToSAP.KKBER.substring(0, 2)){
                    thisFinanceInfo.Key__c = iFinancialInfoToSAP.KUNNR + iFinancialInfoToSAP.BUKRS + iFinancialInfoToSAP.KKBER;
                    thisFinanceInfo.CompanyName__c = accSFId.get(iFinancialInfoToSAP.KUNNR);
                    thisFinanceInfo.CompanyCode__c = iFinancialInfoToSAP.BUKRS;
                    thisFinanceInfo.CreditControlArea__c = iFinancialInfoToSAP.KKBER;
                    thisFinanceInfo.CreditLimit__c = iFinancialInfoToSAP.KLIMK;
                    thisFinanceInfo.CreditBalance__c = iFinancialInfoToSAP.ABSBT;
                    thisFinanceInfo.Outstanding__c = iFinancialInfoToSAP.OBLIG;
                    thisFinanceInfo.Currency__c = iFinancialInfoToSAP.CASHC;
                    thisFinanceInfo.Indicator__c = (iFinancialInfoToSAP.CRBLB == 'X') ? True : False;
                    FinanceInfoList.add(thisFinanceInfo);
                }
            }
            upsert FinanceInfoList Key__c;
            ApplicationLogUtils.saveLogInbound(endpoint, applog);
            responseDTO = dto_response.parse(
                JSON.serialize(
                    new Map<String, Object>{
                        'description' => new Map<String, Object>{
						'success' => FinanceInfoList.size() > 0,
						'message' => FinanceInfoList.size() > 0 ? '' : 'Not found Financial Information'
						}
                    }
                )
            );
        }catch (Exception e){
            responseDTO = dto_response.parse(
                JSON.serialize(
                    new Map<String, Object>{
                        'description' => new Map<String, Object>{ 'success' => false, 'message' => e.getMessage() },
                        'result' => new Map<String, Object>{ 'data' => new List<Object>() }
                    }
                )
            );
            applog.Message_Type__c = 'Fail';
            applog.Error_Message__c = e.getMessage();
            applog.SAP_Response_Body__c = JSON.serialize(result).abbreviate(90000);
            ApplicationLogUtils.saveLogInbound(endpoint, applog);
        }
        return responseDTO;
    }
    static String removeLeadingZeros(String num){
        for(integer i=0;i<num.length();i++){
            if(num.charAt(i)!=48){
                String res = num.substring(i);
                return res;
            }
        }
        return '0';
    }
}