force-app/main/default/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Application Log</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Integration_Message__c</fullName>
        <label>Integration Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Requested Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>System_Status_Text__c</fullName>
        <defaultValue>&apos;CRTD&apos;</defaultValue>
        <label>System Status Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Status__c</fullName>
        <label>User Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/THOR_BApiOrderHelperTest.cls
@isTest
public class THOR_BApiOrderHelperTest 
{

    @isTest
    public static void executeTest()
    {
        Order__c o = new Order__c();
        o.Name = 'Test';
        insert o;
        
        String jsonSTR = '{     "Order__c": {         "Id": "'+o.id+'",         "Name": "Success",         "System_Status_Text__c": "Success",         "User_Status__c": "Success",         "Requested_Date__c": "2021-11-03",         "Integration_Status__c": "Success",         "Integration_Message__c": "test call"     },     "uuid": "2304a315-9df9-42c8-99a6-ca656ad759cb" }';
        Map<String, Object> response_value = (Map<String, Object>)JSON.deserializeUntyped(jsonSTR);        
        
        Test.startTest(); 
        THOR_BApiOrderHelper.execute('order_endpoint',response_value);
        Test.stopTest();
        
        List<Order__c> upsertedOrder = [select id,System_Status_Text__c from Order__c];
        
        system.assert(upsertedOrder[0].System_Status_Text__c == 'Success');
    }
    
    @isTest
    public static void executeTest_Error()
    {
        Order__c o = new Order__c();
        o.Name = 'Test';
        insert o;
        
        String jsonSTR = '{     "Order__c": {         "Id": "'+o.id+'",         "Name": "Success",         "System_Status_Text__c": "Success",         "User_Status__c": "Success",         "Requested_Date__c": "2021-1103",         "Integration_Status__c": "Success",         "Integration_Message__c": "test call"     },     "uuid": "2304a315-9df9-42c8-99a6-ca656ad759cb" }';
        Map<String, Object> response_value = (Map<String, Object>)JSON.deserializeUntyped(jsonSTR);        
        
        Test.startTest(); 
        THOR_BApiOrderHelper.execute('order_endpoint',response_value);
        Test.stopTest();
        
        List<Application_Log__c> logList = [select id from Application_Log__c];
        
        system.assert(logList.size() > 0);
    }
}