force-app/main/default/objects/Application_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Integration_Name__c</fullName>
        <label>Integration Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Log_Type__c</fullName>
        <label>Log Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message_Type__c</fullName>
        <label>Message Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Upsert</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Response_Body__c</fullName>
        <label>Response Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Application Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Application Log</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_Product__c.object
<CustomObject>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <externalId>true</externalId>
        <label>Material Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_ProductSalesArea__c.object
<CustomObject>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <description>Distribution Channel</description>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DistributionChannel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>External ID</description>
        <externalId>true</externalId>
        <label>Key</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarkForDelete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mark for delete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <description>Plant</description>
        <label>Plant</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product Name</description>
        <label>Product Name</label>
        <referenceTo>C360_Product__c</referenceTo>
        <relationshipLabel>Product Sales Area</relationshipLabel>
        <relationshipName>Product_Sales_Area</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <description>Sales Organization</description>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <label>Product Sales Area</label>
    <nameField>
        <label>Product Sales Area Nunber</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/DistributionChannel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>10-Domestic Major Oil</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11-Domestic Third Party</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12-Domestic TOP Group</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>13-Domestic Other</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>14-Domestic User/Blnder</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>15-Domestic Trade/Resel</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>16-Domestic</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>17-Free Tax Zone</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20-Export Direct</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>21-Export Indirect</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>22-Export Free Zone</label>
    </customValue>
    <customValue>
        <fullName>23</fullName>
        <label>23-Exp Direct Trading</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>24-Exp Indirect Trading</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>25-Export</label>
    </customValue>
    <customValue>
        <fullName>26</fullName>
        <label>26-Export Direct Broker</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>30-Import (VAT)</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>31-Import Indirect(VAT)</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>32-Import (Non-VAT)</label>
    </customValue>
    <customValue>
        <fullName>33</fullName>
        <label>33-Import Indirect(NonV</label>
    </customValue>
    <customValue>
        <fullName>IC</fullName>
        <label>IC-Intra-comp. Transfer</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <isActive>false</isActive>
        <label>01</label>
    </customValue>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SalesOrganization.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1100</fullName>
        <label>1100-Thai Oil</label>
    </customValue>
    <customValue>
        <fullName>1300</fullName>
        <label>1300-Thai Paraxylene</label>
    </customValue>
    <customValue>
        <fullName>1400</fullName>
        <label>1400-Thai Lube Base</label>
    </customValue>
    <customValue>
        <fullName>1700</fullName>
        <label>1700-LABIX</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <label>2000-TOP NEXT International Company Limited</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <label>9100-TOP SOLVENT VIETNAM</label>
    </customValue>
    <customValue>
        <fullName>9200</fullName>
        <label>9200-PT.TIRTA SURYA RAYA</label>
    </customValue>
    <customValue>
        <fullName>9300</fullName>
        <label>9300-JSKem Pte Ltd</label>
    </customValue>
    <customValue>
        <fullName>9400</fullName>
        <label>9400-TSChem</label>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
        <isActive>false</isActive>
        <label>0001</label>
    </customValue>
    <masterLabel>Sales Organization</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/C360_productSalesareaBatch.cls
public without sharing class C360_productSalesareaBatch implements Database.Batchable<Object>,Database.AllowsCallouts,Database.Stateful{
    public Iterable<Object> start(Database.BatchableContext BC) {
        String respone = C360_CalloutBIService.calloutBI('ProductArea');
        Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(respone);
        List<Object> rs = (List<Object>) ((Map<String, Object>) results.get('d')).get('results');
        //system.debug(': Heap size is ' + limits.getHeapSize() + ' enforced is ' + limits.getLimitHeapSize());
        return rs;
    }
    public void execute(Database.BatchableContext BC, List<Object> scope){
        List<C360_CalloutBIService.prdSalesarea> ProductAreaList = (List<C360_CalloutBIService.prdSalesarea>) JSON.deserialize(JSON.serialize(scope),List<C360_CalloutBIService.prdSalesarea>.class);
        List<Database.upsertResult> productArea_resultList = new List<Database.upsertResult>();
        List<Application_Log__c> insertApplogList = new List<Application_Log__c>();
        List<C360_ProductSalesArea__c> upsertProductAreaList = new List<C360_ProductSalesArea__c>();
        List<String> productList = new List<String>();
        try{
            for(C360_CalloutBIService.prdSalesarea prdSalesarea : ProductAreaList){
                productList.add(prdSalesarea.A0MAT_SALES);
            }
            //=====Mapping Product=============================
            List<C360_Product__c> insertProductList = [select id, MaterialCode__c from C360_Product__c Where MaterialCode__c in:(productList)];
            Map<String,String> ProductMap = new Map<String,String>();
            for(C360_Product__c prdItem : insertProductList ){
                ProductMap.put(prdItem.MaterialCode__c, prdItem.id);
            }
            //===End====Mapping Product Master=============================
            for(C360_CalloutBIService.prdSalesarea prdSalesarea : ProductAreaList){
                C360_ProductSalesArea__c upsertProductArea = new C360_ProductSalesArea__c();
                if(prdSalesarea.A0MAT_SALES != '' && prdSalesarea.A0MAT_SALES != null){
                    if(productMap.get(prdSalesarea.A0MAT_SALES) != '' && productMap.get(prdSalesarea.A0MAT_SALES) != null){
                        upsertProductArea.Product__c = productMap.get(prdSalesarea.A0MAT_SALES);
                        if(prdSalesarea.A0SALESORG != '' && prdSalesarea.A0SALESORG != null && prdSalesarea.A0DISTR_CHAN != '' && prdSalesarea.A0DISTR_CHAN != null){
                            upsertProductArea.Name = prdSalesarea.A0MAT_SALES +' '+ prdSalesarea.A0SALESORG +' '+ prdSalesarea.A0DISTR_CHAN;
                            String prdSalesareaExtId = prdSalesarea.A0MAT_SALES + prdSalesarea.A0SALESORG + prdSalesarea.A0DISTR_CHAN;
                            upsertProductArea.Key__c =prdSalesareaExtId;
                        }
                        upsertProductArea.SalesOrganization__c = prdSalesarea.A0SALESORG;
                        upsertProductArea.DistributionChannel__c = prdSalesarea.A0DISTR_CHAN;
                        upsertProductArea.Plant__c = prdSalesarea.A0MAT_SALES_ZDWERK;
                        if(prdSalesarea.A0DEL_FLAG != '' && prdSalesarea.A0DEL_FLAG != null){
                            upsertProductArea.MarkForDelete__c = true;
                        }else{
                            upsertProductArea.MarkForDelete__c = False;
                        }
                        upsertProductAreaList.add(upsertProductArea);
                    }
                }
            }
            if(upsertProductAreaList.size()> 0){
                Schema.SObjectField ProductAreaKey = C360_ProductSalesArea__c.Fields.Key__c;
                ProductArea_resultList = Database.upsert(upsertProductAreaList, ProductAreaKey, false);
                if(ProductArea_resultList.size() > 0){
                    List<String> ProductIdList_suc = new List<String>();
                    List<String> ProductArea_errorMsg_List = new List<String>();
                    Map<String,List<String>> ProductArea_errorMap = new Map<String,List<String>>();
                    for(Integer idx = 0; idx < ProductArea_resultList.size(); idx++){
                        if(ProductArea_resultList[idx].isSuccess()){
                            ProductIdList_suc.add(ProductArea_resultList[idx].getId());
                        }else{
                            ProductArea_errorMsg_List = new List<String>();
                            for(Database.Error err : ProductArea_resultList[idx].getErrors()){
                                ProductArea_errorMsg_List.add('Field:'+err.getFields()+': '+err.getMessage());
                            }
                        }
                        ProductArea_errorMap.put(ProductArea_resultList[idx].getId(),ProductArea_errorMsg_List);
                    }
                    if(ProductArea_errorMsg_List.size() > 0){
                        Application_Log__c log = new Application_Log__c();
                        log.Method__c = 'Upsert';
                        log.Integration_Name__c = 'C360 Replicated ProductSalesArea Webservice';
                        log.Log_Type__c = 'Error';
                        log.Message_Type__c = 'Fail';
                        log.Response_Body__c = JSON.serialize(scope).abbreviate(131000);
                        log.Error_Message__c = 'ProductSalesArea - '+ProductArea_errorMap.keyset()+' : '+ProductArea_errorMap.values();
                        log.OwnerId = UserInfo.getUserId();
                        insertApplogList.add(log);
                    }else{
                        Application_Log__c log = new Application_Log__c();
                        log.Method__c = 'Upsert';
                        log.Integration_Name__c = 'C360 Replicated ProductSalesArea Webservice';
                        log.Log_Type__c = 'Success';
                        log.Message_Type__c = 'Success';
                        log.Response_Body__c = JSON.serialize(scope).abbreviate(131000);
                        log.Error_Message__c = 'ProductSalesArea - Success';
                        log.OwnerId = UserInfo.getUserId();
                        insertApplogList.add(log);
                    }
                }
            }
            Map<String,Set<String>> MapSalesOrgIdList = getProductSalesareaMap();
            list<C360_Product__c> mtProductList = [select id,MaterialCode__c from C360_Product__c Where MaterialCode__c in:(productList)];
            List<C360_Product__c> upsertProductList = new List<C360_Product__c>();
            for(C360_Product__c prdItem : mtProductList ){
                C360_Product__c upsertProduct = new C360_Product__c();upsertProduct.id = prdItem.id;
                upsertProductList.add(upsertProduct);
            }
            if(upsertProductList.size()>0){
                update upsertProductList;
            }
        }catch (Exception e){
            Application_Log__c log = new Application_Log__c();
            log.Method__c = 'Upsert';
            log.Integration_Name__c = 'C360 Replicated ProductSalesAre Webservice';
            log.Log_Type__c = 'Error';
            log.Message_Type__c = 'Fail';
            log.Response_Body__c = JSON.serialize(scope).abbreviate(131000);
            log.OwnerId = UserInfo.getUserId();
            insertApplogList.add(log);
        }
        if(insertApplogList.size() > 0){
            insert insertApplogList;
        }
    }
    public void finish(Database.BatchableContext BC){}
    public static string getProductSalesarea(string productId){
        List<string> prodId= new List<string>();
        prodId.add(productId);
        List<string> prodList= new List<string>();
        List<C360_ProductSalesArea__c> prdAreatList = [SELECT Product__c,SalesOrganization__c FROM C360_ProductSalesArea__c WHERE Product__c in:prodId and SalesOrganization__c <> null order by SalesOrganization__c asc];
        for(C360_ProductSalesArea__c areaitem : prdAreatList){
            if(!prodList.contains(areaitem.SalesOrganization__c)){
                prodList.add(areaitem.SalesOrganization__c);
            }
        }
        string proSalesOrg = string.join(prodList, ',' );
        return proSalesOrg;
    }
    public static map<string,Set<String>> getProductSalesareaMap(){
        Map<String,Set<String>> salesOrgMap = new Map<String,Set<String>>();
        List<C360_ProductSalesArea__c> prdAreatList = [SELECT Product__c,SalesOrganization__c FROM C360_ProductSalesArea__c WHERE SalesOrganization__c <> null order by SalesOrganization__c asc];
        for(C360_ProductSalesArea__c i: prdAreatList){
            if(salesOrgMap.containskey(i.Product__c)){
                Set<string> salesOrgList = salesOrgMap.get(i.Product__c);
                salesOrgList.add(i.SalesOrganization__c);
            }else{
                Set<string> salesOrgList = new Set<String>();
                salesOrgList.add(i.SalesOrganization__c);
                salesOrgMap.put(i.Product__c,salesOrgList);
            }
        }
        return salesOrgMap;
     }
}