force-app/main/default/objects/C360_BuyingPerformanceDailyTOP__c.object
<CustomObject>
    <description>TOP Daily Buying Performance</description>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <formula>Customer__r.AccountNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BilledQuantity__c</fullName>
        <label>Billed Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BillingDate__c</fullName>
        <description>Billing Date</description>
        <label>Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPtargetNetProfitUSD__c</fullName>
        <label>CP target Net Profit (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CPtargetVolume__c</fullName>
        <label>CP target Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company Name</description>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>TOP_Daily_Buying_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DistributionChannel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NetProfitUSD__c</fullName>
        <label>Net Profit (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Name</label>
        <referenceTo>C360_Product__c</referenceTo>
        <relationshipName>TOP_Daily_Buying_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuantityL30__c</fullName>
        <description>Quantity (L30)</description>
        <label>Quantity (L30)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuantityMT__c</fullName>
        <label>Quantity (MT)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <description>Sales Organization</description>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Salesgroup__c</fullName>
        <label>Sales Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesGroup</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Salesunit__c</fullName>
        <label>Sales unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalTHB__c</fullName>
        <label>Total (THB)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalUSD__c</fullName>
        <label>Total (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Daily Buying Performance</label>
    <nameField>
        <displayFormat>BPD{00000000}</displayFormat>
        <label>Daily Buying Performance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <recordTypes>
        <fullName>DailyPerformance</fullName>
        <active>true</active>
        <description>TLB TPX LABIX</description>
        <label>Daily Performance</label>
    </recordTypes>
    <recordTypes>
        <fullName>TXDailyPerformance</fullName>
        <active>true</active>
        <description>TSTH TSV TSR TSChem TSJSKem</description>
        <label>TX Daily Performance</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_BuyingPerformanceMonthlyTOP__c.object
<CustomObject>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <description>From BI</description>
        <label>Business Unit</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPtargetNetProfitUSD__c</fullName>
        <label>CP target Net Profit (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CPtargetVolume__c</fullName>
        <description>From BI</description>
        <label>CP target Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Monthly Lifting and Allocation</relationshipLabel>
        <relationshipName>TOP_Month_Buying_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DistributionChannel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LastYearQuantity__c</fullName>
        <description>From BI</description>
        <label>Last Year Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <description>Month</description>
        <label>Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NetProfitUSD__c</fullName>
        <description>From BI</description>
        <label>Net Profit (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product Name</description>
        <label>Product Name</label>
        <referenceTo>C360_Product__c</referenceTo>
        <relationshipName>TOP_Month_Buying_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesGroup__c</fullName>
        <label>Sales Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesGroup</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>From SAP</description>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Monthly Buying Performance</label>
    <nameField>
        <displayFormat>BPM{00000000}</displayFormat>
        <label>Monthly Buying Performance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <recordTypes>
        <fullName>TXMonthlyPerformance</fullName>
        <active>true</active>
        <description>TS Group</description>
        <label>TX Monthly Performance</label>
    </recordTypes>
    <recordTypes>
        <fullName>TXTargetMonthlyPerformance</fullName>
        <active>true</active>
        <description>TS Group</description>
        <label>TX Target Monthly Performance</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_Contract__c.object
<CustomObject>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SalesOrganization__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>DistributionChannel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <displayFormat>SFCT{0000000}</displayFormat>
        <label>SF Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_ContractLineItem__c.object
<CustomObject>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <formula>Text(Contract__r.DistributionChannel__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Distribution Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <externalId>true</externalId>
        <label>Key</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>C360_Product__c.DeletionMark__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>C360_Product__c</referenceTo>
        <relationshipLabel>Contract Line Item</relationshipLabel>
        <relationshipName>Contract_Line_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesUnit__c</fullName>
        <label>Sales Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Unit</valueSetName>
        </valueSet>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <displayFormat>SFCTI{0000000}</displayFormat>
        <label>Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_Product__c.object
<CustomObject>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <externalId>true</externalId>
        <label>Material Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_SalesArea__c.object
<CustomObject>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Area</relationshipLabel>
        <relationshipName>Sales_Area</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillingDate__c</fullName>
        <description>Invoice Customer</description>
        <label>Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DistributionChannel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>Sales area External id</description>
        <externalId>true</externalId>
        <label>Key</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesGroup__c</fullName>
        <description>Sales Group</description>
        <label>Sales Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesGroup</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <label>Sales Area</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Sales Area Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C360Integration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>DeletedBatchSize__c</fullName>
        <description>For use delete Daily Buying Performance (Job Clear data Schedule)</description>
        <label>Deleted Batch Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DeletedDays__c</fullName>
        <description>For use delete Daily Buying Performance (Job Clear data Schedule)</description>
        <label>Deleted Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>C360Integration</label>
</CustomObject>

force-app/main/default/globalValueSets/DistributionChannel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>10-Domestic Major Oil</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11-Domestic Third Party</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12-Domestic TOP Group</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>13-Domestic Other</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>14-Domestic User/Blnder</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>15-Domestic Trade/Resel</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>16-Domestic</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>17-Free Tax Zone</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20-Export Direct</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>21-Export Indirect</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>22-Export Free Zone</label>
    </customValue>
    <customValue>
        <fullName>23</fullName>
        <label>23-Exp Direct Trading</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>24-Exp Indirect Trading</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>25-Export</label>
    </customValue>
    <customValue>
        <fullName>26</fullName>
        <label>26-Export Direct Broker</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>30-Import (VAT)</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>31-Import Indirect(VAT)</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>32-Import (Non-VAT)</label>
    </customValue>
    <customValue>
        <fullName>33</fullName>
        <label>33-Import Indirect(NonV</label>
    </customValue>
    <customValue>
        <fullName>IC</fullName>
        <label>IC-Intra-comp. Transfer</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <isActive>false</isActive>
        <label>01</label>
    </customValue>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SalesOrganization.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1100</fullName>
        <label>1100-Thai Oil</label>
    </customValue>
    <customValue>
        <fullName>1300</fullName>
        <label>1300-Thai Paraxylene</label>
    </customValue>
    <customValue>
        <fullName>1400</fullName>
        <label>1400-Thai Lube Base</label>
    </customValue>
    <customValue>
        <fullName>1700</fullName>
        <label>1700-LABIX</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <label>2000-TOP NEXT International Company Limited</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <label>9100-TOP SOLVENT VIETNAM</label>
    </customValue>
    <customValue>
        <fullName>9200</fullName>
        <label>9200-PT.TIRTA SURYA RAYA</label>
    </customValue>
    <customValue>
        <fullName>9300</fullName>
        <label>9300-JSKem Pte Ltd</label>
    </customValue>
    <customValue>
        <fullName>9400</fullName>
        <label>9400-TSChem</label>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
        <isActive>false</isActive>
        <label>0001</label>
    </customValue>
    <masterLabel>Sales Organization</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/C360_ReportBuyingPerformanceTest.cls
@isTest
public class C360_ReportBuyingPerformanceTest {
	 @TestSetup
    static void setup() {
        C360Integration__c Integrate = new C360Integration__c();
        Integrate.DeletedDays__c= 1;
        Integrate.DeletedBatchSize__c = 200;
        insert Integrate;
        
   
        Id accRecordTypeId = [select id from RecordType where DeveloperName = 'SoldTo'].Id;
          
        List<Account> accList = new List<Account>();
        Account a1 = new Account(AccountNumber__c='302', Name='A', RecordTypeId = accRecordTypeId);
        Account a2 = new Account(AccountNumber__c='1', Name='A1', RecordTypeId = accRecordTypeId, TOPSOLVENTTH__c=true);
        Account a3 = new Account(AccountNumber__c='2', Name='A2', RecordTypeId = accRecordTypeId, TOPSOLVENTVN__c=true);
        accList.add(a1);
        accList.add(a2);
        accList.add(a3);
        insert accList;
    //========================Sales Area=========================================================================================================================================================================================
  
    List<C360_SalesArea__c> areaList = new List<C360_SalesArea__c>();
 			
               C360_SalesArea__c SalesArea1 = new C360_SalesArea__c(
                AccountNumber__c  = accList[0].id,
                SalesGroup__c='TD1',
                SalesOrganization__c='2000');
       		 areaList.add(SalesArea1);
        C360_SalesArea__c SalesArea2 = new C360_SalesArea__c(
                AccountNumber__c  = accList[0].id,
                SalesGroup__c='TD1',
                SalesOrganization__c='9100');
            
			areaList.add(SalesArea2);    
        insert  areaList;
     //===================End=====Sales Area=========================================================================================================================================================================================
                  
        List<C360_Product__c> productMasterList = new List<C360_Product__c>();
        C360_Product__c pdm1 = new C360_Product__c(MaterialCode__c ='m001', Name ='product name1');
        productMasterList.add(pdm1);
        
        insert productMasterList;
        
        DateTime yesterday;
        
        Id RecordTypeId = [select id from RecordType where DeveloperName = 'TXDailyPerformance'].Id;
        Id RecordTypeIdDailyPer = [select id from RecordType where DeveloperName = 'DailyPerformance'].Id;
       
        List<C360_BuyingPerformanceDailyTOP__c > BuyingPerformanceList = new List<C360_BuyingPerformanceDailyTOP__c >();
        for (Integer i=0;i<20;i++) {
            yesterday = System.Today().addDays(-i);
            if(i<=7){
                C360_BuyingPerformanceDailyTOP__c BuyingPerformance = new C360_BuyingPerformanceDailyTOP__c(
                RecordTypeId = RecordTypeId,
                Key__c = 'by-'+i,
                Customer__c  = accList[0].id,
                Product__c= productMasterList[0].id,
                BillingDate__c =Date.valueOf(yesterday),
                SalesOrganization__c='1300',
                DistributionChannel__c='10',
                BilledQuantity__c=10,
        		QuantityL30__c=10,
                TotalTHB__c =10,
                TotalUSD__c =10,
                Salesunit__c='BBL',
                QuantityMT__c=30);
                BuyingPerformanceList.add(BuyingPerformance);
                
            }else if(i>7 && i< 15){
                C360_BuyingPerformanceDailyTOP__c BuyingPer1300 = new C360_BuyingPerformanceDailyTOP__c(
                RecordTypeId = RecordTypeIdDailyPer,
                Key__c = 'by-'+i,
                Customer__c  = accList[0].id,
                Product__c= productMasterList[0].id,
                BillingDate__c =Date.valueOf(yesterday),
                SalesOrganization__c='1300',
                DistributionChannel__c='10',
                BilledQuantity__c=10,
        		QuantityL30__c=10,
                TotalTHB__c =10,
                TotalUSD__c =10,
                Salesunit__c='BBL',
                QuantityMT__c=30);
                BuyingPerformanceList.add(BuyingPer1300);
              }else if(i>= 15){
                C360_BuyingPerformanceDailyTOP__c BuyingPer1700 = new C360_BuyingPerformanceDailyTOP__c(
                RecordTypeId = RecordTypeIdDailyPer,
                Key__c = 'by-'+i,
                Customer__c  = accList[0].id,
                Product__c= productMasterList[0].id,
                BillingDate__c =Date.valueOf(yesterday),
                SalesOrganization__c='1700',
                DistributionChannel__c='10',
                Salesunit__c='BBL',
                BilledQuantity__c=10,
        		QuantityL30__c=10,
                TotalTHB__c =10,
                TotalUSD__c =10,
                QuantityMT__c=30);
                BuyingPerformanceList.add(BuyingPer1700);
            }
        }
        insert BuyingPerformanceList;
  //========================Buying Monthhly=========================================================================================================================================================================================
    Id RecordTypeIdTx = [select id from RecordType where DeveloperName = 'TXMonthlyPerformance'].Id;    
     
    List<C360_BuyingPerformanceMonthlyTOP__c > BuyingMonthList = new List<C360_BuyingPerformanceMonthlyTOP__c>();
        for (Integer i=0;i<12;i++) {
          
               C360_BuyingPerformanceMonthlyTOP__c BuyingMonthlyTOP = new C360_BuyingPerformanceMonthlyTOP__c(
                RecordTypeId = RecordTypeIdTx,
                Key__c = 'by-'+i,
                Customer__c  = accList[0].id,
                Product__c= productMasterList[0].id,
                BusinessUnit__c='BBL',
                Year__c='2022',
                Month__c='2',
                SalesGroup__c='TD1',
                SalesOrganization__c='2000',
                DistributionChannel__c='10',
                CPtargetNetProfitUSD__c =0,
                NetProfitUSD__c =0,
                LastYearQuantity__c =0,
                CPtargetVolume__c =0,
                Volume__c =0,
                LastYearPocketmarginUSD__c =0,
                CPtargetPocketMarginUSD__c =0,
                PocketmarginUSD__c =0,
                CumLYNetProfitUSD__c =0,
                CumCPtargetNetProfitUSD__c =0,
                CumNetProfitUSD__c =0,
                CumLastYearVolume__c =0,
                CumCPTargetVolume__c =0,
                CumVolume__c =0,
                CumLYPocketmarginUSD__c =0,
                CumCPtargetPocketMarginUSD__c =0,
                CumPocketmarginUSD__c =0,
      		    LastYearMonthlyPocketmarginLocal__c =0,
			    LastYearMonthlyPocketmarginUSD__c=30
               );
              BuyingMonthList.add(BuyingMonthlyTOP);
            
            if(i>10){
                 C360_BuyingPerformanceMonthlyTOP__c BuyingMonthlyTOPNull = new C360_BuyingPerformanceMonthlyTOP__c(
                RecordTypeId = RecordTypeIdTx,
                Key__c = 'bynull-'+i,
                Customer__c  = accList[0].id,
                Product__c= productMasterList[0].id,
                BusinessUnit__c='BBL',
                Year__c='2022',
                Month__c=''+i,
                SalesGroup__c='TD1',
                SalesOrganization__c='9100',
                DistributionChannel__c='16'
               );
              BuyingMonthList.add(BuyingMonthlyTOPNull);
                
            }
        }
          insert BuyingMonthList;
         List<C360_BuyingPerformanceMonthlyTOP__c > BuyingMonthTargerList = new List<C360_BuyingPerformanceMonthlyTOP__c>();
       Id RecordTypeIdTarget = [select id from RecordType where DeveloperName = 'TXTargetMonthlyPerformance'].Id; 
       for (Integer n=0;n<12;n++) {
           if(n>10){
               C360_BuyingPerformanceMonthlyTOP__c BuyingMonthlyTaregt = new C360_BuyingPerformanceMonthlyTOP__c(
                RecordTypeId = RecordTypeIdTarget,
                Key__c = 'byTG-'+n,
                Customer__c  = accList[0].id,
                Product__c= productMasterList[0].id,
                BusinessUnit__c='BBL',
                Year__c='2022',
                Month__c= String.valueOf(n),
                SalesGroup__c='TD1',
                SalesOrganization__c='2000',
                DistributionChannel__c='10',
                CPtargetNetProfitUSD__c=10,
               
                CumCPtargetNetProfitUSD__c=10,
                CumCPTargetVolume__c=10,
                CumCPtargetPocketMarginUSD__c=10
               );
              BuyingMonthTargerList.add(BuyingMonthlyTaregt);
           }else{
               
              C360_BuyingPerformanceMonthlyTOP__c BuyingMonthlyTaregt = new C360_BuyingPerformanceMonthlyTOP__c(
                RecordTypeId = RecordTypeIdTarget,
                Key__c = 'byTG-'+n,
                Customer__c  = accList[0].id,
                Product__c= productMasterList[0].id,
                BusinessUnit__c='BBL',
                Year__c='2022',
                Month__c= String.valueOf(n),
                SalesGroup__c='TD1',
                SalesOrganization__c='2000',
                DistributionChannel__c='10',
                CPtargetNetProfitUSD__c=10,
                CPtargetVolume__c=10,
                CPtargetPocketMarginUSD__c=10,
                CumCPtargetNetProfitUSD__c=10,
                CumCPTargetVolume__c=10,
                CumCPtargetPocketMarginUSD__c=10
               );
              BuyingMonthTargerList.add(BuyingMonthlyTaregt); 
           }
        }
        insert BuyingMonthTargerList;
        
         yesterday = System.Today();
         List<C360_Contract__c> contractHeadList = new List<C360_Contract__c >();
         C360_Contract__c contractHead = new C360_Contract__c(
             SoldTo__c  = accList[0].id,
             ContractStartDate__c =Date.valueOf(yesterday),
             ContractEndDate__c =Date.valueOf(yesterday),
             SalesOrganization__c='1300',
             DistributionChannel__c='10');
        contractHeadList.add(contractHead);
        
        insert contractHeadList;
        /* Product__c= productMasterList[0].id,
                BillingDate__c =Date.valueOf(yesterday),
                SalesOrganization__c='1300',
                DistributionChannel__c='10',
                BilledQuantity__c=10,
        		QuantityL30__c=10,
                TotalTHB__c =10,
                TotalUSD__c =10,
                Salesunit__c='BBL',

TEXT(SalesOrganization__c) &"_"&
TEXT(DistributionChannel__c) &"_"&
Customer__r.AccountNumber__c &"_"&
Product__r.MaterialCode__c &"_"&
TEXT(Salesunit__c),
null) 302_m001_BBL*/
         List<C360_ContractLineItem__c > contractItemList = new List<C360_ContractLineItem__c >();
        for (Integer i=0;i<2;i++) {
           //s yesterday = System.Today().addDays(-i);
            if(i < 1){
            	C360_ContractLineItem__c contrItem = new C360_ContractLineItem__c(
                    Key__c = '1300_10_302_m001_BBL',
                    Contract__c  = contractHeadList[0].id,
                     Product__c= productMasterList[0].id,
                    ContractVolumeUOM__c='BBL',
                    ContractVolume__c=30);
                  contractItemList.add(contrItem);
                }else{
                     C360_ContractLineItem__c contrItem = new C360_ContractLineItem__c(
                    Key__c = '1300_10_302_m001_MT',
                    Contract__c  = contractHeadList[0].id,
                    Product__c= productMasterList[0].id,
                    ContractVolumeUOM__c='MT',
                    ContractVolume__c=30);
                   contractItemList.add(contrItem);
                }
          
        }

        insert contractItemList;
    }
    
   @isTest
   static void test_ReportBuyingDailySummary()
     {
        
      Test.startTest(); 
        C360_ReportBuyingDailySummary.sumBuyingDailyMonthYear();
      Test.stopTest();
 
     }
	
  @isTest
   static void test_C360_ReportContractLineItemSummary()
     {
        
      Test.startTest();
        C360_ReportContractLineItemSummary.sumContractItemMonthYear();
      Test.stopTest();
 
     }
      @isTest
   static void test_C360_ReportBuyingDailyTransFormToMTD()
     {
        
      Test.startTest();
       C360_ReportBuyingDailyTransFormToMTD.sumBuyingDaily();
      Test.stopTest();
 
     }
  @isTest
   static void test_ReportTxSalesSummaryControlleGetYear()
     {  
      Test.startTest();
       C360_ReportTxSalesSummaryController.getYear();
      Test.stopTest();
 
     }
   @isTest
   static void test_ReportTxSalesSummaryControlleGetBu()
     {  
      Test.startTest();
       C360_ReportTxSalesSummaryController.getBu();
      Test.stopTest();
 
     }  
   
    @isTest
   static void test_ReportTxSalesSummaryControlleGetSales()
     {  
       string selectedSalesOrg = '2000';
       string selectedDistributionChannel = '10'; 
         
      Test.startTest();
       C360_ReportTxSalesSummaryController.getSalesGroup(selectedSalesOrg,selectedDistributionChannel);
      Test.stopTest();
 
     }  
    
   @isTest
   static void test_ReportTxSalesSummaryControlleGetSales2()
     {  
       string selectedSalesOrg2 = '2000';
       string selectedDistributionChannel2 = ''; 
         
      Test.startTest();
       C360_ReportTxSalesSummaryController.getSalesGroup(selectedSalesOrg2,selectedDistributionChannel2);
      Test.stopTest();
 
     } 
  @isTest
   static void test_ReportTxSalesSummaryControlleGetSales3()
     {  
       string selectedSalesOrg3 = '';
       string selectedDistributionChannel3 = '10'; 
         
      Test.startTest();
       C360_ReportTxSalesSummaryController.getSalesGroup(selectedSalesOrg3,selectedDistributionChannel3);
      Test.stopTest();
 
     } 
  @isTest
   static void test_ReportTxSalesSummaryControlleGetSales4()
     {  
       string selectedSalesOrg4 = '';
       string selectedDistributionChannel4 = ''; 
         
      Test.startTest();
       C360_ReportTxSalesSummaryController.getSalesGroup(selectedSalesOrg4,selectedDistributionChannel4);
      Test.stopTest();
 
     } 
    @isTest
   static void test_ReportTxSalesSummaryControlleGetAcc()
     {  
       string selectedSalesOrg = '2000';
       string selectedSalesGroup = 'TD1'; 
         
      Test.startTest();
       C360_ReportTxSalesSummaryController.getAccountList(selectedSalesOrg, selectedSalesGroup);
      Test.stopTest();
 
     }   
    @isTest
   static void test_ReportTxSalesSummaryControlleGetAcc2()
     {  
       string selectedSalesOrg = '9100';
       string selectedSalesGroup = 'TD1'; 
         
      Test.startTest();
       C360_ReportTxSalesSummaryController.getAccountList(selectedSalesOrg, selectedSalesGroup);
      Test.stopTest();
 
     } 
     @isTest
   static void test_ReportTxSalesSummaryControlleGetAcc3()
     {  
       string selectedSalesOrg = '';
       string selectedSalesGroup = 'TD1'; 
         
      Test.startTest();
       C360_ReportTxSalesSummaryController.getAccountList(selectedSalesOrg, selectedSalesGroup);
      Test.stopTest();
 
     } 
     @isTest
   static void test_ReportTxSalesSummaryControlleGetAcc4()
     {  
       string selectedSalesOrg = '2000';
       string selectedSalesGroup = ''; 
         
      Test.startTest();
       C360_ReportTxSalesSummaryController.getAccountList(selectedSalesOrg, selectedSalesGroup);
      Test.stopTest();
 
     }   
    @isTest
   static void test_ReportTxSalesSummaryControlleGetAcc5()
     {  
       string selectedSalesOrg = '9100';
       string selectedSalesGroup = ''; 
         
      Test.startTest();
       C360_ReportTxSalesSummaryController.getAccountList(selectedSalesOrg, selectedSalesGroup);
      Test.stopTest();
 
     } 
     @isTest
   static void test_ReportTxSalesSummaryControlleGetDataQuery()
     {  
      string selectedMonth= '12';
      string selectedYear= '2022';
      string selectedSalesOrg= '9100';
      string selectedSalesGroup  = 'TD1'; 
      string selectedAccount= '';
      string selectedDistributionChannel = '';
      string selectedBu = 'BBL';
         
      Test.startTest();
       C360_ReportTxSalesSummaryController.getDataQuery(selectedMonth,selectedYear,selectedSalesOrg,selectedSalesGroup,selectedAccount,selectedDistributionChannel, selectedBu);
      Test.stopTest();
 
     }    
   
   @isTest
   static void test_ReportTxSalesSummaryControlleGetDataQuery2()
     {  
      string selectedMonth= '';
      string selectedYear= '2022';
      string selectedSalesOrg= '';
      string selectedSalesGroup  = ''; 
      string selectedAccount= '';
      string selectedDistributionChannel = '';
      string selectedBu = '';
         
      Test.startTest();
       C360_ReportTxSalesSummaryController.getDataQuery(selectedMonth,selectedYear,selectedSalesOrg,selectedSalesGroup,selectedAccount,selectedDistributionChannel, selectedBu);
      Test.stopTest();
     } 
       @isTest
   static void test_ReportTxSalesSummaryControlleGetDataQuery3()
     {  
      string selectedMonth= '2';
      string selectedYear= '2022';
      string selectedSalesOrg= '2000';
      string selectedSalesGroup  = 'TD1'; 
      string selectedAccount= '302';
      string selectedDistributionChannel = '10';
      string selectedBu = 'BBL';
         
      Test.startTest();
       C360_ReportTxSalesSummaryController.getDataQuery(selectedMonth,selectedYear,selectedSalesOrg,selectedSalesGroup,selectedAccount,selectedDistributionChannel, selectedBu);
      Test.stopTest();
 
     } 
       @isTest
   static void test_ReportTxSalesSummaryControlleGetDataQuery4()
     {  
      string selectedMonth= '';
      string selectedYear= '';
      string selectedSalesOrg= '';
      string selectedSalesGroup  = ''; 
      string selectedAccount= '';
      string selectedDistributionChannel = '';
      string selectedBu = '';
         
      Test.startTest();
       C360_ReportTxSalesSummaryController.getDataQuery(selectedMonth,selectedYear,selectedSalesOrg,selectedSalesGroup,selectedAccount,selectedDistributionChannel, selectedBu);
      Test.stopTest();
     } 
    
   @isTest
    static void testC360_ScheduteRPTBuyingDailySummary() 
    {
        Test.startTest();
        String jobId = System.schedule('C360_ScheduteRPTBuyingDailySummary',
                                       '0 30 1 * * ?', 
                                       new C360_ScheduteRPTBuyingDailySummary());
        Test.stopTest();
    }
    

    
    @isTest
    static void testC360_ScheduteRPTBuyingDailyToMTD() 
    {
        Test.startTest();
        String jobId = System.schedule('C360_ScheduteRPTBuyingDailyToMTD',
                                       '0 30 3 * * ?', 
                                       new C360_ScheduteRPTBuyingDailyToMTD());
        Test.stopTest();
    }
    
     @isTest
    static void testC360_ScheduteRPTContractLineItemSummary() 
    {
        Test.startTest();
        String jobId = System.schedule('C360_ScheduteRPTContractLineItemSummary',
                                       '0 30 3 * * ?', 
                                       new C360_ScheduteRPTContractLineItemSummary());
        Test.stopTest();
    }
}