force-app/main/default/objects/C360_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <formula>Account__r.AccountNumber__c</formula>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Function</relationshipLabel>
        <relationshipName>Partner_Function</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReverseAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reverse Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Function (Reverse Account)</relationshipLabel>
        <relationshipName>Partner_Function1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Function</label>
    <nameField>
        <displayFormat>Rel-{0000000}</displayFormat>
        <label>Partner Function Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/C360_CustomerNoBranchTest.cls
@isTest
public class C360_CustomerNoBranchTest {
	 @TestSetup
    static void setup() {
        Id accRecordTypeId = [select id from RecordType where DeveloperName = 'SoldTo'].Id;
        Id shipRecordTypeId = [select id from RecordType where DeveloperName = 'ShipTo'].Id;
        
        List<Account> accList = new List<Account>();
        Account a1 = new Account(AccountNumber__c='302', Name='A', RecordTypeId = accRecordTypeId);
        accList.add(a1);
        Account a2 = new Account(AccountNumber__c='1', Name='A2' , RecordTypeId = shipRecordTypeId );
        accList.add(a2);
        Account b2 = new Account(AccountNumber__c='2', Name='b2' , RecordTypeId = shipRecordTypeId );
        accList.add(b2);
        insert accList;
        
         List<C360_Relationship__c> RelaList = new List<C360_Relationship__c>();
         List<Account> accountList=[Select Id from Account  order by id asc];
            for(Account actItem :accountList){
                C360_Relationship__c r1 = new C360_Relationship__c();
                   r1.Account__c = actItem.id ;
                   r1.ReverseAccount__c = actItem.id ;
                  RelaList.add(r1);
            }
      
 		insert RelaList;
    }
    
    @isTest
    static void test_getAccountLocation() 
    {
        Test.startTest();
        
        Id a = [select id from Account where AccountNumber__c = '302'].Id;
        C360_CustomerNoBranch.AccountList();
        Test.stopTest();
        
    }
    
     @isTest
    static void testC360_ScheduleCustomerNoBranch() 
    {
        Test.startTest();
        String jobId = System.schedule('C360_ScheduleCustomerNoBranch',
                                       '0 30 4 * * ?', 
                                       new C360_ScheduleCustomerNoBranch());
        Test.stopTest();
    }
}