force-app/main/default/objects/C360_SalesArea__c.object
<CustomObject>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Area</relationshipLabel>
        <relationshipName>Sales_Area</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CreditControlArea__c</fullName>
        <label>Credit Control Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CreditControlArea</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DistributionChannel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <label>Sales Area</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Sales Area Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CTRRequestFormHeader__c.object
<CustomObject>
    <fields>
        <fullName>CreditControlArea__c</fullName>
        <label>Credit Control Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2000</fullName>
                    <label>2000 Credit Control Area TS</label>
                </value>
                <value>
                    <fullName>20ZC</fullName>
                    <label>20ZC Credit Control Area TS (ZC)</label>
                </value>
                <value>
                    <fullName>9100</fullName>
                    <label>9100 Credit Control Area TSV</label>
                </value>
                <value>
                    <fullName>91ZC</fullName>
                    <label>91ZC Credit Control Area TSV (ZC)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Request_Form_Header</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>16 Domestic - TS/TSV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>GatewayID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>GatewayID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2000</fullName>
                    <label>2000 - TXTH</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CTR Request Form Header</label>
    <nameField>
        <label>Request Form Header Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/DistributionChannel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>10-Domestic Major Oil</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11-Domestic Third Party</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12-Domestic TOP Group</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>13-Domestic Other</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>14-Domestic User/Blnder</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>15-Domestic Trade/Resel</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>16-Domestic</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>17-Free Tax Zone</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20-Export Direct</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>21-Export Indirect</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>22-Export Free Zone</label>
    </customValue>
    <customValue>
        <fullName>23</fullName>
        <label>23-Exp Direct Trading</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>24-Exp Indirect Trading</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>25-Export</label>
    </customValue>
    <customValue>
        <fullName>26</fullName>
        <label>26-Export Direct Broker</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>30-Import (VAT)</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>31-Import Indirect(VAT)</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>32-Import (Non-VAT)</label>
    </customValue>
    <customValue>
        <fullName>33</fullName>
        <label>33-Import Indirect(NonV</label>
    </customValue>
    <customValue>
        <fullName>IC</fullName>
        <label>IC-Intra-comp. Transfer</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <isActive>false</isActive>
        <label>01</label>
    </customValue>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
        <label>00-Cross Division</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10-Crude / Feedstock</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11-Ole</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20-Light Distillate</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>21-Middle Distillate</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>22-Heavy Distillate</label>
    </customValue>
    <customValue>
        <fullName>23</fullName>
        <label>23-Fuels Additive</label>
    </customValue>
    <customValue>
        <fullName>29</fullName>
        <label>29-Other (TOP)</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>30-Aromatics</label>
    </customValue>
    <customValue>
        <fullName>39</fullName>
        <label>39-Other (TPX)</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>40-Lube Base Group I</label>
    </customValue>
    <customValue>
        <fullName>41</fullName>
        <label>41-Lube Base Group II</label>
    </customValue>
    <customValue>
        <fullName>42</fullName>
        <label>42-Lube Base Group III</label>
    </customValue>
    <customValue>
        <fullName>43</fullName>
        <label>43-Bitumen</label>
    </customValue>
    <customValue>
        <fullName>44</fullName>
        <label>44-Specialty</label>
    </customValue>
    <customValue>
        <fullName>49</fullName>
        <label>49-Other (TLB)</label>
    </customValue>
    <customValue>
        <fullName>50</fullName>
        <label>50-Hydrocarbon Solvent</label>
    </customValue>
    <customValue>
        <fullName>51</fullName>
        <label>51-Other Chemicals&amp;Lube</label>
    </customValue>
    <customValue>
        <fullName>52</fullName>
        <label>52-Chemical Solvent</label>
    </customValue>
    <customValue>
        <fullName>53</fullName>
        <label>53-Petroleum</label>
    </customValue>
    <customValue>
        <fullName>59</fullName>
        <label>59-Olefins &amp; Polymer</label>
    </customValue>
    <customValue>
        <fullName>60</fullName>
        <label>60-LAB</label>
    </customValue>
    <customValue>
        <fullName>69</fullName>
        <label>69-Other (LAB)</label>
    </customValue>
    <customValue>
        <fullName>70</fullName>
        <label>70-Olefin</label>
    </customValue>
    <customValue>
        <fullName>80</fullName>
        <label>80-Hydrocarbon Services</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90-Non Hydrocarbon</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SalesOrganization.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1100</fullName>
        <label>1100-Thai Oil</label>
    </customValue>
    <customValue>
        <fullName>1300</fullName>
        <label>1300-Thai Paraxylene</label>
    </customValue>
    <customValue>
        <fullName>1400</fullName>
        <label>1400-Thai Lube Base</label>
    </customValue>
    <customValue>
        <fullName>1700</fullName>
        <label>1700-LABIX</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <label>2000-TOP NEXT International Company Limited</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <label>9100-TOP SOLVENT VIETNAM</label>
    </customValue>
    <customValue>
        <fullName>9200</fullName>
        <label>9200-PT.TIRTA SURYA RAYA</label>
    </customValue>
    <customValue>
        <fullName>9300</fullName>
        <label>9300-JSKem Pte Ltd</label>
    </customValue>
    <customValue>
        <fullName>9400</fullName>
        <label>9400-TSChem</label>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
        <isActive>false</isActive>
        <label>0001</label>
    </customValue>
    <masterLabel>Sales Organization</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CTRBlockRequestFormItemModelData.cls
public with sharing class CTRBlockRequestFormItemModelData 
{
    public CTRBlockRequestFormItemModelChild input { get; set; }

    public class CTRBlockRequestFormItemModelChild
    {
        public CTRBlockRequestFormItemModelSubChild input{ get; set; }
    } 

    public class CTRBlockRequestFormItemModelSubChild {
        public String AccountNumber{ get; set; }
        public String CompanyCode{ get; set; }
        public String SalesOrganization{ get; set; }
        public String DistributionChannel{ get; set; }
        public String Division{ get; set; }
        public String Id{ get; set; }
        public String GatewayId{ get; set; }
        public String Flag{ get; set; }
        public String RecordType{ get; set; }
        

        public List<CentralDataModel> CentralData{ get; set; }
        public List<AddressModel> AddressGen{ get; set; }
        public List<AddressIntModel> AddressInt{ get; set; }
        public List<SalesDataModel> SalesData{ get; set; }
        public List<TaxClassificationModel> TaxClassification{ get; set; }
        public List<CompanyCodeViewModel> CompanyCodeView{ get; set; }
    }

    public class CentralDataModel {}

    public class AddressModel{}
    
    public class AddressIntModel{}

    public class SalesDataModel
    {
        public String Task{ get; set; }
        public String CreditControlArea{ get; set; }
        public String Block{ get; set; }
        public String Flag{ get; set; }
    }

    public class TaxClassificationModel{}

    public class CompanyCodeViewModel{}

    public static CTRBlockRequestFormItemModelData SetupJsonForBlockDataModel (CTRRequestFormHeader__c mRequestHeader, CTRRequestFormItem__c mRequestItem, String mRecordType, String mBusinessUni,String mGatewayId)
    {
        String uuid = mGatewayId;//(mRequestItem.GatewayId__c!= null)?mRequestItem.GatewayId__c:Uuid.randomUUID();
        CTRBlockRequestFormItemModelData ctrData = new CTRBlockRequestFormItemModelData();
        CTRBlockRequestFormItemModelChild inputModel = new CTRBlockRequestFormItemModelChild();
        CTRBlockRequestFormItemModelSubChild subInputModel = new CTRBlockRequestFormItemModelSubChild();
        
        List<CentralDataModel> centralDataModelList = new List<CentralDataModel>();
        List<AddressModel> addressGenModelList = new List<AddressModel>();
        List<AddressIntModel> addressIntModelList = new List<AddressIntModel>();
        List<SalesDataModel> salesDataModelList = new List<SalesDataModel>();
        List<TaxClassificationModel> taxClassificationModelList = new List<TaxClassificationModel>();
        List<CompanyCodeViewModel> companyCodeViewModelList = new List<CompanyCodeViewModel>();
        
        // SalesDataModel
        SalesDataModel salesDataModel = new SalesDataModel();
        salesDataModel.Task = 'U';
        salesDataModel.CreditControlArea = mRequestItem.CreditControlArea__c !=null ? mRequestItem.CreditControlArea__c: '';
        salesDataModel.Block = mRequestItem.OrderBlock__c !=null ? mRequestItem.OrderBlock__c: '';
        salesDataModel.Flag = 'U';
        salesDataModelList.add(salesDataModel);
        
        subInputModel.AccountNumber = mRequestItem.Customer__r.AccountNumber__c !=null ? mRequestItem.Customer__r.AccountNumber__c: ''; //TODO Null value in google sheet
        subInputModel.CompanyCode = '';
        subInputModel.SalesOrganization = mRequestItem.SalesOrganization__c !=null ? mRequestItem.SalesOrganization__c: '';
        subInputModel.DistributionChannel = mRequestItem.DistributionChannel__c !=null ? mRequestItem.DistributionChannel__c: '';
        subInputModel.Division = mRequestItem.Division__c !=null ? mRequestItem.Division__c: '';
        subInputModel.Id = mRequestHeader.Customer__c;
        subInputModel.GatewayId = uuid;
        subInputModel.RecordType = mRecordType; //only Customer: Sold To
        subInputModel.CentralData = centralDataModelList;
        subInputModel.AddressGen = addressGenModelList;
        subInputModel.AddressInt = addressIntModelList;
        subInputModel.SalesData = salesDataModelList;
        subInputModel.TaxClassification = taxClassificationModelList;
        subInputModel.CompanyCodeView = companyCodeViewModelList;
        subInputModel.Flag = 'U';
        
        inputModel.input =subInputModel;

        ctrData.input =inputModel;
   
        system.debug('json--'+JSON.serialize(ctrData));
        return ctrData;
    }

    public static String SetupJsonForBlockDataModelCustomer (C360_SalesArea__c mSalesArea)
    {
        String uuid = Uuid.randomUUID();//(mRequestItem.GatewayId__c!= null)?mRequestItem.GatewayId__c:Uuid.randomUUID();
        CTRBlockRequestFormItemModelData ctrData = new CTRBlockRequestFormItemModelData();
        CTRBlockRequestFormItemModelChild inputModel = new CTRBlockRequestFormItemModelChild();
        CTRBlockRequestFormItemModelSubChild subInputModel = new CTRBlockRequestFormItemModelSubChild();
        
        List<CentralDataModel> centralDataModelList = new List<CentralDataModel>();
        List<AddressModel> addressGenModelList = new List<AddressModel>();
        List<AddressIntModel> addressIntModelList = new List<AddressIntModel>();
        List<SalesDataModel> salesDataModelList = new List<SalesDataModel>();
        List<TaxClassificationModel> taxClassificationModelList = new List<TaxClassificationModel>();
        List<CompanyCodeViewModel> companyCodeViewModelList = new List<CompanyCodeViewModel>();
        
        // SalesDataModel
        SalesDataModel salesDataModel = new SalesDataModel();
        salesDataModel.Task = 'U';
        salesDataModel.CreditControlArea = mSalesArea.CreditControlArea__c !=null ? mSalesArea.CreditControlArea__c: '';
        salesDataModel.Block = 'T1';
        salesDataModel.Flag = 'U';
        salesDataModelList.add(salesDataModel);
        
        subInputModel.AccountNumber = mSalesArea.AccountNumber__r.AccountNumber__c !=null ? mSalesArea.AccountNumber__r.AccountNumber__c: '';
        subInputModel.CompanyCode = '';
        subInputModel.SalesOrganization = mSalesArea.SalesOrganization__c !=null ? mSalesArea.SalesOrganization__c: '';
        subInputModel.DistributionChannel = mSalesArea.DistributionChannel__c !=null ? mSalesArea.DistributionChannel__c: '';
        subInputModel.Division = mSalesArea.Division__c !=null ? mSalesArea.Division__c: '';
        subInputModel.Id = mSalesArea.AccountNumber__c;
        subInputModel.GatewayId = uuid;
        subInputModel.RecordType = 'SoldTo'; //only Customer: Sold To
        subInputModel.CentralData = centralDataModelList;
        subInputModel.AddressGen = addressGenModelList;
        subInputModel.AddressInt = addressIntModelList;
        subInputModel.SalesData = salesDataModelList;
        subInputModel.TaxClassification = taxClassificationModelList;
        subInputModel.CompanyCodeView = companyCodeViewModelList;
        subInputModel.Flag = 'U';
        
        inputModel.input = subInputModel;

        ctrData.input = inputModel;
   
        system.debug('json--'+JSON.serialize(ctrData));
        String mJson = JSON.serialize(ctrData);
        return mJson;
    }
}