force-app/main/default/objects/C360_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Function</relationshipLabel>
        <relationshipName>Partner_Function</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelationshipType__c</fullName>
        <label>Relationship Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AG</fullName>
                    <label>Has AG</label>
                </value>
                <value>
                    <fullName>RE</fullName>
                    <label>Has Bill to</label>
                </value>
                <value>
                    <fullName>RG</fullName>
                    <label>Has Payer</label>
                </value>
                <value>
                    <fullName>WE</fullName>
                    <label>Has Ship to Party</label>
                </value>
                <value>
                    <fullName>WE-RE</fullName>
                    <label>Is Ship to Party</label>
                </value>
                <value>
                    <fullName>Has Sold-to</fullName>
                    <isActive>false</isActive>
                    <label>Has Sold-to</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Partner Function</label>
    <nameField>
        <displayFormat>Rel-{0000000}</displayFormat>
        <label>Partner Function Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/C360_CustomerNoBranch.cls
public class C360_CustomerNoBranch{
   public static void AccountList(){ 
      Map<String,integer> ptCountMap = new Map<String,integer>();
      for(AggregateResult cnPartner : [SELECT Account__c,count(id) FROM C360_Relationship__c WHERE RelationshipType__c ='WE' group by Account__c]){
         ptCountMap.put((id)cnPartner.get('Account__c'),(integer)cnPartner.get('expr0'));
      }
      List<Account> upDateAccountList = new List<Account>();
      List<Account> accountList=[Select Id from Account where RecordType.Name in ('Sold To') order by id asc];
      for(Account actItem :accountList){
         Account upDateAccount = new Account();
         upDateAccount.NoofBranch__c = ptCountMap.get(actItem.id);
         upDateAccount.id = actItem.id;
         upDateAccountList.add(upDateAccount);
      }
      if(upDateAccountList.size() > 0){
         Update upDateAccountList;
      }
	}
}