force-app/main/default/objects/C360Integration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>HerokuIntegrationDomain__c</fullName>
        <label>Heroku Integration Domain</label>
        <type>Url</type>
    </fields>
    <label>C360Integration</label>
</CustomObject>

force-app/main/default/objects/CTRIntegrationMapping__mdt.object
<CustomObject>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TOP</fullName>
                    <default>true</default>
                    <label>TOP</label>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntegrationType__c</fullName>
        <label>Integration Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Edit</fullName>
                    <default>true</default>
                    <label>Edit</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JsonMapping__c</fullName>
        <label>Json Mapping</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                    <default>true</default>
                    <label>Customer</label>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
                <value>
                    <fullName>ShipTo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CTRIntegrationMapping</label>
</CustomObject>

force-app/main/default/objects/CTRRequestFormHeader__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AP001 - ABS</fullName>
                </value>
                <value>
                    <fullName>AP002 - Adhesive</fullName>
                </value>
                <value>
                    <fullName>AP003 - Adhesive for footwear</fullName>
                </value>
                <value>
                    <fullName>AP004 - Adhesive tape</fullName>
                </value>
                <value>
                    <fullName>AP005 – Aerosal paint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CityStateLocal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City/State (Local)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Province</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>CTR Request Form Header</relationshipLabel>
        <relationshipName>CTR_Request_Form_Header</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Country</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>CTR Request Form Header (Country)</relationshipLabel>
        <relationshipName>CTR_Request_Form_Header1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomerGroup__c</fullName>
        <label>Customer Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CG001 - ALCAN Group</fullName>
                </value>
                <value>
                    <fullName>CG002 - BAFS</fullName>
                </value>
                <value>
                    <fullName>CG003 - BRIDGESTONE Group</fullName>
                </value>
                <value>
                    <fullName>CG004 - CAP</fullName>
                </value>
                <value>
                    <fullName>CG005 - Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomerType__c</fullName>
        <label>Customer Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Wholesale</fullName>
                </value>
                <value>
                    <fullName>End Consumer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Request_Form_Header</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GatewayID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>GatewayID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NP000</fullName>
                    <label>NP000 : Other - อื่นๆ</label>
                </value>
                <value>
                    <fullName>NP001</fullName>
                    <label>NP001 : Petroleum&amp;Gas Station - สถานีบริการน้ำมันและก๊าซ</label>
                </value>
                <value>
                    <fullName>NP002</fullName>
                    <label>NP002 : Petroleum&amp;Gas Retailer - ร้านค้าน้ำมันและก๊าซ</label>
                </value>
                <value>
                    <fullName>NP003</fullName>
                    <label>NP003 : Transportation - การขนส่ง</label>
                </value>
                <value>
                    <fullName>NP004</fullName>
                    <label>NP004 : Industrial - อุตสาหากรรม</label>
                </value>
                <value>
                    <fullName>NP005</fullName>
                    <label>NP005 : Electricity Generating - การผลิตไฟฟ้า</label>
                </value>
                <value>
                    <fullName>NP006</fullName>
                    <label>NP006 : Goverment Organization - ราชการและรัฐวิสาหกิจ</label>
                </value>
                <value>
                    <fullName>0001</fullName>
                    <isActive>false</isActive>
                    <label>0001</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InterGroup__c</fullName>
        <label>Inter Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IG001 - External</fullName>
                </value>
                <value>
                    <fullName>IG002 - JSKEM</fullName>
                </value>
                <value>
                    <fullName>IG003 - LABIX</fullName>
                </value>
                <value>
                    <fullName>IG004 - TET</fullName>
                </value>
                <value>
                    <fullName>IG005 – TLB</fullName>
                </value>
                <value>
                    <fullName>IG006 – TM</fullName>
                </value>
                <value>
                    <fullName>IG007 – TOP</fullName>
                </value>
                <value>
                    <fullName>IG008 – TOP SPP</fullName>
                </value>
                <value>
                    <fullName>IG009 – TPX</fullName>
                </value>
                <value>
                    <fullName>IG010 – TSR</fullName>
                </value>
                <value>
                    <fullName>IG011 – TSTH</fullName>
                </value>
                <value>
                    <fullName>IG012 - TSV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OriginalRequestFormHeader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CTR Request Form Header</label>
        <referenceTo>CTRRequestFormHeader__c</referenceTo>
        <relationshipLabel>CTR Request Form Header</relationshipLabel>
        <relationshipName>CTRRequestFormHeader</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CTR Request Form Header (Partner)</relationshipLabel>
        <relationshipName>CTRRequestFormHeader</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubIndustry__c</fullName>
        <label>Sub-Industry</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SI001 - ABS</fullName>
                </value>
                <value>
                    <fullName>SI002 - Adhesive</fullName>
                </value>
                <value>
                    <fullName>SI003 - Agrochemical</fullName>
                </value>
                <value>
                    <fullName>SI004 - Animal feed</fullName>
                </value>
                <value>
                    <fullName>SI005 – Asphalt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TermofPayment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TermofPayment</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Payment Term</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>CTR Request Form Header (TermofPayment)</relationshipLabel>
        <relationshipName>CTR_Request_Form_Header6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TradingPartner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trading Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Trading Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>CTR Request Form Header (Trading Partner)</relationshipLabel>
        <relationshipName>CTR_Request_Form_Header8</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CTR Request Form Header</label>
    <nameField>
        <label>Request Form Header Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Map__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Master Map Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CTRRequestItemIntegrationBatchController.cls
public with sharing class CTRRequestItemIntegrationBatchController implements Database.Batchable<sObject>, Database.AllowsCallouts
{
    public static final Id mRecordTypeEditCustomer = Schema.SObjectType.CTRRequestFormItem__c.getRecordTypeInfosByDeveloperName().get('CustomerEditInfo').getRecordTypeId();
    public static final Id mRecordTypeEditSupplier = Schema.SObjectType.CTRRequestFormItem__c.getRecordTypeInfosByDeveloperName().get('SupplierEditInfo').getRecordTypeId();
    public Database.QueryLocator start(Database.BatchableContext BC) 
    {
        Date mToday = System.today();
        
        List<String> mRequestItemFields = new List<String>(CTRRequestFormItem__c.SObjectType.getDescribe().fields.getMap().keySet());
        String query =  ' SELECT ' + String.join(mRequestItemFields, ',');
        query += ' ,CTRRequestFormHeader__r.Country__r.Code__c';
        query += ' ,Customer__r.AccountNumber__c, RecordType.Name';
        query += ' ,Customer__r.SupplierNumber__c';
        query += ' ,Partner__r.SupplierNumber__c, Partner__r.AccountNumber__c';
        query += ' ,Owner.ProfileId, Owner.Profile.Name, Owner.Email, Owner.Name';
        query += ' ,RecordType.DeveloperName ,TermofPayment__r.Code__c';
        query += ' ,CustomerType__r.Code__c ,CustomerGroup__r.Code__c';
        query += ' ,Industry__r.Code__c ,SubIndustry__r.Code__c';
        query += ' ,Application__r.Code__c ,InterGroup__r.Code__c';
        query += ' FROM CTRRequestFormItem__c';
        query += ' WHERE EffectiveDate__c != null AND EffectiveDate = :mToday AND Status__c = \'Approved\'' ;
        query += ' AND ((RecordTypeId = :mRecordTypeEditCustomer AND Customer__r.AccountNumber__c ! = null) OR (RecordTypeId =:mRecordTypeEditSupplier AND Customer__r.SupplierNumber__c != null))';
        query += ' AND SAPNumber__c = null AND EffectiveType__c = \'Schedule\' AND CTRRequestFormHeader__c != null';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> sObj) 
    {
        //Batch size 1 to callout
        C360Integration__c mSetting = C360Integration__c.getInstance();
        List<CTRRequestFormItem__c> mItemList = (List<CTRRequestFormItem__c>)sObj;
        Set<Id> mItemSetId = new Set<Id>();
        Set<Id> mHeaderSetId = new Set<Id>();
        for(CTRRequestFormItem__c mItem: mItemList)
        {
            if(mItem.CTRRequestFormHeader__c != null)
            {
                mHeaderSetId.add(mItem.CTRRequestFormHeader__c);
            }
        }
        if(mHeaderSetId.size()>0)
        {
            List<String> mRequestHeaderFields = new List<String>(CTRRequestFormHeader__c.SObjectType.getDescribe().fields.getMap().keySet());            
                String soqlHeader = ''
                    + ' SELECT ' + String.join(mRequestHeaderFields, ',')
                    + ' ,Country__r.Code__c'
                    + ' ,TradingPartner__r.Code__c'
                    + ' ,CityStateLocal__r.Description__c'
                    + ' ,Customer__r.AccountNumber__c'
                    + ' ,Customer__r.SupplierNumber__c'
                    + ' ,RecordType.DeveloperName'
                    + ' FROM CTRRequestFormHeader__c'
                    + ' WHERE ID IN :mSetId';
                List<CTRRequestFormHeader__c> mHeaderList = Database.query(soqlHeader);
                String mIntegrationName = '';
                String mPath = mSetting.HerokuIntegrationDomain__c;
                String mEndPoint = '';
                String jsonInput = '';
                String mToken = '';
            if(mHeaderList.size()>0)
            {
                CTRIntegraionList__mdt mIntegrationInitialCustomer = CTRIntegraionList__mdt.getInstance('CTRCustomer');
                CTRIntegraionList__mdt mIntegrationInintialSupplier = CTRIntegraionList__mdt.getInstance('CTRSupplier');
                CTRRequestFormItem__c mRequestItem = mItemList[0];
                CTRRequestFormHeader__c mRequestHeader =mHeaderList[0];
                String mGatewayId = (mRequestItem.GatewayId__c != null)?mRequestItem.GatewayId__c: Uuid.randomUUID();
                List<CTRIntegrationMapping__mdt> mAllMappingList = [SELECT Id, BusinessUnit__c, IntegrationType__c, JsonMapping__c, RecordType__c, ViewName__c, SupportIntegrationType__c FROM CTRIntegrationMapping__mdt];

                if(mRequestItem.RecordType.DeveloperName.contains('Customer') && mIntegrationInitialCustomer != null)
                {
                    if(mRequestItem.Customer__r.AccountNumber__c != null)
                    {
                        mToken = mIntegrationInitialCustomer.Token__c;
                        mIntegrationName= 'Edit Customer General+Sales View';
                        CTRRequestItemIntegrationEditController.mapLv1 mEditData = new CTRRequestItemIntegrationEditController.mapLv1();
                        mEditData = CTRRequestItemIntegrationEditController.SetupJsonForCTRDataModel(mAllMappingList, mRequestHeader,mRequestItem, 'Customer', mRequestItem.BusinessUnit__c, mGatewayId);
                        mPath = mIntegrationInitialCustomer.Path__c;
                        if(mPath != null)
                        {
                            mEndPoint += mPath;
                        }
                        jsonInput = JSON.serialize(mEditData);
                    }
                }
                else if(mRequestItem.RecordType.DeveloperName.contains('Supplier') && mIntegrationInintialSupplier != null)
                {
                    if(mRequestItem.Customer__r.SupplierNumber__c != null)
                    {
                        mToken = mIntegrationInintialSupplier.Token__c;
                        mIntegrationName= 'Edit Supplier General+Purchasing View';
                        CTRRequestItemIntegrationEditController.mapLv1 mEditData = new CTRRequestItemIntegrationEditController.mapLv1();
                        mEditData = CTRRequestItemIntegrationEditController.SetupJsonForCTRDataModel(mAllMappingList,mRequestHeader,mRequestItem, 'Supplier', mRequestItem.BusinessUnit__c, mGatewayId);
                        mPath = mIntegrationInintialSupplier.Path__c;
                        System.debug('Endpoint:'+mEndPoint);
                        if(mPath != null)
                            {
                                mEndPoint += mPath;
                            }
                        jsonInput = JSON.serialize(mEditData);
                        //mGatewayId = mEditData.input.input.get('GatewayId');
                    }
                }
                if(String.isNotBlank(jsonInput) && String.isNotBlank(mEndpoint)&& String.isNotBlank(mPath))
                {
                    HttpRequest request = new HttpRequest();
                    request.setMethod('POST');  
                    request.setHeader('Content-Type', 'application/json');
                    request.setBody(jsonInput);
                    request.setHeader('Authorization', 'Bearer ' + mToken);
                    request.setEndpoint(mEndPoint);

                    Http http = new Http();
                    HttpResponse response = http.send(request);

                    // Parse and handle the response
                    if (response.getStatusCode() == 200) 
                    {
                        CTRRequestFormItem__c mRequestItemUpdate = new CTRRequestFormItem__c(Id = mRequestItem.Id);
                        mRequestItemUpdate.IntegrationStatus__c = 'In Progress';

                        // Successful response
                        String SAPStatus = mRequestItem.SAPStatus__c;

                        if (mIntegrationName == 'Edit Supplier General+Purchasing View' ||
                            mIntegrationName == 'Edit Customer General+Purchasing View')
                        {
                            SAPStatus = 'Send Sales/Purchasing View To SAP';
                        }
                        

                        System.debug('Success Response: ' + response.getBody());                        
                        mRequestItemUpdate.SAPStatus__c = SAPStatus;
                        mRequestItemUpdate.GatewayId__c = mGatewayId;
                        //mRequestItemUpdate.SAPSubmitTime__c = DateTime.Now();
                        mRequestItemUpdate.LatestIntegrationName__c = mIntegrationName;
                        
                        update mRequestItemUpdate;
                        System.debug('SAPStatus : ' + SAPStatus);
                        System.debug('mGatewayId : ' + mGatewayId);
                        System.debug('mIntegrationName : ' + mIntegrationName);
    
                    } 
                    else 
                    {
                        // Error handling
                        String SAPStatus = mRequestItem.SAPStatus__c;
                        if(mIntegrationName == 'Edit Supplier General+Purchasing View' ||
                            mIntegrationName == 'Edit Customer General+Purchasing View')
                        {
                            SAPStatus= 'Unsuccessful Send Sales/Purchasing view to SAP';
                        }
                        CTRRequestFormItem__c mRequestItemUpdate = new CTRRequestFormItem__c(Id = mRequestItem.Id);
                        mRequestItemUpdate.SAPStatus__c = SAPStatus;
                        mRequestItemUpdate.GatewayId__c = mGatewayId;
                        mRequestItemUpdate.LatestIntegrationName__c = mIntegrationName;
                        //mRequestItemUpdate.SAPSubmitTime__c = DateTime.Now();
                        mRequestItemUpdate.IntegrationStatus__c = 'Fail';
    
                        update mRequestItemUpdate;
                        System.debug('HTTP error: ' + response.getStatusCode() + ' ' + response.getBody());
                        
                    }
                }
            }
        }
        
    }
    
    public void finish(Database.BatchableContext BC) 
    {

    }
}