force-app/main/default/objects/C360Integration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>DeletedBatchSize__c</fullName>
        <description>For use delete Daily Buying Performance (Job Clear data Schedule)</description>
        <label>Deleted Batch Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>C360Integration</label>
</CustomObject>

force-app/main/default/classes/C360_ScheduleBuyingDailyJobClearData.cls
global class C360_ScheduleBuyingDailyJobClearData implements Schedulable
{ 
    global void execute(SchedulableContext contextSchedule){
        //Method to get data from C360_BuyingDailyJobClearData Object
        C360_BuyingDailyJobClearData deleteBuyingDailyJobClearData = new C360_BuyingDailyJobClearData();
        //Get batch size from Custom Setting
        C360Integration__c  delCustomSet = C360Integration__c.getInstance();
        Integer batchSize = Integer.valueOf(delCustomSet.DeletedBatchSize__c);
        String check = String.valueOf(batchSize);      
        if(check == null)  
        {
            system.debug('Batch Size Null');
        }else{
            // Method to delete Application Log 
            database.executeBatch(deleteBuyingDailyJobClearData,batchSize);
        } 
     }
}