force-app/main/default/objects/C360_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <formula>Account__r.AccountNumber__c</formula>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Function</relationshipLabel>
        <relationshipName>Partner_Function</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelationshipType__c</fullName>
        <label>Relationship Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AG</fullName>
                    <label>Has AG</label>
                </value>
                <value>
                    <fullName>RE</fullName>
                    <label>Has Bill to</label>
                </value>
                <value>
                    <fullName>RG</fullName>
                    <label>Has Payer</label>
                </value>
                <value>
                    <fullName>WE</fullName>
                    <label>Has Ship to Party</label>
                </value>
                <value>
                    <fullName>WE-RE</fullName>
                    <label>Is Ship to Party</label>
                </value>
                <value>
                    <fullName>Has Sold-to</fullName>
                    <isActive>false</isActive>
                    <label>Has Sold-to</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReverseAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reverse Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Function (Reverse Account)</relationshipLabel>
        <relationshipName>Partner_Function1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Function</label>
    <nameField>
        <displayFormat>Rel-{0000000}</displayFormat>
        <label>Partner Function Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_SalesArea__c.object
<CustomObject>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Area</relationshipLabel>
        <relationshipName>Sales_Area</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DeliveryPriority__c</fullName>
        <label>Delivery Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DeliveryPriority</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DistributionChannel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesDistrict__c</fullName>
        <label>Sales District</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesDistrict</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ShippingCondition__c</fullName>
        <description>Shipping Condition</description>
        <label>Shipping Condition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ShippingConditions</valueSetName>
        </valueSet>
    </fields>
    <label>Sales Area</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Sales Area Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CTRRequestFormHeader__c.object
<CustomObject>
    <fields>
        <fullName>BuildingCodeLocal__c</fullName>
        <label>Building Code (Local)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CityStateLocal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City/State (Local)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Province</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>CTR Request Form Header</relationshipLabel>
        <relationshipName>CTR_Request_Form_Header</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CoName__c</fullName>
        <label>C/O Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyNameENF__c</fullName>
        <label>Company Name EN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyNameLocal__c</fullName>
        <label>Company Name (Local)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactSalutation__c</fullName>
        <label>Contact Salutation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Salutation</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CountryCode__c</fullName>
        <label>Country Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TH</fullName>
                    <label>+66 Thailand</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Country</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>CTR Request Form Header (Country)</relationshipLabel>
        <relationshipName>CTR_Request_Form_Header1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomerNameLocal1__c</fullName>
        <label>CustomerNameLocal1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerSearchTermEN__c</fullName>
        <label>Customer Search Term (EN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerSearchTermLocal__c</fullName>
        <label>Customer Search Term(Local)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Request_Form_Header</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DeliveryPriority__c</fullName>
        <label>Delivery Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>16 Domestic - TS/TSV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DistrictLocalText__c</fullName>
        <label>District (Local)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Division</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FaxCountryCode__c</fullName>
        <label>Fax Country Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCodePhone</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>FaxExtension__c</fullName>
        <label>Fax Extension</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FloorLocal__c</fullName>
        <label>Floor (Local)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HousenoLocal__c</fullName>
        <label>House no. (Local)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationInGoogleMapsLinks__c</fullName>
        <label>Location in Google Maps (Link)</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MobileCountryCode__c</fullName>
        <label>Mobile Country Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCodePhone</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MobilePhone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Nickname__c</fullName>
        <label>Nickname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PhoneCountryCode__c</fullName>
        <label>Phone Country Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCodePhone</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PhoneExtension__c</fullName>
        <label>Phone Extension</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalCodeLocalText__c</fullName>
        <label>PostalCodeLocalText</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoomLocal__c</fullName>
        <label>Room (Local)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesDistrict__c</fullName>
        <label>Sales District</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales Disctrict</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2000</fullName>
                    <label>2000 - TXTH</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ShippingCondition__c</fullName>
        <label>Shipping Condition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StreetLocal__c</fullName>
        <label>Street (Local)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubDistrictLocalText__c</fullName>
        <label>Sub District (Local)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaxCode1__c</fullName>
        <label>Tax Code1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>CTR Request Form Header</label>
    <nameField>
        <label>Request Form Header Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Map__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Master Map Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/DeliveryPriority.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>High</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Normal Item</label>
    </customValue>
    <masterLabel>Delivery Priority</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DistributionChannel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>10-Domestic Major Oil</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11-Domestic Third Party</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12-Domestic TOP Group</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>13-Domestic Other</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>14-Domestic User/Blnder</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>15-Domestic Trade/Resel</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>16-Domestic</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>17-Free Tax Zone</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20-Export Direct</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>21-Export Indirect</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>22-Export Free Zone</label>
    </customValue>
    <customValue>
        <fullName>23</fullName>
        <label>23-Exp Direct Trading</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>24-Exp Indirect Trading</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>25-Export</label>
    </customValue>
    <customValue>
        <fullName>26</fullName>
        <label>26-Export Direct Broker</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>30-Import (VAT)</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>31-Import Indirect(VAT)</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>32-Import (Non-VAT)</label>
    </customValue>
    <customValue>
        <fullName>33</fullName>
        <label>33-Import Indirect(NonV</label>
    </customValue>
    <customValue>
        <fullName>IC</fullName>
        <label>IC-Intra-comp. Transfer</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <isActive>false</isActive>
        <label>01</label>
    </customValue>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Division.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>00</fullName>
        <label>00-Cross Division</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10-Crude / Feedstock</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11-Ole</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20-Light Distillate</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>21-Middle Distillate</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>22-Heavy Distillate</label>
    </customValue>
    <customValue>
        <fullName>23</fullName>
        <label>23-Fuels Additive</label>
    </customValue>
    <customValue>
        <fullName>29</fullName>
        <label>29-Other (TOP)</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>30-Aromatics</label>
    </customValue>
    <customValue>
        <fullName>39</fullName>
        <label>39-Other (TPX)</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>40-Lube Base Group I</label>
    </customValue>
    <customValue>
        <fullName>41</fullName>
        <label>41-Lube Base Group II</label>
    </customValue>
    <customValue>
        <fullName>42</fullName>
        <label>42-Lube Base Group III</label>
    </customValue>
    <customValue>
        <fullName>43</fullName>
        <label>43-Bitumen</label>
    </customValue>
    <customValue>
        <fullName>44</fullName>
        <label>44-Specialty</label>
    </customValue>
    <customValue>
        <fullName>49</fullName>
        <label>49-Other (TLB)</label>
    </customValue>
    <customValue>
        <fullName>50</fullName>
        <label>50-Hydrocarbon Solvent</label>
    </customValue>
    <customValue>
        <fullName>51</fullName>
        <label>51-Other Chemicals&amp;Lube</label>
    </customValue>
    <customValue>
        <fullName>52</fullName>
        <label>52-Chemical Solvent</label>
    </customValue>
    <customValue>
        <fullName>53</fullName>
        <label>53-Petroleum</label>
    </customValue>
    <customValue>
        <fullName>59</fullName>
        <label>59-Olefins &amp; Polymer</label>
    </customValue>
    <customValue>
        <fullName>60</fullName>
        <label>60-LAB</label>
    </customValue>
    <customValue>
        <fullName>69</fullName>
        <label>69-Other (LAB)</label>
    </customValue>
    <customValue>
        <fullName>70</fullName>
        <label>70-Olefin</label>
    </customValue>
    <customValue>
        <fullName>80</fullName>
        <label>80-Hydrocarbon Services</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>90-Non Hydrocarbon</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <masterLabel>Division</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SalesDistrict.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>000001</fullName>
        <label>Northern region</label>
    </customValue>
    <customValue>
        <fullName>000002</fullName>
        <label>Southern region</label>
    </customValue>
    <customValue>
        <fullName>CENTRE</fullName>
        <label>Lower North Island</label>
    </customValue>
    <customValue>
        <fullName>NORTH</fullName>
        <label>Upper North Island</label>
    </customValue>
    <customValue>
        <fullName>SOUTH</fullName>
        <label>South Island</label>
    </customValue>
    <customValue>
        <fullName>ZTH001</fullName>
        <label>TH_Central</label>
    </customValue>
    <customValue>
        <fullName>ZTH002</fullName>
        <label>TH_Northern</label>
    </customValue>
    <customValue>
        <fullName>ZTH003</fullName>
        <label>TH_Northeastern</label>
    </customValue>
    <customValue>
        <fullName>ZTH004</fullName>
        <label>TH_Eastern</label>
    </customValue>
    <customValue>
        <fullName>ZTH005</fullName>
        <label>TH_Southern</label>
    </customValue>
    <customValue>
        <fullName>ZTH006</fullName>
        <label>TH_Western</label>
    </customValue>
    <customValue>
        <fullName>ZTH0EX</fullName>
        <label>TH_Export</label>
    </customValue>
    <customValue>
        <fullName>ZTHOTH</fullName>
        <label>TH_Other Country</label>
    </customValue>
    <customValue>
        <fullName>ZVN001</fullName>
        <label>VN_North</label>
    </customValue>
    <customValue>
        <fullName>ZVN002</fullName>
        <label>VN_South</label>
    </customValue>
    <customValue>
        <fullName>ZVN0EX</fullName>
        <label>VN_Export</label>
    </customValue>
    <customValue>
        <fullName>ZID001</fullName>
        <label>ID_JKT</label>
    </customValue>
    <customValue>
        <fullName>ZID002</fullName>
        <label>ID_Jawa</label>
    </customValue>
    <customValue>
        <fullName>ZID003</fullName>
        <label>ID_Sumatera</label>
    </customValue>
    <customValue>
        <fullName>ZID004</fullName>
        <label>ID_Kalimantan</label>
    </customValue>
    <customValue>
        <fullName>ZID005</fullName>
        <label>ID_Sulawesi</label>
    </customValue>
    <customValue>
        <fullName>ZSG001</fullName>
        <label>SG_Central</label>
    </customValue>
    <masterLabel>Sales District</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SalesOrganization.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1100</fullName>
        <label>1100-Thai Oil</label>
    </customValue>
    <customValue>
        <fullName>1300</fullName>
        <label>1300-Thai Paraxylene</label>
    </customValue>
    <customValue>
        <fullName>1400</fullName>
        <label>1400-Thai Lube Base</label>
    </customValue>
    <customValue>
        <fullName>1700</fullName>
        <label>1700-LABIX</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <label>2000-TOP NEXT International Company Limited</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <label>9100-TOP SOLVENT VIETNAM</label>
    </customValue>
    <customValue>
        <fullName>9200</fullName>
        <label>9200-PT.TIRTA SURYA RAYA</label>
    </customValue>
    <customValue>
        <fullName>9300</fullName>
        <label>9300-JSKem Pte Ltd</label>
    </customValue>
    <customValue>
        <fullName>9400</fullName>
        <label>9400-TSChem</label>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
        <isActive>false</isActive>
        <label>0001</label>
    </customValue>
    <masterLabel>Sales Organization</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ShippingConditions.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
        <label>As Soon As Possible</label>
    </customValue>
    <customValue>
        <fullName>02</fullName>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>Company Delivery</label>
    </customValue>
    <customValue>
        <fullName>91</fullName>
        <label>Own Pickup Pack</label>
    </customValue>
    <customValue>
        <fullName>92</fullName>
        <label>Own Pickup Bulk</label>
    </customValue>
    <customValue>
        <fullName>93</fullName>
        <label>Transport 3rd Pack</label>
    </customValue>
    <customValue>
        <fullName>94</fullName>
        <label>Transport 3rd Bulk</label>
    </customValue>
    <customValue>
        <fullName>95</fullName>
        <label>Return</label>
    </customValue>
    <customValue>
        <fullName>99</fullName>
        <label>Others</label>
    </customValue>
    <customValue>
        <fullName>GN</fullName>
        <label>Non-Hydrocarbon</label>
    </customValue>
    <customValue>
        <fullName>LO</fullName>
        <label>Lorry</label>
    </customValue>
    <customValue>
        <fullName>PI</fullName>
        <label>Pipeline</label>
    </customValue>
    <customValue>
        <fullName>SH</fullName>
        <label>Ship</label>
    </customValue>
    <customValue>
        <fullName>SV</fullName>
        <label>Service</label>
    </customValue>
    <customValue>
        <fullName>SW</fullName>
        <label>Swap</label>
    </customValue>
    <customValue>
        <fullName>TH</fullName>
        <label>Thappline</label>
    </customValue>
    <customValue>
        <fullName>TK</fullName>
        <label>Tank</label>
    </customValue>
    <customValue>
        <fullName>UR</fullName>
        <label>Urgent</label>
    </customValue>
    <customValue>
        <fullName>SB</fullName>
        <label>Ship-Bulk</label>
    </customValue>
    <customValue>
        <fullName>SI</fullName>
        <label>Ship-Isotank/Cont.</label>
    </customValue>
    <masterLabel>Shipping Conditions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CTRRequestShipToController.cls
public with sharing class CTRRequestShipToController {
    public class RequestWrapper
    {
        @auraEnabled public Id mRecordId {get; set;}
        @auraEnabled public Integer mIndex {get; set;}
        @auraEnabled public String mAccountId {get; set;}
        @auraEnabled public String mShipToName {get; set;}
        @auraEnabled public String mCountry {get; set;}
        @auraEnabled public String mSalesOrg {get; set;}
        @auraEnabled public String mDivision {get;set;}
        @auraEnabled public String mDistributionChannel {get;set;}
        @auraEnabled public String mLabelSalesOrg {get; set;}
        @auraEnabled public String mLabelDivision {get;set;}
        @auraEnabled public String mLabelDistributionChannel {get;set;}
        @auraEnabled public Boolean mSelected {get; set;}
    }

    public class ResponseWrapper {
        @AuraEnabled public Boolean result {get; set;}
        @AuraEnabled public String message {get; set;} 
        @AuraEnabled public Id resRecordId {get; set;}
    }

    @AuraEnabled
    public static List<RequestWrapper> onloadCreatePage(Id mAccountId, Id RecordType)
    {
        try 
        {
            List<Account> currAccount = [SELECT Id, SalesOrganization__c FROM Account WHERE Id =: mAccountId];
            List<RequestWrapper> mRequestWrapperList = new List<RequestWrapper>();
            Set<String> setSalesOrg = new Set<String>{'2000','9100','9200','9300','9400'};
            List<RecordType> RecordTypeList = [SELECT Id, Name, DeveloperName FROM RecordType WHERE Id = :RecordType LIMIT 1];

            if(RecordTypeList[0].DeveloperName.contains('Edit')) {

                List<C360_Relationship__c> mRelatedShipToList = new List<C360_Relationship__c>([SELECT Id, ReverseAccount__c, ReverseAccount__r.Name, ReverseAccount__r.Country__r.Description__c, RelationshipType__c FROM C360_Relationship__c WHERE Account__c =: mAccountId AND RelationshipType__c = 'WE']); // Has Ship to Party
                // Set<Id> mAccIdSet = new Set<Id>();
                Map<Id, C360_Relationship__c> mapAccIdRelatedShipTo = new Map<Id, C360_Relationship__c>();
                for(C360_Relationship__c relatedShipTo : mRelatedShipToList) {
                    mapAccIdRelatedShipTo.put(relatedShipTo.ReverseAccount__c,relatedShipTo);
                }
                System.debug('Debug key '+mapAccIdRelatedShipTo.keySet());
                
                List<C360_SalesArea__c> mSalesAreaList = new List<C360_SalesArea__c>([SELECT AccountNumber__c, SalesOrganization__c, Division__c, DistributionChannel__c, toLabel(SalesOrganization__c) salesOrgLabel, toLabel(Division__c) divisionLabel, toLabel(DistributionChannel__c) distChLabel FROM C360_SalesArea__c WHERE AccountNumber__c IN :mapAccIdRelatedShipTo.keySet() AND SalesOrganization__c IN :setSalesOrg]);
                Integer mIndex = 1;
                for(C360_SalesArea__c mSalesArea: mSalesAreaList)
                {
                    RequestWrapper mRequestWrapper = new RequestWrapper();
                    mRequestWrapper.mRecordId = mSalesArea.Id;
                    mRequestWrapper.mIndex = mIndex;
                    mRequestWrapper.mAccountId = mSalesArea.AccountNumber__c;
                    mRequestWrapper.mShipToName = mapAccIdRelatedShipTo.get(mSalesArea.AccountNumber__c)?.ReverseAccount__r.Name;
                    mRequestWrapper.mCountry = mapAccIdRelatedShipTo.get(mSalesArea.AccountNumber__c)?.ReverseAccount__r.Country__r.Description__c;
                    mRequestWrapper.mSalesOrg = mSalesArea.SalesOrganization__c;
                    mRequestWrapper.mDivision = mSalesArea.Division__c;
                    mRequestWrapper.mDistributionChannel = mSalesArea.DistributionChannel__c;
                    mRequestWrapper.mLabelSalesOrg = String.valueOf(mSalesArea.get('salesOrgLabel'));
                    mRequestWrapper.mLabelDivision = String.valueOf(mSalesArea.get('divisionLabel'));
                    mRequestWrapper.mLabelDistributionChannel = String.valueOf(mSalesArea.get('distChLabel'));
                    if(currAccount[0].SalesOrganization__c == mSalesArea.SalesOrganization__c) {
                        mRequestWrapper.mSelected = true; // default as selected customer
                    }
                    mRequestWrapperList.add(mRequestWrapper);
                    mIndex++;
                }
            } else {

                List<C360_SalesArea__c> mSalesAreaList = new List<C360_SalesArea__c>([SELECT SalesOrganization__c, Division__c, DistributionChannel__c, toLabel(SalesOrganization__c) salesOrgLabel, toLabel(Division__c) divisionLabel, toLabel(DistributionChannel__c) distChLabel FROM C360_SalesArea__c WHERE AccountNumber__c = :mAccountId AND SalesOrganization__c IN :setSalesOrg]);
                Integer mIndex = 1;
                for(C360_SalesArea__c mSalesArea: mSalesAreaList)
                {
                    RequestWrapper mRequestWrapper = new RequestWrapper();
                    mRequestWrapper.mRecordId = mSalesArea.Id;
                    mRequestWrapper.mIndex = mIndex;
                    mRequestWrapper.mSalesOrg = mSalesArea.SalesOrganization__c;
                    mRequestWrapper.mDivision = mSalesArea.Division__c;
                    mRequestWrapper.mDistributionChannel = mSalesArea.DistributionChannel__c;
                    mRequestWrapper.mLabelSalesOrg = String.valueOf(mSalesArea.get('salesOrgLabel'));
                    mRequestWrapper.mLabelDivision = String.valueOf(mSalesArea.get('divisionLabel'));
                    mRequestWrapper.mLabelDistributionChannel = String.valueOf(mSalesArea.get('distChLabel'));
                    if(currAccount[0].SalesOrganization__c == mSalesArea.SalesOrganization__c) {
                        mRequestWrapper.mSelected = true; // default as selected customer
                    }
                    mRequestWrapperList.add(mRequestWrapper);
                    mIndex++;
                }
            }

            return mRequestWrapperList;
        } 
        catch (Exception e) 
        {
            System.debug('Error From CTRRequestShipToController.onloadCreatePage Line: '+e.getLineNumber()+' || Message:'+e.getMessage());
            return null;
        }
    }

    @AuraEnabled
    public static ResponseWrapper saveRequestShipTo(Id mItemId, String formData, String customerId, String itemRecordTypeId, RequestWrapper requestWrapper ){
        ResponseWrapper responseResult = new ResponseWrapper();
        responseResult.result = false;
        try
        {
            List<RecordType> RecordTypeList = [SELECT Id, Name, DeveloperName FROM RecordType WHERE Id = :itemRecordTypeId LIMIT 1];

            if(requestWrapper == null) {
                responseResult.message = 'Not found selected item';
                return responseResult;
            }
            
            System.debug(' Accomplished: '+formData);
            Map<String, Object> cObjMap = (Map<String, Object>) JSON.deserializeUntyped(formData);
            System.debug(' cObjMap: '+cObjMap);
            String cObjJson = JSON.serialize(cObjMap);
            System.debug(' cObjJson: '+cObjJson);
            Map<String, Object> cObjMapFurious = (Map<String, Object>) JSON.deserializeUntyped(cObjJson);
            String cObjJsonDrunk = JSON.serialize(cObjMapFurious);
            
            // Account accobj = (Account)JSON.deserialize(cObjJsonDrunk, Account.class);
            // System.debug(' Accomplished: '+accobj);

            Object obj = JSON.deserializeUntyped(cObjJsonDrunk);
            System.debug(' Accomplished: '+obj);

            Map<String, Object> objMap = new Map<String, Object>();
            if (obj instanceof Map<String, Object>) {
                objMap = (Map<String, Object>) obj;
            } else {
                System.debug('Deserialized object is not a Map.');
            }
            
            System.debug('Country__c : ' + objMap.get('Country__c'));

            if(mItemId == null) { // create from New Request button
                if(RecordTypeList[0].DeveloperName.contains('Edit')) {
                    customerId = requestWrapper.mAccountId;
                }
                List<String> mSalesAreaFields = new List<String>(Schema.getGlobalDescribe().get('C360_SalesArea__c').getDescribe().fields.getMap().keySet());            
                String soqlText = '';
                soqlText+= ' SELECT ' + String.join(mSalesAreaFields, ',');
                soqlText+= ' FROM C360_SalesArea__c';
                soqlText+= ' WHERE Id = \''+requestWrapper.mRecordId+'\'';
                List<C360_SalesArea__c> mSalesAreaList = new List<C360_SalesArea__c>();
                mSalesAreaList = Database.query(soqlText);
                
                // CTRAccountCtrl.duplicateCheckResult isdup = CTRAccountCtrl.checkDuplicateAccount(accobj,shippingList,shareholderList, null);
                // System.debug(' isdup: '+isdup);
                Id headerRecordTypeId = Schema.SObjectType.CTRRequestFormHeader__c.getRecordTypeInfosByDeveloperName().get(RecordTypeList[0].DeveloperName).getRecordTypeId();
    
                if(mSalesAreaList.size() > 0) {
                    C360_SalesArea__c salesArea = mSalesAreaList[0];
                    CTRRequestFormHeader__c mRequestFormHeader = new CTRRequestFormHeader__c();
                    mRequestFormHeader.RecordTypeId = headerRecordTypeId;
                    mRequestFormHeader.Customer__c = customerId;
                    mRequestFormHeader.CompanyNameENF__c = String.valueOf(objMap.get('CompanyNameENF__c'));
                    mRequestFormHeader.CustomerNameLocal1__c = String.valueOf(objMap.get('CompanyNameLocal__c'));
                    mRequestFormHeader.Country__c = String.valueOf(objMap.get('Country__c'));
                    mRequestFormHeader.TaxCode1__c = String.valueOf(objMap.get('TaxCode1__c'));
                    mRequestFormHeader.CustomerSearchTermEN__c = String.valueOf(objMap.get('CustomerSearchTermEN__c'));
                    mRequestFormHeader.CustomerSearchTermLocal__c = String.valueOf(objMap.get('CustomerSearchTermLocal__c'));
                    mRequestFormHeader.HousenoLocal__c = String.valueOf(objMap.get('HousenoLocal__c'));
                    mRequestFormHeader.BuildingCodeLocal__c = String.valueOf(objMap.get('BuildingCodeLocal__c'));
                    mRequestFormHeader.RoomLocal__c = String.valueOf(objMap.get('RoomLocal__c'));
                    mRequestFormHeader.FloorLocal__c = String.valueOf(objMap.get('FloorLocal__c'));
                    mRequestFormHeader.CoName__c = String.valueOf(objMap.get('CoName__c'));
                    mRequestFormHeader.StreetLocal__c = String.valueOf(objMap.get('StreetLocal__c'));
                    mRequestFormHeader.SubDistrictLocalText__c = String.valueOf(objMap.get('SubDistrictLocalText__c'));
                    mRequestFormHeader.DistrictLocalText__c = String.valueOf(objMap.get('DistrictLocalText__c'));
                    mRequestFormHeader.CityStateLocal__c = String.valueOf(objMap.get('CityStateLocal__c'));
                    mRequestFormHeader.PostalCodeLocalText__c = String.valueOf(objMap.get('PostalCodeLocalText__c'));
                    mRequestFormHeader.LocationInGoogleMapsLinks__c = String.valueOf(objMap.get('LocationInGoogleMapsLinks__c'));
                    mRequestFormHeader.LocationInGoogleMapsGeolocation__Latitude__s = Decimal.valueOf((String)objMap.get('Location__Latitude__s'));
                    mRequestFormHeader.LocationInGoogleMapsGeolocation__Longitude__s = Decimal.valueOf((String)objMap.get('Location__Longitude__s'));
                    mRequestFormHeader.ContactSalutation__c = String.valueOf(objMap.get('ContactSalutation__c'));
                    mRequestFormHeader.Nickname__c = String.valueOf(objMap.get('Nickname__c'));
                    mRequestFormHeader.FirstName__c = String.valueOf(objMap.get('FirstName__c'));
                    mRequestFormHeader.LastName__c = String.valueOf(objMap.get('LastName__c'));
                    mRequestFormHeader.Position__c = String.valueOf(objMap.get('Position__c'));
                    mRequestFormHeader.Email__c = String.valueOf(objMap.get('Email__c'));
                    mRequestFormHeader.MobileCountryCode__c = String.valueOf(objMap.get('MobileCountryCode__c'));
                    mRequestFormHeader.CountryCode__c = String.valueOf(objMap.get('CountryCode__c'));
                    mRequestFormHeader.MobilePhone__c = String.valueOf(objMap.get('MobilePhone__c'));
                    mRequestFormHeader.PhoneCountryCode__c = String.valueOf(objMap.get('PhoneCountryCode__c'));
                    mRequestFormHeader.Phone__c = String.valueOf(objMap.get('Phone'));
                    // mRequestFormHeader.PhoneExtension__c = accobj.PhoneExtension__c;
                    mRequestFormHeader.FaxCountryCode__c = String.valueOf(objMap.get('FaxCountryCode__c'));
                    mRequestFormHeader.Fax__c = String.valueOf(objMap.get('Fax'));
                    // mRequestFormHeader.FaxExtension__c = accobj.FaxExtension__c;
                    // mRequestFormHeader.SalesDistrict__c = salesArea.SalesDistrict__c;
                    // mRequestFormHeader.DeliveryPriority__c = salesArea.DeliveryPriority__c;
                    // mRequestFormHeader.ShippingCondition__c = salesArea.ShippingConditions__c;
                    // mRequestFormHeader.DeliveryPlant__c = salesArea.DeliveryPlant__c;
                    // mRequestFormHeader.MaxPartialDeliveries__c = salesArea.MaxPartialDeliveries__c != null ? String.valueOf(salesArea.MaxPartialDeliveries__c) : null;
                    mRequestFormHeader.TransportationZone__c = String.valueOf(objMap.get('TransportationZone__c'));
                    // mRequestFormHeader.PartialDeliveriesperitem__c = salesArea.PartialDeliveriesperitem__c;
                    // mRequestFormHeader.UnderdeliveryTolerance__c = salesArea.UnderdeliveryTolerance__c;
                    // mRequestFormHeader.OverdeliveryTolerance__c = salesArea.OverdeliveryTolerance__c;
                    // mRequestFormHeader.AccountAssignmentGroup__c = salesArea.AccountAssignmentGroup__c;
                    mRequestFormHeader.TAXClassification__c = String.valueOf(objMap.get('TaxClassification__c'));
    
                    // mRequestFormHeader.DistributionChannel__c = requestWrapper.mDistributionChannel;
                    // mRequestFormHeader.Division__c = requestWrapper.mDivision;
                    // mRequestFormHeader.SalesOrganization__c = requestWrapper.mSalesOrg;
                    insert mRequestFormHeader;
    
                
                    CTRRequestFormItem__c mRequestFormItem = new CTRRequestFormItem__c();
                    mRequestFormItem.CTRRequestFormHeader__c = mRequestFormHeader.Id;
                    mRequestFormItem.Customer__c = customerId;
                    // mRequestFormItem.Objective__c = ;
                    // mRequestFormItem.EffectiveType__c = ;
                    // mRequestFormItem.EffectiveDate__c = ;
                    mRequestFormItem.RecordTypeId = itemRecordTypeId;
                    mRequestFormItem.Status__c = 'New';
                    mRequestFormItem.Approval_Step__c = 'Open';
                    mRequestFormItem.Sensitive__c = true;
                    mRequestFormItem.SalesDistrict__c = String.valueOf(objMap.get('SalesDistrict__c'));
                    mRequestFormItem.DeliveryPriority__c = String.valueOf(objMap.get('DeliveryPriority__c'));
                    mRequestFormItem.ShippingConditions__c = String.valueOf(objMap.get('ShippingConditions__c'));
                    mRequestFormItem.DeliveryPlant__c = String.valueOf(objMap.get('DeliveryPlant__c'));
                    mRequestFormItem.MaxPartialDeliveries__c = Decimal.valueOf((String)objMap.get('MaxPartialDeliveries__c')) != null ? Decimal.valueOf((String)objMap.get('MaxPartialDeliveries__c')) : null;
                    // mRequestFormItem.TransportationZone__c = salesArea.TransportationZone__c;
                    mRequestFormItem.PartialDeliveriesperitem__c = String.valueOf(objMap.get('PartialDeliveriesperitem__c'));
                    mRequestFormItem.UnderdeliveryTolerance__c = Decimal.valueOf((String)objMap.get('UnderdeliveryTolerance__c'));
                    mRequestFormItem.OverdeliveryTolerance__c = Decimal.valueOf((String)objMap.get('OverdeliveryTolerance__c'));
                    mRequestFormItem.AccountAssignmentGroup__c = String.valueOf(objMap.get('AccountAssignmentGroup__c'));
                    // mRequestFormItem.TaxClassification__c = accobj.TaxClassification__c;
    
                    mRequestFormItem.DistributionChannel__c = salesArea.DistributionChannel__c;
                    mRequestFormItem.Division__c = salesArea.Division__c;
                    mRequestFormItem.SalesOrganization__c = salesArea.SalesOrganization__c;
                    mRequestFormItem.SalesOrganizationTX__c = salesArea.SalesOrganization__c;
                    insert mRequestFormItem;
    
                    responseResult.result = true;
                    responseResult.message = 'Success';
                    responseResult.resRecordId = mRequestFormItem.Id;
                }
            } else { // edit from item detail screen
                    System.debug('Debug existing item id '+mItemId);
                    CTRRequestFormItem__c mRequestFormItem = [SELECT Id,CTRRequestFormHeader__c,SalesDistrict__c,DeliveryPriority__c,ShippingConditions__c,DeliveryPlant__c,MaxPartialDeliveries__c,PartialDeliveriesperitem__c,UnderdeliveryTolerance__c,OverdeliveryTolerance__c,AccountAssignmentGroup__c FROM CTRRequestFormItem__c WHERE Id =: mItemId];

                    // CTRRequestFormHeader__c mRequestFormHeader = [SELECT Id FROM CTRRequestFormHeader__c WHERE Id =: mRequestFormItem.CTRRequestFormHeader__c];
                    CTRRequestFormHeader__c mRequestFormHeader = new CTRRequestFormHeader__c();


                    mRequestFormHeader.Id = mRequestFormItem.CTRRequestFormHeader__c;
                    mRequestFormHeader.CompanyNameENF__c = String.valueOf(objMap.get('CompanyNameENF__c'));
                    mRequestFormHeader.CustomerNameLocal1__c = String.valueOf(objMap.get('CustomerNameLocal1__c'));
                    mRequestFormHeader.Country__c = String.valueOf(objMap.get('Country__c'));
                    mRequestFormHeader.TaxCode1__c = String.valueOf(objMap.get('TaxCode1__c'));
                    mRequestFormHeader.CustomerSearchTermEN__c = String.valueOf(objMap.get('CustomerSearchTermEN__c'));
                    mRequestFormHeader.CustomerSearchTermLocal__c = String.valueOf(objMap.get('CustomerSearchTermLocal__c'));
                    mRequestFormHeader.HousenoLocal__c = String.valueOf(objMap.get('HousenoLocal__c'));
                    mRequestFormHeader.BuildingCodeLocal__c = String.valueOf(objMap.get('BuildingCodeLocal__c'));
                    mRequestFormHeader.RoomLocal__c = String.valueOf(objMap.get('RoomLocal__c'));
                    mRequestFormHeader.FloorLocal__c = String.valueOf(objMap.get('FloorLocal__c'));
                    mRequestFormHeader.CoName__c = String.valueOf(objMap.get('CoName__c'));
                    mRequestFormHeader.StreetLocal__c = String.valueOf(objMap.get('StreetLocal__c'));
                    mRequestFormHeader.SubDistrictLocalText__c = String.valueOf(objMap.get('SubDistrictLocalText__c'));
                    mRequestFormHeader.DistrictLocalText__c = String.valueOf(objMap.get('DistrictLocalText__c'));
                    mRequestFormHeader.CityStateLocal__c = String.valueOf(objMap.get('CityStateLocal__c'));
                    mRequestFormHeader.PostalCodeLocalText__c = String.valueOf(objMap.get('PostalCodeLocalText__c'));
                    mRequestFormHeader.LocationInGoogleMapsLinks__c = String.valueOf(objMap.get('LocationInGoogleMapsLinks__c'));
                    mRequestFormHeader.LocationInGoogleMapsGeolocation__Latitude__s = Decimal.valueOf(String.valueOf(objMap.get('LocationInGoogleMapsGeolocation__Latitude__s')));
                    mRequestFormHeader.LocationInGoogleMapsGeolocation__Longitude__s = Decimal.valueOf(String.valueOf(objMap.get('LocationInGoogleMapsGeolocation__Longitude__s')));
                    mRequestFormHeader.ContactSalutation__c = String.valueOf(objMap.get('ContactSalutation__c'));
                    mRequestFormHeader.Nickname__c = String.valueOf(objMap.get('Nickname__c'));
                    mRequestFormHeader.FirstName__c = String.valueOf(objMap.get('FirstName__c'));
                    mRequestFormHeader.LastName__c = String.valueOf(objMap.get('LastName__c'));
                    mRequestFormHeader.Position__c = String.valueOf(objMap.get('Position__c'));
                    mRequestFormHeader.Email__c = String.valueOf(objMap.get('Email__c'));
                    mRequestFormHeader.MobileCountryCode__c = String.valueOf(objMap.get('MobileCountryCode__c'));
                    mRequestFormHeader.CountryCode__c = String.valueOf(objMap.get('CountryCode__c'));
                    mRequestFormHeader.MobilePhone__c = String.valueOf(objMap.get('MobilePhone__c'));
                    mRequestFormHeader.PhoneCountryCode__c = String.valueOf(objMap.get('PhoneCountryCode__c'));
                    mRequestFormHeader.Phone__c = String.valueOf(objMap.get('Phone__c'));
                    mRequestFormHeader.FaxCountryCode__c = String.valueOf(objMap.get('FaxCountryCode__c'));
                    mRequestFormHeader.Fax__c = String.valueOf(objMap.get('Fax__c'));
                    mRequestFormHeader.TransportationZone__c = String.valueOf(objMap.get('TransportationZone__c')); 
                    mRequestFormHeader.InternalEditField__c = objMap.get('HeaderInternalEditField') != null ? String.valueOf(objMap.get('HeaderInternalEditField')) : null; 
                    mRequestFormHeader.TAXClassification__c = String.valueOf(objMap.get('TAXClassification__c'));
                
                    // CTRRequestFormItem__c mRequestFormItem = new CTRRequestFormItem__c();
                    // mRequestFormItem.CTRRequestFormHeader__c = mRequestFormHeader.Id;
                    // mRequestFormItem.Customer__c = customerId;
                    // mRequestFormItem.RecordTypeId = itemRecordTypeId;
                    // mRequestFormItem.Status__c = 'New';
                    // mRequestFormItem.Approval_Step__c = 'Open';
                    // mRequestFormItem.Sensitive__c = true;
                    mRequestFormItem.SalesDistrict__c = String.valueOf(objMap.get('SalesDistrict__c'));
                    mRequestFormItem.DeliveryPriority__c = String.valueOf(objMap.get('DeliveryPriority__c'));
                    mRequestFormItem.ShippingConditions__c = String.valueOf(objMap.get('ShippingConditions__c'));
                    mRequestFormItem.DeliveryPlant__c = String.valueOf(objMap.get('DeliveryPlant__c'));
                    mRequestFormItem.MaxPartialDeliveries__c = Decimal.valueOf((String)objMap.get('MaxPartialDeliveries__c')) != null ? Decimal.valueOf((String)objMap.get('MaxPartialDeliveries__c')) : null;
                    mRequestFormItem.PartialDeliveriesperitem__c = String.valueOf(objMap.get('PartialDeliveriesperitem__c'));
                    mRequestFormItem.UnderdeliveryTolerance__c = Decimal.valueOf((String)objMap.get('UnderdeliveryTolerance__c'));
                    mRequestFormItem.OverdeliveryTolerance__c = Decimal.valueOf((String)objMap.get('OverdeliveryTolerance__c'));
                    mRequestFormItem.AccountAssignmentGroup__c = String.valueOf(objMap.get('AccountAssignmentGroup__c'));
                    mRequestFormItem.InternalEditField__c = objMap.get('ItemInternalEditField') != null ? String.valueOf(objMap.get('ItemInternalEditField')) : null; 

                    update mRequestFormHeader;
                    update mRequestFormItem;

                    responseResult.result = true;
                    responseResult.message = 'Success';
                    responseResult.resRecordId = mRequestFormItem.Id;
            }
            
            return responseResult;
        }
        catch(Exception e)
        {
            String mError = 'CTRRequestShipToController.saveRequesShipTo Line:'+e.getmessage()+' line:'+e.getLineNumber();
            System.debug('CTRRequestShipToController.saveRequesShipTo'+e.getmessage()+' line:'+e.getLineNumber());      
            responseResult.message = e.getmessage();      
            return responseResult;
        }
    }
    
    public class DefaultDataWrapper {
        @AuraEnabled public CTRRequestFormHeader__c mRequestHeader {get; set;}
        @AuraEnabled public CTRRequestFormItem__c mRequestItem {get; set;} 
    }
    
    @AuraEnabled
    public static DefaultDataWrapper getDefaultItem(Id mItemId)
    {
        try 
        {
            CTRRequestFormItem__c responseItem = [SELECT Id, CTRRequestFormHeader__c, Name, Customer__c, Customer__r.Country__c, Customer__r.Country__r.Description__c, SalesOrganizationTX__c, Division__c, DistributionChannel__c, toLabel(SalesOrganizationTX__c) salesOrgLabel, toLabel(Division__c) divisionLabel, toLabel(DistributionChannel__c) distChLabel, InternalEditField__c FROM CTRRequestFormItem__c WHERE Id =: mItemId LIMIT 1];

            CTRRequestFormHeader__c responseHeader = [SELECT Id,InternalEditField__c  FROM CTRRequestFormHeader__c WHERE Id =: responseItem.CTRRequestFormHeader__c LIMIT 1];

            DefaultDataWrapper response = new DefaultDataWrapper();
            response.mRequestHeader = responseHeader;
            response.mRequestItem = responseItem;

            return response;
        } 
        catch (Exception e) 
        {
            System.debug('Error From CTRRequestShipToController.getDefaultItem Line: '+e.getLineNumber()+' || Message:'+e.getMessage());
            return null;
        }
    }
}