force-app/main/default/objects/C360_BuyingPerformanceMonthlyTOP__c.object
<CustomObject>
    <fields>
        <fullName>CurrencyLocal__c</fullName>
        <description>From SAP, Allocation, and BI Currency (Local)</description>
        <label>Currency (Local)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Currency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Monthly Lifting and Allocation</relationshipLabel>
        <relationshipName>TOP_Month_Buying_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DistributionChannel__c</fullName>
        <label>Distribution Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DistributionChannel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <description>Month</description>
        <label>Month</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NetProfitLocal__c</fullName>
        <description>From BI</description>
        <label>Net Profit (Local)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NetValueLocal__c</fullName>
        <description>From SAP, Allocation, and BI</description>
        <label>Net Value (Local)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product Name</description>
        <label>Product Name</label>
        <referenceTo>C360_Product__c</referenceTo>
        <relationshipName>TOP_Month_Buying_Performance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SalesOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <description>From SAP</description>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Monthly Buying Performance</label>
    <nameField>
        <displayFormat>BPM{00000000}</displayFormat>
        <label>Monthly Buying Performance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <recordTypes>
        <fullName>TXMonthlyPerformance</fullName>
        <active>true</active>
        <description>TS Group</description>
        <label>TX Monthly Performance</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_Product__c.object
<CustomObject>
    <fields>
        <fullName>MaterialCode__c</fullName>
        <externalId>true</externalId>
        <label>Material Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/DistributionChannel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>10-Domestic Major Oil</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11-Domestic Third Party</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12-Domestic TOP Group</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>13-Domestic Other</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>14-Domestic User/Blnder</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>15-Domestic Trade/Resel</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>16-Domestic</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>17-Free Tax Zone</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>20-Export Direct</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>21-Export Indirect</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>22-Export Free Zone</label>
    </customValue>
    <customValue>
        <fullName>23</fullName>
        <label>23-Exp Direct Trading</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>24-Exp Indirect Trading</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>25-Export</label>
    </customValue>
    <customValue>
        <fullName>26</fullName>
        <label>26-Export Direct Broker</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>30-Import (VAT)</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>31-Import Indirect(VAT)</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>32-Import (Non-VAT)</label>
    </customValue>
    <customValue>
        <fullName>33</fullName>
        <label>33-Import Indirect(NonV</label>
    </customValue>
    <customValue>
        <fullName>IC</fullName>
        <label>IC-Intra-comp. Transfer</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <isActive>false</isActive>
        <label>01</label>
    </customValue>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SalesOrganization.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1100</fullName>
        <label>1100-Thai Oil</label>
    </customValue>
    <customValue>
        <fullName>1300</fullName>
        <label>1300-Thai Paraxylene</label>
    </customValue>
    <customValue>
        <fullName>1400</fullName>
        <label>1400-Thai Lube Base</label>
    </customValue>
    <customValue>
        <fullName>1700</fullName>
        <label>1700-LABIX</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <label>2000-TOP NEXT International Company Limited</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <label>9100-TOP SOLVENT VIETNAM</label>
    </customValue>
    <customValue>
        <fullName>9200</fullName>
        <label>9200-PT.TIRTA SURYA RAYA</label>
    </customValue>
    <customValue>
        <fullName>9300</fullName>
        <label>9300-JSKem Pte Ltd</label>
    </customValue>
    <customValue>
        <fullName>9400</fullName>
        <label>9400-TSChem</label>
    </customValue>
    <customValue>
        <fullName>0001</fullName>
        <isActive>false</isActive>
        <label>0001</label>
    </customValue>
    <masterLabel>Sales Organization</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/C360_TxBuyingPerformanceMonthlyList.cls
public class C360_TxBuyingPerformanceMonthlyList 
{
    public class BuyingPerformanceMonthlyWrapper
    {       
        @AuraEnabled public string VolumeMT;
        @AuraEnabled public String NetValueLocal;
        @AuraEnabled public String NetProfitLocal;    
        @AuraEnabled public String count;
        @AuraEnabled public Integer itemsize;
        @AuraEnabled public List<ItemWrapper> itemList;
    }
    class ItemWrapper
    {
        @AuraEnabled public String MonthlyBuyingPerformanceNumber;
        @AuraEnabled public String CurrencyLocal;
        @AuraEnabled public String Product;
        @AuraEnabled public String DistributionChannel;    
        @AuraEnabled public String SalesOrganization;
        @AuraEnabled public String Year;
        @AuraEnabled public String Month;
        @AuraEnabled public Integer index;
        @AuraEnabled public String itemId;
    }
    
    @AuraEnabled(cacheable=false)
    public static List<BuyingPerformanceMonthlyWrapper> getTableDetails(String customerID,String status)
    {
        List<BuyingPerformanceMonthlyWrapper>returnList = new List<BuyingPerformanceMonthlyWrapper>();
        try {   
            map<String,Decimal>VolumeMTONMap = new map<String,Decimal>();
            map<String,Decimal>NetValueLocalMap = new map<String,Decimal>();
            map<String,Decimal>NetProfitLocalMap = new map<String,Decimal>();
            AggregateResult[] result  = [SELECT Year__c,Month__c,SalesOrganization__c,DistributionChannel__c,Product__r.MaterialCode__c,Product__r.Name,CurrencyLocal__c,SUM(Volume__c) VolumeMTON,SUM(NetValueLocal__c) NetValueLocal,SUM(NetProfitLocal__c) NetProfitLocal from C360_BuyingPerformanceMonthlyTOP__c where Customer__c =: customerID and recordtype.developername = 'TXMonthlyPerformance' group by Year__c,SalesOrganization__c ,DistributionChannel__c,Month__c,Product__r.MaterialCode__c,Product__r.Name,CurrencyLocal__c];
            C360_BuyingPerformanceMonthlyTOP__c[] sfBuyingList =[SELECT Id,Year__c,Name,SalesOrganization__c,DistributionChannel__c,Month__c,Product__r.MaterialCode__c,Product__r.Name,CurrencyLocal__c from C360_BuyingPerformanceMonthlyTOP__c where Customer__c =: customerID and recordtype.developername ='TXMonthlyPerformance' order by name desc];
            if(!result.isempty())
            {
                for (AggregateResult ar : result)  {
                    String key = String.valueof(ar.get('Year__c'))+String.valueof(ar.get('Month__c'))+String.valueof(ar.get('SalesOrganization__c'))+String.valueof(ar.get('DistributionChannel__c'))+String.valueof(ar.get('MaterialCode__c'))+String.valueof(ar.get('Name'))+String.valueof(ar.get('CurrencyLocal__c'));
                    VolumeMTONMap.put(key,(Decimal)ar.get('VolumeMTON'));
                    NetValueLocalMap.put(key,(Decimal)ar.get('NetValueLocal'));
                    NetProfitLocalMap.put(key,(Decimal)ar.get('NetProfitLocal'));
                }
            }
            List<String> args = new String[]{'0','number','###,###,##0.00'};
            Integer count = 0;
            Map<String,List<C360_BuyingPerformanceMonthlyTOP__c>>buyingItemMap = new Map<String,List<C360_BuyingPerformanceMonthlyTOP__c>>();
            if(!sfBuyingList.isempty())
            {
                for(C360_BuyingPerformanceMonthlyTOP__c item : sfBuyingList)
                {
                    String key = item.Year__c+item.Month__c+item.SalesOrganization__c+item.DistributionChannel__c+item.Product__r.MaterialCode__c+item.Product__r.Name+item.CurrencyLocal__c;
                    if(buyingItemMap.containskey(key))
                    {
                        List<C360_BuyingPerformanceMonthlyTOP__c>temp =  buyingItemMap.get(key);
                        temp.add(item);
                        buyingItemMap.put(key,temp);
                    }
                    else
                    {
                        List<C360_BuyingPerformanceMonthlyTOP__c>temp = new List<C360_BuyingPerformanceMonthlyTOP__c>();
                        temp.add(item);
                        buyingItemMap.put(key,temp);
                    }  
                }
            }
            for(String key : VolumeMTONMap.keyset())
            {
                BuyingPerformanceMonthlyWrapper item = new BuyingPerformanceMonthlyWrapper();
                if(VolumeMTONMap.containskey(key))
                {
                    item.VolumeMT  = '0';
                    item.NetValueLocal  = '0';
                    item.NetProfitLocal  = '0';
                    if(VolumeMTONMap.get(key) != null)
                    {
                        Decimal volume = VolumeMTONMap.get(key).setScale(2);
                        
                        item.VolumeMT  =String.format(volume.format(), args);
                    }
                    if(NetValueLocalMap.get(key) != null)
                    {
                        Decimal netlocal = NetValueLocalMap.get(key).setScale(2);
                        item.NetValueLocal  = String.format(netlocal.format(), args);
                    }
                    if(NetProfitLocalMap.get(key) != null)
                    {
                        Decimal profitlocal = NetProfitLocalMap.get(key).setScale(2);
                        item.NetProfitLocal  = String.format(profitlocal.format(), args);
                    }  
                }
                
                Schema.DescribeFieldResult salesorgResult = C360_BuyingPerformanceMonthlyTOP__c.SalesOrganization__c.getDescribe();
                List<Schema.PicklistEntry> salesorgpicklistValues = salesorgResult.getPickListValues();
                Map<String, String> salesorgMap = new Map<String, String>();
                for(Schema.PicklistEntry plVal : salesorgpicklistValues) {
                    salesorgMap.put(plVal.getValue() ,plVal.getLabel());
                }
                
                Schema.DescribeFieldResult channelResult = C360_BuyingPerformanceMonthlyTOP__c.DistributionChannel__c.getDescribe();
                List<Schema.PicklistEntry> channelpicklistValues = channelResult.getPickListValues();
                Map<String, String> channelMap = new Map<String, String>();
                for(Schema.PicklistEntry plVal : channelpicklistValues) {
                    channelMap.put(plVal.getValue() ,plVal.getLabel());
                }
                
                if(buyingItemMap.containskey(key))
                {
                    if(buyingItemMap.get(key).size() > 0)
                    {
                        item.count = String.valueof(buyingItemMap.get(key).size());
                        List<ItemWrapper>tempList = new List<ItemWrapper>();
                        Integer idx = 0;
                        for(C360_BuyingPerformanceMonthlyTOP__c buyingItem : buyingItemMap.get(key))
                        {
                            ItemWrapper temp = new ItemWrapper();
                            temp.CurrencyLocal = buyingItem.CurrencyLocal__c;
                            temp.Product = buyingItem.Product__r.Name;//MaterialCode__c
                            temp.DistributionChannel = channelMap.get(buyingItem.DistributionChannel__c);
                            temp.SalesOrganization = salesorgMap.get(buyingItem.SalesOrganization__c);
                            temp.Year = buyingItem.Year__c;
                            temp.Month = buyingItem.Month__c;
                            temp.MonthlyBuyingPerformanceNumber = buyingItem.Name;
                            temp.itemId = buyingItem.Id;
                            temp.index = idx;
                            tempList.add(temp);
                            idx = idx +1;
                        }
                        item.itemList = tempList;
                        count = count + tempList.size();
                    }
                }   
                returnList.add(item);
            }
            List<BuyingPerformanceMonthlyWrapper>tempList = new List<BuyingPerformanceMonthlyWrapper>();
            Integer itemsize = 0;
            Integer lastitemsize = 0;
            if(status == 'Loading' && returnList.size() > 0)
            {   
                itemsize = returnList[0].itemList.size();
                for(BuyingPerformanceMonthlyWrapper item : returnList)
                {
                    BuyingPerformanceMonthlyWrapper temp = new BuyingPerformanceMonthlyWrapper();
                    temp = item;
                    if(itemsize > 10)
                    {
                        Integer diff = 10 - lastitemsize; 
                        List<ItemWrapper>itemwrapperList = new List<ItemWrapper>();
                        for(Integer i = 0 ; i < diff ; i++)
                        {
                            itemwrapperList.add(item.itemList[i]);
                        }
                        temp.itemList = itemwrapperList;
                        tempList.add(temp);
                        break;
                    }
                    else
                    {
                        tempList.add(temp);
                    }
                    lastitemsize = itemsize;
                    itemsize = itemsize + item.itemList.size();    
                }
            }
            
            BuyingPerformanceMonthlyWrapper addItemSize = new BuyingPerformanceMonthlyWrapper();
            addItemSize.itemsize = count;
            if(tempList.size() > 0)
            {
                tempList.add(addItemSize);
                return tempList;
            }
            else
            {
                returnList.add(addItemSize);
                return returnList; 
            }   
        }
        catch (Exception e) 
        {
            system.debug(e.getLineNumber() + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }   
}