force-app/main/default/objects/CCE_Approval_Process_19__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>CCE_Approval_Process1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SME</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected User is not SME. Please select SME user.</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>PM</value>
            </filterItems>
            <infoMessage>Please select SME user.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Step 19: CCE Approval Process</relationshipLabel>
        <relationshipName>Step_19_CCE_Approval_Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Step 19 : CCE Approval Process</label>
    <nameField>
        <displayFormat>WP19-{00000}</displayFormat>
        <label>Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCE_Approval_Process__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>CCE_Approval_Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SME</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected User is not SME. Please select SME user.</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>PM</value>
            </filterItems>
            <infoMessage>Please select SME user.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Step 11: CCE Approval Process</relationshipLabel>
        <relationshipName>Step_11_CCE_Approval_Process</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Step 11 : CCE Approval Process</label>
    <nameField>
        <displayFormat>WP11-{00000}</displayFormat>
        <label>Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCE_with_Sub_Contract_19__c.object
<CustomObject>
    <fields>
        <fullName>Not_Applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Not Applicable</label>
        <type>Checkbox</type>
    </fields>
    <label>CCE with Sub Contract*</label>
    <nameField>
        <label>Subcontract Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CCE_with_Sub_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Not_Applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Not Applicable</label>
        <type>Checkbox</type>
    </fields>
    <label>CCE with Sub Contract*</label>
    <nameField>
        <label>Subcontract Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ITB_Standard_18__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Invitation_to_Bid</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SME</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected User is not SME. Please select SME user.</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>PM</value>
            </filterItems>
            <infoMessage>Please select SME user.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Step 18: ITB Standard</relationshipLabel>
        <relationshipName>Step_18_ITB_Standard</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Step 18 : ITB Standard</label>
    <nameField>
        <displayFormat>WP18-{00000}</displayFormat>
        <label>Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ITB_Standard__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>ITB_Standard</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SME</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected User is not SME. Please select SME user.</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>PM</value>
            </filterItems>
            <infoMessage>Please select SME user.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Step 10: ITB Standard</relationshipLabel>
        <relationshipName>Step_10_ITB_Standard</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Step 10 : ITB Standard</label>
    <nameField>
        <displayFormat>WP10-{00000}</displayFormat>
        <label>Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ITB_with_Sub_Contract_18__c.object
<CustomObject>
    <fields>
        <fullName>ITB_Standard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ITB Standard</label>
        <referenceTo>ITB_Standard_18__c</referenceTo>
        <relationshipName>ITB_with_Sub_Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Not_Applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Not Applicable</label>
        <type>Checkbox</type>
    </fields>
    <label>ITB with Sub Contract*</label>
    <nameField>
        <label>Subcontract Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ITB_with_Sub_Contract__c.object
<CustomObject>
    <fields>
        <fullName>ITB_Standard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ITB Standard</label>
        <referenceTo>ITB_Standard__c</referenceTo>
        <relationshipName>ITB_with_Sub_Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Not_Applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Not Applicable</label>
        <type>Checkbox</type>
    </fields>
    <label>ITB with Sub Contract*</label>
    <nameField>
        <label>Subcontract Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Master_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Data</label>
        <referenceTo>Master_Data__c</referenceTo>
        <relationshipLabel>Master Data Detail</relationshipLabel>
        <relationshipName>Master_Data_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SME</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected user is not SME user. Please select SME user.</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>PM</value>
            </filterItems>
            <infoMessage>Please select SME user.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Master_Data_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Process_Group__c</fullName>
        <label>Work Process Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Group</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Process_No__c</fullName>
        <label>Work Process No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Master Data Detail</label>
    <nameField>
        <label>Work Process Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Please select only PM user.</errorMessage>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>TOPPMP-AI</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>CPEM Admin</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Project</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Number__c</fullName>
        <label>Project Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Procurement_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Project_Procurement_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SME</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected User is not SME. Please select SME user.</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>PM</value>
            </filterItems>
            <infoMessage>Please select SME user.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Step 5: Project Procurement Plan</relationshipLabel>
        <relationshipName>Step_5_Project_Procurement_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Step 5 : Project Procurement Plan</label>
    <nameField>
        <displayFormat>WP5-{00000}</displayFormat>
        <label>Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subcontractor_Bidding__c.object
<CustomObject>
    <fields>
        <fullName>Project_Procurement_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Procurement Plan</label>
        <referenceTo>Project_Procurement_Plan__c</referenceTo>
        <relationshipName>Subcontractor_Bidding</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subcontractor Bidding*</label>
    <nameField>
        <label>Subcontractor Bidding Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Group.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Project Scope and Information</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Project Cost Control</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Project Schedule Control</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Procurement Status Report</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Document Management</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Engineering</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Material Control</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Execution</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Project Handover</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Risk Analyst</label>
    </customValue>
    <masterLabel>Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TC_TRG_UpdateNotApplicableWorkProcess.cls
/* Test class for Not Applicable in All Work Processes */
@isTest
public class TC_TRG_UpdateNotApplicableWorkProcess {

    public static void MasterDataInfo() {
        //Master Data
        User SMEUser = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'SME'].Id,
            UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI AD&SME'].Id,
            LastName = 'last',
            Email = 'test@thaioilgroup.com',
            Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
            CompanyName = 'Thaioil',
            Alias = 'test',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
            );
        insert(SMEUser);
        
        System.runAs(SMEUser) {
            Master_Data__c MD = new Master_Data__c();
            MD.Name = 'SME and Guideline';
            insert(MD);
            
            List<Master_Data_Detail__c> MDDs = new List<Master_Data_Detail__c>();
            
            Master_Data_Detail__c MDD1 = new Master_Data_Detail__c();
            MDD1.Work_Process_No__c = 0;
            MDD1.Group__c = 10;
            MDD1.Name = 'Project Risk Assessment';
            MDD1.Work_Process_Group__c = '10';
            MDD1.Master_Data__c = MD.Id;
            MDD1.SME__c = SMEUser.Id;
            MDDs.add(MDD1);
            
            insert(MDDs);
        }
    }
    
    public static TestMethod void WP10NotApplicableTrue() {
        
        MasterDataInfo();
        
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'PM'].Id,
        UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI PM'].Id,
        LastName = 'last',
        Email = 'test@thaioilgroup.com',
        Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
        CompanyName = 'Thaioil',
        Alias = 'test',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US'
    	);
        insert(u);
        
        System.runAs(u) {
            
            Project__c Proj = new Project__c();
            Proj.Name = 'Test Project';
            Proj.Project_Number__c = 'Test 001';
            Proj.Project_Manager__c = u.Id;
            insert(Proj);
            
            Project_Procurement_Plan__c WP5 = [select id, Project__c from Project_Procurement_Plan__c where Project__c =: Proj.Id];
            
            Subcontractor_Bidding__c WP5SubContract = new Subcontractor_Bidding__c();
            WP5SubContract.Project_Procurement_Plan__c = WP5.Id;
            insert(WP5SubContract);
            
            ITB_Standard__c WP10 = [select id, Project__c from ITB_Standard__c where Project__c =: Proj.Id];
            
            ITB_with_Sub_Contract__c WP10SubContract = new ITB_with_Sub_Contract__c();
            WP10SubContract.ITB_Standard__c = WP10.Id;
            WP10SubContract.Not_Applicable__c = false;
            insert(WP10SubContract);
            
            ITB_Standard_18__c WP18 = [select id, Project__c from ITB_Standard_18__c where Project__c =: Proj.Id];
            
            ITB_with_Sub_Contract_18__c WP18SubContract = new ITB_with_Sub_Contract_18__c();
            WP18SubContract.Name = 'Test';
            WP18SubContract.ITB_Standard__c = WP18.Id;
            WP18SubContract.BE_ITB_Subcontract_10_ID__c = WP10SubContract.Id;
            WP18SubContract.Not_Applicable__c = false;
            insert(WP18SubContract);
            
            WP10SubContract.Not_Applicable__c = true;
            WP10SubContract.BE_ITB_Subcontract_18_ID__c = WP10SubContract.Id;
            update(WP10SubContract);
        }
    }
    
    public static TestMethod void WP10NotApplicableFalse() {
        
        MasterDataInfo();
        
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'PM'].Id,
        UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI PM'].Id,
        LastName = 'last',
        Email = 'test@thaioilgroup.com',
        Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
        CompanyName = 'Thaioil',
        Alias = 'test',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US'
    	);
        insert(u);
        
        System.runAs(u) {
            
            Project__c Proj = new Project__c();
            Proj.Name = 'Test Project';
            Proj.Project_Number__c = 'Test 001';
            Proj.Project_Manager__c = u.Id;
            insert(Proj);
                
            Project_Procurement_Plan__c WP5 = [select id, Project__c from Project_Procurement_Plan__c where Project__c =: Proj.Id];
            
            Subcontractor_Bidding__c WP5SubContract = new Subcontractor_Bidding__c();
            WP5SubContract.Project_Procurement_Plan__c = WP5.Id;
            insert(WP5SubContract);
            
            ITB_Standard__c WP10 = [select id, Project__c from ITB_Standard__c where Project__c =: Proj.Id];
            
            ITB_with_Sub_Contract__c WP10SubContract = new ITB_with_Sub_Contract__c();
            WP10SubContract.ITB_Standard__c = WP10.Id;
            WP10SubContract.Not_Applicable__c = true;
            insert(WP10SubContract);
            
            ITB_Standard_18__c WP18 = [select id, Project__c from ITB_Standard_18__c where Project__c =: Proj.Id];
            
            ITB_with_Sub_Contract_18__c WP18SubContract = new ITB_with_Sub_Contract_18__c();
            WP18SubContract.Name = 'Test';
            WP18SubContract.ITB_Standard__c = WP18.Id;
            WP18SubContract.BE_ITB_Subcontract_10_ID__c = WP10SubContract.Id;
            WP18SubContract.Not_Applicable__c = false;
            insert(WP18SubContract);
            
            WP10SubContract.Not_Applicable__c = false;
            WP10SubContract.BE_ITB_Subcontract_18_ID__c = WP10SubContract.Id;
            update(WP10SubContract);
        }
        
    }
    
    public static TestMethod void WP18NotApplicableTrue() {
        
        MasterDataInfo();
        
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'PM'].Id,
        UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI PM'].Id,
        LastName = 'last',
        Email = 'test@thaioilgroup.com',
        Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
        CompanyName = 'Thaioil',
        Alias = 'test',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US'
    	);
        insert(u);
        
        System.runAs(u) {
            
            Project__c Proj = new Project__c();
            Proj.Name = 'Test Project';
            Proj.Project_Number__c = 'Test 001';
            Proj.Project_Manager__c = u.Id;
            insert(Proj);
        
            Project_Procurement_Plan__c WP5 = [select id, Project__c from Project_Procurement_Plan__c where Project__c =: Proj.Id];
            
            Subcontractor_Bidding__c WP5SubContract = new Subcontractor_Bidding__c();
            WP5SubContract.Project_Procurement_Plan__c = WP5.Id;
            insert(WP5SubContract);
            
            ITB_Standard__c WP10 = [select id, Project__c from ITB_Standard__c where Project__c =: Proj.Id];
            
            ITB_with_Sub_Contract__c WP10SubContract = new ITB_with_Sub_Contract__c();
            WP10SubContract.ITB_Standard__c = WP10.Id;
            WP10SubContract.Not_Applicable__c = false;
            insert(WP10SubContract);
            
            ITB_Standard_18__c WP18 = [select id, Project__c from ITB_Standard_18__c where Project__c =: Proj.Id];
            
            ITB_with_Sub_Contract_18__c WP18SubContract = new ITB_with_Sub_Contract_18__c();
            WP18SubContract.Name = 'Test';
            WP18SubContract.ITB_Standard__c = WP18.Id;
            WP18SubContract.BE_ITB_Subcontract_10_ID__c = WP10SubContract.Id;
            WP18SubContract.Not_Applicable__c = false;
            insert(WP18SubContract);
            
            WP10SubContract.BE_ITB_Subcontract_18_ID__c = WP18SubContract.Id;
            update(WP10SubContract);
            
            WP18SubContract.Not_Applicable__c = true;
            update(WP18SubContract);
        }
    }
    
    public static TestMethod void WP18NotApplicableFalse() {
        
        MasterDataInfo();
        
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'PM'].Id,
        UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI PM'].Id,
        LastName = 'last',
        Email = 'test@thaioilgroup.com',
        Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
        CompanyName = 'Thaioil',
        Alias = 'test',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US'
    	);
        insert(u);
        
        System.runAs(u) {
            
            Project__c Proj = new Project__c();
            Proj.Name = 'Test Project';
            Proj.Project_Number__c = 'Test 001';
            Proj.Project_Manager__c = u.Id;
            insert(Proj);
                
            Project_Procurement_Plan__c WP5 = [select id, Project__c from Project_Procurement_Plan__c where Project__c =: Proj.Id];
            
            Subcontractor_Bidding__c WP5SubContract = new Subcontractor_Bidding__c();
            WP5SubContract.Project_Procurement_Plan__c = WP5.Id;
            insert(WP5SubContract);
            
            ITB_Standard__c WP10 = [select id, Project__c from ITB_Standard__c where Project__c =: Proj.Id];
            
            ITB_with_Sub_Contract__c WP10SubContract = new ITB_with_Sub_Contract__c();
            WP10SubContract.ITB_Standard__c = WP10.Id;
            WP10SubContract.Not_Applicable__c = false;
            insert(WP10SubContract);
            
            ITB_Standard_18__c WP18 = [select id, Project__c from ITB_Standard_18__c where Project__c =: Proj.Id];
            
            ITB_with_Sub_Contract_18__c WP18SubContract = new ITB_with_Sub_Contract_18__c();
            WP18SubContract.Name = 'Test';
            WP18SubContract.ITB_Standard__c = WP18.Id;
            WP18SubContract.BE_ITB_Subcontract_10_ID__c = WP10SubContract.Id;
            WP18SubContract.Not_Applicable__c = true;
            insert(WP18SubContract);
            
            WP10SubContract.BE_ITB_Subcontract_18_ID__c = WP18SubContract.Id;
            update(WP10SubContract);
            
            WP18SubContract.Not_Applicable__c = false;
            update(WP18SubContract);
        }        
    }
    
    public static TestMethod void WP11NotApplicableTrue() {
        
        MasterDataInfo();
        
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'PM'].Id,
        UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI PM'].Id,
        LastName = 'last',
        Email = 'test@thaioilgroup.com',
        Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
        CompanyName = 'Thaioil',
        Alias = 'test',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US'
    	);
        insert(u);
        
        System.runAs(u) {
            
            Project__c Proj = new Project__c();
            Proj.Name = 'Test Project';
            Proj.Project_Number__c = 'Test 001';
            Proj.Project_Manager__c = u.Id;
            insert(Proj);
                
            Project_Procurement_Plan__c WP5 = [select id, Project__c from Project_Procurement_Plan__c where Project__c =: Proj.Id];
            
            Subcontractor_Bidding__c WP5SubContract = new Subcontractor_Bidding__c();
            WP5SubContract.Project_Procurement_Plan__c = WP5.Id;
            insert(WP5SubContract);
            
            CCE_Approval_Process__c WP11 = [select id, Project__c from CCE_Approval_Process__c where Project__c =: Proj.Id];
            
            CCE_with_Sub_Contract__c WP11SubContract = new CCE_with_Sub_Contract__c();
            WP11SubContract.CCE_Approval_Process__c = WP11.Id;
            WP11SubContract.Not_Applicable__c = false;
            insert(WP11SubContract);
            
            CCE_Approval_Process_19__c WP19 = [select id, Project__c from CCE_Approval_Process_19__c where Project__c =: Proj.Id];
            
            CCE_with_Sub_Contract_19__c WP19SubContract = new CCE_with_Sub_Contract_19__c();
            WP19SubContract.Name = 'Test';
            WP19SubContract.CCE_Approval_Process__c = WP19.Id;
            WP19SubContract.BE_Sub_Contract_11_ID__c = WP11SubContract.Id;
            insert(WP19SubContract);
            
            WP11SubContract.BE_Sub_Contract_19_ID__c = WP19SubContract.Id;
            WP11SubContract.Not_Applicable__c = true;
            update(WP11SubContract);
        }
    }
    
    public static TestMethod void WP11NotApplicableFalse() {
        
        MasterDataInfo();
        
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'PM'].Id,
        UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI PM'].Id,
        LastName = 'last',
        Email = 'test@thaioilgroup.com',
        Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
        CompanyName = 'Thaioil',
        Alias = 'test',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US'
    	);
        insert(u);
        
        System.runAs(u) {
            
            Project__c Proj = new Project__c();
            Proj.Name = 'Test Project';
            Proj.Project_Number__c = 'Test 001';
            Proj.Project_Manager__c = u.Id;
            insert(Proj);
        
            Project_Procurement_Plan__c WP5 = [select id, Project__c from Project_Procurement_Plan__c where Project__c =: Proj.Id];
            
            Subcontractor_Bidding__c WP5SubContract = new Subcontractor_Bidding__c();
            WP5SubContract.Project_Procurement_Plan__c = WP5.Id;
            insert(WP5SubContract);
            
            CCE_Approval_Process__c WP11 = [select id, Project__c from CCE_Approval_Process__c where Project__c =: Proj.Id];
            
            CCE_with_Sub_Contract__c WP11SubContract = new CCE_with_Sub_Contract__c();
            WP11SubContract.CCE_Approval_Process__c = WP11.Id;
            WP11SubContract.Not_Applicable__c = true;
            insert(WP11SubContract);
            
            CCE_Approval_Process_19__c WP19 = [select id, Project__c from CCE_Approval_Process_19__c where Project__c =: Proj.Id];
            
            CCE_with_Sub_Contract_19__c WP19SubContract = new CCE_with_Sub_Contract_19__c();
            WP19SubContract.Name = 'Test';
            WP19SubContract.CCE_Approval_Process__c = WP19.Id;
            WP19SubContract.BE_Sub_Contract_11_ID__c = WP11SubContract.Id;
            insert(WP19SubContract);
            
            WP11SubContract.BE_Sub_Contract_19_ID__c = WP19SubContract.Id;
            WP11SubContract.Not_Applicable__c = false;
            update(WP11SubContract);
        }
    }
    
    public static TestMethod void WP19NotApplicableTrue() {
        
        MasterDataInfo();
        
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'PM'].Id,
        UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI PM'].Id,
        LastName = 'last',
        Email = 'test@thaioilgroup.com',
        Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
        CompanyName = 'Thaioil',
        Alias = 'test',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US'
    	);
        insert(u);
        
        System.runAs(u) {
            
            Project__c Proj = new Project__c();
            Proj.Name = 'Test Project';
            Proj.Project_Number__c = 'Test 001';
            Proj.Project_Manager__c = u.Id;
            insert(Proj);
        
            Project_Procurement_Plan__c WP5 = [select id, Project__c from Project_Procurement_Plan__c where Project__c =: Proj.Id];
            
            Subcontractor_Bidding__c WP5SubContract = new Subcontractor_Bidding__c();
            WP5SubContract.Project_Procurement_Plan__c = WP5.Id;
            insert(WP5SubContract);
            
            CCE_Approval_Process__c WP11 = [select id, Project__c from CCE_Approval_Process__c where Project__c =: Proj.Id];
            
            CCE_with_Sub_Contract__c WP11SubContract = new CCE_with_Sub_Contract__c();
            WP11SubContract.CCE_Approval_Process__c = WP11.Id;
            WP11SubContract.Not_Applicable__c = false;
            insert(WP11SubContract);
            
            CCE_Approval_Process_19__c WP19 = [select id, Project__c from CCE_Approval_Process_19__c where Project__c =: Proj.Id];
            
            CCE_with_Sub_Contract_19__c WP19SubContract = new CCE_with_Sub_Contract_19__c();
            WP19SubContract.Name = 'Test';
            WP19SubContract.CCE_Approval_Process__c = WP19.Id;
            WP19SubContract.BE_Sub_Contract_11_ID__c = WP11SubContract.Id;
            WP19SubContract.Not_Applicable__c = false;
            insert(WP19SubContract);
            
            WP11SubContract.BE_Sub_Contract_19_ID__c = WP19SubContract.Id;
            update(WP11SubContract);
            
            WP19SubContract.Not_Applicable__c = true;
            update(WP19SubContract);
        }
    }
    
    public static TestMethod void WP19NotApplicableFalse() {
        
        MasterDataInfo();
        
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'PM'].Id,
        UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI PM'].Id,
        LastName = 'last',
        Email = 'test@thaioilgroup.com',
        Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
        CompanyName = 'Thaioil',
        Alias = 'test',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US'
    	);
        insert(u);
        
        System.runAs(u) {
            
            Project__c Proj = new Project__c();
            Proj.Name = 'Test Project';
            Proj.Project_Number__c = 'Test 001';
            Proj.Project_Manager__c = u.Id;
            insert(Proj);
        
            Project_Procurement_Plan__c WP5 = [select id, Project__c from Project_Procurement_Plan__c where Project__c =: Proj.Id];
            
            Subcontractor_Bidding__c WP5SubContract = new Subcontractor_Bidding__c();
            WP5SubContract.Project_Procurement_Plan__c = WP5.Id;
            insert(WP5SubContract);
            
            CCE_Approval_Process__c WP11 = [select id, Project__c from CCE_Approval_Process__c where Project__c =: Proj.Id];
            
            CCE_with_Sub_Contract__c WP11SubContract = new CCE_with_Sub_Contract__c();
            WP11SubContract.CCE_Approval_Process__c = WP11.Id;
            WP11SubContract.Not_Applicable__c = false;
            insert(WP11SubContract);
            
            CCE_Approval_Process_19__c WP19 = [select id, Project__c from CCE_Approval_Process_19__c where Project__c =: Proj.Id];
            
            CCE_with_Sub_Contract_19__c WP19SubContract = new CCE_with_Sub_Contract_19__c();
            WP19SubContract.Name = 'Test';
            WP19SubContract.CCE_Approval_Process__c = WP19.Id;
            WP19SubContract.BE_Sub_Contract_11_ID__c = WP11SubContract.Id;
            WP19SubContract.Not_Applicable__c = true;
            insert(WP19SubContract);
            
            WP11SubContract.BE_Sub_Contract_19_ID__c = WP19SubContract.Id;
            update(WP11SubContract);
            
            WP19SubContract.Not_Applicable__c = false;
            update(WP19SubContract);
        }
    }
    
}