force-app/main/default/objects/CG_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CG_Annual_Running_No__c</fullName>
        <inlineHelpText>CG-{yyyy}-02-{0000}</inlineHelpText>
        <label>CG Annual Running No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CG_Manual_Running_No__c</fullName>
        <inlineHelpText>CG-{yyyy}-03-{0000}</inlineHelpText>
        <label>CG Manual Running No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CG_New_User_Running_No__c</fullName>
        <inlineHelpText>CG-{yyyy}-01-{0000}</inlineHelpText>
        <label>CG New User Running No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>COI_Annual_Running_No__c</fullName>
        <inlineHelpText>COI-{yyyy}-03-{0000}</inlineHelpText>
        <label>COI Annual Running No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>COI_Incident_Running_No__c</fullName>
        <inlineHelpText>Format COI-{yyyy}-01-{0000}</inlineHelpText>
        <label>COI Incident Running No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>COI_New_User_Running_No__c</fullName>
        <inlineHelpText>COI-{yyyy}-02-{0000}</inlineHelpText>
        <label>COI New User Running No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gift_Running_No__c</fullName>
        <inlineHelpText>GIFT-{yyyy}-{0000}</inlineHelpText>
        <label>Gift Running No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>CG Config</label>
</CustomObject>

force-app/main/default/objects/CG_Reporting__c.object
<CustomObject>
    <fields>
        <fullName>Employee_Id__c</fullName>
        <formula>Owner:User.Employee_Id__c</formula>
        <label>Employee Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Duration__c</fullName>
        <label>End Duration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <formula>Owner:User.Function__c</formula>
        <label>Function</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GenerateFromBatch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GenerateFromBatch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Owner_Department__c</fullName>
        <label>Owner Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Function__c</fullName>
        <label>Owner Function</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Section__c</fullName>
        <label>Owner Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Unit__c</fullName>
        <label>Owner Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Running_No__c</fullName>
        <label>Running No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Duration__c</fullName>
        <label>Start Duration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_JSON__c</fullName>
        <label>Status JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WaitingForSubmit</fullName>
                    <label>Waiting for Submit</label>
                </value>
                <value>
                    <fullName>WaitingSupervisor</fullName>
                    <label>Waiting Supervisor</label>
                </value>
                <value>
                    <fullName>WaitingGLVP</fullName>
                    <label>Waiting GLVP</label>
                </value>
                <value>
                    <fullName>WaitingGLGC</fullName>
                    <label>Waiting GLGC</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Report__c</fullName>
        <label>Type of Report</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COIAnnual</fullName>
                    <label>COI (Annual Report)</label>
                </value>
                <value>
                    <fullName>COIIncident</fullName>
                    <label>COI (Incident Report)</label>
                </value>
                <value>
                    <fullName>COINewEmployee</fullName>
                    <label>COI (New Employee Report)</label>
                </value>
                <value>
                    <fullName>CGNewEmployee</fullName>
                    <label>CG Manual (New Employee)</label>
                </value>
                <value>
                    <fullName>CGAnnual</fullName>
                    <label>CG Manual (Annual)</label>
                </value>
                <value>
                    <fullName>CGManual</fullName>
                    <label>CG Manual (Manual)</label>
                </value>
                <value>
                    <fullName>GiftRegistration</fullName>
                    <label>Gift Registration</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CG_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CG Reporting</label>
    <nameField>
        <displayFormat>Report-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PISUsers__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EMAIL__c</fullName>
        <label>EMAIL</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EMPLOYEEID__c</fullName>
        <externalId>true</externalId>
        <label>EMPLOYEEID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ENFIRSTNAME__c</fullName>
        <label>ENFIRSTNAME</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ENLASTNAME__c</fullName>
        <label>ENLASTNAME</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FUNCTION__c</fullName>
        <label>FUNCTION</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HOLDERPOSITION__c</fullName>
        <label>HOLDERPOSITION</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LEVEL__c</fullName>
        <label>LEVEL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LineManagerUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LineManagerUser</label>
        <referenceTo>User</referenceTo>
        <relationshipName>LMPISUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAINPOSITION__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MAINPOSITION</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ORGID__c</fullName>
        <label>ORGID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POSID__c</fullName>
        <label>POSID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReportToEmail__c</fullName>
        <label>ReportToEmail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ReportToID__c</fullName>
        <label>ReportToID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReportToPOS__c</fullName>
        <label>ReportToPOS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReportToUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ReportToUser</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PISUsers_ReportToUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subcordinate__c</fullName>
        <label>Subcordinate</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PISUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PISUsers</label>
    <nameField>
        <label>UserID</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SD_Company__c.object
<CustomObject>
    <fields>
        <fullName>Company_Full_Name__c</fullName>
        <label>Company Full Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Master Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CG_Home_API_Test.cls
@isTest
public class CG_Home_API_Test {

    public static testMethod void DoPostTest() {
        
        User testUser = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'Non Operation'].Id,
            LastName = 'Test',
            Email = 'test@thaioilgroup.com',
            Username = 'test@thaioilgroup.com.icr',
            CompanyName = 'TOP',
            Alias = 'test',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Employee_Id__c = '0000001'
            );
        insert(testUser);
        
        PISUsers__c thaninthon = new PISUsers__c();
        thaninthon.Active__c = true;
        thaninthon.MAINPOSITION__c = true;
        thaninthon.EMPLOYEEID__c = '08000288';
        thaninthon.Name = 'Test';
        thaninthon.LEVEL__c = 'Junior';
        thaninthon.ORGID__c = '00000818';
        thaninthon.POSID__c = '00000544';
        thaninthon.ENFIRSTNAME__c = 'Test';
        thaninthon.ENLASTNAME__c = 'Test';
        thaninthon.HOLDERPOSITION__c = '00000544';
        thaninthon.EMAIL__c = 'test@thaioilgroup.com';
        thaninthon.User__c = testUser.Id;
        thaninthon.ReportToPOS__c = '00001365';
        thaninthon.ReportToID__c = '00000598';
        thaninthon.ReportToEmail__c = 'test@thaioilgroup.com';
        thaninthon.ReportToUser__c = testUser.Id;
        thaninthon.Subcordinate__c = '["08000288"]';
        thaninthon.LineManagerUser__c = testUser.Id;
        thaninthon.FUNCTION__c = 'EVPC';
        insert(thaninthon);
        
        InsertUserToGroup(testUser.Id);
        
        System.runAs(testUser) {
            
        	Test.startTest();  
        
            CG_Reporting__c CGReporting = new CG_Reporting__c();
            CGReporting.Running_No__c = 'COI-2022-01-0001';
            CGReporting.OwnerId = testUser.Id;
            CGReporting.User__c = testUser.Id;
            CGReporting.Start_Duration__c = date.today();
            CGReporting.End_Duration__c = date.today();
            CGReporting.Type_of_Report__c = String.ValueOf(CG_Enum.COIReportType.COINewEmployee);
            CGReporting.Status__c = String.ValueOf(CG_Enum.ReportStatus.WaitingForSubmit);
            CGReporting.GenerateFromBatch__c = true;
            CGReporting.Status_JSON__c = '{"status":{"value":"WaitingForSubmit","key":"WaitingForSubmit","enumName":"WaitingForSubmit"},"reportId":null,"historyWorkflows":null,"currentWorkflow":{"submittedDate":null,"createdDate":"2022-07-07T00:00:00.000Z","approvers":null}}';
            CGReporting.Owner_Function__c = 'EVPC';
            CGReporting.Owner_Department__c = 'EVPO';
            CGReporting.Owner_Section__c = 'SCSE';
            CGReporting.Owner_Unit__c = 'ABCD';
            insert(CGReporting);
            
            //Add Company
            SD_Company__c Company = new SD_Company__c();
            Company.name = 'TOP';
            Company.Company_Full_Name__c = 'TOP';
            Company.Order__c = 0;
            insert(Company);
            
            //CG Config
            CG_Config__c CGConfig = new CG_Config__c();
            CGConfig.Year__c = '2022';
            CGConfig.COI_New_User_Running_No__c = '0';
            CGConfig.COI_Incident_Running_No__c = '0';
            CGConfig.COI_Annual_Running_No__c = '0';
            CGConfig.CG_New_User_Running_No__c = '0';
            CGConfig.CG_Manual_Running_No__c = '0';
            CGConfig.CG_Annual_Running_No__c = '0';
            CGConfig.Gift_Running_No__c = '0';
            insert(CGConfig);
            
            RestRequest req = new RestRequest();
            RestResponse res = new RestResponse();
            
            req.requestUri = '/services/apexrest/CG_Home_API/doPost/GetHomeMenu';       
            req.httpMethod = 'POST';
            string postData = '{\"\" : \"\"}';
            
            String JsonMsg = JSON.serialize(postData);
            req.requestBody = Blob.valueof(JsonMsg);
            RestContext.request = req; 
            RestContext.response= res;
            
            CG_Home_API.doPost(postData);
            
            Test.stopTest();
        }
        
    }
    
    @future
    private static void InsertUserToGroup(string userId)
    {
        //CG Admin
        Group approverAdminGroup = [select id from Group where developername = 'CG_Admin'];
        GroupMember memberAdmin = new GroupMember();
        memberAdmin.UserOrGroupId = userId;
        memberAdmin.GroupId = approverAdminGroup.Id;
        insert(memberAdmin);
        
        //CG GLVP
        Group approverGLVPGroup = [select id from Group where developername = 'CG_GLVP'];
        GroupMember memberGLVP = new GroupMember();
        memberGLVP.UserOrGroupId = userId;
        memberGLVP.GroupId = approverGLVPGroup.Id;
        insert(memberGLVP);
        
        //CG GLGC
        Group approverGLGCGroup = [select id from Group where developername = 'CG_GLGC'];
        GroupMember memberGLGC = new GroupMember();
        memberGLGC.UserOrGroupId = userId;
        memberGLGC.GroupId = approverGLGCGroup.Id;
        insert(memberGLGC);
    }
    
    
    
}