force-app/main/default/objects/CG_Reporting__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WaitingForSubmit</fullName>
                    <label>Waiting for Submit</label>
                </value>
                <value>
                    <fullName>WaitingSupervisor</fullName>
                    <label>Waiting Supervisor</label>
                </value>
                <value>
                    <fullName>WaitingGLVP</fullName>
                    <label>Waiting GLVP</label>
                </value>
                <value>
                    <fullName>WaitingGLGC</fullName>
                    <label>Waiting GLGC</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Report__c</fullName>
        <label>Type of Report</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COIAnnual</fullName>
                    <label>COI (Annual Report)</label>
                </value>
                <value>
                    <fullName>COIIncident</fullName>
                    <label>COI (Incident Report)</label>
                </value>
                <value>
                    <fullName>COINewEmployee</fullName>
                    <label>COI (New Employee Report)</label>
                </value>
                <value>
                    <fullName>CGNewEmployee</fullName>
                    <label>CG Manual (New Employee)</label>
                </value>
                <value>
                    <fullName>CGAnnual</fullName>
                    <label>CG Manual (Annual)</label>
                </value>
                <value>
                    <fullName>CGManual</fullName>
                    <label>CG Manual (Manual)</label>
                </value>
                <value>
                    <fullName>GiftRegistration</fullName>
                    <label>Gift Registration</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CG_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CG Reporting</label>
    <nameField>
        <displayFormat>Report-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PISUsers__c.object
<CustomObject>
    <fields>
        <fullName>LineManagerEmail__c</fullName>
        <label>LineManagerEmail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LineManagerUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LineManagerUser</label>
        <referenceTo>User</referenceTo>
        <relationshipName>LMPISUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAINPOSITION__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MAINPOSITION</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PISUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PISUsers</label>
    <nameField>
        <label>UserID</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CG_PrivilegeHandler.cls
public class CG_PrivilegeHandler {

    public static string getUserId() {
        return UserInfo.getUserId();
    }
    
    public static string getUserProfile() {
        string userProfile = '';
        
        Id profileId = UserInfo.getProfileId();
		userProfile = [Select Id,Name from Profile where Id =: profileId].Name;
        
        if(userProfile == 'ผู้ดูแลระบบ' || userProfile == 'System Administrator') {
            userProfile = String.ValueOf(CG_Enum.ApproverRole.SuperAdmin);
            return userProfile;
        }
        
        boolean isUserAsApprover = findUserAsApprover();
        if(isUserAsApprover) { userProfile = 'Approver'; }
        
        boolean isUserAsAdmin = findUserAsAdmin();
        if(isUserAsAdmin) { userProfile = 'Admin'; }
        
        if(!isUserAsApprover && !isUserAsAdmin) {
            userProfile = String.ValueOf(CG_Enum.ApproverRole.Employee);
        }
        
        //Supervisor
        boolean isUserAsSupervisor = findUserAsSupervisor();
        if(isUserAsSupervisor) { userProfile = String.ValueOf(CG_Enum.ApproverRole.Supervisor); }
        
        //GLVP
        boolean isUserAsGLVP = findUserAsGLVP();
        if(isUserAsGLVP) { userProfile = String.ValueOf(CG_Enum.ApproverRole.GLVP); }
        
        //GLGC
        boolean isUserAsGLGC = findUserAsGLGC();
        if(isUserAsGLGC) { userProfile = String.ValueOf(CG_Enum.ApproverRole.GLGC); }
        
        return userProfile;
    }

    public static boolean checkAccessPrivilege(string recordId) {
        
        boolean canAccess = true;
        Id userId = UserInfo.getUserId();
        
        CG_Reporting__c CGReport = [select id, ownerId, User__c, Status__c, Type_Of_Report__c from CG_Reporting__c where Id =: recordId];
        
        if(CGReport.Status__c == String.ValueOf(CG_Enum.ReportStatus.WaitingForSubmit) ||
          	CGReport.Status__c == String.ValueOf(CG_Enum.ReportStatus.Success) ||
          	CGReport.Status__c == String.ValueOf(CG_Enum.ReportStatus.Cancel) || 
          	CGReport.Status__c == String.ValueOf(CG_Enum.ReportStatus.Rejected)) {
            if(userId != CGReport.OwnerId) canAccess = false; 
                
        }
        else if(CGReport.Status__c == String.ValueOf(CG_Enum.ReportStatus.WaitingSupervisor)) {
            if(userId != CGReport.User__c) canAccess = false;
        }
        else if(CGReport.Status__c == String.ValueOf(CG_Enum.ReportStatus.WaitingGLVP)) {
            boolean isGLVPUser = findUserAsGLVP();
            if(!isGLVPUser) canAccess = false;
        }
        else if(CGReport.Status__c == String.ValueOf(CG_Enum.ReportStatus.WaitingGLGC)) {
            boolean isGLGCUser = findUserAsGLGC();
            if(!isGLGCUser) canAccess = false;
        }
        
        //GLGC Access when Gift status Success
        if(CGReport.Status__c == String.ValueOf(CG_Enum.ReportStatus.Success) && CGReport.Type_Of_Report__c == 'GiftRegistration') {
            boolean isGLGCUser = findUserAsGLGC();
            canAccess = isGLGCUser;
        }
        
        if(userId == CGReport.OwnerId) {
            canAccess = true;
        }
        
        if(!canAccess) {
            //Give Access to Admin
            canAccess = findUserAsAdmin();  
        }
        
        return canAccess;
        
    }
    
    public static string findLineManager(string userId) {
        
        PISUsers__c PISUser = [select id, User__c, LineManagerUser__c, LineManagerEmail__c from PISUsers__c where User__c =: userId AND Mainposition__c = true];
        
        return PISUser.LineManagerUser__c;
        
    }
    
    public static boolean findUserAsApprover() {
        
        boolean isUserAsApprover = false;
        Set<Id> UserIds = new Set<Id>();
        
        Id userId = getUserId();
        
        //Find 
        List<PISUsers__c> PISUsers = [select id, User__c, LineManagerUser__c, LineManagerEmail__c from PISUsers__c where LineManagerUser__c =: userId AND Mainposition__c = true];
        
        if(PISUsers.size() > 0) {
            for(PISUsers__c PISUser : PISUsers) {
                if(!string.isBlank(PISUser.User__c)) {
                    UserIds.add(PISUser.User__c);
                }
            }
        }
        
        if(UserIds.size() > 0) {
            List<CG_Reporting__c> CGReports = [select id, OwnerId, User__c from CG_Reporting__c where User__c IN: UserIds];
            if(CGReports.size() > 0) {
                isUserAsApprover = true;
            }
        }
        
        return isUserAsApprover;
    }
    
    public static boolean findUserAsSupervisor() {
        
        boolean isUserAsSupervisor = false;
        Id userId = getUserId();
        
        //Find from CG Reporting
        List<CG_Reporting__c> CGReports = [select id, user__c, status__c from CG_Reporting__c where user__c =: userId];
        
        if(CGReports.size() > 0) {
            isUserAsSupervisor = true;
        }
        
        return isUserAsSupervisor;
    }
    
    public static boolean findUserAsAdmin() {
        
        boolean isUserAsAdmin = false;
        Id userId = getUserId();
        
        //Find from Group Admin
        Group ApproverGroup = [select id, developername from Group where developername =: 'CG_Admin'];
        List<GroupMember> ApproverUsers = [select id, groupid, userorgroupid from GroupMember where GroupId =: ApproverGroup.Id AND UserOrGroupId =: userId];
        
        if(ApproverUsers.size() > 0) {
            isUserAsAdmin = true;
        }
        
        return isUserAsAdmin;
    }
    
    public static boolean findUserAsGLGC() {
        
        boolean isUserAsGLGC = false;
        Id userId = getUserId();
        
        //Find from Group GLGC
        Group GLGCGroup = [select id, developername from Group where developername =: 'CG_GLGC'];
        List<GroupMember> GLGCUsers = [select id, groupid, userorgroupid from GroupMember where GroupId =: GLGCGroup.Id AND UserOrGroupId =: userId];
        
        if(GLGCUsers.size() > 0) {
            isUserAsGLGC = true;
        }
        
        return isUserAsGLGC;
    }
    
    public static boolean findUserAsGLVP() {
        
        boolean isUserAsGLVP = false;
        Id userId = getUserId();
        
        //Find from Group GLVP
        Group GLVPGroup = [select id, developername from Group where developername =: 'CG_GLVP'];
        List<GroupMember> GLVPUsers = [select id, groupid, userorgroupid from GroupMember where GroupId =: GLVPGroup.Id AND UserOrGroupId =: userId];
        
        if(GLVPUsers.size() > 0) {
            isUserAsGLVP = true;
        }
        
        return isUserAsGLVP;
    }
    
}