force-app/main/default/objects/CG_Setting__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>COIAnnual</fullName>
                    <label>COI Annual</label>
                </value>
                <value>
                    <fullName>COIMassAcknowledge</fullName>
                    <label>COI Mass Acknowledge</label>
                </value>
                <value>
                    <fullName>CGNewEmployee</fullName>
                    <label>CG New Employee</label>
                </value>
                <value>
                    <fullName>CGAnnual</fullName>
                    <label>CG Annual</label>
                </value>
                <value>
                    <fullName>CGManual</fullName>
                    <label>New CG Manual</label>
                </value>
                <value>
                    <fullName>ResendAnnual</fullName>
                    <label>Resend (Annual)</label>
                </value>
                <value>
                    <fullName>Annual</fullName>
                    <label>COI &amp; CG Annual</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CG Setting</label>
    <nameField>
        <displayFormat>CGS-{000}</displayFormat>
        <label>CG Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <recordTypes>
        <fullName>CG_Manual</fullName>
        <active>true</active>
        <label>CG Manual</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CG_UploadFileController_Test.cls
/* 
 * Author : Softever
*/
@isTest
public with sharing class CG_UploadFileController_Test {

    public static testMethod void CGUploadFile() {
        
        RecordType RT = [select id, developername from RecordType where developername = 'CG_Manual' AND sobjectType = 'CG_Setting__c'];
        
        CG_Setting__c CGSetting = new CG_Setting__c();
        CGSetting.Start_Date__c = system.today();
        CGSetting.End_Date__c = system.today();
        CGSetting.Type__c = 'New CG Manual';
        CGSetting.RecordTypeId = RT.Id;
        insert(CGSetting);
        
        PageReference pageRef = Page.CG_Setting_Import_File;
        pageRef.getParameters().put('Id',CGSetting.Id);        
        Test.setCurrentPage(PageRef);
        
        test.startTest();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(CGSetting);                         
        CG_UploadFileController CGUploadFile = new CG_UploadFileController(sc); 
        
        Attachment attach = new Attachment();       
        attach.Name = 'Unit Test Attachment';
        Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
        attach.body = bodyBlob;
        attach.parentId = CGSetting.id;
        insert attach;
        
        CGUploadFile.cgSettingId = CGSetting.Id;
        CGUploadFile.SaveAttachments();
        CGUploadFile.FileCount = '1';
        CGUploadFile.ChangeCount();
        CGUploadFile.fileId = attach.Id;
        CGUploadFile.DeleteFile();
        
        test.stopTest();
    }
    
}