force-app/main/default/objects/Checked_Sheet_Pointer__mdt.object
<CustomObject>
    <fields>
        <fullName>Form_Code__c</fullName>
        <label>Form Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Checked Sheet Pointer</label>
</CustomObject>

force-app/main/default/objects/EQCC_Checked_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Form_Type__c</fullName>
        <label>Form Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Count__c</fullName>
        <label>Group Count</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Task__c</fullName>
        <label>Group Task</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sheet_Code__c</fullName>
        <label>Sheet Code</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>EQCC Checked Sheet</label>
    <nameField>
        <label>EQCC Checked Sheet Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EQCC_Header__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>EQCC Headers</relationshipLabel>
        <relationshipName>EQCC_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FunctionalLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Location</label>
        <referenceTo>Functional_Location__c</referenceTo>
        <relationshipLabel>EQCC Headers</relationshipLabel>
        <relationshipName>EQCC_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Location__c</fullName>
        <formula>Order__r.Functional_Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Functional Location</label>
        <type>Text</type>
    </fields>
    <label>EQCC Header</label>
    <nameField>
        <displayFormat>EQCCH-{0000}</displayFormat>
        <label>EQCC Header</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EQCC_Step__c.object
<CustomObject>
    <fields>
        <fullName>Form_Code__c</fullName>
        <label>Form Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Header_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Header Sheet</label>
        <referenceTo>Header_Sheet__c</referenceTo>
        <relationshipLabel>EQCC Steps</relationshipLabel>
        <relationshipName>EQCC_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Step_Number__c</fullName>
        <label>Step Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EQCC Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Functional_Location__c.object
<CustomObject>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Functional Location</label>
    <nameField>
        <label>Functional Location</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Header_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Header__c</fullName>
        <label>EQCC Header</label>
        <referenceTo>EQCC_Header__c</referenceTo>
        <relationshipLabel>Header Sheets</relationshipLabel>
        <relationshipName>Header_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sheet__c</fullName>
        <label>EQCC Checked Sheet</label>
        <referenceTo>EQCC_Checked_Sheet__c</referenceTo>
        <relationshipLabel>Header Sheets</relationshipLabel>
        <relationshipName>Header_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Header Sheet</label>
    <nameField>
        <displayFormat>HS-{0000}</displayFormat>
        <label>Header Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sheet_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Form_Code__c</fullName>
        <label>Form Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Count__c</fullName>
        <label>Group Count</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Task__c</fullName>
        <label>Group Task</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operation_Text__c</fullName>
        <label>Operation Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sheet Mapping</label>
    <nameField>
        <displayFormat>SM-{0000}</displayFormat>
        <label>Sheet Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EQCCCheckedSheetNavigateController_Test.cls
@isTest
public class EQCCCheckedSheetNavigateController_Test {
    @IsTest
    static void getStepFromNumber() {
        EQCC_Header__c header = new EQCC_Header__c();
        insert header;

        EQCC_Checked_Sheet__c sheet = new EQCC_Checked_Sheet__c();
        sheet.Name = 'something';
        sheet.Form_Type__c = 'Tank_Gauge_Level_Maintenance_Record';
        insert sheet;

        Header_Sheet__c headerSheet = new Header_Sheet__c(Header__c = header.Id, Sheet__c = sheet.Id);
        insert headerSheet;

        EQCC_Step__c step = [SELECT Id, Step_Number__c FROM EQCC_Step__c LIMIT 1];

        Test.startTest();
        EQCC_Step__c me = EQCCCheckedSheetNavigationController.getStepFromNumber(step.Id, ((Integer) step.Step_Number__c));
        Test.stopTest();

        System.assert(me != null);
    }

    @IsTest
    static void getIdOfCurrentStep() {
        EQCC_Header__c header = new EQCC_Header__c();
        insert header;

        EQCC_Checked_Sheet__c sheet = new EQCC_Checked_Sheet__c();
        sheet.Name = 'something';
        sheet.Form_Type__c = 'Tank_Gauge_Level_Maintenance_Record';
        insert sheet;

        Header_Sheet__c headerSheet = new Header_Sheet__c(Header__c = header.Id, Sheet__c = sheet.Id);
        insert headerSheet;

        Test.startTest();
        Id me = EQCCCheckedSheetNavigationController.getIdOfCurrentStep(headerSheet.Id);
        Test.stopTest();

        System.assert(me != null);
    }

    /**
     * @given an EQCC Header
     * @when EQCC Checked Sheet is related to the Header
     * @then a new Header_Sheet__c is created
     */
    @isTest
    static void testCreateEQCCCheckedSheetWithHeader() {
        EQCC_Header__c header = new EQCC_Header__c();
        insert header;
        
        EQCC_Checked_Sheet__c sheet = new EQCC_Checked_Sheet__c(
            Form_Type__c = 'Tank_Gauge_Level_Maintenance_Record',
            Sheet_Code__c = 'CODE'
        );
        
        insert sheet;

        List<Header_Sheet__c> initialHeaderSheets = getHeaderSheets();

        Test.startTest();
        EQCCCheckedSheetNavigationController.associateCheckedSheetToHeader(sheet.Id, header.Id);
        Test.stopTest();

        List<Header_Sheet__c> finalHeaderSheets = getHeaderSheets();

        System.assertEquals(
            initialHeaderSheets.size() + 1,
            finalHeaderSheets.size(),
            'A new Header_Sheet__c should have been created'
        );
    }

    /**
     * @given an EQCC Header
     * @when EQCC Checked Sheet is related to the Header and user has no the right permissions
     * @then no new Header_Sheet__c is created and an exception is thrown
     */
    @isTest
    static void testCreateEQCCCheckedSheetWithHeaderNoPermission() {
        EQCC_Header__c header = new EQCC_Header__c();
        insert header;

        EQCC_Checked_Sheet__c sheet = new EQCC_Checked_Sheet__c(
            Form_Type__c = 'Tank_Gauge_Level_Maintenance_Record',
            Sheet_Code__c = 'CODE'
        );
        
        insert sheet;

        List<Header_Sheet__c> initialHeaderSheets = getHeaderSheets();

        Test.startTest();
        try {
            System.runAs(getReadOnlyUser()) {
                EQCCCheckedSheetNavigationController.associateCheckedSheetToHeader(sheet.Id, header.Id);
                System.assert(false, 'An exception should have been thrown');
            }
        } catch (Exception ex) {
            System.assertEquals(
                'System.AuraHandledException',
                ex.getTypeName(),
                'An exception should have prevented relating the EQCC Checked Sheet to the Header'
            );
        }
        Test.stopTest();

        List<Header_Sheet__c> finalHeaderSheets = getHeaderSheets();

        System.assertEquals(
            initialHeaderSheets.size(),
            finalHeaderSheets.size(),
            'No new Header_Sheet__c should have been created'
        );
    }
    
    /**
     * @given a Header with Equipment and Functional Location and a service to suggest Checked Sheets
     * @when service is invoked
     * @then all suggested Checked Sheets should be retrieved
     */
    @isTest
    static void testSuggestCheckedSheetsFromHeader() {
        createTestData();
        EQCC_Header__c header = new EQCC_Header__c(
            Equipment__c = getEquipmentFromName('Equipment 1').Id,
            FunctionalLocation__c = getFunctionalLocationFromName('funcLocation 1').Id
        );
        insert header;
        
        Test.startTest();
        List<EQCC_Checked_Sheet__c> suggestedSheets = EQCCCheckedSheetNavigationController.retrieveSuggestedCheckedSheets(
            header.Id
        );
        Test.stopTest();
        
        /*System.assertEquals(
            2,
            suggestedSheets.size(),
            'All suggested Checked Sheets should have been returned'
        );*/
    }

    private static List<Header_Sheet__c> getHeaderSheets() {
        return [SELECT Id FROM Header_Sheet__c];
    }

    private static User getReadOnlyUser() {
        Profile userProfile = [SELECT Id FROM Profile WHERE Name = 'Read Only'];
        User readOnlyUser = new User(
            Alias = 'standt',
            Email = 'ReadOnlyUser@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = userProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'ReadOnlyUser' + DateTime.now().getTime() + '@testorg.com'
        );
        insert readOnlyUser;

        return readOnlyUser;
    }
    
    private static void createTestData() {
        List<Equipment__c> equipments = new List<Equipment__c>();
        for (Integer i = 0; i < 10; i += 2) {
            equipments.add(new Equipment__c(Name = 'Equipment ' + i, Object_Type__c = 'EquipmentObjectType' + i));
            equipments.add(
                new Equipment__c(Name = 'Equipment ' + (i + 1), Object_Type__c = 'EquipmentObjectType' + (i + 1))
            );
        }
        insert equipments;

        List<Functional_Location__c> funcLocations = new List<Functional_Location__c>();
        for (Integer i = 0; i < 10; i += 2) {
            funcLocations.add(
                new Functional_Location__c(Name = 'funcLocation ' + i, Object_Type__c = 'funcLocationObjectType' + i)
            );
            funcLocations.add(
                new Functional_Location__c(
                    Name = 'funcLocation ' + (i + 1),
                    Object_Type__c = 'funcLocationObjectType' + (i + 1)
                )
            );
        }
        insert funcLocations;

        Checked_Sheet_Pointer__mdt formType = [
            SELECT Id, MasterLabel, DeveloperName
            FROM Checked_Sheet_Pointer__mdt
            LIMIT 1
        ];

        EQCC_Header__c header = new EQCC_Header__c();
        insert header;

        List<EQCC_Checked_Sheet__c> sheets = new List<EQCC_Checked_Sheet__c>();
        for (Integer i = 0; i < 10; i += 2) {
            sheets.add(
                new EQCC_Checked_Sheet__c(
                    Name = 'Sheet Equipment ' + i,
                    Form_Type__c = formType.DeveloperName,
                    Sheet_Code__c = 'SHEETCODE' + i
                )
            );
            sheets.add(
                new EQCC_Checked_Sheet__c(
                    Name = 'Sheet Equipment ' + (i + 1),
                    Form_Type__c = formType.DeveloperName,
                    Sheet_Code__c = 'SHEETCODE' + (i + 1)
                )
            );

            sheets.add(
                new EQCC_Checked_Sheet__c(
                    Name = 'Sheet FL ' + i,
                    Form_Type__c = formType.DeveloperName,
                    Sheet_Code__c = 'SHEETCODE' + i
                )
            );
            sheets.add(
                new EQCC_Checked_Sheet__c(
                    Name = 'Sheet FL ' + i + 1,
                    Form_Type__c = formType.DeveloperName,
                    Sheet_Code__c = 'SHEETCODE' + (i + 1)
                )
            );
        }
        insert sheets;

        List<Header_Sheet__c> headerSheets = new List<Header_Sheet__c>();
        for (EQCC_Checked_Sheet__c sheet : sheets) {
            headerSheets.add(new Header_Sheet__c(Header__c = header.Id, Sheet__c = sheet.Id));
        }
        insert headerSheets;
        
        insert new Sheet_Mapping__c(
            Object_Type__c = 'EquipmentObjectType1',
            Form_Code__c = 'SHEETCODE1',
            Group_Task__c = 'Task1',
            Group_Count__c = 'Count1',
            Operation_Text__c = 'OPERATION1'
        );
    }
    
    private static Equipment__c getEquipmentFromName(String equipment) {
        return [SELECT Id FROM Equipment__c WHERE Name = :equipment];
    }
    
    private static Functional_Location__c getFunctionalLocationFromName(String funcLocation) {
        return [SELECT Id FROM Functional_Location__c WHERE Name = :funcLocation];
    }
}