force-app/main/default/objects/Checked_Sheet_Pointer__mdt.object
<CustomObject>
    <fields>
        <fullName>Form_Code__c</fullName>
        <label>Form Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Form_Questions__c</fullName>
        <label>Form Questions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Checked Sheet Pointer</label>
</CustomObject>

force-app/main/default/objects/EQCC_Checked_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Form_Questions__c</fullName>
        <description>This is used to calculate the forms completion percentage</description>
        <label>Form Questions</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Form_Type__c</fullName>
        <label>Form Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sheet_Code__c</fullName>
        <label>Sheet Code</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Draft&apos;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending for approval</fullName>
                </value>
                <value>
                    <fullName>Revised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isManuallyCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manually Created</label>
        <type>Checkbox</type>
    </fields>
    <label>EQCC Checked Sheet</label>
    <nameField>
        <label>EQCC Checked Sheet Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EQCC_Header__c.object
<CustomObject>
    <fields>
        <fullName>Notification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Notification</label>
        <referenceTo>Notification__c</referenceTo>
        <relationshipLabel>EQCC Headers</relationshipLabel>
        <relationshipName>EQCC_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>EQCC Headers</relationshipLabel>
        <relationshipName>EQCC_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EQCC Header</label>
    <nameField>
        <displayFormat>EQCCH-{0000}</displayFormat>
        <label>EQCC Header</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EQCC_Step__c.object
<CustomObject>
    <fields>
        <fullName>Form_Code__c</fullName>
        <label>Form Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Header_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Header Sheet</label>
        <referenceTo>Header_Sheet__c</referenceTo>
        <relationshipLabel>EQCC Steps</relationshipLabel>
        <relationshipName>EQCC_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Needs Revision</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Step_Number__c</fullName>
        <label>Step Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EQCC Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Header_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Header__c</fullName>
        <label>EQCC Header</label>
        <referenceTo>EQCC_Header__c</referenceTo>
        <relationshipLabel>Header Sheets</relationshipLabel>
        <relationshipName>Header_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sheet__c</fullName>
        <label>EQCC Checked Sheet</label>
        <referenceTo>EQCC_Checked_Sheet__c</referenceTo>
        <relationshipLabel>Header Sheets</relationshipLabel>
        <relationshipName>Header_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Draft&apos;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Needs Revision</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isManuallyCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manually Created</label>
        <type>Checkbox</type>
    </fields>
    <label>Header Sheet</label>
    <nameField>
        <displayFormat>HS-{0000}</displayFormat>
        <label>Header Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Order does not integration with SAP System</errorMessage>
            <filterItems>
                <field>Order__c.Order_Number__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Clearance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Clearance</label>
        <referenceTo>Work_Clearance__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Notification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Notification</label>
        <referenceTo>Notification__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <externalId>true</externalId>
        <label>Order Number</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Super_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Super Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Sub Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Clearance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Clearance</label>
        <referenceTo>Work_Clearance__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Clearance__c.object
<CustomObject>
    <fields>
        <fullName>Notification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Notification</label>
        <referenceTo>Notification__c</referenceTo>
        <relationshipLabel>Work Clearances</relationshipLabel>
        <relationshipName>Work_Clearances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Work Clearances</relationshipLabel>
        <relationshipName>Work_Clearances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Clearance__c</fullName>
        <externalId>true</externalId>
        <label>Work Clearance</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Work Clearance</label>
    <nameField>
        <label>Work Clearance Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/THOR_MakeMockData.cls
@isTest
public with sharing class THOR_MakeMockData {
    public static void makeMockData() {
        Checked_Sheet_Pointer__mdt formType = [
            SELECT Id, MasterLabel, DeveloperName, Form_Questions__c 
            FROM Checked_Sheet_Pointer__mdt
            LIMIT 1
        ];

        Order__c mockOrder = new Order__c(Name = 'Test Order', Order_Number__c = '9123450001');
        insert mockOrder;

        Order__c childMockOrder = new Order__c(
            Name='Child Test Order',
            Super_Order__c = mockOrder.Id,
            Order_Number__c = '1234512345'
        );
        insert childMockOrder;

        Notification__c mockNotification = new Notification__c(Name = 'Test Notification', Order__c = mockOrder.Id);
        insert mockNotification;

        List<EQCC_Header__c> mockHeaders = new List<EQCC_Header__c>{
            new EQCC_Header__c(Order__c = mockOrder.Id, Notification__c = mockNotification.Id),
            new EQCC_Header__c()
        };
        insert mockHeaders;

        List<EQCC_Checked_Sheet__c> mockCheckedSheets = new List<EQCC_Checked_Sheet__c>{
            new EQCC_Checked_Sheet__c(
                Name = 'Test Checked Sheet',
               	Form_Questions__c = 10,
                Form_Type__c = formType.DeveloperName,
                Sheet_Code__c = '34523',
                Status__c = 'Done'
          		
            ),
            new EQCC_Checked_Sheet__c(Name = 'Submit for approval',Form_Questions__c = 10, Form_Type__c = formType.DeveloperName),
            new EQCC_Checked_Sheet__c(Name = 'Approve EQCC',Form_Questions__c = 15, Form_Type__c = formType.DeveloperName),
            new EQCC_Checked_Sheet__c(Name = 'Reject EQCC',Form_Questions__c = 20, Form_Type__c = formType.DeveloperName)
        };
            system.debug('===mockCheckedSheets==>'+mockCheckedSheets);
        insert mockCheckedSheets;



        List<Header_Sheet__c> headerSheets = new List<Header_Sheet__c>{
            new Header_Sheet__c(isManuallyCreated__c = true, Header__c = mockHeaders[0].Id, Sheet__c = mockCheckedSheets[0].Id),
            new Header_Sheet__c(isManuallyCreated__c = true, Header__c = mockHeaders[1].Id, Sheet__c = mockCheckedSheets[1].Id),
            new Header_Sheet__c(isManuallyCreated__c = true, Header__c = mockHeaders[1].Id, Sheet__c = mockCheckedSheets[2].Id),
            new Header_Sheet__c(isManuallyCreated__c = true, Header__c = mockHeaders[1].Id, Sheet__c = mockCheckedSheets[3].Id),
            new Header_Sheet__c(isManuallyCreated__c = true, Header__c = mockHeaders[1].Id, Sheet__c = mockCheckedSheets[3].Id)
        };
        insert headerSheets;

        EQCC_Step__c mockStep = new EQCC_Step__c(
            Name = 'Test Step',
            Step_Number__c = 1,
            Status__c = 'Draft',
            Header_Sheet__c = headerSheets[0].Id,
            //EQCC_Checked_Sheet__c = mockCheckedSheets[0].Id,
            Form_Code__c = 'EQCC-ENRM-001'
        );
        insert mockStep;

        EQCC_Header__c mockHeaderGenerated = new EQCC_Header__c(
            Order__c=childMockOrder.Id
        );
        insert mockHeaderGenerated;

        Header_Sheet__c mockHeaderJuntionGenerated = new Header_Sheet__c(
            Header__c = mockHeaderGenerated.Id,
            isManuallyCreated__c = false,
            Sheet__c = mockCheckedSheets[0].Id
        );
        insert mockHeaderJuntionGenerated;



        // set up a Read Only user so we can test the try/catch exceptions by restricting our access to records
        // https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_testing_tools_runas.htm
        Profile userProfile = [SELECT Id FROM Profile WHERE Name = 'Read Only'];
        User readOnlyUser = new User(
            Alias = 'standt',
            Email = 'ReadOnlyUser@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = userProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'ReadOnlyUser' + DateTime.now().getTime() + '@testorg.com'
        );
        insert readOnlyUser;

        Work_Clearance__c mockWorkClearance = new Work_Clearance__c(
            Name = 'Test WC',
            Notification__c = mockNotification.Id,
            Order__c = mockOrder.Id
        );
        insert mockWorkClearance;

        // https://salesforce.stackexchange.com/questions/181963/test-class-for-contentdocumentlink
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        //create ContentDocumentLink  record
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.LinkedEntityId = mockNotification.Id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        ContentVersion contentVersion2 = new ContentVersion(
            Title = 'Tigers',
            PathOnClient = 'Tigers.jpg',
            VersionData = Blob.valueOf('Test Content Tigers'),
            IsMajorVersion = true
        );
        insert contentVersion2;
        List<ContentDocument> documents2 = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        //create ContentDocumentLink  record
        ContentDocumentLink cdl2 = new ContentDocumentLink();
        cdl2.LinkedEntityId = mockWorkClearance.Id;
        cdl2.ContentDocumentId = documents2[1].Id;
        cdl2.shareType = 'V';
        insert cdl2;
    }
}