force-app/main/default/objects/CTRBuProfile__mdt.object
<CustomObject>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TOP</fullName>
                    <default>true</default>
                    <label>TOP</label>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>LABIX</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Edit_Button_Name__c</fullName>
        <label>Edit Button Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReassignTask_Section_Name__c</fullName>
        <label>ReassignTask Section Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_Credit_Condition__c</fullName>
        <label>Section Credit Condition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VPSectionName__c</fullName>
        <label>VP Section Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CTRBuProfile</label>
</CustomObject>

force-app/main/default/objects/CTRRequestFormHeader__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Request_Form_Header</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>CTR Request Form Header</label>
    <nameField>
        <label>Request Form Header Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CTRShippingCountry__c.object
<CustomObject>
    <fields>
        <fullName>CTRRequestFormItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CTR Request Form Item</label>
        <referenceTo>CTRRequestFormItem__c</referenceTo>
        <relationshipLabel>CTR Shipping Country</relationshipLabel>
        <relationshipName>CTRShippingCountry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CTR Shipping Country</relationshipLabel>
        <relationshipName>CTR_Shipping_Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShippingCountry__c</fullName>
        <label>Shipping Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <label>CTR Shipping Country</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Shipping Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CTRRequestFormItemControllerTest.cls
@isTest
public with sharing class CTRRequestFormItemControllerTest {
    private class MockHttpResponse implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setBody('{"status":"success"}');
            return res;
        }
    }

	@TestSetup
    static void makeData(){
        Account acc = new Account();
        acc.Name = 'R2 Solutions Co.,Ltd.';
        insert acc;

        CTRRequestFormHeader__c reqHeader = new CTRRequestFormHeader__c();
        reqHeader.Name ='R2 Solutions. Co.,Ltd.';
        insert reqHeader;

        CTRRequestFormItem__c reqItem = new CTRRequestFormItem__c();
        reqItem.Customer__c = acc.Id;
        reqItem.CTRRequestFormHeader__c = reqHeader.Id;
        reqItem.Email__c = 'testmockemail@gmail.com';
        reqItem.EmailPageAttachment__c = 'Screen Shot 2024-01-18 at 9.34.00 PM.png,Screen Shot 2024-01-18 at 9.34.00 PM.png';
        insert reqItem;
        
        CTRShippingCountry__c shipping = new CTRShippingCountry__c();
        shipping.CTRRequestFormItem__c = reqItem.id;
        //shipping.ShippingCountry__c = 'TH - Thailand'; 
        shipping.ShippingCountry__c = 'TH';
        insert shipping;
        
        shipping = new CTRShippingCountry__c();
        shipping.CTRRequestFormItem__c = reqItem.id;
        //shipping.ShippingCountry__c = 'US - United State';
        shipping.ShippingCountry__c = 'US ';
        insert shipping;


        ContentVersion testContent1 = new ContentVersion(
            Title = 'Screen Shot 2024-01-18 at 9.34.00 PM.png', 
            PathOnClient = 'Screen Shot 2024-01-18 at 9.34.00 PM.png', 
            VersionData = Blob.valueOf('Test content for file 1'),
            IsMajorVersion = true
        );
        insert testContent1;

        ContentDocument testDocument1 = [SELECT Id FROM ContentDocument WHERE Id IN (SELECT ContentDocumentId FROM ContentVersion WHERE Id = :testContent1.Id) LIMIT 1];
        
        ContentDocumentLink link1 = new ContentDocumentLink(
            ContentDocumentId = testDocument1.Id, 
            LinkedEntityId = reqItem.Id, 
            ShareType = 'I', 
            Visibility = 'AllUsers'
        );
        insert link1;

        Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
        
        /*CTRBuProfile__mdt mdt = new CTRBuProfile__mdt();
        mdt.MasterLabel = 'System Administrator';
        mdt.BusinessUnit__c = 'TOP';
        mdt.ReassignTask_Section_Name__c ='FALB Reassign Task';
        mdt.VPSectionName__c ='CMVP/SA09';
        mdt.Edit_Button_Name__c ='Evaluate Credit';
        mdt.Section_Credit_Condition__c ='Excel Summary';
        insert mdt;*/
        
    }
    
    @IsTest 
    public static void getRequestItemRecordTypeTest(){
        Test.startTest();
        	CTRRequestFormItemController.getRequestItemRecordType();
        Test.stopTest();
    }
    
    @IsTest 
    public static void getRequestFormItemTest(){
        CTRRequestFormItem__c record =[SELECT Id FROM CTRRequestFormItem__c WHERE Email__c = 'testmockemail@gmail.com'];
        Test.startTest();
        	CTRRequestFormItemController.getRequestFormItem(record.Id);
        Test.stopTest();
    }
    
    @IsTest 
    public static void getBUInfoTest(){
        CTRRequestFormItem__c record =[SELECT Id FROM CTRRequestFormItem__c WHERE Email__c = 'testmockemail@gmail.com'];
        Test.startTest();
        	CTRRequestFormItemController.getBUInfo(record.Id);
        Test.stopTest();
    }

	@IsTest 
    public static void getUserInfomationTest(){
        CTRRequestFormItem__c record =[SELECT Id FROM CTRRequestFormItem__c WHERE Email__c = 'testmockemail@gmail.com'];
        Test.startTest();
        	CTRRequestFormItemController.getUserInfomation(record.Id);
        Test.stopTest();
    }    
    
    @IsTest 
    public static void getShippingCountryTest(){
        CTRRequestFormItem__c record =[SELECT Id FROM CTRRequestFormItem__c WHERE Email__c = 'testmockemail@gmail.com'];
        Test.startTest();
        	CTRRequestFormItemController.getShippingCountry(record.Id);
        Test.stopTest();
    }
    
    @IsTest 
    public static void deleteAttachmentsTest(){
        CTRRequestFormItem__c record =[SELECT Id FROM CTRRequestFormItem__c WHERE Email__c = 'testmockemail@gmail.com'];
        Test.startTest();
        	CTRRequestFormItemController.deleteAttachments(record.Id,'EmailPageAttachement__c');
            CTRRequestFormItemController.deleteAttachments(record.Id,'CustomerAttachment__c');
            CTRRequestFormItemController.deleteAttachments(record.Id,'CommitteeAttachment__c');
            CTRRequestFormItemController.deleteAttachments(record.Id,'SummarizeReportAttachment__c');
        Test.stopTest();
    }
    
    
    
}