force-app/main/default/objects/CTRBuProfile__mdt.object
<CustomObject>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TOP</fullName>
                    <default>true</default>
                    <label>TOP</label>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>LABIX</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CTRBuProfile</label>
</CustomObject>

force-app/main/default/objects/CTRDocumentItem__c.object
<CustomObject>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTRRequestFormItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CTR Request Form Item</label>
        <referenceTo>CTRRequestFormItem__c</referenceTo>
        <relationshipLabel>CTR Document Item</relationshipLabel>
        <relationshipName>CTR_Document_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CTR Document Item</label>
    <nameField>
        <label>CTR Document Item Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CTREmailTemplateMaster__c.object
<CustomObject>
    <fields>
        <fullName>HTMLBody__c</fullName>
        <label>Html Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Committee TOP</fullName>
                </value>
                <value>
                    <fullName>Committee Customer TX</fullName>
                </value>
                <value>
                    <fullName>Committee Supplier TX</fullName>
                </value>
                <value>
                    <fullName>Request More Document TOP</fullName>
                </value>
                <value>
                    <fullName>Request More Document TX</fullName>
                </value>
                <value>
                    <fullName>Summarize Report TOP</fullName>
                </value>
                <value>
                    <fullName>Summarize Report TX</fullName>
                </value>
                <value>
                    <fullName>Lead TX</fullName>
                </value>
                <value>
                    <fullName>Lead TOP</fullName>
                </value>
                <value>
                    <fullName>Committee LABIX</fullName>
                </value>
                <value>
                    <fullName>Customer TOP Due Diligence Result High</fullName>
                </value>
                <value>
                    <fullName>Customer LABIX Due Diligence Result High</fullName>
                </value>
                <value>
                    <fullName>Customer TX Due Diligence Result High</fullName>
                </value>
                <value>
                    <fullName>Supplier TOP Due Diligence Result High</fullName>
                </value>
                <value>
                    <fullName>Supplier LABIX Due Diligence Result High</fullName>
                </value>
                <value>
                    <fullName>Supplier TX Due Diligence Result High</fullName>
                </value>
                <value>
                    <fullName>Customer TOP Due Diligence Result High High</fullName>
                </value>
                <value>
                    <fullName>Customer LABIX Due Diligence Result High High</fullName>
                </value>
                <value>
                    <fullName>Customer TX Due Diligence Result High High</fullName>
                </value>
                <value>
                    <fullName>Supplier TOP Due Diligence Result High High</fullName>
                </value>
                <value>
                    <fullName>Supplier LABIX Due Diligence Result High High</fullName>
                </value>
                <value>
                    <fullName>Supplier TX Due Diligence Result High High</fullName>
                </value>
                <value>
                    <fullName>Approved Summarize Report TOP</fullName>
                </value>
                <value>
                    <fullName>Approved Summarize Report TX</fullName>
                </value>
                <value>
                    <fullName>Rejected Summarize Report TOP</fullName>
                </value>
                <value>
                    <fullName>Rejected Summarize Report TX</fullName>
                </value>
                <value>
                    <fullName>Approved Customer TOP</fullName>
                </value>
                <value>
                    <fullName>Approved Supplier TOP</fullName>
                </value>
                <value>
                    <fullName>Rejected Customer TOP</fullName>
                </value>
                <value>
                    <fullName>Rejected Supplier TOP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CTR Email Template Master</label>
    <nameField>
        <label>CTR Email Template Master Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CTRRequestFormHeader__c.object
<CustomObject>
    <fields>
        <fullName>CTRUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CTR User</label>
        <referenceTo>CTRUser__c</referenceTo>
        <relationshipLabel>CTR Request Form Header</relationshipLabel>
        <relationshipName>CTRRequestFormHeader</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CompanyNameENF__c</fullName>
        <label>Company Name EN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Request_Form_Header</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OriginalRequestFormHeader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CTR Request Form Header</label>
        <referenceTo>CTRRequestFormHeader__c</referenceTo>
        <relationshipLabel>CTR Request Form Header</relationshipLabel>
        <relationshipName>CTRRequestFormHeader</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TypeOfBusiness__c</fullName>
        <label>Type of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>National Oil Company</fullName>
                </value>
                <value>
                    <fullName>End User</fullName>
                </value>
                <value>
                    <fullName>Trader &amp; Distributor</fullName>
                </value>
                <value>
                    <fullName>Other (Please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CTR Request Form Header</label>
    <nameField>
        <label>Request Form Header Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CTRUser__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>CTR User</label>
    <nameField>
        <label>CTR User Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CTRDocumentChecklistControllerTest.cls
@isTest
public without sharing class CTRDocumentChecklistControllerTest {

    private class MockHttpResponse implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setBody('{"status":"success"}');
            return res;
        }
    }

    @testSetup
    static void setup() {
        
        Id devRecordTypeId = Schema.SObjectType.CTRRequestFormItem__c.getRecordTypeInfosByDeveloperName().get('CustomerInitial').getRecordTypeId();
        Account newAcc = new Account();
        newAcc.Name = 'Test Acc';
        newAcc.AccountNumber = '0001';
        newAcc.AccountNumber__c = '0001';
        newAcc.CompanyNameENF__c = 'Test Acc';
        insert newAcc;
        
        CTRRequestFormHeader__c reqHeader = new CTRRequestFormHeader__c(
            Status__c = 'New',
            Customer__c = newAcc.Id,
            FirstName__c = 'test',
            LastName__c = 'test'
        );
        insert reqHeader;

        CTRRequestFormItem__c reqItem = new CTRRequestFormItem__c(
            CustomerSubject__c = '',
            CustomerMessage__c = '',
            CustomerEmailTo__c = 'testuser@test.com',
            CustomerEmailCC__c = 'testcc@test.com',
            Customer__c = newAcc.Id,
            CTRRequestFormHeader__c = reqHeader.Id,
            RecordTypeId = devRecordTypeId
        );
        insert reqItem;

        CTREmailTemplateMaster__c emailTemp = new CTREmailTemplateMaster__c(         
            Subject__c = 'Subject',
            HTMLBody__c = 'Body',
            Type__c = 'Request More Document TOP'
        );
        insert emailTemp;

        String base64Data = EncodingUtil.urlDecode('YWJj', 'UTF-8');
        Blob fileBody = EncodingUtil.base64Decode(base64Data);
        ContentVersion contentVersion = new ContentVersion (
            ContentLocation = 'S',
            PathOnClient = 'TestFile.txt',
            Title = 'TestFile.txt',
            VersionData = EncodingUtil.base64Decode(base64Data)
        );
        insert contentVersion;

        ContentVersion queriedContentVersion = [
            SELECT Id, ContentDocumentId
            FROM ContentVersion
            WHERE Id = :contentVersion.Id
            LIMIT 1
        ];

        ContentDocumentLink contentLink = new ContentDocumentLink(
            ContentDocumentId = queriedContentVersion.ContentDocumentId,
            LinkedEntityId = reqItem.Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );
        insert contentLink;

        Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
    }

    @isTest
    static void testGetDocChecklistInfo() {
        Test.startTest();
        CTRRequestFormItem__c testRecord = [SELECT Id FROM CTRRequestFormItem__c LIMIT 1];
        System.debug('testRecord: ' + testRecord);
        
        CTRRequestFormItem__c reqFormItem = [SELECT CTRRequestFormHeader__r.Email__c, CustomerEmailCC__c,CTRRequestFormHeader__r.Customer__r.CTRUser__c,
                                             CustomerSubject__c, CustomerMessage__c, RecordType.Name, Name, RecordType.DeveloperName,BusinessUnit__c
                                             FROM CTRRequestFormItem__c WHERE Id = :testRecord.Id];
        System.debug('reqFormRecord :' );
        System.debug(reqFormItem);
        
        CTRRequestFormItem__c reqItem = CTRDocumentChecklistController.getDocChecklistInfo(testRecord.Id, 'Request More Document TOP');
        System.assertNotEquals(null, reqItem);
        Test.stopTest();
    }

    @isTest
    static void testSaveDocChecklist() {
        Test.startTest();
        CTRRequestFormItem__c reqItems = [SELECT Id FROM CTRRequestFormItem__c LIMIT 1];
        CTRRequestFormItem__c reqItem = new CTRRequestFormItem__c(
            Id = reqItems.Id,
            HasCOI__c = 'Pass'
            //HasMDA__c = 'Pass'
        );
        try {
            CTRDocumentChecklistController.saveDocChecklist(reqItem,new List<CTRDocumentItem__c>());

            // Fail Case
            reqItem.TypeOfBusiness__c = 'Invalid Type';
            CTRDocumentChecklistController.saveDocChecklist(reqItem,new List<CTRDocumentItem__c>());
            
        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'exception thrown');
        }
        
        Test.stopTest();
    }

    @isTest
    static void testUpdateListFileName() {
        Test.startTest();
        CTRRequestFormItem__c reqItems = [SELECT Id FROM CTRRequestFormItem__c LIMIT 1];
        
        try {
            CTRDocumentChecklistController.updateListFileName(reqItems.Id, 'TestFile.txt');

            // Fail Case
            CTRDocumentChecklistController.updateListFileName('', 'TestFile.txt');
        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'exception thrown');
        }
        Test.stopTest();
    }

    @isTest
    static void tesGetUploadedFileName() {
        
        Test.startTest();
        CTRRequestFormItem__c reqItems = [SELECT Id FROM CTRRequestFormItem__c LIMIT 1];
        try {
            String fileName = CTRDocumentChecklistController.getUploadedFileName(reqItems.Id);
        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'exception thrown');
        }
        Test.stopTest();
    }

    @isTest
    static void testSaveRequestDoc() {
        // Create test data
        CTRRequestFormItem__c reqFormItem = new CTRRequestFormItem__c();
        reqFormItem.Name = 'Test Item';
        // Set other required fields as needed

        Boolean isSubmit = true;
        String uploadedList = '[{"Title": "File1.txt"}, {"Title": "File2.doc"}]';

        Test.startTest();

        try {
            CTRDocumentChecklistController.saveRequestDoc(reqFormItem, isSubmit, uploadedList);

        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'exception thrown');
        }

        // End test
        Test.stopTest();
        // Test.startTest();
        // CTRRequestFormItem__c reqItems = [SELECT Id FROM CTRRequestFormItem__c LIMIT 1];
        // CTRRequestFormItem__c reqItem = new CTRRequestFormItem__c(
        //     Id = reqItems.Id,
        //     CustomerSubject__c = 'Test Subject',
        //     CustomerMessage__c = 'Test',
        //     CustomerEmailTo__c = 'testuser@test.com, testuser@test.com',
        //     CustomerEmailCC__c = 'testcc@test.com'
        // );
        // CTRDocumentChecklistController.saveRequestDoc(reqItem, true, 'TestFile.txt');
        // Test.stopTest();
    }

    @isTest
    static void testSendEmailWithAttachment() {
        CTRRequestFormItem__c reqFormObj = [SELECT Id FROM CTRRequestFormItem__c LIMIT 1];
        reqFormObj.CustomerEmailTo__c = 'test1@test.com,test2@test.com';
        reqFormObj.CustomerEmailCC__c = 'test1@test.com,test2@test.com';
        reqFormObj.CustomerMessage__c = '<p>Dear <span style="color: rgb(68, 68, 68);">Lube Base Products</span>,</p><p><br></p><p>file.force.com We would like to request more document of <span style="font-size: 14px; color: rgb(68, 68, 68);">Lube Base Products</span></p><ol><li>Memorandum of Association (MOA)</li><li><span style="font-size: 11.36px; font-family: Arial, Helvetica, sans-serif; color: rgb(0, 0, 0);">Audited Financial Statements with Notes to the Financial Statements for the last 3 years</span></li></ol><p>Please attach document via <a href="file.force.com" target="_blank">this link</a></p><p><br></p><p>Best Regards,</p><p>Counterparties Registration Automated System$</p>';
        Id recordId = reqFormObj.Id;
        String uploadedList = 'File1.txt,File2.doc';
        
        ContentVersion testContent1 = new ContentVersion(
            Title = 'File1.txt', 
            PathOnClient = 'File1.txt', 
            VersionData = Blob.valueOf('Test content for file 1'),
            IsMajorVersion = true
        );
        insert testContent1;

        ContentDocument testDocument1 = [SELECT Id FROM ContentDocument WHERE Id IN (SELECT ContentDocumentId FROM ContentVersion WHERE Id = :testContent1.Id) LIMIT 1];
        
        ContentDocumentLink link1 = new ContentDocumentLink(
            ContentDocumentId = testDocument1.Id, 
            LinkedEntityId = reqFormObj.Id, 
            ShareType = 'I', 
            Visibility = 'AllUsers'
        );
        insert link1;

        // Start test
        Test.startTest();

        try {
            CTRDocumentChecklistController.sendEmailWithAttachment(recordId, reqFormObj, uploadedList);

        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'exception thrown');
        }

        // End test
        Test.stopTest();
    }

    // @isTest
    // static void testSendEmailWithAttachment() {
    //     CTRRequestFormItem__c reqFormObj = [SELECT Id FROM CTRRequestFormItem__c LIMIT 1];
    //     reqFormObj.CustomerEmailTo__c = 'test1@test.com,test2@test.com';
    //     reqFormObj.CustomerEmailCC__c = 'test1@test.com,test2@test.com';
    //     reqFormObj.CustomerMessage__c = '<p>Dear <span style="color: rgb(68, 68, 68);">Lube Base Products</span>,</p><p><br></p><p>We would like to request more document of <span style="font-size: 14px; color: rgb(68, 68, 68);">Lube Base Products</span></p><ol><li>Memorandum of Association (MOA)</li><li><span style="font-size: 11.36px; font-family: Arial, Helvetica, sans-serif; color: rgb(0, 0, 0);">Audited Financial Statements with Notes to the Financial Statements for the last 3 years</span></li></ol><p>Please attach document via <a href="file.force.com" target="_blank">this link</a></p><p><br></p><p>Best Regards,</p><p>Counterparties Registration Automated System$</p>';
   
    //     String uploadedList = 'File1,File2';

    //     Account testAccount = new Account(Name = 'Test Account');
    //     insert testAccount;

    //     ContentVersion testContent1 = new ContentVersion(
    //         Title = 'File1', 
    //         PathOnClient = 'testFile1.txt', 
    //         VersionData = Blob.valueOf('Test content for file 1'),
    //         IsMajorVersion = true
    //     );
    //     insert testContent1;

    //     ContentDocument testDocument1 = [SELECT Id FROM ContentDocument WHERE Id IN (SELECT ContentDocumentId FROM ContentVersion WHERE Id = :testContent1.Id) LIMIT 1];
        
    //     ContentDocumentLink link1 = new ContentDocumentLink(
    //         ContentDocumentId = testDocument1.Id, 
    //         LinkedEntityId = testAccount.Id, 
    //         ShareType = 'I', 
    //         Visibility = 'AllUsers'
    //     );
    //     insert link1;

    //     Test.startTest();
    //     CTRDocumentChecklistController.sendEmailWithAttachment(testAccount.Id, reqFormObj, uploadedList);
    //     Test.stopTest();

    // }

    @isTest
    static void testGetCurrentUserProfileName() {
        Test.startTest();
        CTRDocumentChecklistController.getCurrentUserProfileName();
        Test.stopTest();
    }

    @isTest
    static void testGetBUInfo() {
        CTRBuProfile__mdt buProfileRecord = new CTRBuProfile__mdt(
            MasterLabel = 'Test BU Profile'
        );

        Id recordId = buProfileRecord.Id;

        Test.startTest();

        try {
            CTRBuProfile__mdt result = CTRDocumentChecklistController.getBUInfo(recordId);
            System.assertNotEquals(null, result, 'Expected result to be not null');

            result = CTRDocumentChecklistController.getBUInfo(null);

        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'exception thrown');
        }

        Test.stopTest();
    }

    @isTest
    static void testSendFiletoHeroku() {
        CTRRequestFormItem__c reqFormItem = [SELECT CustomerSubject__c, CustomerMessage__c, CustomerEmailTo__c, CustomerEmailCC__c FROM CTRRequestFormItem__c LIMIT 1];
         
        Id recordId = reqFormItem.Id;
        String uploadedList = '[{"Title": "File1.txt", "IsSaved": true, "Id": "0123456789ABCDEF"}, {"Title": "File2.doc", "IsSaved": false, "Id": null}]';

        Test.startTest();

        try {
            CTRDocumentChecklistController.sendFiletoHeroku(recordId, uploadedList, reqFormItem);

        } catch (Exception e) {
            System.assertNotEquals(null, e.getMessage(), 'exception thrown');
        }

        Test.stopTest();
    }

}