force-app/main/default/objects/CTRRequestFormHeader__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Country</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>CTR Request Form Header (Country)</relationshipLabel>
        <relationshipName>CTR_Request_Form_Header1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Request_Form_Header</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InterestedProductTypeAsCustomerTOP__c</fullName>
        <label>Interested Product Type as Customer TOP</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>InterestedProductTypeasCustomerTOP</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>InterestedProductTypeAsSupplierTOP__c</fullName>
        <label>Interested Product Type As Supplier TOP</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>InterestedProductTypeasSupplierTOP</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OriginalRequestFormHeader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CTR Request Form Header</label>
        <referenceTo>CTRRequestFormHeader__c</referenceTo>
        <relationshipLabel>CTR Request Form Header</relationshipLabel>
        <relationshipName>CTRRequestFormHeader</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PurchasingOrganization__c</fullName>
        <label>Purchasing Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PurchasingOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>Sales Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2000</fullName>
                    <label>2000 - TXTH</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TermofPayment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TermofPayment</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Payment Term</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>CTR Request Form Header (TermofPayment)</relationshipLabel>
        <relationshipName>CTR_Request_Form_Header6</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CTR Request Form Header</label>
    <nameField>
        <label>Request Form Header Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Map__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Master Map Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/InterestedProductTypeasCustomerTOP.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Crude</fullName>
    </customValue>
    <customValue>
        <fullName>Petroleum Products</fullName>
    </customValue>
    <customValue>
        <fullName>Petrochemical Products</fullName>
    </customValue>
    <customValue>
        <fullName>Lube Base Products</fullName>
    </customValue>
    <customValue>
        <fullName>LABIX Products</fullName>
    </customValue>
    <customValue>
        <fullName>Other Products</fullName>
    </customValue>
    <masterLabel>InterestedProductTypeasCustomerTOP</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/InterestedProductTypeasSupplierTOP.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Crude</fullName>
    </customValue>
    <customValue>
        <fullName>B100/Ethanol</fullName>
    </customValue>
    <customValue>
        <fullName>Petroleum and Components</fullName>
    </customValue>
    <customValue>
        <fullName>Normal Paraffin</fullName>
    </customValue>
    <customValue>
        <fullName>Other Products</fullName>
    </customValue>
    <masterLabel>InterestedProductTypeasSupplierTOP</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/PurchasingOrganization.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1000</fullName>
        <label>1000 SS: non-Hydrocarbon</label>
    </customValue>
    <customValue>
        <fullName>1100</fullName>
        <label>1100 SS: Hydrocarbon</label>
    </customValue>
    <customValue>
        <fullName>A000</fullName>
        <label>A000: TXTH</label>
    </customValue>
    <customValue>
        <fullName>H100</fullName>
        <label>H100: TSV</label>
    </customValue>
    <customValue>
        <fullName>I100</fullName>
        <label>I100: TSR</label>
    </customValue>
    <customValue>
        <fullName>S100</fullName>
        <label>S100: JSKem</label>
    </customValue>
    <customValue>
        <fullName>N100</fullName>
        <label>N100: TXIN</label>
    </customValue>
    <customValue>
        <fullName>9200</fullName>
        <isActive>false</isActive>
        <label>9200 - TSR</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <isActive>false</isActive>
        <label>9100 - TSV</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <isActive>false</isActive>
        <label>2000 - TXTH</label>
    </customValue>
    <customValue>
        <fullName>9300</fullName>
        <isActive>false</isActive>
        <label>9300 - JSKem</label>
    </customValue>
    <masterLabel>PurchasingOrganization</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CTRRequestFormItemEditController.cls
public with sharing class CTRRequestFormItemEditController 
{
    public class options
    {
        @AuraEnabled public String label {get; set;}
        @AuraEnabled public String value {get; set;}
    }
    public class mResultWrapper
    {
        @AuraEnabled public Id mRecordId {get; set;}
        @AuraEnabled public CTRRequestFormItem__c mRequestItem {get; set;}
        @AuraEnabled public CTRRequestFormHeader__c mRequestHeader {get; set;}
        @AuraEnabled public List<options> mProductCustomerTopPicklist {get; set;}
        @AuraEnabled public List<options> mProductSupplierTopPicklist {get; set;}
        @AuraEnabled public String mBuProfile {get; set;}
        @AuraEnabled public String mCurrentUserName {get; set;}
        @AuraEnabled public String mRecordTypeName {get; set;}
        @AuraEnabled public String mResult {get; set;}
        @AuraEnabled public String mMessage {get; set;}

    }

    @AuraEnabled
    public static mResultWrapper onloadEditPage(Id mRecordId)
    {
        try 
        {
            List<String> mRequestItemFields = new List<String>(CTRRequestFormItem__c.SObjectType.getDescribe().fields.getMap().keySet());
            String soqlItem = ''
            + ' SELECT ' + String.join(mRequestItemFields, ',')
            + ' ,CTRRequestFormHeader__r.Country__r.Code__c'
            + ' ,Customer__r.AccountNumber__c, RecordType.Name'
            + ' ,Customer__r.SupplierNumber__c'
            + ' ,Owner.ProfileId, Owner.Profile.Name'
            + ' ,RecordType.DeveloperName ,TermofPayment__r.Code__c'
            + ' FROM CTRRequestFormItem__c'
            + ' WHERE ID = :mRecordId LIMIT 1';
            CTRRequestFormItem__c mRequestItem = Database.query(soqlItem);

            Id mHeaderId = mRequestItem.CTRRequestFormHeader__c;
            List<String> mRequestHeaderFields = new List<String>(CTRRequestFormHeader__c.SObjectType.getDescribe().fields.getMap().keySet());            
            String soqlHeader = ''
                + ' SELECT ' + String.join(mRequestHeaderFields, ',')
                + ' ,Customer__r.AccountNumber__c, RecordType.DeveloperName, RecordType.Name, Customer__r.SupplierNumber__c'
                + ' FROM CTRRequestFormHeader__c'
                + ' WHERE ID = :mHeaderId LIMIT 1';
            CTRRequestFormHeader__c mHeader = Database.query(soqlHeader);

            String mSalesOrg = '';
            if(mRequestItem.RecordType.DeveloperName.contains('Customer'))
            {
                mSalesOrg = mRequestItem.SalesOrganization__c;
            }
            else if(mRequestItem.RecordType.DeveloperName.contains('Supplier'))
            {
                mSalesOrg = mRequestItem.PurchasingOrganization__c;
            }


            mResultWrapper mResult = new mResultWrapper();
            mResult.mRequestItem = mRequestItem;
            mResult.mRequestHeader = mHeader;
            mResult.mBuProfile = CTRBuProfileController.checkBusinessUnitFromProfile(UserInfo.getUserId(), mRecordId).BusinessUnit__c;
            mResult.mProductCustomerTopPicklist = convertedDropdownToOptions('CTRRequestFormItem__c', 'InterestedProductTypeAsCustomerTOP__c');
            mResult.mProductSupplierTopPicklist = convertedDropdownToOptions('CTRRequestFormItem__c', 'InterestedProductTypeAsSupplierTOP__c');
            mResult.mRecordTypeName = mRequestItem.RecordType.DeveloperName;
            mResult.mCurrentUserName = [SELECT Id, Name FROM User WHERE Id = :UserInfo.getUserId()].Name;
            mResult.mResult = 'Success';
            return mResult;
        }
        catch (Exception e) 
        {
            //throw new AuraHandledException(e.getMessage());
            mResultWrapper mResult = new mResultWrapper();
            mResult.mResult = 'Failed';
            mResult.mMessage = 'Apex Doinit Error Line '+e.getLineNumber()+' Message: '+e.getMessage();
            return mResult;
        }
    }

    public static List<options> convertedDropdownToOptions(String mObj, String mField)
    {
        List<options> mOptionList = new List<options>();
        Schema.DescribeFieldResult plistvalues = Schema.getGlobalDescribe().get(mObj).getDescribe().fields.getMap().get(mField).getDescribe();
        for(PicklistEntry mPicklist:plistvalues.getpicklistvalues()) 
        {
            options mOption = new options();
            mOption.label = mPicklist.getLabel();
            mOption.value =mPicklist.getValue();
            mOptionList.add(mOption);
        }        
        return mOptionList;
    }

    

}