force-app/main/default/objects/CTRRequestFormHeader__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Country</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>CTR Request Form Header (Country)</relationshipLabel>
        <relationshipName>CTR_Request_Form_Header1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InterestedProductTypeAsCustomerTOP__c</fullName>
        <label>Interested Product Type as Customer TOP</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>InterestedProductTypeasCustomerTOP</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>InterestedProductTypeAsCustomerTX__c</fullName>
        <label>Interested Product Type as Customer TX</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>InterestedProductTypeasCustomerTX</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>InterestedProductTypeAsSupplierTOP__c</fullName>
        <label>Interested Product Type As Supplier TOP</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>InterestedProductTypeasSupplierTOP</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>InterestedProductTypeAsSupplierTX__c</fullName>
        <label>Interested Product Type as Supplier TX</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>InterestedProductTypeasSupplierTX</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>InternalEditField__c</fullName>
        <label>Internal Edit Field</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TransportationZone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transportation Zone</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Transportation Zone</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>CTR Request Form Header (Transportation Zone)</relationshipLabel>
        <relationshipName>CTR_Request_Form_Header3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CTR Request Form Header</label>
    <nameField>
        <label>Request Form Header Name</label>
        <type>Text</type>
    </nameField>
    <recordTypes>
        <fullName>EditInformation</fullName>
        <active>true</active>
        <label>Edit Information</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Map__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Master Map Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/InterestedProductTypeasCustomerTOP.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Crude</fullName>
    </customValue>
    <customValue>
        <fullName>Petroleum Products</fullName>
    </customValue>
    <customValue>
        <fullName>Petrochemical Products</fullName>
    </customValue>
    <customValue>
        <fullName>Lube Base Products</fullName>
    </customValue>
    <customValue>
        <fullName>LABIX Products</fullName>
    </customValue>
    <customValue>
        <fullName>Other Products</fullName>
    </customValue>
    <masterLabel>InterestedProductTypeasCustomerTOP</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/InterestedProductTypeasCustomerTX.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Fuel</fullName>
    </customValue>
    <customValue>
        <fullName>Lube</fullName>
    </customValue>
    <customValue>
        <fullName>Aromatic</fullName>
    </customValue>
    <customValue>
        <fullName>LAB</fullName>
    </customValue>
    <customValue>
        <fullName>Solvents &amp; Chemical</fullName>
    </customValue>
    <customValue>
        <fullName>Olefins</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>InterestedProductTypeasCustomerTX</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/InterestedProductTypeasSupplierTOP.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Crude</fullName>
    </customValue>
    <customValue>
        <fullName>B100/Ethanol</fullName>
    </customValue>
    <customValue>
        <fullName>Petroleum and Components</fullName>
    </customValue>
    <customValue>
        <fullName>Normal Paraffin</fullName>
    </customValue>
    <customValue>
        <fullName>Other Products</fullName>
    </customValue>
    <masterLabel>InterestedProductTypeasSupplierTOP</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/InterestedProductTypeasSupplierTX.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Fuel</fullName>
    </customValue>
    <customValue>
        <fullName>Lube</fullName>
    </customValue>
    <customValue>
        <fullName>Aromatic</fullName>
    </customValue>
    <customValue>
        <fullName>LAB</fullName>
    </customValue>
    <customValue>
        <fullName>Solvents &amp; Chemical</fullName>
    </customValue>
    <customValue>
        <fullName>Olefins</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>InterestedProductTypeasSupplierTX</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CTRRequestHeaderHandlerTest.cls
@isTest
public class CTRRequestHeaderHandlerTest {

    @isTest
    static void testOnChangeJsonForEditAfterUpdate(){
        RecordType rt = [SELECT id FROM RecordType WHERE SobjectType = 'CTRRequestFormHeader__c' AND DeveloperName = 'EditInformation' limit 1];
        
        CTRRequestFormHeader__c reqHeader = new CTRRequestFormHeader__c(
            Status__c = 'New',
            RecordTypeId = rt.Id,
            InterestedProductTypeAsCustomerTOP__c = 'Crude', 
            InterestedProductTypeAsSupplierTOP__c = 'B100/Ethanol',
            InterestedProductTypeAsCustomerTX__c = 'Lube', 
            InterestedProductTypeAsSupplierTX__c = 'LAB',
            InternalEditField__c = '[{"Lebel":"TEST"}]'
        );
        insert reqHeader;

        Map<Id, CTRRequestFormHeader__c> mRequestHeaderOldMap = new Map<Id, CTRRequestFormHeader__c>();
        mRequestHeaderOldMap.put(reqHeader.Id,reqHeader);

        List<Master_Map__c> Master = new List<Master_Map__c>();
        Master_Map__c m1 = new Master_Map__c(Code__c='ZTH0245', Type__c='Transportation Zone');
        Master.add(m1);
        Master_Map__c m2 = new Master_Map__c(Code__c='TH', Type__c='Country');
        Master.add(m2);
        Master_Map__c m3 = new Master_Map__c(Code__c='TH-Bangkok', Name ='TH-Bangkok',  Type__c='Province');
        Master.add(m3);
        Master_Map__c m4 = new Master_Map__c(Code__c='mg1', Type__c='Material Group');
        Master.add(m4);
        Master_Map__c m5 = new Master_Map__c(Code__c='ZA00001', Type__c ='Payment Term');   
        Master.add(m5);
        
        insert Master;


        CTRRequestFormHeader__c reqHeaderNew = new CTRRequestFormHeader__c(
            Id = reqHeader.Id,
            Status__c = 'New',
            RecordTypeId = rt.Id,
            InterestedProductTypeAsCustomerTOP__c = 'Crude', 
            InterestedProductTypeAsSupplierTOP__c = 'B100/Ethanol',
            InterestedProductTypeAsCustomerTX__c = 'Lube', 
            InterestedProductTypeAsSupplierTX__c = 'LAB',
            InternalEditField__c = '[{"Label":"Country","Api":"Country__c","Value":"'+ Master[1].Id +'"},{"Label":"TransportationZone","Api":"TransportationZone__c","Value":"'+ Master[0].Id +'"},{"Label":"CityLocal","Api":"CityLocal__c","Value":"'+ Master[2].Id +'"}]'
        );
    
        Map<Id, CTRRequestFormHeader__c> mRequestHeaderNewMap = new Map<Id, CTRRequestFormHeader__c>();
        mRequestHeaderNewMap.put(reqHeader.Id,reqHeaderNew);


        /*Test.startTest();
        CTRRequestHeaderHandler.onChangeJsonForEditAfterUpdate(mRequestHeaderOldMap, mRequestHeaderNewMap);
        Test.stopTest();*/
    }
    
    @isTest
    static void testAddJsonEditInfoBeforeUpdate(){
        RecordType rt = [SELECT id FROM RecordType WHERE SobjectType = 'CTRRequestFormHeader__c' AND DeveloperName = 'EditInformation' limit 1];
        
        List<Master_Map__c> Master = new List<Master_Map__c>();
        Master_Map__c m1 = new Master_Map__c(Code__c='ZTH0245', Type__c='Transportation Zone');
        Master.add(m1);
        Master_Map__c m2 = new Master_Map__c(Code__c='TH', Type__c='Country');
        Master.add(m2);
        Master_Map__c m3 = new Master_Map__c(Code__c='TH-Bangkok', Name ='TH-Bangkok',  Type__c='Province');
        Master.add(m3);
        Master_Map__c m4 = new Master_Map__c(Code__c='mg1', Type__c='Material Group');
        Master.add(m4);
        Master_Map__c m5 = new Master_Map__c(Code__c='ZA00001', Type__c ='Payment Term');   
        Master.add(m5);
        
        insert Master;

        CTRRequestFormHeader__c reqHeader = new CTRRequestFormHeader__c(
            Status__c = 'New',
            Name = 'Test',
            RecordTypeId = rt.Id,
            InterestedProductTypeAsCustomerTOP__c = 'Crude', 
            InterestedProductTypeAsSupplierTOP__c = 'B100/Ethanol',
            InterestedProductTypeAsCustomerTX__c = 'Lube', 
            InterestedProductTypeAsSupplierTX__c = 'LAB',
            InternalEditField__c = '[{"Label":"Country","Api":"Country__c","Value":"'+ Master[1].Id +'", "Source":""},{"Label":"TransportationZone","Api":"TransportationZone__c","Value":"'+ Master[0].Id +'", "Source":""},{"Label":"CityLocal","Api":"CityLocal__c","Value":"'+ Master[2].Id +'", "Source":""}]'
        );
        insert reqHeader;
        Id mID = reqHeader.Id;
        List<String> mRequestHeaderFields = new List<String>(CTRRequestFormHeader__c.SObjectType.getDescribe().fields.getMap().keySet());            
        String soqlHeader = ''
            + ' SELECT ' + String.join(mRequestHeaderFields, ',')
            + ' FROM CTRRequestFormHeader__c'
            + ' WHERE Id = :mID LIMIT 1';
        CTRRequestFormHeader__c reqHeaderQ1 = Database.query(soqlHeader);
        

        Map<Id, CTRRequestFormHeader__c> mRequestHeaderOldMap = new Map<Id, CTRRequestFormHeader__c>();
        mRequestHeaderOldMap.put(reqHeader.Id,reqHeaderQ1);

        
        CTRRequestFormHeader__c reqHeaderNew2 = new CTRRequestFormHeader__c(
            Name = 'Edit Test2',
            Status__c = 'New',
            RecordTypeId = rt.Id,
            InterestedProductTypeAsCustomerTOP__c = 'Crude', 
            InterestedProductTypeAsSupplierTOP__c = 'B100/Ethanol',
            InterestedProductTypeAsCustomerTX__c = 'Lube', 
            InterestedProductTypeAsSupplierTX__c = 'LAB',
            InternalEditField__c = '[{"Label":"Country","Api":"Country__c","Value":"'+ Master[1].Id +'", "Source":""},{"Label":"Transportation Zone","Api":"TransportationZone__c","Value":"'+ Master[0].Id +'"},{"Label":"CityLocal","Api":"CityLocal__c","Value":"'+ Master[2].Id +'", "Source":""}]'
        );
        
        // insert reqHeaderNew2;
        reqHeaderQ1.Name = 'Edit test';
        Map<Id, CTRRequestFormHeader__c> mRequestHeaderNewMap = new Map<Id, CTRRequestFormHeader__c>();
        mRequestHeaderNewMap.put(reqHeader.Id,reqHeaderQ1);
        
        Test.startTest();
         	reqHeaderQ1.Name = 'Edit test';
        	update reqHeaderQ1;
        //CTRRequestHeaderHandler.AddJsonEditInfoBeforeUpdate(mRequestHeaderOldMap, mRequestHeaderNewMap);
        Test.stopTest();
    }


    @isTest
    static void testAddJsonEditInfoBeforeUpdate2()
    {
        RecordType rt = [SELECT id FROM RecordType WHERE SobjectType = 'CTRRequestFormHeader__c' AND DeveloperName = 'EditInformation' limit 1];

        List<Master_Map__c> Master = new List<Master_Map__c>();
        Master_Map__c m1 = new Master_Map__c(Code__c='ZTH0245', Type__c='Transportation Zone');
        Master.add(m1);
        Master_Map__c m2 = new Master_Map__c(Code__c='TH', Type__c='Country');
        Master.add(m2);
        Master_Map__c m3 = new Master_Map__c(Code__c='TH-Bangkok', Name ='TH-Bangkok',  Type__c='Province');
        Master.add(m3);
        Master_Map__c m4 = new Master_Map__c(Code__c='mg1', Type__c='Material Group');
        Master.add(m4);
        Master_Map__c m5 = new Master_Map__c(Code__c='ZA00001', Type__c ='Payment Term');   
        Master.add(m5);

        insert Master;

        CTRRequestFormHeader__c reqHeader = new CTRRequestFormHeader__c(
            Status__c = 'New',
            Name = 'Test',
            RecordTypeId = rt.Id,
            InterestedProductTypeAsCustomerTOP__c = 'Crude', 
            InterestedProductTypeAsSupplierTOP__c = 'B100/Ethanol',
            InterestedProductTypeAsCustomerTX__c = 'Lube', 
            InterestedProductTypeAsSupplierTX__c = 'LAB',
            InternalEditField__c = '[{"Label":"Country","Api":"Country__c","Value":"'+ Master[1].Id +'", "Source":""},{"Label":"TransportationZone","Api":"TransportationZone__c","Value":"'+ Master[0].Id +'", "Source":""},{"Label":"CityLocal","Api":"CityLocal__c","Value":"'+ Master[2].Id +'", "Source":""}]'
        );
        insert reqHeader;
        
        Map<Id, CTRRequestFormHeader__c> mRequestHeaderOldMap = new Map<Id, CTRRequestFormHeader__c>();
        mRequestHeaderOldMap.put(reqHeader.Id, reqHeader);

        CTRRequestFormHeader__c reqHeaderNew = new CTRRequestFormHeader__c(
            Id = reqHeader.Id,
            Name = 'Edit Test2',
            Status__c = 'New',
            RecordTypeId = rt.Id,
            InterestedProductTypeAsCustomerTOP__c = 'Crude', 
            InterestedProductTypeAsSupplierTOP__c = 'B100/Ethanol',
            InterestedProductTypeAsCustomerTX__c = 'Lube',  
            InterestedProductTypeAsSupplierTX__c = 'LAB',
            InternalEditField__c = '[{"Label":"Country","Api":"Country__c","Value":"'+ Master[1].Id +'", "Source":""},{"Label":"Transportation Zone","Api":"TransportationZone__c","Value":"'+ Master[0].Id +'"},{"Label":"CityLocal","Api":"CityLocal__c","Value":"'+ Master[2].Id +'", "Source":""}]'
        );

        Test.startTest();
        // Simulate changes in the header fields
        reqHeaderNew.Name = 'Edit test';
        Map<Id, CTRRequestFormHeader__c> mRequestHeaderNewMap = new Map<Id, CTRRequestFormHeader__c>();
        mRequestHeaderNewMap.put(reqHeader.Id, reqHeaderNew);

        // Call the method you want to test
        CTRRequestHeaderHandler.AddJsonEditInfoBeforeUpdate(mRequestHeaderOldMap, mRequestHeaderNewMap);
        Test.stopTest();

        // Add assertions if needed
    }


}