force-app/main/default/objects/CTRRequestFormHeader__c.object
<CustomObject>
    <fields>
        <fullName>AccountGroup__c</fullName>
        <label>Account Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AccountGroup</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Authorization__c</fullName>
        <label>Authorization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BuildingCodeLocal__c</fullName>
        <label>Building Code (Local)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CashManagementGroup__c</fullName>
        <label>Cash Management Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PO Lr-Feedstack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CityStateLocal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City/State (Local)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Province</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>CTR Request Form Header</relationshipLabel>
        <relationshipName>CTR_Request_Form_Header</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CoName__c</fullName>
        <label>C/O Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Country</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>CTR Request Form Header (Country)</relationshipLabel>
        <relationshipName>CTR_Request_Form_Header1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomerNameEN1__c</fullName>
        <label>CustomerNameEN1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerNameEN2__c</fullName>
        <label>CustomerNameEN2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerNameLocal1__c</fullName>
        <label>CustomerNameLocal1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerNameLocal2__c</fullName>
        <label>CustomerNameLocal2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerSearchTermEN__c</fullName>
        <label>Customer Search Term (EN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerSearchTermLocal__c</fullName>
        <label>Customer Search Term(Local)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Request_Form_Header</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DistrictENText__c</fullName>
        <label>DistrictENText</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DistrictLocalText__c</fullName>
        <label>District (Local)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FaxCountryCode__c</fullName>
        <label>Fax Country Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCodePhone</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>FaxExtension__c</fullName>
        <label>Fax Extension</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fax__c</fullName>
        <label>Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>FloorLocal__c</fullName>
        <label>Floor (Local)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HousenoLocal__c</fullName>
        <label>House no. (Local)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LanguageForIntegrationM41</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MobileCountryCode__c</fullName>
        <label>Mobile Country Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCodePhone</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MobilePhone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PhoneCountryCode__c</fullName>
        <label>Phone Country Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CountryCodePhone</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PhoneExtension__c</fullName>
        <label>Phone Extension</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PostalCodeLocalText__c</fullName>
        <label>PostalCodeLocalText</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchasingOrganization__c</fullName>
        <label>Purchasing Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PurchasingOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReconAccount__c</fullName>
        <label>Recon. Account</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1020000</fullName>
                    <label>1020000  Trade Account Receivable - Others</label>
                </value>
                <value>
                    <fullName>1020010  Trade Account Receivable - Others Allwdoubtfuldebt</fullName>
                </value>
                <value>
                    <fullName>1020100  Trade Account Receivable - Group Consolidation</fullName>
                </value>
                <value>
                    <fullName>1020110  Trade Account Receivable-GrpConsol AllowaDoubtDebt</fullName>
                </value>
                <value>
                    <fullName>1020200  Trade Account Receivable - Related</fullName>
                </value>
                <value>
                    <fullName>1020210  Trade Account Receivable-Related AllowDoubtfulDebt</fullName>
                </value>
                <value>
                    <fullName>1040000  Other Account Receivable - Others</fullName>
                </value>
                <value>
                    <fullName>1040010 Other Account Receivable-Other AllowaceDoubtfulDbt</fullName>
                </value>
                <value>
                    <fullName>1040100  Other Account Receivable - Group Consolidation</fullName>
                </value>
                <value>
                    <fullName>1040110  Other Account Receivable-GrpCons AllowDoubtfulDebt</fullName>
                </value>
                <value>
                    <fullName>1040200  Other Account Receivable - Related</fullName>
                </value>
                <value>
                    <fullName>1040210  Other Account Receivable-Relate-Allow. Doubt.Debt</fullName>
                </value>
                <value>
                    <fullName>2040090  Other Account Payable - Advance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RegionSAP__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RoomLocal__c</fullName>
        <label>Room (Local)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortKey__c</fullName>
        <label>Sort Key</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>009</fullName>
                    <label>009 External Doc. Number</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street2EN__c</fullName>
        <label>Street2EN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street2Local__c</fullName>
        <label>Street2Local</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street3EN__c</fullName>
        <label>Street3EN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street3Local__c</fullName>
        <label>Street3Local</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street4EN__c</fullName>
        <label>Street4EN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street4Local__c</fullName>
        <label>Street4Local</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street5EN__c</fullName>
        <label>Street5EN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street5Local__c</fullName>
        <label>Street5Local</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetEN__c</fullName>
        <label>StreetEN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetLocal__c</fullName>
        <label>Street (Local)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubDistrictLocalText__c</fullName>
        <label>Sub District (Local)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SupplierSearchTermEN__c</fullName>
        <label>Supplier Search Term (EN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SupplierSearchTermLocal__c</fullName>
        <label>Supplier Search Term (Local)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TAXClassification__c</fullName>
        <label>TAX Classification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TaxClassification</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaxCode1__c</fullName>
        <label>Tax Code1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeZone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeZone</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TradingPartner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trading Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Trading Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>CTR Request Form Header (Trading Partner)</relationshipLabel>
        <relationshipName>CTR_Request_Form_Header8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TypeOfBusinessBranch__c</fullName>
        <label>Type of Business (Branch)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TypeOfBusinessBranch</valueSetName>
        </valueSet>
    </fields>
    <label>CTR Request Form Header</label>
    <nameField>
        <label>Request Form Header Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Map__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Master Map Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/AccountGroup.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>TOPG</fullName>
        <label>TOPG=TOP Group</label>
    </customValue>
    <customValue>
        <fullName>TRDL</fullName>
        <label>TRDL=Trade Receivable - Local</label>
    </customValue>
    <customValue>
        <fullName>ZSHP</fullName>
        <label>ZSHP=Ship-to Party</label>
    </customValue>
    <customValue>
        <fullName>TRDF</fullName>
        <label>TRDF=Trade Receivable - Foreign</label>
    </customValue>
    <customValue>
        <fullName>ZBIL</fullName>
        <label>ZBIL=Bill-to Party</label>
    </customValue>
    <customValue>
        <fullName>NTRF</fullName>
        <isActive>false</isActive>
        <label>NTRF : Non Trade Payable - Foreign</label>
    </customValue>
    <customValue>
        <fullName>NTRL</fullName>
        <isActive>false</isActive>
        <label>NTRL : Non Trade Payable - Local</label>
    </customValue>
    <customValue>
        <fullName>ONET</fullName>
        <isActive>false</isActive>
        <label>ONET : One Time Vendor Group</label>
    </customValue>
    <customValue>
        <fullName>GOVN</fullName>
        <isActive>false</isActive>
        <label>GOVN : Government Vendor Group</label>
    </customValue>
    <masterLabel>Account Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LanguageForIntegrationM41.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2</fullName>
        <label>Thai</label>
    </customValue>
    <customValue>
        <fullName>E</fullName>
        <label>English</label>
    </customValue>
    <masterLabel>Language (For Integration M4-1)</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/PurchasingOrganization.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1000</fullName>
        <label>1000 SS: non-Hydrocarbon</label>
    </customValue>
    <customValue>
        <fullName>1100</fullName>
        <label>1100 SS: Hydrocarbon</label>
    </customValue>
    <customValue>
        <fullName>A000</fullName>
        <label>A000: TXTH</label>
    </customValue>
    <customValue>
        <fullName>H100</fullName>
        <label>H100: TSV</label>
    </customValue>
    <customValue>
        <fullName>I100</fullName>
        <label>I100: TSR</label>
    </customValue>
    <customValue>
        <fullName>S100</fullName>
        <label>S100: JSKem</label>
    </customValue>
    <customValue>
        <fullName>N100</fullName>
        <label>N100: TXIN</label>
    </customValue>
    <customValue>
        <fullName>9200</fullName>
        <isActive>false</isActive>
        <label>9200 - TSR</label>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
        <isActive>false</isActive>
        <label>9100 - TSV</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <isActive>false</isActive>
        <label>2000 - TXTH</label>
    </customValue>
    <customValue>
        <fullName>9300</fullName>
        <isActive>false</isActive>
        <label>9300 - JSKem</label>
    </customValue>
    <masterLabel>PurchasingOrganization</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TaxClassification.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <label>0 : Tax Excempt</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>1 : Liable for Taxes</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>2 : Free Tax Zone</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>3 : Non Tax</label>
    </customValue>
    <masterLabel>Tax Classification</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TypeOfBusinessBranch.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>00000</fullName>
    </customValue>
    <customValue>
        <fullName>00001</fullName>
    </customValue>
    <customValue>
        <fullName>00002</fullName>
    </customValue>
    <customValue>
        <fullName>00003</fullName>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
    </customValue>
    <masterLabel>TypeOfBusinessBranch</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CTRShipToRequestFormItemModelDataTest.cls
@isTest
public class CTRShipToRequestFormItemModelDataTest {
   
    @TestSetup
    static void makeData(){
        Account mAccount = new Account();
        mAccount.Name = 'Test Initial Account';
        mAccount.AccountNumber__c = '0001';
        mAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Initial').getRecordTypeId();
        insert mAccount;

        Master_Map__c m1 = new Master_Map__c(Code__c='TSV', Type__c='Trading Partner');
        insert m1;

        CTRRequestFormHeader__c mRequestHeader = new CTRRequestFormHeader__c();
        mRequestHeader.Name = 'Initial Account Request Header';
        mRequestHeader.Status__c = 'New';
        mRequestHeader.Customer__c = mAccount.Id;
        mRequestHeader.TradingPartner__c = m1.Id;
        insert mRequestHeader;

        RecordType rt = [SELECT id FROM RecordType WHERE SobjectType = 'CTRRequestFormItem__c' AND DeveloperName = 'SupplierInitial' limit 1];
        CTRRequestFormItem__c reqItemConditionTrue = new CTRRequestFormItem__c();
        reqItemConditionTrue.Name = 'TestConditionTrue Item';
        reqItemConditionTrue.CTRRequestFormHeader__c = mRequestHeader.Id;
        reqItemConditionTrue.RecordTypeId = rt.Id;
        reqItemConditionTrue.EmailTo__c = 'testemailto@test.com';
        reqItemConditionTrue.EmailCC__c = 'testemailcc@test.com';
        reqItemConditionTrue.PurchasingOrganization__c = 'H100';
        insert reqItemConditionTrue;
    }

    @isTest
    public static void testSetupJsonForSupplierDataModel(){

        CTRRequestFormHeader__c mRequestHeader = [SELECT ID,Customer__c,
                                                    AccountGroup__c,
                                                    TaxCode1__c,
                                                    CoName__c,
                                                    CustomerNameLocal1__c,
                                                    CustomerNameLocal2__c,
                                                    CityStateLocal__r.Description__c,
                                                    DistrictLocalText__c,
                                                    PostalCodeLocalText__c,
                                                    BuildingCodeLocal__c,
                                                    RoomLocal__c,
                                                    FloorLocal__c,
                                                    HousenoLocal__c,
                                                    StreetLocal__c,
                                                    Street2Local__c,
                                                    Street3Local__c,
                                                    Street4Local__c,
                                                    Street5Local__c,
                                                    Country__r.Code__c,
                                                    Language__c,
                                                    SupplierSearchTermLocal__c,
                                                    SupplierSearchTermEN__c,
                                                    PhoneCountryCode__c,
                                                    Phone__c,
                                                    PhoneExtension__c,
                                                    FaxCountryCode__c,
                                                    Fax__c,
                                                    FaxExtension__c,
                                                    Email__c,
                                                    MobileCountryCode__c,
                                                    MobilePhone__c,
                                                    CustomerNameEN1__c,
                                                    CustomerNameEN2__c,
                                                    DistrictENText__c,
                                                    StreetEN__c,
                                                    Street2EN__c,
                                                    Street3EN__c,
                                                    Street4EN__c,
                                                    Street5EN__c,
                                                    SortKey__c,
                                                    ReconAccount__c,
                                                    CashManagementGroup__c,
                                                    Authorization__c,
                                                    TradingPartner__c,
                                                    RegionSAP__c,
                                                    TimeZone__c,
                                                    CustomerSearchTermLocal__c,
                                                    CustomerSearchTermEN__c,
                                                    TAXClassification__c,
                                                    SubDistrictLocalText__c,TypeOfBusinessBranch__c,CustomerTypeSAP__c,Industry__c,
                                                    TradingPartner__r.Code__c
                                                    FROM CTRRequestFormHeader__c LIMIT 1];
        CTRRequestFormItem__c mRequestItem = [SELECT ID, GatewayId__c,Customer__r.SupplierNumber__c,PurchasingOrganization__c,
                                                Incoterms__c,
                                                Incoterms2__c,
                                                Currency__c,
                                                TermOfPayment__r.Code__c,
                                                GRBasedInvVerif__c,
                                                VendorName__c,
                                                VendorPhone__c,
                                                ShippingConditions__c,
                                                SalesOrganization__c,
                                                ReconAccount__c,
                                                PaymentMethod__c,
                                                AccigClerk__c,
                                                CashManagementGroup__c,
                                                SortKey__c,
                                                WHTaxCountry__c,
                                                Chkdoubleinv__c,
                                                DistributionChannel__c,
                                                Division__c,
                                                RecordType.DeveloperName,
                                                CreditControlArea__c,
                                                SalesDistrict__c,
                                                SalesOffice__c,
                                                SalesGroup__c,
                                                OrderProbability__c,
                                                ExchangeRateType__c,
                                                CustPriceProc__c,
                                                CustStatGroup__c,
                                                DeliveryPriority__c,
                                                DeliveryPlant__c,
                                                OrderCombination__c,
                                                PartialDeliveriesperitem__c,
                                                MaxPartialDeliveries__c,
                                                UnderdeliveryTolerance__c,
                                                OverdeliveryTolerance__c,
                                                Rebate__c,
                                                IsPriceDetermin__c,
                                                PriceGroup__c,
                                                AccountAssignmentGroup__c,
                                                PaymentGuaranteeProcedure__c,PaymentHistoryRecord__c
                                                FROM CTRRequestFormItem__c LIMIT 1];
        Test.startTest();
        CTRShipToRequestFormItemModelData.SetupJsonForShipToDataModel(mRequestHeader, mRequestItem, 'General', 'TX', 'UUID');
        CTRShipToRequestFormItemModelData.SetupJsonForShipToDataModel(mRequestHeader, mRequestItem, 'Sale', 'TX', 'UUID');
        Test.stopTest();

    }
}