force-app/main/default/objects/E_MOC_Application__c.object
<CustomObject>
    <fields>
        <fullName>Disable_Alarm_by_Ops_for_HW__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disable alarm by Ops for HW</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inhibit_Alarm_request_for_FOX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inhibit alarm request for FOX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inhibit_alarm_for_maintenance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inhibit alarm for maintenance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inhibit_for_process_or_Equipment_S_D__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>(Excluded Fire&amp;Gas system)</inlineHelpText>
        <label>Inhibit for process or equipment S/D</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MOS_for_maintenance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MOS for maintenance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MOS_for_ops_purpose__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MOS for Ops purpose</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OOS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OOS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Safeguarding_force_signal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Safeguarding force signal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status_Functional_Override__c</fullName>
        <label>Status Functional Override</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                </value>
                <value>
                    <fullName>Approval #1</fullName>
                </value>
                <value>
                    <fullName>Implementation#1</fullName>
                </value>
                <value>
                    <fullName>Approval #2</fullName>
                </value>
                <value>
                    <fullName>Risk assessment</fullName>
                </value>
                <value>
                    <fullName>Technical review</fullName>
                </value>
                <value>
                    <fullName>Approval #3 (APU)</fullName>
                </value>
                <value>
                    <fullName>Approval #3 (VP)</fullName>
                </value>
                <value>
                    <fullName>Implementation#2</fullName>
                </value>
                <value>
                    <fullName>Return to normal condition</fullName>
                </value>
                <value>
                    <fullName>Close out</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>E-MOC Application</label>
    <nameField>
        <label>E-MOC No.</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EMOC_StatusPathFnOvrController.cls
public class EMOC_StatusPathFnOvrController {
    @AuraEnabled
    public static List<Map<String, String>> getStageNamePath(String recordId) {
        Schema.DescribeFieldResult fieldResult = E_MOC_Application__c.Status_Functional_Override__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        List<Map<String, String>> valuesList = new List<Map<String, String>>();
        for( Schema.PicklistEntry pickListVal : ple){
            Map<String, String> listValues= new Map<String, String>();
            E_MOC_Application__c emocApp = [SELECT Id, Status_Functional_Override__c ,
                                            OOS__c, MOS_for_ops_purpose__c, Inhibit_for_process_or_Equipment_S_D__c,
                                            Inhibit_alarm_for_maintenance__c, Disable_Alarm_by_Ops_for_HW__c, Inhibit_Alarm_request_for_FOX__c,
                                            MOS_for_maintenance__c, Safeguarding_force_signal__c 
                                            FROM E_MOC_Application__c  WHERE Id = :recordId ];
            if (emocApp.OOS__c == true || emocApp.MOS_for_ops_purpose__c == true || emocApp.Inhibit_for_process_or_Equipment_S_D__c == true) {
                if (pickListVal.getValue() != 'Approval #2' && pickListVal.getValue() != 'Risk assessment' && pickListVal.getValue() != 'Technical review' 
                    && pickListVal.getValue() != 'Approval #3 (APU)' && pickListVal.getValue() != 'Approval #3 (VP)' && pickListVal.getValue() != 'Implementation#2' && pickListVal.getValue() != 'Cancelled' && pickListVal.getValue() != 'Rejected' ) {
                    listValues.put('value', pickListVal.getValue());
                    listValues.put('label', pickListVal.getLabel());  
                    listValues.put('currentStep',emocApp.Status_Functional_Override__c != null ? emocApp.Status_Functional_Override__c : '');
                    listValues.put('customcss',emocApp.Status_Functional_Override__c != pickListVal.getValue() ? 'slds-tabs_path__item slds-is-incomplete' : 'slds-tabs_path__item slds-is-current');
                    valuesList.add(listValues);
                } else if ((emocApp.Status_Functional_Override__c  == 'Cancelled' && pickListVal.getValue() == 'Cancelled') || (emocApp.Status_Functional_Override__c  == 'Rejected' && pickListVal.getValue() == 'Rejected')) {
                    listValues.put('value', pickListVal.getValue());
                    listValues.put('label', pickListVal.getLabel());
                    listValues.put('currentStep',emocApp.Status_Functional_Override__c  != null ? emocApp.Status_Functional_Override__c  : '');
                    listValues.put('customcss',emocApp.Status_Functional_Override__c  != null && emocApp.Status_Functional_Override__c  != pickListVal.getValue() ? 'slds-tabs_path__item slds-is-incomplete' : 'slds-tabs_path__item slds-is-current');
                    valuesList.add(listValues);
                } 
            } else if (emocApp.Inhibit_alarm_for_maintenance__c == true || emocApp.Disable_Alarm_by_Ops_for_HW__c == true || emocApp.Inhibit_Alarm_request_for_FOX__c == true) {
                if (pickListVal.getValue() != 'Risk assessment' && pickListVal.getValue() != 'Technical review' && pickListVal.getValue() != 'Approval #3 (APU)' 
                    && pickListVal.getValue() != 'Approval #3 (VP)' && pickListVal.getValue() != 'Cancelled' && pickListVal.getValue() != 'Rejected' ) {
                    listValues.put('value', pickListVal.getValue());
                    listValues.put('label', pickListVal.getLabel());  
                    listValues.put('currentStep',emocApp.Status_Functional_Override__c != null ? emocApp.Status_Functional_Override__c : '');
                    listValues.put('customcss',emocApp.Status_Functional_Override__c != pickListVal.getValue() ? 'slds-tabs_path__item slds-is-incomplete' : 'slds-tabs_path__item slds-is-current');
                    valuesList.add(listValues);
                } else if (pickListVal.getValue() != 'Risk assessment' && pickListVal.getValue() != 'Technical review' && pickListVal.getValue() != 'Approval #3 (APU)' && pickListVal.getValue() != 'Approval #3 (VP)' && ((emocApp.Status_Functional_Override__c  == 'Cancelled' && pickListVal.getValue() == 'Cancelled') || (emocApp.Status_Functional_Override__c  == 'Rejected' && pickListVal.getValue() == 'Rejected'))) {
                    listValues.put('value', pickListVal.getValue());
                    listValues.put('label', pickListVal.getLabel());
                    listValues.put('currentStep',emocApp.Status_Functional_Override__c  != null ? emocApp.Status_Functional_Override__c  : '');
                    listValues.put('customcss',emocApp.Status_Functional_Override__c  != null && emocApp.Status_Functional_Override__c  != pickListVal.getValue() ? 'slds-tabs_path__item slds-is-incomplete' : 'slds-tabs_path__item slds-is-current');
                    valuesList.add(listValues);
                } 
            } else if (emocApp.MOS_for_maintenance__c == true || emocApp.Safeguarding_force_signal__c == true) {
                if (pickListVal.getValue() != 'Cancelled' && pickListVal.getValue() != 'Rejected' ) {
                    listValues.put('value', pickListVal.getValue());
                    listValues.put('label', pickListVal.getLabel());  
                    listValues.put('currentStep',emocApp.Status_Functional_Override__c != null ? emocApp.Status_Functional_Override__c : '');
                    listValues.put('customcss',emocApp.Status_Functional_Override__c != pickListVal.getValue() ? 'slds-tabs_path__item slds-is-incomplete' : 'slds-tabs_path__item slds-is-current');
                    valuesList.add(listValues);
                } else if ((emocApp.Status_Functional_Override__c  == 'Cancelled' && pickListVal.getValue() == 'Cancelled') || (emocApp.Status_Functional_Override__c  == 'Rejected' && pickListVal.getValue() == 'Rejected')) {
                    listValues.put('value', pickListVal.getValue());
                    listValues.put('label', pickListVal.getLabel());
                    listValues.put('currentStep',emocApp.Status_Functional_Override__c  != null ? emocApp.Status_Functional_Override__c  : '');
                    listValues.put('customcss',emocApp.Status_Functional_Override__c  != null && emocApp.Status_Functional_Override__c  != pickListVal.getValue() ? 'slds-tabs_path__item slds-is-incomplete' : 'slds-tabs_path__item slds-is-current');
                    valuesList.add(listValues);
                } 
            }
        }
        return valuesList;
    } 
}