force-app/main/default/objects/EQCC_Checked_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Form_Name__c</fullName>
        <label>Form Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Type__c</fullName>
        <label>Form Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sheet_Code__c</fullName>
        <label>Sheet Code</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>EQCC Checked Sheet</label>
    <nameField>
        <label>EQCC Checked Sheet Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EQCC_Header__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>EQCC Headers</relationshipLabel>
        <relationshipName>EQCC_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FunctionalLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Location</label>
        <referenceTo>Functional_Location__c</referenceTo>
        <relationshipLabel>EQCC Headers</relationshipLabel>
        <relationshipName>EQCC_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Location__c</fullName>
        <formula>Order__r.Functional_Location__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Functional Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center_Text__c</fullName>
        <label>Main Work Center Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Notification</label>
        <referenceTo>Notification__c</referenceTo>
        <relationshipLabel>EQCC Headers</relationshipLabel>
        <relationshipName>EQCC_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>EQCC Headers</relationshipLabel>
        <relationshipName>EQCC_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EQCC Header</label>
    <nameField>
        <displayFormat>EQCCH-{0000}</displayFormat>
        <label>EQCC Header</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>mainWorkCenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>mainWorkCenter</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Main Work Center</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Equipment</relationshipLabel>
        <relationshipName>Equipment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Functional_Location__c.object
<CustomObject>
    <fields>
        <fullName>MainWorkCenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MainWorkCenter</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Main Work Center</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Functional Location (MainWorkCenter)</relationshipLabel>
        <relationshipName>Functional_Location5</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Functional Location</label>
    <nameField>
        <label>Functional Location</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Header_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Header__c</fullName>
        <label>EQCC Header</label>
        <referenceTo>EQCC_Header__c</referenceTo>
        <relationshipLabel>Header Sheets</relationshipLabel>
        <relationshipName>Header_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sheet__c</fullName>
        <label>EQCC Checked Sheet</label>
        <referenceTo>EQCC_Checked_Sheet__c</referenceTo>
        <relationshipLabel>Header Sheets</relationshipLabel>
        <relationshipName>Header_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF(!ISNULL(Header__r.Order__c) &amp;&amp; ISPICKVAL(Header__r.Order__r.Order_Type__c, &quot;CM01&quot;), &quot;CM&quot;, 
IF(!ISNULL(Header__r.Order__c) &amp;&amp; ISPICKVAL(Header__r.Order__r.Order_Type__c, &quot;PM01&quot;), &quot;PM&quot;,
IF(!ISNULL(Header__r.Order__c) &amp;&amp; ISPICKVAL(Header__r.Order__r.Order_Type__c, &quot;SH01&quot;), &quot;SH&quot;, 
IF(!ISNULL(Header__r.Notification__c), Text(Header__r.Order__r.Order_Type__c), &quot;&quot;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Header Sheet</label>
    <nameField>
        <displayFormat>HS-{0000}</displayFormat>
        <label>Header Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Map__c.object
<CustomObject>
    <fields>
        <fullName>Master_Map_Set__c</fullName>
        <label>Master Map Set</label>
        <referenceTo>Master_Map_Set__c</referenceTo>
        <relationshipLabel>Master Maps</relationshipLabel>
        <relationshipName>Master_Maps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Master Map Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Map_Set__c.object
<CustomObject>
    <label>Master Map Set</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Master Map Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Location</label>
        <referenceTo>Functional_Location__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center_Text__c</fullName>
        <label>Main Work Center Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Work Center</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notification_Number__c</fullName>
        <externalId>true</externalId>
        <label>Notification Number</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Order does not integration with SAP System</errorMessage>
            <filterItems>
                <field>Order__c.Order_Number__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CM</fullName>
                    <default>true</default>
                    <label>CM</label>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>SH</fullName>
                </value>
                <value>
                    <fullName>OP</fullName>
                </value>
                <value>
                    <fullName>CR</fullName>
                </value>
                <value>
                    <fullName>FN</fullName>
                </value>
                <value>
                    <fullName>PJ</fullName>
                    <isActive>false</isActive>
                    <label>PJ</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Location</label>
        <referenceTo>Functional_Location__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center_Text__c</fullName>
        <label>Main Work Center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Work Center</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Orders (Main Work Center)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Notification</label>
        <referenceTo>Notification__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/SetEQCCHeaderHelperTest.cls
/**
* @R2
* @description test class for SetEQCCHeaderHelper
*/
@isTest
public class SetEQCCHeaderHelperTest {
    @testSetup
    static void setup() {
        Master_Map_Set__c mapSet = new Master_Map_Set__c();
        insert mapSet;
        Master_Map__c masterMapNotification = new Master_Map__c(
            Name = 'Test Master Notification',
            Type__c = 'Main Work Center',
            Master_Map_Set__c = mapSet.Id
        );
        insert masterMapNotification;
        Master_Map__c masterMapOrder = new Master_Map__c(
            Name = 'Test Master Order',
            Type__c = 'Main Work Center',
            Master_Map_Set__c = mapSet.Id
        );
        insert masterMapOrder;
        Master_Map__c masterMapEquipment = new Master_Map__c(
            Name = 'Test Master Equipment',
            Type__c = 'Main Work Center',
            Master_Map_Set__c = mapSet.Id
        );
        insert masterMapEquipment;
        Master_Map__c masterMapFLocation = new Master_Map__c(
            Name = 'Test Master FLocation',
            Type__c = 'Main Work Center',
            Master_Map_Set__c = mapSet.Id
        );
        insert masterMapFLocation;
        Notification__c notification = new Notification__c(
            Notification_Number__c = '10676451',
            Main_Work_Center__c = masterMapNotification.Id
        );
        insert notification;
        
        Order__c order = new Order__c(Name = '12345678', Main_Work_Center__c = masterMapOrder.Id);
        insert order;
        
        Equipment__c equipment = new Equipment__c(Name = 'Equipment', mainWorkCenter__c = masterMapEquipment.Id);
        insert equipment;
        
        Functional_Location__c fLocation = new Functional_Location__c(
            Name = 'fLocation',
            MainWorkCenter__c = masterMapFLocation.Id
        );
        insert fLocation;
        
        
    }
    
    @isTest
    static void DeleteEQCCHeader() 
    {
        Order__c order = getOrder();
        Equipment__c equipment = getEquipment();
        Functional_Location__c fLocation = getFunctionalLocation();
        EQCC_Header__c header = new EQCC_Header__c(
            Order__c = order.Id,
            Equipment__c = equipment.Id,
            FunctionalLocation__c = fLocation.Id
        );
        insert header;
        try
        {
            Delete 	header;
        }
        catch(Exception ee)
        {}
    }
    
    @isTest
    static void UpdateEQCCHeader() 
    {
        Notification__c notification = getNotification();
        Order__c order = getOrder();
        Equipment__c equipment = getEquipment();
        Functional_Location__c fLocation = getFunctionalLocation();
        EQCC_Header__c header = new EQCC_Header__c(
            Order__c = order.Id,
            Equipment__c = equipment.Id,
            FunctionalLocation__c = fLocation.Id
        );
        insert header;
        
        EQCC_Checked_Sheet__c eqccCheckSheet = new EQCC_Checked_Sheet__c(
            Name = 'Sheet 4',
            Form_Name__c = 'General Flange Assembly QAQC Rev01',
            Form_Type__c = 'Flange_Assembly_Control_Record',
            Sheet_Code__c = 'EQCC-MECH-001'
        );
        insert eqccCheckSheet;
            
        Header_Sheet__c headerSheet = new Header_Sheet__c(
            Sheet__c = eqccCheckSheet.Id,
            Header__c = header.Id
        );
        insert headerSheet;
        
        update header;
        
    }

    @isTest
    static void testMainWorkCenterNotification() {
        Notification__c notification = getNotification();
        Order__c order = getOrder();
        Equipment__c equipment = getEquipment();
        Functional_Location__c fLocation = getFunctionalLocation();
        EQCC_Header__c header = new EQCC_Header__c(
            Notification__c = notification.Id,
            Order__c = order.Id,
            Equipment__c = equipment.Id,
            FunctionalLocation__c = fLocation.Id
        );

        Test.startTest();
        insert header;
        Test.stopTest();

        header = getHeaderById(header.Id);

        System.assertEquals(
            notification.Main_Work_Center__c,
            header.Main_Work_Center_Text__c,
            'EQCC Header MWC value should have been pulled from the Notification MWC'
        );
    }

    @isTest
    static void testMainWorkCenterOrder() {
        Order__c order = getOrder();
        Equipment__c equipment = getEquipment();
        Functional_Location__c fLocation = getFunctionalLocation();
        EQCC_Header__c header = new EQCC_Header__c(
            Order__c = order.Id,
            Equipment__c = equipment.Id,
            FunctionalLocation__c = fLocation.Id
        );

        Test.startTest();
        insert header;
        Test.stopTest();

        header = getHeaderById(header.Id);

        System.assertEquals(
            order.Main_Work_Center__c,
            header.Main_Work_Center_Text__c,
            'EQCC Header MWC value should have been pulled from the Order MWC'
        );
    }

    @isTest
    static void testMainWorkCenterEquipment() {
        Equipment__c equipment = getEquipment();
        Functional_Location__c fLocation = getFunctionalLocation();
        EQCC_Header__c header = new EQCC_Header__c(Equipment__c = equipment.Id, FunctionalLocation__c = fLocation.Id);

        Test.startTest();
        insert header;
        Test.stopTest();

        header = getHeaderById(header.Id);

        System.assertEquals(
            equipment.MainWorkCenter__c,
            header.Main_Work_Center_Text__c,
            'EQCC Header MWC value should have been pulled from the Equipment MWC'
        );
    }

    @isTest
    static void testMainWorkCenterFunctionalLocation() {
        Functional_Location__c fLocation = getFunctionalLocation();
        EQCC_Header__c header = new EQCC_Header__c(FunctionalLocation__c = fLocation.Id);

        Test.startTest();
        insert header;
        Test.stopTest();

        header = getHeaderById(header.Id);

        System.assertEquals(
            fLocation.MainWorkCenter__c,
            header.Main_Work_Center_Text__c,
            'EQCC Header MWC value should have been pulled from the Functional Location MWC'
        );
    }

    private static Notification__c getNotification() {
        return [SELECT Id, Main_Work_Center__c FROM Notification__c LIMIT 1];
    }

    private static Equipment__c getEquipment() {
        return [SELECT Id, MainWorkCenter__c FROM Equipment__c LIMIT 1];
    }

    private static Functional_Location__c getFunctionalLocation() {
        return [SELECT Id, MainWorkCenter__c FROM Functional_Location__c LIMIT 1];
    }

    private static EQCC_Header__c getHeaderById(Id headerId) {
        return [SELECT Id, Main_Work_Center_Text__c FROM EQCC_Header__c WHERE Id = :headerId];
    }

    private static Order__c getOrder() {
        return [SELECT Id, Main_Work_Center__c FROM Order__c LIMIT 1];
    }
}