force-app/main/default/objects/EQCC_Checked_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Form_Name__c</fullName>
        <label>Form Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EQCC Checked Sheet</label>
    <nameField>
        <label>EQCC Checked Sheet Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EQCC_Header__c.object
<CustomObject>
    <fields>
        <fullName>Form_Name_Text__c</fullName>
        <label>Form Name</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>EQCC Header</label>
    <nameField>
        <displayFormat>EQCCH-{0000}</displayFormat>
        <label>EQCC Header</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Header_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Header__c</fullName>
        <label>EQCC Header</label>
        <referenceTo>EQCC_Header__c</referenceTo>
        <relationshipLabel>Header Sheets</relationshipLabel>
        <relationshipName>Header_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sheet__c</fullName>
        <label>EQCC Checked Sheet</label>
        <referenceTo>EQCC_Checked_Sheet__c</referenceTo>
        <relationshipLabel>Header Sheets</relationshipLabel>
        <relationshipName>Header_Sheets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Header Sheet</label>
    <nameField>
        <displayFormat>HS-{0000}</displayFormat>
        <label>Header Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SetEQCCHeaderHelper.cls
/**
 * @author R2
 * @description helper for SetEQCCHeaderHelper Trigger
 */
public with sharing class SetEQCCHeaderHelper {
	public static void updateEQCCHeader(List<EQCC_Header__c> eqccHeaders){

        Map<Id, List<Header_Sheet__c>> eqccHeaderMap = new Map<Id, List<Header_Sheet__c>>();
        Set<Id> eqccHeaderIdSet = new Set<Id>();
        for (EQCC_Header__c eqccHeader : eqccHeaders){
            //List<Header_Sheet__c> headerSheets = [SELECT Id, Sheet__r.Form_Name__c FROM Header_Sheet__c WHERE Header__c =: eqccHeader.Id];
            eqccHeaderIdSet.add(eqccHeader.Id);
            
        }

        for(EQCC_Header__c eqccHeader : [SELECT Id, (SELECT Id, Sheet__r.Form_Name__c FROM Header_Sheets__r) FROM EQCC_Header__c WHERE Id IN: eqccHeaderIdSet]) {
            eqccHeaderMap.put(eqccHeader.Id, eqccHeader.Header_Sheets__r);
        }

        for(EQCC_Header__c eqccHeader : eqccHeaders) {
            if(eqccHeaderMap.containsKey(eqccHeader.Id)) {
                List<Header_Sheet__c> headerSheets = eqccHeaderMap.get(eqccHeader.Id);
                String str = '';
                for(Header_Sheet__c headerSheet : headerSheets) {
                    str += headerSheet.Sheet__r.Form_Name__c + ',';
                }
                eqccHeader.Form_Name_Text__c = str;
            }
        }
	}
}