force-app/main/default/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>description__c</fullName>
        <label>description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>location__c</fullName>
        <label>location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Functional_Location__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maintenance_Plant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Maintenance Plant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Plant</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Functional Location (Maintenance Plant)</relationshipLabel>
        <relationshipName>Functional_Location6</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Functional Location</label>
    <nameField>
        <label>Functional Location</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/THOR_Filter__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Breakdown__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Breakdown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clearance_Number__c</fullName>
        <label>Clearance Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Date_From__c</fullName>
        <label>Create Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Create_Date_To__c</fullName>
        <label>Create Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_By__c</fullName>
        <label>Created By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>- Notification Description 
- Order Description</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter_type__c</fullName>
        <label>Filter type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HomeNotification</fullName>
                </value>
                <value>
                    <fullName>HomeOrder</fullName>
                </value>
                <value>
                    <fullName>Notification</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>EQCC</fullName>
                </value>
                <value>
                    <fullName>My Approval</fullName>
                </value>
                <value>
                    <fullName>Work Clearance</fullName>
                </value>
                <value>
                    <fullName>NotificationHistorical</fullName>
                    <label>Notification Historical</label>
                </value>
                <value>
                    <fullName>OrderHistorical</fullName>
                    <label>Order Historical</label>
                </value>
                <value>
                    <fullName>WorkClearanceHistorical</fullName>
                    <label>Work Clearance Historical</label>
                </value>
                <value>
                    <fullName>EQCCHistorical</fullName>
                    <label>EQCC Historical</label>
                </value>
                <value>
                    <fullName>ODM Notification</fullName>
                </value>
                <value>
                    <fullName>ODM_HistoricalNotification</fullName>
                </value>
                <value>
                    <fullName>ODM WorkClearance</fullName>
                </value>
                <value>
                    <fullName>ODM_HistoricalWorkClearance</fullName>
                </value>
                <value>
                    <fullName>ODM WorkClearance Inspection</fullName>
                </value>
                <value>
                    <fullName>ODM WorkClearance Verification</fullName>
                </value>
                <value>
                    <fullName>ODM NotificationSwitchOver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Functional_Location__c</fullName>
        <label>Functional Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center__c</fullName>
        <label>Main Work Center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maintenance_Plant__c</fullName>
        <label>Maintenance Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NotificationTypeMulti__c</fullName>
        <label>NotificationTypeMulti</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>SH</fullName>
                </value>
                <value>
                    <fullName>OP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification_Date__c</fullName>
        <label>Notification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Notification_Number__c</fullName>
        <label>Notification Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Type__c</fullName>
        <label>Notification Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CM</fullName>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>SH</fullName>
                </value>
                <value>
                    <fullName>OP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderTypeMulti__c</fullName>
        <label>OrderTypeMulti</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CM01</fullName>
                </value>
                <value>
                    <fullName>PM01</fullName>
                </value>
                <value>
                    <fullName>SH01</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CM01</fullName>
                </value>
                <value>
                    <fullName>PM01</fullName>
                </value>
                <value>
                    <fullName>SH01</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plant_Section__c</fullName>
        <label>Plant Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriorityMulti__c</fullName>
        <label>Priority</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Normal</fullName>
                </value>
                <value>
                    <fullName>Urgent</fullName>
                </value>
                <value>
                    <fullName>Immediately</fullName>
                </value>
                <value>
                    <fullName>Float Time - 1M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 3M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 6M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 9M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 12M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 15M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 18M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Normal</fullName>
                </value>
                <value>
                    <fullName>Urgent</fullName>
                </value>
                <value>
                    <fullName>Immediately</fullName>
                </value>
                <value>
                    <fullName>Float Time - 1M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 3M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 6M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 9M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 12M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 15M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 18M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Date_Form__c</fullName>
        <label>Requested Date Form</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requested_Date_To__c</fullName>
        <label>Requested Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <label>Requester</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusMulti__c</fullName>
        <label>StatusMulti</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Delete Flag</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Need Revision</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Date_From__c</fullName>
        <label>Submission Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submission_Date_To__c</fullName>
        <label>Submission Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>THOR_Filter</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>THOR Filter</label>
    <nameField>
        <label>THOR Filter Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ODM_HistoricalSearchController.cls
public with sharing class ODM_HistoricalSearchController {

	@AuraEnabled
	public static string getMyMainWorkCenter(){
		User me = [SELECT Main_Work_Center__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
		return me.Main_Work_Center__c;
	}

	@AuraEnabled
	public static Object getMyFilterHistoricalSearch(String filterType, List<String> fields) {
		Id userId = UserInfo.getUserId();
		Set<String> fieldSets = new Set<String>(fields);

		// fields.add('Id');
		// System.debug('fieldSets' + fieldSets);
		String query = String.format(
			'SELECT {0} FROM THOR_Filter__c WHERE User__c = :userId AND Filter_type__c = :filterType LIMIT 1',
			new List<String>{ String.join(fields, ', ') }
		);

		THOR_Filter__c filterValues = (THOR_Filter__c) Database.query(query);
		return filterValues;
	}

	@AuraEnabled
	public static Object getHistoricalNotificationList(
		String filter,
		Integer offset,
		Integer rowlimit,
		Boolean isSharingSettings
	) {
		try {
			THOR_Filter__c notificationFields = [
				SELECT
					id,
					Notification_Number__c,
					NotificationTypeMulti__c,
					StatusMulti__c,
					Functional_Location__c,
					Create_Date_From__c,
					Create_Date_To__c,
					Notification_Date__c,
					Requester__c,
					Submission_Date_From__c,
					Submission_Date_To__c,
					Main_Work_Center__c,
					Maintenance_Plant__c,
					Plant_Section__c,
					Description__c
				FROM THOR_Filter__c
				WHERE id = :filter
				LIMIT 1
			];

			Map<String, String> filterMap = new Map<String, String>();
			filterMap.put('Notification_Number__c', notificationFields.Notification_Number__c);
			filterMap.put('Functional_Location__c', notificationFields.Functional_Location__c);
			filterMap.put('Notification_Type__c', notificationFields.NotificationTypeMulti__c);
			filterMap.put('Notification_Status__c', notificationFields.StatusMulti__c);
			filterMap.put('Create_Date_From__c', String.valueOf(notificationFields.Create_Date_From__c));
			filterMap.put('Create_Date_To__c', String.valueOf(notificationFields.Create_Date_To__c));
			filterMap.put('Notification_Date__c', String.valueOf(notificationFields.Notification_Date__c));
			filterMap.put('Requester__c', notificationFields.Requester__c);
			filterMap.put('Main_Work_Center__c', notificationFields.Main_Work_Center__c);
			//filterMap.put('MaintenancePlantText__c', notificationFields.Maintenance_Plant__c);
			filterMap.put('Submission_Date_From__c', String.valueOf(notificationFields.Submission_Date_From__c));
			filterMap.put('Submission_Date_To__c', String.valueOf(notificationFields.Submission_Date_To__c));
			filterMap.put('Maintenance_Plant__c', String.valueOf(notificationFields.Maintenance_Plant__c));
			filterMap.put('Plant_Section__c', String.valueOf(notificationFields.Plant_Section__c));
			filterMap.put('Description__c', String.valueOf(notificationFields.Description__c));

			for (String key : filterMap.keySet()) {
				// if blank as value for key, value pair
				// if (filterMap.get(key) == null || filterMap.get(key) == '' || filterMap.get(key) == 'null') {
				if (String.isEmpty(filterMap.get(key))) {
					filterMap.remove(key);
				}
			}

			Object obj = ODM_NotificationController.getNotificationList(filterMap, offset, rowlimit, isSharingSettings);
			return obj;
		} catch (Exception e) {
			System.debug(System.LoggingLevel.DEBUG, e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}

	@AuraEnabled
	public static Object getHistoricalWcList(
		String filter,
		Integer offset,
		Integer rowlimit,
		Boolean isSharingSettings
	) {
		//try {
			THOR_Filter__c wcFields = [
				SELECT
					id,
					Clearance_Number__c,
					StatusMulti__c,
					Main_Work_Center__c,
					Functional_Location__c,
					Create_Date_From__c,
					Create_Date_To__c,
					Requested_Date_Form__c,
					Requested_Date_To__c,
					Notification_Number__c,
					NotificationTypeMulti__c,
					Order_Number__c,
					OrderTypeMulti__c,
					PriorityMulti__c,
					Created_By__c,
					Requester__c,
					Area__c,
					Location__c,
					Plant_Section__c,
					Maintenance_Plant__c
				FROM THOR_Filter__c
				WHERE id = :filter
				LIMIT 1
			];

			Map<String, String> filterMap = new Map<String, String>();
			filterMap.put('Clearance_Number__c', wcFields.Clearance_Number__c);
			filterMap.put('Status__c', wcFields.StatusMulti__c);
			filterMap.put('Functional_Location__c', wcFields.Functional_Location__c);
			filterMap.put('Main_Work_Center__c', wcFields.Main_Work_Center__c);
			filterMap.put('Area__c', wcFields.Area__c);
			filterMap.put('MaintenancePlantText__c', wcFields.Maintenance_Plant__c);
			filterMap.put('Create_Date_From__c', String.valueOf(wcFields.Create_Date_From__c));
			filterMap.put('Create_Date_To__c', String.valueOf(wcFields.Create_Date_To__c));
			filterMap.put('Requested_Date_Form__c', String.valueOf(wcFields.Requested_Date_Form__c));
			filterMap.put('Requested_Date_To__c', String.valueOf(wcFields.Requested_Date_To__c));
			filterMap.put('Notification_Number__c', wcFields.Notification_Number__c);
			filterMap.put('Notification_Type__c', wcFields.NotificationTypeMulti__c);
			filterMap.put('Order_Number__c', wcFields.Order_Number__c);
			filterMap.put('Order_Type__c', wcFields.OrderTypeMulti__c);
			filterMap.put('Priority__c', wcFields.PriorityMulti__c);
			filterMap.put('Requester__c', wcFields.Requester__c);
			filterMap.put('Plant_Section__c', wcFields.Plant_Section__c);
			filterMap.put('Location__c', wcFields.Location__c);

			for (String key : filterMap.keySet()) {
				// if blank as value for key, value pair
				// if (filterMap.get(key) == null || filterMap.get(key) == '' || filterMap.get(key) == 'null') {
				if (String.isEmpty(filterMap.get(key))) {
					filterMap.remove(key);
				}
			}

			Object obj = ODM_WorkClearanceController.getWcList(filterMap, offset, rowlimit, isSharingSettings);
			return obj;
		//} catch (Exception e) {
		//	System.debug(System.LoggingLevel.DEBUG, e.getStackTraceString());
		//	throw new AuraHandledException(e.getMessage());
		//}
	}

	@AuraEnabled
	public static sObject getMyFilter(String recordId) {
		try {
			List<THOR_Filter__c> savedFilters = [
				SELECT
					Id,
					Name,
					Filter_type__c,
					Notification_Number__c,
					NotificationTypeMulti__c,
					Functional_Location__c,
					Create_Date_To__c,
					Create_Date_From__c,
					StatusMulti__c,
					PriorityMulti__c,
					Main_Work_Center__c,
					Plant_Section__c,
					Maintenance_Plant__c,
					Location__c,
					Breakdown__c,
					Order_Number__c,
					OrderTypeMulti__c,
					Super_Order__c,
					Clearance_Number__c,
					// Requested_Date_Form__c,
					// Requested_Date_To__c,
					Created_By__c,
					Creator__c,
					Equipment__c,
					EQCC_Code__c,
					EQCC_Name__c,
					Notification_Date__c,
					Requester__c,
					Submission_Date_From__c,
					Submission_Date_To__c
				FROM THOR_Filter__c
				WHERE Id = :recordId
				LIMIT 1
			];

			if (savedFilters.size() > 0) {
				return savedFilters[0];
			} else {
				return null;
			}
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}
}