force-app/main/default/objects/ESS_Master_Stationary__c.object
<CustomObject>
    <fields>
        <fullName>Service_For__c</fullName>
        <label>Service For</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TSR</fullName>
                    <label>TOP-TSR (ศรีราชา)</label>
                </value>
                <value>
                    <fullName>TBK</fullName>
                    <label>TOP-TBK (กรุงเทพ)</label>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stock_on_Hand__c</fullName>
        <label>Stock on Hand</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>ESS Master Stationary</label>
    <nameField>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ESS_Stationary__c.object
<CustomObject>
    <fields>
        <fullName>Accepted_By__c</fullName>
        <label>Accepted By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approved_Comment__c</fullName>
        <label>Approved Comment</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Approved_Date__c</fullName>
        <label>Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Attentiveness_Rating_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attentiveness Rating 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attentiveness_Rating__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attentiveness Rating</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancel_Comment__c</fullName>
        <label>Cancel Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancelled_By__c</fullName>
        <label>Cancelled By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancelled_Date__c</fullName>
        <label>Cancelled Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Document_No__c</fullName>
        <label>Document No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expertise_Rating_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expertise Rating 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expertise_Rating__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expertise Rating</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fast_Rating_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fast Rating 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fast_Rating__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fast Rating</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_No__c</fullName>
        <label>Internal No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_No__c</fullName>
        <label>Mobile No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Need_Date__c</fullName>
        <label>Need Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>On_Behalf_Flow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>On Behalf Flow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>On_Behalf_Of_Department__c</fullName>
        <label>On Behalf Of Department</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>On_Behalf_Of_EN__c</fullName>
        <label>On Behalf Of EN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>On_Behalf_Of_Email__c</fullName>
        <label>On Behalf Of Email</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>On_Behalf_Of_Employee_Id__c</fullName>
        <label>On Behalf Of Employee Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>On_Behalf_Of_Flow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>On Behalf Of Flow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>On_Behalf_Of_Function__c</fullName>
        <label>On Behalf Of Function</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>On_Behalf_Of_Position__c</fullName>
        <label>On Behalf Of Position</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>On_Behalf_Of_Section__c</fullName>
        <label>On Behalf Of Section</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>On_Behalf_Of_Unit__c</fullName>
        <label>On Behalf Of Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>On_Behalf_Of_Verifying__c</fullName>
        <defaultValue>false</defaultValue>
        <label>On Behalf Of Verifying</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PMSV_Comment__c</fullName>
        <label>PMSV Comment</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PMSV__c</fullName>
        <label>PMSV</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Punctuality_Rating_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Punctuality Rating 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Punctuality_Rating__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Punctuality Rating</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rating_Date_2__c</fullName>
        <label>Rating Date 2</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Rating_Date__c</fullName>
        <label>Rating Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Rating_Score_2__c</fullName>
        <label>Rating Score 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rating_Score__c</fullName>
        <label>Rating Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reject_Comment__c</fullName>
        <label>Reject Comment</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rejected_By__c</fullName>
        <label>Rejected By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rejected_Date__c</fullName>
        <label>Rejected Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Requester_Department__c</fullName>
        <label>Requester Department</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester_Email__c</fullName>
        <label>Requester Email</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester_Employee_Id__c</fullName>
        <label>Requester Employee Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester_Function__c</fullName>
        <label>Requester Function</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester_Name_EN__c</fullName>
        <label>Requester Name EN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester_Position__c</fullName>
        <label>Requester Position</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester_Section__c</fullName>
        <label>Requester Section</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester_Unit__c</fullName>
        <label>Requester Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_For__c</fullName>
        <label>Service For</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TOPTSR</fullName>
                    <label>TOP-TSR (ศรีราชา)</label>
                </value>
                <value>
                    <fullName>TOPTBK</fullName>
                    <label>TOP-TBK (กรุงเทพ)</label>
                </value>
                <value>
                    <fullName>TLB</fullName>
                </value>
                <value>
                    <fullName>TPX</fullName>
                </value>
                <value>
                    <fullName>TTC</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>TES</fullName>
                </value>
                <value>
                    <fullName>LABIX</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <label>อื่นๆ</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Staff_Comment__c</fullName>
        <label>Staff Comment</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>WaitingToApprove</fullName>
                    <label>To Be Approved</label>
                </value>
                <value>
                    <fullName>OnProcess</fullName>
                    <label>On Process</label>
                </value>
                <value>
                    <fullName>Verifying</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <label>Submitted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_Other__c</fullName>
        <label>Total Other</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Stock__c</fullName>
        <label>Total Stock</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_Manager_EN__c</fullName>
        <label>User Manager EN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Manager_Flow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>User Manager Flow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Verified_By__c</fullName>
        <label>Verified By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Verified_Date__c</fullName>
        <label>Verified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Verify_Comment__c</fullName>
        <label>Verify Comment</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Withdraw_From_Stock__c</fullName>
        <label>Withdraw From Stock</label>
        <length>30000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Withdraw_From__c</fullName>
        <label>Withdraw From</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TSR</fullName>
                    <label>สำนักงานศรีราชา (TSR)</label>
                </value>
                <value>
                    <fullName>TBK</fullName>
                    <label>สำนักงานกรุงเทพ (TBK)</label>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Withdraw_Other__c</fullName>
        <label>Withdraw Other</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <label>ESS Stationary</label>
    <nameField>
        <displayFormat>STA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ESS_StationaryExcelController.cls
public with sharing class ESS_StationaryExcelController {

    public integer stationarySize {get;set;}
    public string todayDate {get;set;}
    public string todayTime {get;set;}
    public integer year {get;set;}
    public string monthName {get;set;}
    public string stationaryFrom {get;set;}
    
    public List<ESS_Stationary_DTO.StationaryExcelDTO> stationaryTables {get;set;}
    
    public void OnloadExcel() {
        
        year = datetime.now().year();
        todayDate = datetime.now().format('dd-MM-yyyy');
        todayTime = datetime.now().format('HH:mm');
        string userId = ESS_PrivilegeHandler.getUserId();
        stationarySize = 0;
        stationaryTables = new List<ESS_Stationary_DTO.StationaryExcelDTO>();
        
        ESS_Stationary.AdminSearchCriteria filter = new ESS_Stationary.AdminSearchCriteria();
        if(ApexPages.currentPage().getParameters().get('year') != null && ApexPages.currentPage().getParameters().get('year') != 'null') {
            filter.year = Integer.ValueOf(ApexPages.currentPage().getParameters().get('year'));
        }
        if(ApexPages.currentPage().getParameters().get('month') != null && ApexPages.currentPage().getParameters().get('month') != 'null') {
            filter.month = Integer.ValueOf(ApexPages.currentPage().getParameters().get('month'));
        	monthName = getMonthName(filter.month);
        }
        
        PISUsers__c loginedUser = new PISUsers__c();
        User User = new User();
        boolean isPRTRUser = ESS_Global.checkPRTRUser(userId);
        if(isPRTRUser) {
            User = ESS_Global.assignToUser(userId);
        }
        else {
            loginedUser = ESS_Global.assignToPISUser(userId);
        }

        string query = ESS_Stationary.getStationaryDetailQuery();

        //Add authorize filter
        query +=  ' where document_no__c != null'; 

        //From Privilege
        List<string> loginAs = ESS_PrivilegeHandler.StationaryLoginPrivilege();
        if(loginAs.size() > 0) {
            query += ' and Withdraw_From__c IN :loginAs';
            
            if(loginAs.size() == 1) {
                stationaryFrom = loginAs.tostring().replace('(','').replace(')','');
                if(stationaryFrom == ESS_Enum.StationaryWithdrawFrom.TSR.name()) {
                    stationaryFrom = 'PMSV';
                }
                else if(stationaryFrom == ESS_Enum.StationaryWithdrawFrom.TBK.name()) {
                    stationaryFrom = 'GSBO';
                }
            }
            else if(loginAs.size() > 1) {
                stationaryFrom = 'ALL';
            }
        }
        
        if (filter != null) {
            if (filter.year != null) {
                integer year = filter.year;
                query += ' and CALENDAR_YEAR(CreatedDate) = :year';
            }
            if (filter.month != null && filter.month != 0) {
                integer month = filter.month;
                query += ' and CALENDAR_MONTH(CreatedDate) = :month';
            }
        }
        
        query += ' order by createddate desc';
        Map<string, ESS_Master_Stationary__c> mapMasters = GetStationaryMasters();
        List<ESS_Stationary__c> models = Database.query(query);
        for (ESS_Stationary__c model : models) {
            
            ESS_Stationary_DTO.StationaryExcelDTO result = new ESS_Stationary_DTO.StationaryExcelDTO();
            
            //Withdraw Stock
            if(string.isNotBlank(model.Withdraw_From_Stock__c)) {
                List<ESS_Stationary_DTO.WithdrawDTO> withdrawStocks = (List<ESS_Stationary_DTO.WithdrawDTO>)JSON.deserialize(model.Withdraw_From_Stock__c, List<ESS_Stationary_DTO.WithdrawDTO>.class);
                if(withdrawStocks.size() > 0) {
                    for(integer j=0; j < withdrawStocks.size(); j++) {
                        result = new ESS_Stationary_DTO.StationaryExcelDTO();
                        result.typeOfStationary = ESS_Enum.StationaryType.General.name();
                        result.stationaryId = withdrawStocks[j].stationaryId;
                        result.stationaryName = withdrawStocks[j].name;
                        result.withdrawQuantity = integer.valueOf(withdrawStocks[j].quantity);
                        result.actualQuantity = integer.valueOf(withdrawStocks[j].actualWithdraw);
                        result.unit = withdrawStocks[j].unit;
                        result.price = integer.valueOf(withdrawStocks[j].pricePerUnit);
                        
                        ESS_Master_Stationary__c Master = mapMasters.get(withdrawStocks[j].recordId);
                        if(Master != null) {
                            result.stockOnHand = integer.valueOf(Master.stock_on_hand__c);
                        }
                        stationaryTables.add(assignToStationaryListDTO(model, result));
                    }
                }
            }
            //Withdraw Other
            if(string.isNotBlank(model.Withdraw_Other__c)) {
                List<ESS_Stationary_DTO.WithdrawDTO> withdrawOthers = (List<ESS_Stationary_DTO.WithdrawDTO>)JSON.deserialize(model.Withdraw_Other__c, List<ESS_Stationary_DTO.WithdrawDTO>.class);
                if(withdrawOthers.size() > 0) {
                    for(integer j=0; j < withdrawOthers.size(); j++) {
                        result = new ESS_Stationary_DTO.StationaryExcelDTO();
                        result.typeOfStationary = ESS_Enum.StationaryType.Other.name();
                        result.stationaryId = withdrawOthers[j].stationaryId;
                        result.stationaryName = withdrawOthers[j].name;
                        result.withdrawQuantity = integer.valueOf(withdrawOthers[j].quantity);
                        result.actualQuantity = integer.valueOf(withdrawOthers[j].actualWithdraw);
                        result.unit = withdrawOthers[j].unit;
                        result.price = withdrawOthers[j].pricePerUnit;
                        stationaryTables.add(assignToStationaryListDTO(model, result));
                    }
                }
            }
        }
        
        stationarySize = stationaryTables.size();

    }
    
    private static ESS_Stationary_DTO.StationaryExcelDTO assignToStationaryListDTO(ESS_Stationary__c model, ESS_Stationary_DTO.StationaryExcelDTO result){
        string userId = ESS_PrivilegeHandler.getUserId();
        
        result.documentNo = model.Document_No__c;
        if(model.On_Behalf_Flow__c) {
            result.documentType = 'ดำเนินการแทน';
        }
        else {
            result.documentType = 'ดำเนินการเอง';
        }
        result.withdrawFrom = model.withdraw_from__c;
        result.serviceFor = model.service_for__c;
        result.location = model.location__c;
        if(string.isnotempty(model.internal_no__c)) {
            result.internalNo = model.internal_no__c;
        }
        else {
            result.internalNo = '';
        }
        if(string.isnotempty(model.mobile_no__c)) {
            result.mobileNo = model.mobile_no__c;
        }
        else {
            result.mobileNo = '';
        }
        result.needDate = model.need_date__c;
        result.totalStock = model.total_stock__c;
        result.totalOther = model.total_other__c;
        result.total = model.total__c;
        result.comment = model.comment__c;
        result.verifyStatus = '';
        result.obhComment = '';
        if(model.on_behalf_of_flow__c && model.on_behalf_of_verifying__c) {
            if(model.verified_date__c != null && model.rejected_date__c == null) {
                result.obhComment = model.verify_comment__c;
                result.verifyStatus = 'Verify';
                result.verifiedRejectedDate = model.verified_date__c;
            }
            else if((model.verified_date__c == null && model.rejected_date__c != null) ||
                    model.verified_date__c != null && model.rejected_date__c != null) {
                result.obhComment = model.reject_comment__c;
                result.verifyStatus = 'Reject';
                result.verifiedRejectedDate = model.rejected_date__c;
            }
        }
        result.approveStatus = '';
        result.userManagerComment = '';
        if(model.user_manager_flow__c) {
            if(model.approved_date__c != null) {
                result.userManagerComment = model.approved_comment__c;
                result.approvedRejectedDate = model.approved_date__c;
                result.approveStatus = 'Approved';
            }
            else if(model.approved_date__c == null && model.rejected_date__c != null) {
                result.userManagerComment = model.reject_comment__c;
                result.approvedRejectedDate = model.rejected_date__c;
                result.approveStatus = 'Reject';
            }
        }
        result.staffComment = model.staff_comment__c;
        result.pmsvComment = model.pmsv_comment__c;
        result.requesterName = model.requester_name_en__c;
        if(string.isnotempty(model.requester_employee_id__c)) {
            result.requesterEmployeeId = model.requester_employee_id__c;
        }
        else {
            result.requesterEmployeeId = '';
        }
        result.requesterEmail = model.requester_email__c;
        result.requesterPosition = model.requester_position__c;
        result.requesterFunction = model.requester_function__c;
        result.requesterDepartment = model.requester_department__c;
        result.requesterSection = model.requester_section__c;
        result.requesterUnit = model.requester_unit__c;
        result.obhName = model.on_behalf_of_en__c;
        if(string.isnotempty(model.on_behalf_of_employee_id__c)) {
            result.obhEmployeeId = model.on_behalf_of_employee_id__c;
        }
        else {
            result.obhEmployeeId = '';
        }
        result.obhEmail = model.on_behalf_of_email__c;
        result.obhPosition = model.on_behalf_of_position__c;
        result.obhFunction = model.on_behalf_of_function__c;
        result.obhDepartment = model.on_behalf_of_department__c;
        result.obhSection = model.on_behalf_of_section__c;
        result.obhUnit = model.on_behalf_of_unit__c;
        result.userManagerName = model.user_manager_en__c;
        result.createdDate = model.createdDate;
        result.submittedDate = model.submitted_date__c;
        result.verifiedDate = model.verified_date__c;
        result.approvedDate = model.approved_date__c;
        result.completedDate = model.completed_date__c;
        result.rejectedDate = model.rejected_date__c;
        result.cancelledDate = model.cancelled_date__c;
        result.acceptedBy = model.accepted_by__c;
        result.completedBy = model.pmsv__c;
        result.cancelledBy = model.cancelled_by__c;
        result.verifiedBy = model.verified_by__c;
        result.rejectedBy = model.rejected_by__c;
        result.verifyComment = model.verify_comment__c;
        result.rejectComment = model.reject_comment__c;
        result.cancelledComment = model.cancel_comment__c;
        result.currentStatus = model.status__c;
        result.requesterRatingCompleted = false;
        if(model.rating_date__c != null) {
            result.requesterRatingCompleted = true;
        }
        result.requesterRating = integer.valueOf(model.rating_score__c);
        result.requesterAttentiveness = model.attentiveness_rating__c;
        result.requesterFast = model.fast_rating__c;
        result.requesterPunctuality = model.punctuality_rating__c;
        result.requesterExpertise = model.expertise_rating__c;
        
        result.obhRatingCompleted = false;
        if(model.rating_date_2__c != null) {
            result.obhRatingCompleted = true;
        }
        result.obhRating = integer.valueOf(model.rating_score_2__c);
        result.obhAttentiveness = model.attentiveness_rating_2__c;
        result.obhFast = model.fast_rating_2__c;
        result.obhPunctuality = model.punctuality_rating_2__c;
        result.obhExpertise = model.expertise_rating_2__c;
        return result;
    }
    
    public static Map<string,ESS_Master_Stationary__c> GetStationaryMasters() {
        Map<string,ESS_Master_Stationary__c> mapMasters = new Map<string,ESS_Master_Stationary__c>();
        string query = getMasterStationaryQuery();
        List<ESS_Master_Stationary__c> Masters = database.query(query);
        if(Masters.size() > 0) {
            for(ESS_Master_Stationary__c Master : Masters) {
                mapMasters.put(Master.Id, Master);
            }
        }
        return mapMasters;
    }
    
    public static string getMasterStationaryQuery()
    {
        return 
        'SELECT Active__c,Attachment_Files__c,Available_Stock__c,CreatedDate,Due_Stock__c,Id,LastModifiedById,' +
        'LastModifiedDate,Last_Updated_By__c,Last_Updated_Date__c,Minimum_Stock__c,Name,Other_Supplier__c,OwnerId,' +
        'Price__c,Service_For__c,Stationary_Name__c,Stock_History__c,Stock_on_Hand__c,Supplier__c,Type__c,Unit__c,Image_Url__c,IsLowerMinimumStock__c,' +
        'Last_Updated_By_User__c,Last_Updated_Date_User__c' +
        ' from ESS_Master_Stationary__c where name != null';
    }
    
    public static string getMonthName(integer month) {
        string monthName = '';
        if(month == 1) {
            monthName = 'January';
        }
        else if(month == 2) {
            monthName = 'February';
        }
        else if(month == 3) {
            monthName = 'March';
        }
        else if(month == 4) {
            monthName = 'April';
        }
        else if(month == 5) {
            monthName = 'May';
        }
        else if(month == 6) {
            monthName = 'June';
        }
        else if(month == 7) {
            monthName = 'July';
        }
        else if(month == 8) {
            monthName = 'August';
        }
        else if(month == 9) {
            monthName = 'September';
        }
        else if(month == 10) {
            monthName = 'October';
        }
        else if(month == 11) {
            monthName = 'November';
        }
        else if(month == 12) {
            monthName = 'December';
        }
        else {
            monthName = 'ALL';
        }
        
        return monthName;
    }

}