force-app/main/default/objects/ESS_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Application_Running_No__c</fullName>
        <inlineHelpText>ETI-YYYY-MM-XXXX</inlineHelpText>
        <label>Application Running No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <label>Environment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ESS Config</label>
</CustomObject>

force-app/main/default/objects/ESS_Letter_of_Recommendation__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <label>Employee ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <label>Function</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ESS Letter of Recommendation</label>
    <nameField>
        <displayFormat>LOR-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ESS_Master_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Address_EN_House_No__c</fullName>
        <label>Address EN House No</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_TH_House_No__c</fullName>
        <label>Address TH House No</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Child_JSON__c</fullName>
        <label>Child JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Person_JSON__c</fullName>
        <label>Contact Person JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>OUT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Death_Child_JSON__c</fullName>
        <label>Death Child JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Education_JSON__c</fullName>
        <label>Education JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employee_DOB__c</fullName>
        <label>Employee DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee_Date_Joined__c</fullName>
        <label>Employee Date Joined</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <label>Employee ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_Retirement_Date__c</fullName>
        <label>Employee Retirement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>License_Citizen_Expire_Date__c</fullName>
        <label>License Citizen Expire Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Citizen_Id__c</fullName>
        <label>License Citizen Id</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Citizen_Issue_Date__c</fullName>
        <label>License Citizen Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name_Emp_EN_FN__c</fullName>
        <label>Name Emp EN FN</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Emp_EN_LN__c</fullName>
        <label>Name Emp EN LN</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Emp_EN_Title__c</fullName>
        <label>Name Emp EN Title</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Mr.</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Mrs.</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Miss</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Ms.</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Dr.</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name_Emp_TH_Title_FN_LN__c</fullName>
        <label>Name Emp TH Title FN LN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Marriage_Doc_Issue_Date__c</fullName>
        <label>Status Marriage Doc Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_Marriage_Status__c</fullName>
        <label>Status Marriage Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>Single</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>Married</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Widow</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Divorced</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Seperate</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Marriage_Person_Earn_Income__c</fullName>
        <inlineHelpText>1) ลดหย่อนคู่สมรส = คู่สมรสไม่มีเงินได้
(2) ไม่ลดหย่อนคู่สมรส = คู่สมรสมีเงินได้</inlineHelpText>
        <label>Tax Marriage Person Earn Income</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>ลดหย่อนคู่สมรส</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>ไม่ลดหย่อนคู่สมรส</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Marriage_Status__c</fullName>
        <label>Tax Marriage Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>Single</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>Married</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ESS Master Employee</label>
    <nameField>
        <displayFormat>ME-{00000}</displayFormat>
        <label>ESS Master Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ESS_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Letter_TES_HR_Name_TH__c</fullName>
        <label>Letter : TES HR Name TH</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Letter_TES_HR_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Letter : TES HR Name</label>
        <referenceTo>PISUsers__c</referenceTo>
        <relationshipLabel>ESS Setting (Letter : TES HR Name)</relationshipLabel>
        <relationshipName>ESS_Setting_TES_HR</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Letter_TES_Request__c</fullName>
        <label>Letter : TES Request</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Letter_TOP_HR_Name_EN__c</fullName>
        <label>Letter : TOP HR Name EN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Letter_TOP_HR_Name_TH__c</fullName>
        <label>Letter : TOP HR Name TH</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Letter_TOP_HR_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Letter : TOP HR Name</label>
        <referenceTo>PISUsers__c</referenceTo>
        <relationshipLabel>ESS Setting</relationshipLabel>
        <relationshipName>ESS_Setting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Letter_TOP_Request__c</fullName>
        <label>Letter : TOP Request</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ESS Setting</label>
    <nameField>
        <displayFormat>ESS-{0000}</displayFormat>
        <label>ESS Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PISUsers__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>COMPANYNAME__c</fullName>
        <label>COMPANYNAME (HOME)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DEPARTMENT__c</fullName>
        <label>DEPARTMENT</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EMAIL__c</fullName>
        <label>EMAIL</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EMPLOYEEID__c</fullName>
        <externalId>true</externalId>
        <label>EMPLOYEEID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ENFIRSTNAME__c</fullName>
        <label>ENFIRSTNAME</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ENLASTNAME__c</fullName>
        <label>ENLASTNAME</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FUNCTION__c</fullName>
        <label>FUNCTION</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HOLDERPOSITION__c</fullName>
        <label>HOLDERPOSITION</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HOME_COMP__c</fullName>
        <label>HOME COMP</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LEVEL__c</fullName>
        <label>LEVEL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAINPOSITION__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MAINPOSITION</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ORGID__c</fullName>
        <label>ORGID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POSID__c</fullName>
        <label>POSID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReportToEmail__c</fullName>
        <label>ReportToEmail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ReportToID__c</fullName>
        <label>ReportToID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReportToPOS__c</fullName>
        <label>ReportToPOS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReportToUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ReportToUser</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PISUsers_ReportToUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SECTIONS__c</fullName>
        <label>SECTIONS</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SectHeadUpPosID__c</fullName>
        <label>SectHeadUpPosID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SectHeadUpUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SectHeadUpUser</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PISUsers_SectHeadUpUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subcordinate__c</fullName>
        <label>Subcordinate</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UNITS__c</fullName>
        <label>UNITS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PISUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PISUsers</label>
    <nameField>
        <label>UserID</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ESS_RecommendationLetter_Test.cls
/* Author Softever */
@isTest
public class ESS_RecommendationLetter_Test {

    @testSetup
    public static void setup() {
        
        //Create user here
        User AdminPersonalUser = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'Operation'].Id,
            LastName = 'RATRI',
            Email = 'testratri@thaioilgroup.com',
            Username = 'testratri@thaioilgroup.com' + System.currentTimeMillis(),
            CompanyName = 'Thaioil',
            Alias = 'RA',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
            );
        insert(AdminPersonalUser);
        
        //Employee
        User EmployeeUser = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'Operation'].Id,
            LastName = 'SANEA',
            Email = 'testsanea@thaioilgroup.com',
            Username = 'testsanea@thaioilgroup.com' + System.currentTimeMillis(),
            CompanyName = 'Thaioil',
            Alias = 'SA',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
            );
        insert(EmployeeUser);
        
        //SectionHead
        User SectionHeadUser = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'Operation'].Id,
            LastName = 'SURAPHAN',
            Email = 'testsuraphan@thaioilgroup.com',
            Username = 'testsuraphan@thaioilgroup.com' + System.currentTimeMillis(),
            CompanyName = 'Thaioil',
            Alias = 'SU',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
            );
        insert(SectionHeadUser);
        
        //DepartmentHead
		User DepartmentHeadUser = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'Operation'].Id,
            LastName = 'NUTTAPON',
            Email = 'testnuttapon@thaioilgroup.com',
            Username = 'testnuttapon@thaioilgroup.com' + System.currentTimeMillis(),
            CompanyName = 'Thaioil',
            Alias = 'NU',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
            );
        insert(DepartmentHeadUser);
        
        //Admin
		User LetterAdmin = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'Operation'].Id,
            LastName = 'RATRI',
            Email = 'testratri@thaioilgroup.com',
            Username = 'testratri@thaioilgroup.com' + System.currentTimeMillis(),
            CompanyName = 'Thaioil',
            Alias = 'RA',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Employee_Id__c = '999999'
            );
        insert(LetterAdmin);
        
        //Insert PISUser
        insertPISUsers();
        
        //Insert Public Group
        insertPublicGroup();
        
        //Insert ESS_Config
        ESS_Config__c Config = new ESS_Config__c();
        Config.Application_Running_No__c = '0';
        Config.Environment__c = 'PROD';
        insert(Config);
        
        //Insert Master Employee
        ESS_Master_Employee__c Master = new ESS_Master_Employee__c();
        Master.Data__c = 'IN';
        Master.ExternalId__c = '00000001';
        Master.Employee_ID__c = '00000001';
        Master.Employee_DOB__c = date.today();
        Master.Employee_Retirement_Date__c = date.today();
        Master.Employee_Date_Joined__c = date.today();
        //Name Section
        Master.Name_Emp_TH_Title_FN_LN__c = 'นาย เทส ซอฟ';
        Master.Name_Emp_EN_Title__c = '1';
        Master.Name_Emp_EN_FN__c = 'Test';
        Master.Name_Emp_EN_LN__c = 'Soft';
        //Status Section
        Master.Status_Marriage_Status__c = '1';
        Master.Status_Marriage_Doc_Issue_Date__c = date.today();
        //Child Section
        Master.Child_JSON__c = '';
        //Death Section
        Master.Death_Child_JSON__c = '';
        //Education Section
        Master.Education_JSON__c = '';
        //License Section
        Master.License_Citizen_Id__c = '1234567890123';
        Master.License_Citizen_Issue_Date__c = date.today();
        Master.License_Citizen_Expire_Date__c = date.today();
        //Address Section
        Master.Address_TH_House_No__c = '1';
        Master.Address_EN_House_No__c = '1';
        //Contact Person Section
        Master.Contact_Person_JSON__c = '';
        //Tax Section
        Master.Tax_Marriage_Status__c = '0';
        Master.Tax_Marriage_Person_Earn_Income__c = '1';
        insert(Master);
        
        Master = new ESS_Master_Employee__c();
        Master.Data__c = 'IN';
        Master.ExternalId__c = '99999999';
        Master.Employee_ID__c = '99999999';
        Master.Employee_DOB__c = date.today();
        Master.Employee_Retirement_Date__c = date.today();
        Master.Employee_Date_Joined__c = date.today();
        //Name Section
        Master.Name_Emp_TH_Title_FN_LN__c = 'นาย เทส ซอฟ';
        Master.Name_Emp_EN_Title__c = '1';
        Master.Name_Emp_EN_FN__c = 'Test';
        Master.Name_Emp_EN_LN__c = 'Soft';
        //Status Section
        Master.Status_Marriage_Status__c = '1';
        Master.Status_Marriage_Doc_Issue_Date__c = date.today();
        //Child Section
        Master.Child_JSON__c = '';
        //Death Section
        Master.Death_Child_JSON__c = '';
        //Education Section
        Master.Education_JSON__c = '';
        //License Section
        Master.License_Citizen_Id__c = '1234567890123';
        Master.License_Citizen_Issue_Date__c = date.today();
        Master.License_Citizen_Expire_Date__c = date.today();
        //Address Section
        Master.Address_TH_House_No__c = '1';
        Master.Address_EN_House_No__c = '1';
        //Contact Person Section
        Master.Contact_Person_JSON__c = '';
        //Tax Section
        Master.Tax_Marriage_Status__c = '0';
        Master.Tax_Marriage_Person_Earn_Income__c = '1';
        insert(Master);
    }
    
    @future
    public static void insertPISUsers() {
        
        List<User> Users = [select id, alias from User];
        
        Id PersonalAdminId; //Personal Admin
        Id EmployeeId; //Employee
        Id SectionHeadId; //Section Head
        Id DepartmentHeadId; //Department Head
        
        for(User U : Users) {
            if(U.alias == 'SA') {
                EmployeeId = U.Id;
            }
            else if(U.alias == 'SU') {
                SectionHeadId = U.Id;
            }
            else if(U.alias == 'NU') {
                DepartmentHeadId = U.Id;
            }
            else if(U.alias == 'RA') {
                PersonalAdminId = U.Id;
            }
        }
        
        PISUsers__c sanea = new PISUsers__c();
        sanea.Active__c = true;
        sanea.MAINPOSITION__c = true;
        sanea.EMPLOYEEID__c = '00000001';
        sanea.HOME_COMP__c = '1100';
        sanea.COMPANYNAME__c = 'TOP';
        sanea.Name = 'Test Sanea';
        sanea.LEVEL__c = 'Junior';
        sanea.ORGID__c = '00000001';
        sanea.POSID__c = '00000001';
        sanea.ENFIRSTNAME__c = 'Test';
        sanea.ENLASTNAME__c = 'Test Sanea';
        sanea.HOLDERPOSITION__c = '00000001';
        sanea.EMAIL__c = 'testsanea@thaioilgroup.com';
        sanea.User__c = EmployeeId;
        sanea.FUNCTION__c = 'AAAA';
        sanea.DEPARTMENT__c = 'BBBB';
        sanea.SECTIONS__c = 'CCCC';
        sanea.UNITS__c = 'DDDD';
        sanea.ReportToPOS__c = '00000002';
        sanea.ReportToID__c = '00000002';
        sanea.ReportToEmail__c = 'testsuraphan@thaioilgroup.com';
        sanea.ReportToUser__c = SectionHeadId;
        sanea.SectHeadUpUser__c = SectionHeadId;
        sanea.SectHeadUpPosID__c = '00000002';
        sanea.Subcordinate__c = '[""]';
        insert(sanea);
        
        PISUsers__c suraphan = new PISUsers__c();
        suraphan.Active__c = true;
        suraphan.MAINPOSITION__c = true;
        suraphan.EMPLOYEEID__c = '00000002';
        suraphan.HOME_COMP__c = '1600';
        suraphan.COMPANYNAME__c = 'TES';
        suraphan.Name = 'Test Suraphan';
        suraphan.LEVEL__c = 'Section Head';
        suraphan.ORGID__c = '00000002';
        suraphan.POSID__c = '00000002';
        suraphan.ENFIRSTNAME__c = 'Test';
        suraphan.ENLASTNAME__c = 'Test Suraphan';
        suraphan.HOLDERPOSITION__c = '00000002';
        suraphan.EMAIL__c = 'testsuraphan@thaioilgroup.com';
        suraphan.User__c = SectionHeadId;
        suraphan.ReportToPOS__c = '00000003';
        suraphan.ReportToID__c = '00000003';
        suraphan.ReportToEmail__c = 'testdamrong@thaioilgroup.com';
        suraphan.ReportToUser__c = DepartmentHeadId;
        suraphan.SectHeadUpUser__c = DepartmentHeadId;
        suraphan.SectHeadUpPosID__c = '00000003';
        suraphan.Subcordinate__c = '[""]';
        insert(suraphan);
        
        PISUsers__c nuttapon = new PISUsers__c();
        nuttapon.Active__c = true;
        nuttapon.MAINPOSITION__c = true;
        nuttapon.EMPLOYEEID__c = '00000003';
        nuttapon.HOME_COMP__c = '1100';
        nuttapon.Name = 'Test Nuttapon';
        nuttapon.LEVEL__c = 'Department Head';
        nuttapon.ORGID__c = '00000003';
        nuttapon.POSID__c = '00000003';
        nuttapon.ENFIRSTNAME__c = 'Test';
        nuttapon.ENLASTNAME__c = 'Test Nuttapon';
        nuttapon.HOLDERPOSITION__c = '00000003';
        nuttapon.EMAIL__c = 'testnuttapon@thaioilgroup.com';
        nuttapon.User__c = DepartmentHeadId;
        nuttapon.ReportToPOS__c = '00000003';
        nuttapon.ReportToID__c = '00000003';
        nuttapon.ReportToEmail__c = 'testnuttapon@thaioilgroup.com';
        nuttapon.ReportToUser__c = DepartmentHeadId;
        nuttapon.SectHeadUpUser__c = DepartmentHeadId;
        nuttapon.SectHeadUpPosID__c = '00000003';
        nuttapon.Subcordinate__c = '[""]';
        insert(nuttapon);
        
        PISUsers__c adminPersonal = new PISUsers__c();
        adminPersonal.Active__c = true;
        adminPersonal.MAINPOSITION__c = true;
        adminPersonal.EMPLOYEEID__c = '99999999';
        adminPersonal.HOME_COMP__c = '1100';
        adminPersonal.Name = 'Test AdminPersonal';
        adminPersonal.LEVEL__c = 'VP';
        adminPersonal.ORGID__c = '00000000';
        adminPersonal.POSID__c = '00000000';
        adminPersonal.ENFIRSTNAME__c = 'Test';
        adminPersonal.ENLASTNAME__c = 'Test AdminPersonal';
        adminPersonal.HOLDERPOSITION__c = '00000000';
        adminPersonal.EMAIL__c = 'adminPersonal@thaioilgroup.com';
        adminPersonal.User__c = PersonalAdminId;
        insert(adminPersonal);
    }
    
    @future
    public static void insertPublicGroup() {
        
        List<User> Users = [select id, alias from User];
        
        Id AdminPersonelId;
        
        for(User U : Users) {
            if(U.alias == 'RA') {
                AdminPersonelId = U.Id;
            }
        }
        
        //Create PersonelAdmin Group
        Group adminPersonelGroup = [select id from Group where developername = 'ESS_Recommendation_Letter_Admin'];
        GroupMember personelAdmin = new GroupMember();
        personelAdmin.UserOrGroupId = AdminPersonelId;
        personelAdmin.GroupId = adminPersonelGroup.Id;
        insert(personelAdmin);
        
    }
    
    @isTest
    public static void RecommendationLetterTOPTest() {
        
        Test.startTest();
        
        List<User> Users = [select id, alias, username from User];
        Id EmployeeId;
        User runAsUser;
        for(User U : Users) {
            if(U.alias == 'SA') {
                EmployeeId = U.Id;
                runAsUser = U;
            }
        }
        
        PISUsers__c Sanea = [select id, user__c from PISUsers__c where user__c =: runAsUser.Id];
        
        System.runAs(runAsUser) {
            ESS_Setting__c Setting = new ESS_Setting__c();
            Setting.Letter_TOP_HR_Name__c = Sanea.Id;
            Setting.Letter_TES_HR_Name__c = Sanea.Id;
            Setting.Letter_TOP_Request__c = 10;
            Setting.Letter_TES_Request__c = 10;
            Setting.Letter_TOP_HR_Name_TH__c = 'TOP HR';
            Setting.Letter_TES_HR_Name_TH__c = 'TES HR';
            Setting.Letter_TOP_HR_Name_EN__c = 'TOP HR';
            Setting.Letter_TES_HR_Name_EN__c = 'TES HR';
            Setting.Letter_TOP_HR_Position_TH__c = 'Test';
            Setting.Letter_TOP_HR_Position__c = 'Test';
            Setting.Letter_TES_HR_Position_TH__c = 'Test';
            Setting.Letter_TES_HR_Position__c = 'Test';
            insert(Setting);
            
            ESS_Letter_of_Recommendation__c Letter = new ESS_Letter_of_Recommendation__c();
            Letter.Letter_Type__c = ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name();
            Letter.OwnerId = runAsUser.Id;
            Letter.Language__c = ESS_Enum.RecommendationLetterLanguage.Thai.name();
            Letter.letter_purpose__c = 'Test';
            Letter.To_Organization__c = 'Kasikornbank';
            Letter.Leave_Start__c = date.today();
            Letter.Leave_End__c = date.today();
            Letter.Company_Name__c = 'TOP';
            insert(Letter);
            
            ESS_RecommendationLetter.RecommendationLetterSearchCriteria Filter = new ESS_RecommendationLetter.RecommendationLetterSearchCriteria();
            Filter.letterType = 'All';
            Filter.letterStatus = 'All';
            Filter.startCreatedDate = date.today();
            Filter.endCreatedDate = date.today().addMonths(1);
            Filter.startGeneratedToPDF = date.today();
            Filter.endGeneratedToPDF = date.today().addMonths(1);
            
            ESS_Global.SortByParam SortByParam = new ESS_Global.SortByParam();
            SortByParam.sortBy = '';
            SortByParam.ascending = true;
            
            ESS_RecommendationLetter.GetRecommendationLetterListsCount(Filter);
            ESS_RecommendationLetter.GetRecommendationLetterCount(Filter);
            ESS_RecommendationLetter.GetRecommendationLetterLists(Filter, SortByParam, null);
            ESS_RecommendationLetter_DTO.RecommendationLetterDetailDTO LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(null, ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            LetterDetail.language = new ESS_Global.EnumValue('RecommendationLetterLanguage');
            LetterDetail.language.key = ESS_Enum.RecommendationLetterLanguage.Thai.name();
            LetterDetail.language.value = ESS_Enum.RecommendationLetterLanguage.Thai.name();
            LetterDetail.companyName = 'TOP';
            ESS_RecommendationLetter.SaveRecommendationLetter(LetterDetail);
            
            LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(null, ESS_Enum.RecommendationLetterType.SalaryLetterWithLeaveForVisa.name());
            Letter.Letter_Type__c = ESS_Enum.RecommendationLetterType.SalaryLetterWithLeaveForVisa.name();
            Letter.Language__c = ESS_Enum.RecommendationLetterLanguage.English.name();
            Letter.Current_Status__c = ESS_Enum.RecommendationLetterStatus.GeneratedToPDF.name();
            ESS_RecommendationLetter.assignToRecommendationLetterDetailDTO(Letter);
            LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(null, ESS_Enum.RecommendationLetterType.SalaryLetterWithoutLeaveForVisa.name());
            Letter.Letter_Type__c = ESS_Enum.RecommendationLetterType.SalaryLetterWithoutLeaveForVisa.name();
            ESS_RecommendationLetter.assignToRecommendationLetterDetailDTO(Letter);
            LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(null, ESS_Enum.RecommendationLetterType.WorkLetterWithoutSalary.name());
            Letter.Letter_Type__c = ESS_Enum.RecommendationLetterType.WorkLetterWithoutSalary.name();
            ESS_RecommendationLetter.assignToRecommendationLetterDetailDTO(Letter);
            
            LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(Letter.Id, ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            ESS_RecommendationLetter.SaveRecommendationLetter(LetterDetail);
            ESS_RecommendationLetter.GenerateRecommendationLetter(Letter.Id, ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            ESS_RecommendationLetter.DeleteRecommendationLetter(Letter.Id);
            
            ESS_RecommendationLetter.GetLetterTypes();
            ESS_RecommendationLetter.GetOrganizations(ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            ESS_RecommendationLetter.GetENOrganizations(ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
        	ESS_RecommendationLetter.getDependentPicklistValues();
            ESS_RecommendationLetter.getDependentPicklistENValues();
            
            Letter.Letter_Type__c = String.ValueOf(ESS_Enum.RecommendationLetterType.SalaryLetterWithLeaveForVisa);
            ESS_RecommendationLetter.assignToRecommendationLetterListDTO(Letter);
        }
        
        Test.stopTest();
    }
    
    @isTest
    public static void RecommendationLetterTESTest() {
        
        Test.startTest();
        
        List<User> Users = [select id, alias, username from User];
        Id EmployeeId;
        User runAsUser;
        for(User U : Users) {
            if(U.alias == 'SU') {
                EmployeeId = U.Id;
                runAsUser = U;
            }
        }
        
        PISUsers__c Sanea = [select id, user__c from PISUsers__c where user__c =: runAsUser.Id];
        
        System.runAs(runAsUser) {
            ESS_Setting__c Setting = new ESS_Setting__c();
            Setting.Letter_TOP_HR_Name__c = Sanea.Id;
            Setting.Letter_TES_HR_Name__c = Sanea.Id;
            Setting.Letter_TOP_Request__c = 10;
            Setting.Letter_TES_Request__c = 10;
            Setting.Letter_TOP_HR_Name_TH__c = 'TOP HR';
            Setting.Letter_TES_HR_Name_TH__c = 'TES HR';
            Setting.Letter_TOP_HR_Name_EN__c = 'TOP HR';
            Setting.Letter_TES_HR_Name_EN__c = 'TES HR';
            Setting.Letter_TOP_HR_Position_TH__c = 'Test';
            Setting.Letter_TOP_HR_Position__c = 'Test';
            Setting.Letter_TES_HR_Position_TH__c = 'Test';
            Setting.Letter_TES_HR_Position__c = 'Test';
            insert(Setting);
            
            ESS_Master_Employee__c Master = new ESS_Master_Employee__c();
            Master.Employee_ID__c = '00000002';
            Master.Name_Emp_TH_Title_FN_LN__c = 'Test';
            Master.Name_Emp_EN_Title__c = 'Test';
            Master.Name_Emp_EN_FN__c = 'Test';
            Master.Name_Emp_EN_LN__c = 'Test';
            Master.Position__c = 'Test';
            Master.Unit__c = 'Test';
            Master.employee_date_joined__c = date.today();
            Master.Data__c = 'IN';
            insert(Master);
            
            ESS_Letter_of_Recommendation__c Letter = new ESS_Letter_of_Recommendation__c();
            Letter.Letter_Type__c = ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name();
            Letter.OwnerId = runAsUser.Id;
            Letter.Language__c = ESS_Enum.RecommendationLetterLanguage.Thai.name();
            Letter.letter_purpose__c = 'Test';
            Letter.To_Organization__c = 'Kasikornbank';
            Letter.Company_Name__c = 'TES';
            insert(Letter);
            
            ESS_RecommendationLetter.RecommendationLetterSearchCriteria Filter = new ESS_RecommendationLetter.RecommendationLetterSearchCriteria();
            Filter.letterType = 'All';
            Filter.letterStatus = 'All';
            Filter.startCreatedDate = date.today();
            Filter.endCreatedDate = date.today().addMonths(1);
            Filter.startGeneratedToPDF = date.today();
            Filter.endGeneratedToPDF = date.today().addMonths(1);
            
            ESS_Global.SortByParam SortByParam = new ESS_Global.SortByParam();
            SortByParam.sortBy = '';
            SortByParam.ascending = true;
            
            ESS_RecommendationLetter.GetRecommendationLetterListsCount(Filter);
            ESS_RecommendationLetter.GetRecommendationLetterCount(Filter);
            ESS_RecommendationLetter.GetRecommendationLetterLists(Filter, SortByParam, null);
            ESS_RecommendationLetter_DTO.RecommendationLetterDetailDTO LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(null, ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            LetterDetail.language = new ESS_Global.EnumValue('RecommendationLetterLanguage');
            LetterDetail.language.key = ESS_Enum.RecommendationLetterLanguage.English.name();
            LetterDetail.language.value = ESS_Enum.RecommendationLetterLanguage.English.name();
            LetterDetail.companyName = 'TES';
            ESS_RecommendationLetter.SaveRecommendationLetter(LetterDetail);
            
            Letter.Letter_Type__c = ESS_Enum.RecommendationLetterType.GrantedLetter.name();
            ESS_RecommendationLetter.assignToRecommendationLetterDetailDTO(Letter);
            
            LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(Letter.Id, ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            ESS_RecommendationLetter.SaveRecommendationLetter(LetterDetail);
            ESS_RecommendationLetter.GenerateRecommendationLetter(Letter.Id, ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            ESS_RecommendationLetter.DeleteRecommendationLetter(Letter.Id);
            
            ESS_RecommendationLetter.GetLetterTypes();
            ESS_RecommendationLetter.GetOrganizations(ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            ESS_RecommendationLetter.GetENOrganizations(ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
        	ESS_RecommendationLetter.getDependentPicklistValues();
            ESS_RecommendationLetter.getDependentPicklistENValues();
        }
        
        Test.stopTest();
    }
    
    @isTest
    public static void RecommendationLetterAdminTOPTest() {
        
        Test.startTest();
        
        List<User> Users = [select id, alias, username from User];
        Id EmployeeId;
        User runAsUser;
        for(User U : Users) {
            if(U.alias == 'RA') {
                EmployeeId = U.Id;
                runAsUser = U;
            }
        }
        
        PISUsers__c Sanea = [select id, user__c from PISUsers__c where user__c =: runAsUser.Id];
        
        System.runAs(runAsUser) {
            ESS_Setting__c Setting = new ESS_Setting__c();
            Setting.Letter_TOP_HR_Name__c = Sanea.Id;
            Setting.Letter_TES_HR_Name__c = Sanea.Id;
            Setting.Letter_TOP_Request__c = 10;
            Setting.Letter_TES_Request__c = 10;
            Setting.Letter_TOP_HR_Name_TH__c = 'TOP HR';
            Setting.Letter_TES_HR_Name_TH__c = 'TES HR';
            Setting.Letter_TOP_HR_Name_EN__c = 'TOP HR';
            Setting.Letter_TES_HR_Name_EN__c = 'TES HR';
            Setting.Letter_TOP_HR_Position_TH__c = 'Test';
            Setting.Letter_TOP_HR_Position__c = 'Test';
            Setting.Letter_TES_HR_Position_TH__c = 'Test';
            Setting.Letter_TES_HR_Position__c = 'Test';
            insert(Setting);
            
            ESS_Letter_of_Recommendation__c Letter = new ESS_Letter_of_Recommendation__c();
            Letter.Letter_Type__c = ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name();
            Letter.OwnerId = runAsUser.Id;
            Letter.Language__c = ESS_Enum.RecommendationLetterLanguage.Thai.name();
            Letter.letter_purpose__c = 'Test';
            Letter.To_Organization__c = 'Kasikornbank';
            Letter.Leave_Start__c = date.today();
            Letter.Leave_End__c = date.today();
            Letter.Company_Name__c = 'TOP';
            insert(Letter);
            
            ESS_RecommendationLetter.RecommendationLetterSearchCriteria Filter = new ESS_RecommendationLetter.RecommendationLetterSearchCriteria();
            Filter.letterType = 'All';
            Filter.letterStatus = 'All';
            Filter.startCreatedDate = date.today();
            Filter.endCreatedDate = date.today().addMonths(1);
            Filter.startGeneratedToPDF = date.today();
            Filter.endGeneratedToPDF = date.today().addMonths(1);
            
            ESS_Global.SortByParam SortByParam = new ESS_Global.SortByParam();
            SortByParam.sortBy = '';
            SortByParam.ascending = true;
            
            ESS_RecommendationLetter.GetRecommendationLetterListsCount(Filter);
            ESS_RecommendationLetter.GetRecommendationLetterCount(Filter);
            ESS_RecommendationLetter.GetRecommendationLetterLists(Filter, SortByParam, null);
            ESS_RecommendationLetter_DTO.RecommendationLetterDetailDTO LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(null, ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            LetterDetail.language = new ESS_Global.EnumValue('RecommendationLetterLanguage');
            LetterDetail.language.key = ESS_Enum.RecommendationLetterLanguage.Thai.name();
            LetterDetail.language.value = ESS_Enum.RecommendationLetterLanguage.Thai.name();
            LetterDetail.companyName = 'TOP';
            ESS_RecommendationLetter.SaveRecommendationLetter(LetterDetail);
            
            LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(null, ESS_Enum.RecommendationLetterType.SalaryLetterWithLeaveForVisa.name());
            Letter.Letter_Type__c = ESS_Enum.RecommendationLetterType.SalaryLetterWithLeaveForVisa.name();
            Letter.Language__c = ESS_Enum.RecommendationLetterLanguage.English.name();
            Letter.Current_Status__c = ESS_Enum.RecommendationLetterStatus.GeneratedToPDF.name();
            ESS_RecommendationLetter.assignToRecommendationLetterDetailDTO(Letter);
            LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(null, ESS_Enum.RecommendationLetterType.SalaryLetterWithoutLeaveForVisa.name());
            Letter.Letter_Type__c = ESS_Enum.RecommendationLetterType.SalaryLetterWithoutLeaveForVisa.name();
            ESS_RecommendationLetter.assignToRecommendationLetterDetailDTO(Letter);
            LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(null, ESS_Enum.RecommendationLetterType.WorkLetterWithoutSalary.name());
            Letter.Letter_Type__c = ESS_Enum.RecommendationLetterType.WorkLetterWithoutSalary.name();
            ESS_RecommendationLetter.assignToRecommendationLetterDetailDTO(Letter);
            
            LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(Letter.Id, ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            ESS_RecommendationLetter.SaveRecommendationLetter(LetterDetail);
            ESS_RecommendationLetter.GenerateRecommendationLetter(Letter.Id, ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            ESS_RecommendationLetter.DeleteRecommendationLetter(Letter.Id);
            
            ESS_RecommendationLetter.GetLetterTypes();
            ESS_RecommendationLetter.GetOrganizations(ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            ESS_RecommendationLetter.GetENOrganizations(ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
        	ESS_RecommendationLetter.getDependentPicklistValues();
            ESS_RecommendationLetter.getDependentPicklistENValues();
            
            Letter.Letter_Type__c = String.ValueOf(ESS_Enum.RecommendationLetterType.SalaryLetterWithLeaveForVisa);
            ESS_RecommendationLetter.assignToRecommendationLetterListDTO(Letter);
        }
        
        Test.stopTest();
    }
    @isTest
    public static void RecommendationLetterAdminTESTest() {
        
        Test.startTest();
        
        List<User> Users = [select id, alias, username from User];
        Id EmployeeId;
        User runAsUser;
        for(User U : Users) {
            if(U.alias == 'RA') {
                EmployeeId = U.Id;
                runAsUser = U;
            }
        }
        
        PISUsers__c Sanea = [select id, user__c from PISUsers__c where user__c =: runAsUser.Id];
        
        System.runAs(runAsUser) {
            ESS_Setting__c Setting = new ESS_Setting__c();
            Setting.Letter_TOP_HR_Name__c = Sanea.Id;
            Setting.Letter_TES_HR_Name__c = Sanea.Id;
            Setting.Letter_TOP_Request__c = 10;
            Setting.Letter_TES_Request__c = 10;
            Setting.Letter_TOP_HR_Name_TH__c = 'TOP HR';
            Setting.Letter_TES_HR_Name_TH__c = 'TES HR';
            Setting.Letter_TOP_HR_Name_EN__c = 'TOP HR';
            Setting.Letter_TES_HR_Name_EN__c = 'TES HR';
            Setting.Letter_TOP_HR_Position_TH__c = 'Test';
            Setting.Letter_TOP_HR_Position__c = 'Test';
            Setting.Letter_TES_HR_Position_TH__c = 'Test';
            Setting.Letter_TES_HR_Position__c = 'Test';
            insert(Setting);
            
            ESS_Letter_of_Recommendation__c Letter = new ESS_Letter_of_Recommendation__c();
            Letter.Letter_Type__c = ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name();
            Letter.OwnerId = runAsUser.Id;
            Letter.Language__c = ESS_Enum.RecommendationLetterLanguage.Thai.name();
            Letter.letter_purpose__c = 'Test';
            Letter.To_Organization__c = 'Kasikornbank';
            Letter.Leave_Start__c = date.today();
            Letter.Leave_End__c = date.today();
            Letter.Company_Name__c = 'TOP';
            insert(Letter);
            
            ESS_RecommendationLetter.RecommendationLetterSearchCriteria Filter = new ESS_RecommendationLetter.RecommendationLetterSearchCriteria();
            Filter.letterType = 'All';
            Filter.letterStatus = 'All';
            Filter.startCreatedDate = date.today();
            Filter.endCreatedDate = date.today().addMonths(1);
            Filter.startGeneratedToPDF = date.today();
            Filter.endGeneratedToPDF = date.today().addMonths(1);
            
            ESS_Global.SortByParam SortByParam = new ESS_Global.SortByParam();
            SortByParam.sortBy = '';
            SortByParam.ascending = true;
            
            ESS_RecommendationLetter.GetRecommendationLetterListsCount(Filter);
            ESS_RecommendationLetter.GetRecommendationLetterCount(Filter);
            ESS_RecommendationLetter.GetRecommendationLetterLists(Filter, SortByParam, null);
            ESS_RecommendationLetter_DTO.RecommendationLetterDetailDTO LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(null, ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            LetterDetail.language = new ESS_Global.EnumValue('RecommendationLetterLanguage');
            LetterDetail.language.key = ESS_Enum.RecommendationLetterLanguage.Thai.name();
            LetterDetail.language.value = ESS_Enum.RecommendationLetterLanguage.Thai.name();
            LetterDetail.companyName = 'TOP';
            ESS_RecommendationLetter.SaveRecommendationLetter(LetterDetail);
            
            LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(null, ESS_Enum.RecommendationLetterType.SalaryLetterWithLeaveForVisa.name());
            Letter.Letter_Type__c = ESS_Enum.RecommendationLetterType.SalaryLetterWithLeaveForVisa.name();
            Letter.Language__c = ESS_Enum.RecommendationLetterLanguage.English.name();
            Letter.Current_Status__c = ESS_Enum.RecommendationLetterStatus.GeneratedToPDF.name();
            ESS_RecommendationLetter.assignToRecommendationLetterDetailDTO(Letter);
            LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(null, ESS_Enum.RecommendationLetterType.SalaryLetterWithoutLeaveForVisa.name());
            Letter.Letter_Type__c = ESS_Enum.RecommendationLetterType.SalaryLetterWithoutLeaveForVisa.name();
            ESS_RecommendationLetter.assignToRecommendationLetterDetailDTO(Letter);
            LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(null, ESS_Enum.RecommendationLetterType.WorkLetterWithoutSalary.name());
            Letter.Letter_Type__c = ESS_Enum.RecommendationLetterType.WorkLetterWithoutSalary.name();
            ESS_RecommendationLetter.assignToRecommendationLetterDetailDTO(Letter);
            
            Letter.Company_Name__c = 'TES';
            update(Letter);
            LetterDetail = ESS_RecommendationLetter.GetRecommendationLetterDetail(Letter.Id, ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            ESS_RecommendationLetter.SaveRecommendationLetter(LetterDetail);
            ESS_RecommendationLetter.GenerateRecommendationLetter(Letter.Id, ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            ESS_RecommendationLetter.DeleteRecommendationLetter(Letter.Id);
            
            ESS_RecommendationLetter.GetLetterTypes();
            ESS_RecommendationLetter.GetOrganizations(ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
            ESS_RecommendationLetter.GetENOrganizations(ESS_Enum.RecommendationLetterType.SalaryLetterForFinancial.name());
        	ESS_RecommendationLetter.getDependentPicklistValues();
            ESS_RecommendationLetter.getDependentPicklistENValues();
            
            Letter.Letter_Type__c = String.ValueOf(ESS_Enum.RecommendationLetterType.SalaryLetterWithLeaveForVisa);
            ESS_RecommendationLetter.assignToRecommendationLetterListDTO(Letter);
        }
        
        Test.stopTest();
    }
    
}