force-app/main/default/objects/ESS_Application__c.object
<CustomObject>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Updated to SAP / Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <label>Employee ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>SendingToSAP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <label>Updated in SAP / Completed</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                    <label>Error updated in SAP</label>
                </value>
                <value>
                    <fullName>WaitingForSubmit</fullName>
                    <isActive>false</isActive>
                    <label>WaitingForSubmit</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ESS Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>ESS Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ESS_Master_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Available_Room__c</fullName>
        <defaultValue>5</defaultValue>
        <label>Available Room</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Updated to SAP / Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ESS_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ESS Application</label>
        <referenceTo>ESS_Application__c</referenceTo>
        <relationshipLabel>ESS Master Employee</relationshipLabel>
        <relationshipName>ESS_Master_Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <label>Employee ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>SendingToSAP</fullName>
                    <label>Sending To SAP</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <label>Updated in SAP / Completed</label>
                </value>
                <value>
                    <fullName>Error</fullName>
                    <label>Error updated in SAP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ESS Master Employee</label>
    <nameField>
        <displayFormat>ME-{00000}</displayFormat>
        <label>ESS Master Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ESS_Retirement__c.object
<CustomObject>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <label>Employee ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>WaitingEmployeeSubmit</fullName>
                </value>
                <value>
                    <fullName>WaitingForApprovalSectionHead</fullName>
                </value>
                <value>
                    <fullName>WaitingForApprovalDepartmentHead</fullName>
                </value>
                <value>
                    <fullName>UploadingToPersonalFolder</fullName>
                </value>
                <value>
                    <fullName>SendingToSAP</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>DefaultFromSystem</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                    <label>Error updated in SAP</label>
                </value>
                <value>
                    <fullName>UploadFailed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ESS Retirement</label>
    <nameField>
        <displayFormat>RET-{00000}</displayFormat>
        <label>ESS Retirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ESSRESTINHtlTest.cls
@isTest
public class ESSRESTINHtlTest {
    @Testsetup
    public static void setupData()
    {
        List<ESS_Master_Employee__c> empList = new List<ESS_Master_Employee__c>();
        List<ESS_Application__c> appList = new List<ESS_Application__c>();
        List<ESS_Retirement__c> retirementList = new List<ESS_Retirement__c>();

        ESS_Application__c  essApp = new ESS_Application__c ( 
            Status__c = 'SendingToSAP',
            Completed_Date__c = null
        );
        appList.add(essApp);
        
        insert appList;
        
        /** re-check ExternalId__c again, 
         * if reponse from SAP has return externalId__c fields(Employee_ID__c + Application_Id__c)
         */
        ESS_Master_Employee__c essEmp = new ESS_Master_Employee__c( 
            Employee_ID__c = '00000001',
            Available_Room__c = null,
            ExternalId__c = null
        ); 
        empList.add(essEmp);
        
        ESS_Master_Employee__c essEmp2 = new ESS_Master_Employee__c( 
            Employee_ID__c = '00000002',
            Available_Room__c = null,
            ExternalId__c = null
        ); 
        empList.add(essEmp2);

        ESS_Master_Employee__c essEmp3 = new ESS_Master_Employee__c( 
            Employee_ID__c = '00000003',
            Available_Room__c = null,
            ExternalId__c = null
        ); 
        empList.add(essEmp3);

        ESS_Master_Employee__c essEmp4 = new ESS_Master_Employee__c( 
            Employee_ID__c = '12345678',
            Available_Room__c = null,
            ExternalId__c = null
        ); 
        empList.add(essEmp4);

        insert empList;
    }

    @isTest
    public static void testUpdateHotelPostSuccess(){
        String jsonSTR = '{'+
                            '"UpdateHotelWrapperList": ['
                                +'{'
                                    +'"employeeId": "00000001",'
                                    +'"checkOutDate": "2023-02-09",'
                                    +'"availableRoom": "58"'
                                +'},'
                                +'{'
                                    +'"employeeId": "00000002",'
                                    +'"checkOutDate": "2023-02-09",'
                                    +'"availableRoom": "66"'
                                +'},'
                                +'{'
                                    +'"employeeId": "12345678",'
                                    +'"checkOutDate": "2023-02-19",'
                                    +'"availableRoom": "4"'
                                +'},'
                                +'{'
                                    +'"employeeId": "00000003",'
                                    +'"checkOutDate": "2023-02-18",'
                                    +'"availableRoom": 33'
                                +'},'
                                +'{'
                                    +'"employeeId": "12345678",'
                                    +'"checkOutDate": "2023-02-11",'
                                    +'"availableRoom": "5"'
                                +'},'
                                +'{'
                                    +'"employeeId": "12345678",'
                                    +'"checkOutDate": "2023-02-20",'
                                    +'"availableRoom": "0"'
                                +'}'
                            +']'
                        +'}';

        Map<String, Object> responseValue = (Map<String, Object>)JSON.deserializeUntyped(jsonSTR);        
        String essJson= JSON.serialize(responseValue.get('UpdateHotelWrapperList')) ;
        List<ESSRESTINHtlCtrl.UpdateHotelWrapper>  updWrapperList = (List<ESSRESTINHtlCtrl.UpdateHotelWrapper>)JSON.deserialize(essJson, List<ESSRESTINHtlCtrl.UpdateHotelWrapper>.class);
        
        Test.startTest(); 
        ESSRESTINHtlCtrl.updateHotelPost(updWrapperList);
        Test.stopTest();
    }

    @isTest
    public static void testUpdateHotelPostFail(){

        String jsonSTR = '{'+
                        '"UpdateHotelWrapperList": ['
                        +'{'
                            +'"employeeId": "00000001",'
                            +'"checkOutDate": "2023-02-09",'
                            +'"availableRoom": "58"'
                        +'},'
                        +'{'
                            +'"employeeId": "00000002",'
                            +'"checkOutDate": "2023-02-09",'
                            +'"availableRoom": "66"'
                        +'},'
                        +'{'
                            +'"employeeId": "12345678",'
                            +'"checkOutDate": "2023-02-12",'
                            +'"availableRoom": "55555555555555"'
                        +'},'
                        +'{'
                            +'"employeeId": "12345678",'
                            +'"checkOutDate": "2023-02-21",'
                            +'"availableRoom": "55555555555555"'
                        +'},'
                        +'{'
                            +'"employeeId": "00000003",'
                            +'"checkOutDate": "2023-02-18",'
                            +'"availableRoom": 33'
                        +'},'
                        +'{'
                            +'"employeeId": "12345678",'
                            +'"checkOutDate": "2023-02-11",'
                            +'"availableRoom": "5"'
                        +'},'
                        +'{'
                            +'"employeeId": "12345678",'
                            +'"checkOutDate": "2023-02-20",'
                            +'"availableRoom": "0"'
                            +'}'
                        +']'
                    +'}';

        Map<String, Object> responseValue = (Map<String, Object>)JSON.deserializeUntyped(jsonSTR);        
        String essJson= JSON.serialize(responseValue.get('UpdateHotelWrapperList')) ;
        List<ESSRESTINHtlCtrl.UpdateHotelWrapper>  updWrapperList = (List<ESSRESTINHtlCtrl.UpdateHotelWrapper>)JSON.deserialize(essJson, List<ESSRESTINHtlCtrl.UpdateHotelWrapper>.class);
        
        Test.startTest(); 
        ESSRESTINHtlCtrl.updateHotelPost(updWrapperList);
        Test.stopTest();
    }

    @isTest
    public static void testUpdateHotelPostERR(){

        String jsonSTR = '{'+
                        '"UpdateHotelWrapperList": ['
                        +'{'
                            +'"employeeId": "00000001",'
                            +'"checkOutDate": "2023-02-09",'
                            +'"availableRoom": "58gjdyjtdjtdjtjfyjuyky"'
                        +'},'
                        +'{'
                            +'"employeeId": "00000002",'
                            +'"checkOutDate": "2023-02-09",'
                            +'"availableRoom": "66"'
                        +'},'
                        +'{'
                            +'"employeeId": "12345678",'
                            +'"checkOutDate": "2023-02-12",'
                            +'"availableRoom": "55555555555555"'
                        +'},'
                        +'{'
                            +'"employeeId": "12345678",'
                            +'"checkOutDate": "2023-02-21",'
                            +'"availableRoom": "hillhioloiygugiuygiyg"'
                        +'},'
                        +'{'
                            +'"employeeId": "00000003",'
                            +'"checkOutDate": "2023-02-18",'
                            +'"availableRoom": 33'
                        +'},'
                        +'{'
                            +'"employeeId": "12345678",'
                            +'"checkOutDate": "2023-02-11",'
                            +'"availableRoom": "5"'
                        +'},'
                        +'{'
                            +'"employeeId": "12345678",'
                            +'"checkOutDate": "2023-02-20",'
                            +'"availableRoom": "0"'
                            +'}'
                        +']'
                    +'}';

        Map<String, Object> responseValue = (Map<String, Object>)JSON.deserializeUntyped(jsonSTR);        
        String essJson= JSON.serialize(responseValue.get('UpdateHotelWrapperList')) ;
        List<ESSRESTINHtlCtrl.UpdateHotelWrapper>  updWrapperList = (List<ESSRESTINHtlCtrl.UpdateHotelWrapper>)JSON.deserialize(essJson, List<ESSRESTINHtlCtrl.UpdateHotelWrapper>.class);
        
        Test.startTest(); 
        ESSRESTINHtlCtrl.updateHotelPost(updWrapperList);
        Test.stopTest();
    }
}