force-app/main/default/objects/Functional_Location__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MainWorkCenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MainWorkCenter</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Main Work Center</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Functional Location (MainWorkCenter)</relationshipLabel>
        <relationshipName>Functional_Location5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planning_Plant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Plant</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Functional Location (Planning Plant)</relationshipLabel>
        <relationshipName>Functional_Location2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PlantSection__c</fullName>
        <label>PlantSection</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>mainWorkCenterPlant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>mainWorkCenterPlant</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Functional Location (mainWorkCenterPlant)</relationshipLabel>
        <relationshipName>Functional_Location3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Functional Location</label>
    <nameField>
        <label>Functional Location</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Map__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Master Map Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ORTLAction__c.object
<CustomObject>
    <fields>
        <fullName>APU__c</fullName>
        <description>APU of selected Tag no.</description>
        <inlineHelpText>Default from Risk record</inlineHelpText>
        <label>APU</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <defaultValue>Today()+30</defaultValue>
        <description>Date to finish task</description>
        <inlineHelpText>Default 30 days after create action record and editable</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PlantSection__c</fullName>
        <label>Plant Section</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RiskScenario__c</fullName>
        <description>Default from Risk record</description>
        <label>Threat Scenario</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Threat</label>
        <referenceTo>ORTLRisk__c</referenceTo>
        <relationshipLabel>Action</relationshipLabel>
        <relationshipName>Action</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TagNo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Functional Location</description>
        <inlineHelpText>Default from Risk record</inlineHelpText>
        <label>Tag No.</label>
        <referenceTo>Functional_Location__c</referenceTo>
        <relationshipLabel>Action</relationshipLabel>
        <relationshipName>Action</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaskDescription__c</fullName>
        <description>Task Description detail</description>
        <label>Task Description</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TaskStatus__c</fullName>
        <description>Display the current status</description>
        <label>Task Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ORTLTaskStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaskType__c</fullName>
        <description>Display task type</description>
        <label>Task Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assessment</fullName>
                </value>
                <value>
                    <fullName>Awaiting Opportunity</fullName>
                </value>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>Moc</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Action</label>
    <nameField>
        <label>Action No.</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ORTLAttendee__c.object
<CustomObject>
    <fields>
        <fullName>Risk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Risk</label>
        <referenceTo>ORTLRisk__c</referenceTo>
        <relationshipLabel>Attendee</relationshipLabel>
        <relationshipName>Attendee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Attendee</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initial Risk Assessment</fullName>
                </value>
                <value>
                    <fullName>Final Risk Assessment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Attendee</label>
    <nameField>
        <displayFormat>AT-{000}</displayFormat>
        <label>Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ORTLRelevantUser__c.object
<CustomObject>
    <fields>
        <fullName>ActionNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Display Action Number</description>
        <label>Action Number</label>
        <referenceTo>ORTLAction__c</referenceTo>
        <relationshipLabel>Relevant User (CC to)</relationshipLabel>
        <relationshipName>RelevantUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelevantUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To display Relevant name who related to that particular action</description>
        <label>Relevant User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Relevant_User_CC_to1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TagNo__c</fullName>
        <formula>ActionNumber__r.txtTagNo__c</formula>
        <label>Tag No.</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaskType__c</fullName>
        <formula>TEXT(ActionNumber__r.TaskType__c)</formula>
        <label>Task Type</label>
        <type>Text</type>
    </fields>
    <label>Relevant User (CC to)</label>
    <nameField>
        <displayFormat>CC-{000}</displayFormat>
        <label>CC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ORTLRisk__c.object
<CustomObject>
    <fields>
        <fullName>APU__c</fullName>
        <label>APU</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AssessmentType__c</fullName>
        <description>To select Assessment type of Risk</description>
        <label>Threat Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PRA (Potential Risk Assessment)</fullName>
                </value>
                <value>
                    <fullName>RRA (Reactive Risk Assessment)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DEM__c</fullName>
        <description>To select DEM</description>
        <label>DEM /Causal Learning</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InitialRisk__c</fullName>
        <description>Display level of Initial Risk</description>
        <label>Initial Risk</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>L</fullName>
                </value>
                <value>
                    <fullName>L/N</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>H</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntRiskCons__c</fullName>
        <description>Display Risk consequence of Initial Risk Assessment</description>
        <label>Initial Threat Consequence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>People</fullName>
                </value>
                <value>
                    <fullName>Assets</fullName>
                </value>
                <value>
                    <fullName>Environment</fullName>
                </value>
                <value>
                    <fullName>Reputation</fullName>
                </value>
                <value>
                    <fullName>Product Quality</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PlantSection__c</fullName>
        <label>Plant Section</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RiskInitiator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Display risk initiator name</description>
        <label>Threat Initiator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Risk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RiskScenario__c</fullName>
        <description>To record Risk Scenario</description>
        <label>Threat Scenario</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TagNo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Display Functional Location</description>
        <label>Tag No.</label>
        <referenceTo>Functional_Location__c</referenceTo>
        <relationshipName>Risk1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Threat__c</fullName>
        <description>To select threat of risk record</description>
        <label>Threat</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>UpDT incident</fullName>
                </value>
                <value>
                    <fullName>Process Safety, LOPC</fullName>
                </value>
                <value>
                    <fullName>Stationary Equipment Integrity</fullName>
                </value>
                <value>
                    <fullName>Equipment Frequent Failures</fullName>
                </value>
                <value>
                    <fullName>Frequent Violation of PTM limits</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Threat</label>
    <nameField>
        <label>Threat No.</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/ORTLTaskStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>In Progress</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
        <isActive>false</isActive>
        <label>New</label>
    </customValue>
    <description>Display the current status</description>
    <masterLabel>Task Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ORTLRiskTest.cls
/**
 * ORTLRiskTest used to test all methods in ORTLRiskCtrl and ORTLRiskAssmntCtrl
 * class. These class used to perform create/edit risk, initial/final risk
 * and sending email to notify related users.
 */
@isTest
public class ORTLRiskTest {

	/**
	 * Inititial data before run each test method.
	 * Create sameple risk records that are required for testing.
	 */
	@Testsetup
	public static void setupData() {

		// Create user
		String uniqueUserName1 = 'standarduser' + DateTime.now().getTime() + '@thaioilgroup.com';
		Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
		User u1 = new User(
			Alias = 'standt1',
			Email = 'standarduser1@thaioilgroup.com',
			LastName = 'Testing',
			ProfileId = p.Id,
			EmailEncodingKey = 'UTF-8',
			LanguageLocaleKey = 'en_US',
			LocaleSidKey = 'en_US',
			TimeZoneSidKey = 'Asia/Bangkok',
			Username = uniqueUserName1
		);
		insert u1;

		// Create user
		String uniqueUserName2 = 'standarduser' + DateTime.now().getTime() + '@thaioilgroup.com';
		User u2 = new User(
			Alias = 'standt2',
			Email = 'standarduser2@thaioilgroup.com',
			LastName = 'Testing',
			ProfileId = p.Id,
			EmailEncodingKey = 'UTF-8',
			LanguageLocaleKey = 'en_US',
			LocaleSidKey = 'en_US',
			TimeZoneSidKey = 'Asia/Bangkok',
			Username = uniqueUserName2
		);
		insert u2;

		// Get user
		User u = [SELECT id,Name FROM User WHERE id =: userInfo.getUserId()];

		// Create Contact
		Contact c = new Contact();
		c.FirstName = 'lastnameTest';
		c.LastName = 'firstnameTest';
		c.Phone = '0000000000';
		insert c;
		//c.Email = 'moke.k@roundtwosolutions.com	'

		// Main Work Center
		Master_Map__c mwc1 = new Master_Map__c();
		mwc1.Name = 'ENMA-I';
		insert mwc1;

		Master_Map__c mwc2 = new Master_Map__c();
		mwc2.Name = 'MECH-OP';
		insert mwc2;

		Master_Map__c plantSection = new Master_Map__c();
		plantSection.Name = 'T1';
		plantSection.Type__c = 'Plant Section';
		insert plantSection;

		// Create Functional Location
		Functional_Location__c fl = new Functional_Location__c();
		fl.Name = 'Test FL';
		fl.MainWorkCenter__c = mwc1.Id;
		insert fl;

		Functional_Location__c fl2 = new Functional_Location__c();
		fl2.Name = 'Test FL 2';
		fl2.MainWorkCenter__c = mwc2.Id;
		insert fl2;

		// Get Functional Location
		Functional_Location__c flRecords = [ SELECT
													Id,
													Name,
													Description__c,
													Planning_Plant__c,
													MainWorkCenter__c,
													mainWorkCenterPlant__c,
													mainWorkCenterPlant__r.Name,
													MainWorkCenter__r.Name,
													MainWorkCenter__r.Code__c,
													Location__c,
													PlantSection__c
												FROM Functional_Location__c
												WHERE Name = 'Test FL'
												LIMIT 1
											];

		/** Create ORTLRisk__c*/
		ORTLRisk__c risk = new ORTLRisk__c();
		risk.TagNo__c = flRecords.Id;
		risk.AssessmentType__c = 'PRA (Potential Risk Assessment)';
		risk.APU__c = 'A';
		insert risk;
		ORTLRisk__c riskRecord = [SELECT Id FROM ORTLRisk__c LIMIT 1];

		/** Create ORTLAction__c */
		//List<ORTLAction__c> actionList = new List<ORTLAction__c>();
		ORTLAction__c action = new ORTLAction__c();
		//action.TaskDescription__c = 'Test';
		action.TaskType__c = 'Assessment';
		action.TagNo__c = flRecords.Id;
		action.Risk__c = riskRecord.Id;
		action.TaskStatus__c = 'In Progress';
		action.DueDate__c = Date.today();
		//actionList.add(action);

		// Insert Action List;
		insert action;
		//System.debug('actionList=>'+actionList);

		// Insert ORTLRelevantUser__c
		List<ORTLRelevantUser__c> relavantUserList = new List<ORTLRelevantUser__c>();
		ORTLRelevantUser__c relavantUser = new ORTLRelevantUser__c();
		relavantUser.RelevantUser__c = u.Id;
		relavantUser.ActionNumber__c = action.Id;
		relavantUserList.add(relavantUser);
		insert relavantUserList;
	}

	/**
	 * Test method used to test getRiskAssessmentSelectOptions method on ORTLRiskAssmntCtrl
	 */
	@isTest
	public static void testGetRiskAssessmentSelectOptions() {
		Test.startTest();
		Map<String, List<Map<String, String>>> selectOptions = ORTLRiskAssmntCtrl.getRiskAssessmentSelectOptions();
		Test.stopTest();

		System.assertEquals(true, selectOptions.containsKey('InitialRiskConsequence'));
		System.assertEquals(true, selectOptions.containsKey('InitialSeverity'));
		System.assertEquals(true, selectOptions.containsKey('InitialLikelihood'));
		System.assertEquals(true, selectOptions.containsKey('FinalRiskConsequence'));
		System.assertEquals(true, selectOptions.containsKey('FinalSeverity'));
		System.assertEquals(true, selectOptions.containsKey('FinalLikelihood'));
	}

	/**
	 * Test method used to test getRiskAssessmentCustomMetadata method on ORTLRiskAssmntCtrl
	 */
	@isTest
	public static void testGetRiskAssessmentCustomMetadata() {
		Test.startTest();
		Map<String, List<Object>> selectOptions = ORTLRiskAssmntCtrl.getRiskAssessmentCustomMetadata();
		Test.stopTest();

		System.assertEquals(true, selectOptions.containsKey('ConsequenceDescription'));
		System.assertEquals(true, selectOptions.containsKey('RiskLevel'));
		System.assertEquals(true, selectOptions.containsKey('LikelihoodCaption'));
	}

	/**
	 * Test method used to test sendEmailRiskRegistered method on ORTLRiskCtrl
	 * And test beforeInsert/afterInsert method on ORTLRiskTriggerHandler
	 */
	@isTest
	public static void testCreateRisk() {
		Test.startTest();
		Functional_Location__c flRecords = [ SELECT Id FROM Functional_Location__c WHERE Name = 'Test FL' LIMIT 1 ];

		ORTLRisk__c risk = new ORTLRisk__c();
		risk.TagNo__c = flRecords.Id;
		risk.AssessmentType__c = 'PRA (Potential Risk Assessment)';
		insert risk;
		Test.stopTest();
		System.assert(risk.Id != null);
	}

	/**
	 * Test method used to test updateRisk method on ORTLRiskAssmntCtrl.
	 * And test beforeUpdate/afterUpdate method on ORTLRiskTriggerHandler.
	 */
	@isTest
	public static void testUpdateRisk() {
		Test.startTest();
		Functional_Location__c flRecords = [ SELECT Id FROM Functional_Location__c WHERE Name = 'Test FL' LIMIT 1 ];

		ORTLRisk__c risk = new ORTLRisk__c();
		risk.TagNo__c = flRecords.Id;
		risk.RiskInitiator__c = UserInfo.getUserId();
		risk.AssessmentType__c = 'PRA (Potential Risk Assessment)';
		insert risk;

		// Create Functional Location 1
		Functional_Location__c fl1 = new Functional_Location__c();
		fl1.Name = 'Test FL 1';
		insert fl1;

		// Create Functional Location 2
		Functional_Location__c fl2 = new Functional_Location__c();
		fl2.Name = 'Test FL 2';
		insert fl2;

		List<String> tagNoList = new List<String>();
		tagNoList.add(fl1.Id);
		tagNoList.add(fl2.Id);

		//risk.RiskScenario__c = 'Test Update Risk Scenario';
		risk.DEM__c = 'Yes';
		ORTLRiskAssmntCtrl.updateRisk(risk, tagNoList);

		Test.stopTest();
		System.assert(risk.Id != null);
	}

	/**
	 * Test method used to test beforeDelete/afterDelete method on ORTLRiskTriggerHandler.
	 */
	@isTest
	public static void testDeleteRisk() {
		Test.startTest();
		ORTLRisk__c riskRecord = [SELECT Id FROM ORTLRisk__c LIMIT 1];
		delete riskRecord;
		Test.stopTest();
	}

	/**
	 * Test method used to test updateInitialRiskAssessment method on ORTLRiskAssmntCtrl.
	 */
	@isTest
	public static void testUpdateInitialRisk() {
		Test.startTest();
		Functional_Location__c flRecords = [ SELECT Id FROM Functional_Location__c WHERE Name = 'Test FL' LIMIT 1 ];

		ORTLRisk__c risk = new ORTLRisk__c();
		risk.TagNo__c = flRecords.Id;
		risk.AssessmentType__c = 'PRA (Potential Risk Assessment)';
		insert risk;

		risk.InitialRisk__c = 'H';
		risk.IntRiskCons__c = 'People';
		risk.Threat__c = 'Process Safety, LOPC';
		risk.IntConsEffect__c = 'Other';
		risk.IntlLikelihood__c = 'C';
		risk.InitialSeverity__c = '5';
		risk.InitialValueUSD__c = 300000;
		risk.RiskStatus__c = 'Awaiting Final Assessment';

		// User
		User u1 = [SELECT id,Name FROM User WHERE Alias = 'standt1'];
		User u2 = [SELECT id,Name FROM User WHERE Alias = 'standt2'];

		// Create Attendees
		ORTLAttendee__c attendee1 = new ORTLAttendee__c();
		attendee1.AttendeeName__c = u1.Id;
		ORTLAttendee__c attendee2 = new ORTLAttendee__c();
		attendee2.AttendeeName__c = u2.Id;
		ORTLAttendee__c attendee3 = new ORTLAttendee__c();
		attendee3.AttendeeName__c = null;

		List<ORTLAttendee__c> attendees1 = new List<ORTLAttendee__c>();
		attendees1.add(attendee1);
		attendees1.add(attendee2);
		attendees1.add(attendee3);

		ORTLRiskAssmntCtrl.updateInitialRiskAssessment(risk, attendees1, new List<ORTLAttendee__c>());

		attendee1.AttendeeName__c = u2.Id;

		List<ORTLAttendee__c> attendees2 = new List<ORTLAttendee__c>();
		attendees2.add(attendee2);
		List<ORTLAttendee__c> delAttendees1 = new List<ORTLAttendee__c>();
		delAttendees1.add(attendee1);

		ORTLRiskAssmntCtrl.updateInitialRiskAssessment(risk, attendees2, delAttendees1);

		Test.stopTest();
		System.assert(risk.Id != null);
	}

	/**
	 * Test method used to test updateFinalRiskAssessment method on ORTLRiskAssmntCtrl.
	 */
	@isTest
	public static void testUpdateFinalRisk() {
		Test.startTest();
		Functional_Location__c flRecords = [ SELECT Id FROM Functional_Location__c WHERE Name = 'Test FL' LIMIT 1 ];

		ORTLRisk__c risk = new ORTLRisk__c();
		risk.TagNo__c = flRecords.Id;
		risk.AssessmentType__c = 'PRA (Potential Risk Assessment)';
		insert risk;

		risk.FinalRisk__c = 'H';
		risk.FinRiskCons__c = 'People';
		risk.Threat__c = 'Process Safety, LOPC';
		risk.FinConsEffect__c = 'Other';
		risk.FinalLikelihood__c = 'C';
		risk.FinalSeverity__c = '5';
		risk.FinalValueUSD__c = 300000;
		risk.RiskStatus__c = 'Closed';

		// User
		User u1 = [SELECT id,Name FROM User WHERE Alias = 'standt1'];
		User u2 = [SELECT id,Name FROM User WHERE Alias = 'standt2'];

		// Action
		ORTLAction__c action = new ORTLAction__c();
		//action.TaskDescription__c = 'Test';
		action.TaskType__c = 'Assessment';
		action.TagNo__c = flRecords.Id;
		action.Risk__c = risk.Id;
		action.TaskStatus__c = 'Done';
		action.DueDate__c = Date.today();
		insert action;

		// Action Relevant User
		ORTLRelevantUser__c relUser = new ORTLRelevantUser__c();
		relUser.RelevantUser__c = u1.Id;
		relUser.ActionNumber__c = action.Id;
		List<ORTLRelevantUser__c> relUsers = new List<ORTLRelevantUser__c>();
		relUsers.add(relUser);
		insert relUsers;

		// Create Attendees
		ORTLAttendee__c attendee1 = new ORTLAttendee__c();
		attendee1.AttendeeName__c = u1.Id;
		ORTLAttendee__c attendee2 = new ORTLAttendee__c();
		attendee2.AttendeeName__c = u2.Id;
		ORTLAttendee__c attendee3 = new ORTLAttendee__c();
		attendee3.AttendeeName__c = null;

		List<ORTLAttendee__c> attendees1 = new List<ORTLAttendee__c>();
		attendees1.add(attendee1);
		attendees1.add(attendee2);
		attendees1.add(attendee3);
		ORTLRiskAssmntCtrl.updateFinalRiskAssessment(risk, attendees1, new List<ORTLAttendee__c>());

		attendee1.AttendeeName__c = u2.Id;

		List<ORTLAttendee__c> attendees2 = new List<ORTLAttendee__c>();
		attendees2.add(attendee2);
		List<ORTLAttendee__c> delAttendees1 = new List<ORTLAttendee__c>();
		delAttendees1.add(attendee1);

		ORTLRiskAssmntCtrl.updateFinalRiskAssessment(risk, attendees2, delAttendees1);

		Test.stopTest();
		System.assert(risk.Id != null);
	}

	/**
	 * Test method used to test getAttendees method on ORTLRiskAssmntCtrl.
	 */
	@isTest
	public static void testGetAttendees() {
		Test.startTest();
		Functional_Location__c flRecords = [ SELECT Id FROM Functional_Location__c WHERE Name = 'Test FL' LIMIT 1 ];

		ORTLRisk__c risk = new ORTLRisk__c();
		risk.TagNo__c = flRecords.Id;
		risk.AssessmentType__c = 'PRA (Potential Risk Assessment)';
		insert risk;

		risk.FinalRisk__c = 'H';
		risk.FinRiskCons__c = 'People';
		risk.Threat__c = 'Process Safety, LOPC';
		risk.FinConsEffect__c = 'Other';
		risk.FinalLikelihood__c = 'C';
		risk.FinalSeverity__c = '5';
		risk.FinalValueUSD__c = 300000;

		// User
		User u1 = [SELECT id,Name FROM User WHERE Alias = 'standt1'];
		User u2 = [SELECT id,Name FROM User WHERE Alias = 'standt2'];

		// Create Attendees
		ORTLAttendee__c attendee1 = new ORTLAttendee__c();
		attendee1.AttendeeName__c = u1.Id;
		ORTLAttendee__c attendee2 = new ORTLAttendee__c();
		attendee2.AttendeeName__c = u2.Id;

		List<ORTLAttendee__c> attendees = new List<ORTLAttendee__c>();
		attendees.add(attendee1);
		attendees.add(attendee2);

		ORTLRiskAssmntCtrl.updateFinalRiskAssessment(risk, attendees, new List<ORTLAttendee__c>());
		List<ORTLAttendee__c> resultAttendees = ORTLRiskAssmntCtrl.getAttendees(risk);

		Test.stopTest();
		System.assertEquals(2, resultAttendees.size());
	}

	/**
	 * Test method used to test getActions method on ORTLRiskAssmntCtrl.
	 */
	@isTest
	public static void testGetActions() {
		Test.startTest();
		ORTLRisk__c risk = [SELECT Id FROM ORTLRisk__c LIMIT 1];
		List<ORTLAction__c> actions = ORTLRiskAssmntCtrl.getActions(risk);

		Test.stopTest();
		System.assertEquals(1, actions.size());
	}

	/**
	 * Test method used to test getOrtlAdmins method on ORTLRiskAssmntCtrl.
	 */
	@isTest
	public static void testGetOrtlAdmins() {
		Test.startTest();
		List<PermissionSetAssignment> ortlAdmins = ORTLRiskAssmntCtrl.getOrtlAdmins();
		Test.stopTest();
	}

	/**
	 * Test method used to test getFunctionLocationDetail method on ORTLRiskAssmntCtrl.
	 */
	@isTest
	public static void testGetFunctionLocationDetail() {
		Test.startTest();
		Functional_Location__c flRecords = [ SELECT Id FROM Functional_Location__c WHERE Name = 'Test FL' LIMIT 1 ];
		Object fl = ORTLRiskAssmntCtrl.getFunctionLocationDetail(flRecords.Id);
		Test.stopTest();
		System.assert(fl != null);
	}

	/**
	 * Test method used to test getRelatedRisk method on ORTLRiskAssmntCtrl.
	 */
	@isTest
	public static void testGetRelatedRisk() {
		Test.startTest();
		ORTLRisk__c riskRecord = [SELECT Id FROM ORTLRisk__c LIMIT 1];

		Functional_Location__c flRecords = [ SELECT Id FROM Functional_Location__c WHERE Name = 'Test FL' LIMIT 1 ];

		ORTLRisk__c risk = new ORTLRisk__c();
		risk.TagNo__c = flRecords.Id;
		risk.AssessmentType__c = 'PRA (Potential Risk Assessment)';
		insert risk;
		risk.OriginalRisk__c = riskRecord.Id;
		risk.CheckApplicable__c = true;
		update risk;

		List<ORTLRisk__c> relatedRisks = ORTLRiskAssmntCtrl.getRelatedRisk(riskRecord);
		Test.stopTest();
		System.assertEquals(1, relatedRisks.size());
	}

	/**
	 * Test method used to test renameUploadedFile method on ORTLRiskAssmntCtrl.
	 */
	@isTest
	public static void testUploadFile() {
		Test.startTest();
		ORTLRisk__c riskRecord = [SELECT Id FROM ORTLRisk__c LIMIT 1];

		ContentVersion content = new ContentVersion();
		content.Title = 'vscode';
		content.PathOnClient=content.Title;
		Blob bodyBlob = Blob.valueOf('Unit Test ContentVersion Body');
		content.VersionData = bodyBlob;
		content.origin = 'C';
		insert content;

		String docId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =: content.id].ContentDocumentId;
		ContentDocumentLink contentlink = new ContentDocumentLink();
		contentlink.LinkedEntityId = riskRecord.id;
		contentlink.ContentDocumentId = docId;
		contentlink.ShareType = 'V';
		contentlink.Visibility = 'AllUsers';
		insert contentlink;

		ORTLRiskAssmntCtrl.renameUploadedFile(riskRecord, docId, 'RenameUploadFile');
		List<ContentDocumentLink> attachments = ORTLRiskAssmntCtrl.getContentDocumentLinks(riskRecord);

		Test.stopTest();
		System.assertEquals(1, attachments.size());
	}

	/**
	 * Test method used to test canEditOwner method on ORTLRiskAssmntCtrl.
	 */
	@isTest
	public static void testCanEditOwner() {
		Test.startTest();
		ORTLRisk__c riskRecord = [SELECT Id FROM ORTLRisk__c LIMIT 1];
		Boolean canEditOwner = ORTLRiskAssmntCtrl.canEditOwner(riskRecord);
		System.assertEquals(true, canEditOwner);
		Test.stopTest();
	}
}