force-app/main/default/objects/Functional_Location__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Functional Location</label>
    <nameField>
        <label>Functional Location</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Functional_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Location</label>
        <referenceTo>Functional_Location__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notification_Number__c</fullName>
        <externalId>true</externalId>
        <label>Notification Number</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Requested_Date__c</fullName>
        <label>Requested Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Required_Start__c</fullName>
        <label>Required Start</label>
        <type>Date</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ODM_HomeCtrlTest.cls
@isTest
public class ODM_HomeCtrlTest {

    @TestSetup
    static void makeData(){
        insert new Notification__c(
			Name = '00000001',
            Notification_Number__c = '00000001',
			Description__c = 'Test Notification',
			Requested_Date__c = Date.today(),
			Required_Start__c = Date.today()
		);
    }

    @isTest
    public static void testGetUser() {
        Test.startTest();

        String userId = UserInfo.getUserId();
        User myUser = (User) ODM_HomeCtrl.getUser();

        System.assertEquals(userId, myUser.Id);

        Test.stopTest();
    }

    @isTest
    public static void testGetNotificationList() {
		Test.startTest();

		Object objNotis = ODM_HomeCtrl.getNotificationList(
			new Map<String, String>{
				'Notification_Number__c' => '00000001'
			}, 0, 20, true
		);

        System.debug(JSON.serialize(objNotis));

        Map<String, Object> wrapper = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(objNotis));

        System.assertEquals(1, Integer.valueOf(wrapper.get('count')));
        
		Test.stopTest();
    }
     @isTest
    public static void testGetWcList() {
		Test.startTest();

		Object objNotis = ODM_HomeCtrl.getWcList(
			new Map<String, String>{
				'Functional_Location__c' => '00000001'
			}, 0, 20, true
		);

        System.debug(JSON.serialize(objNotis));

        Map<String, Object> wrapper = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(objNotis));

        System.assertEquals(0, Integer.valueOf(wrapper.get('count')));
        
		Test.stopTest();
    }

    @isTest
    public static void getWcVerificationList() {
		Test.startTest();

		Object objNotis = ODM_HomeCtrl.getWcVerificationList(
			new Map<String, String>{
				'Functional_Location__c' => '00000001'
			}, 0, 20, true
		);

        System.debug(JSON.serialize(objNotis));

        Map<String, Object> wrapper = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(objNotis));

        System.assertEquals(0, Integer.valueOf(wrapper.get('count')));
        
		Test.stopTest();
    }
}