force-app/main/default/objects/Functional_Location__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MainWorkCenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MainWorkCenter</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Main Work Center</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Functional Location (MainWorkCenter)</relationshipLabel>
        <relationshipName>Functional_Location5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>mainWorkCenterPlant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>mainWorkCenterPlant</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Functional Location (mainWorkCenterPlant)</relationshipLabel>
        <relationshipName>Functional_Location3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Functional Location</label>
    <nameField>
        <label>Functional Location</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Map__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedMasterMap1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedMasterMap1</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Master Maps</relationshipLabel>
        <relationshipName>Master_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedMasterMap2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedMasterMap2</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Master Maps (RelatedMasterMap2)</relationshipLabel>
        <relationshipName>Master_Maps2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Master Map Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/EMOC_MasterControllerTest.cls
@isTest
public class EMOC_MasterControllerTest {
    @testSetup static void Data() {  
        Master_Map__c mapMas1 = new Master_Map__c();
        mapMas1.Name = 'CR01';
        mapMas1.Type__c = 'Main Work Center';
        insert mapMas1;

        Master_Map__c mapMas2 = new Master_Map__c();
        mapMas2.Name = 'CR02';
        insert mapMas2;

        Master_Map__c mapMas3 = new Master_Map__c();
        mapMas3.Name = 'CR03';
        mapMas3.RelatedMasterMap1__c = mapMas2.Id;
        mapMas3.RelatedMasterMap2__c = mapMas1.Id;
        insert mapMas3;
        
        Master_Map__c mapMas4 = new Master_Map__c();
        mapMas4.Name = '1200';
        mapMas4.Type__c = 'Plant';
        insert mapMas4;
        
        Functional_Location__c funcLoc = new Functional_Location__c();
        funcLoc.Name = 'Test Functional Location';
        funcLoc.Description__c = 'TEST';
       	funcLoc.MainWorkCenter__c = mapMas1.Id;
        funcLoc.mainWorkCenterPlant__c = mapMas1.Id;
        insert funcLoc;

        User currentuser = [Select Id, Name, Department from User where Id = :userinfo.getuserId()];
        currentuser.Department = 'EMOC';
        update currentuser;

    }
    static testmethod void testData() {
        Test.startTest();

        User currentuser = [Select Id, Name, Department from User where Id = :userinfo.getuserId()];
        
        Master_Map__c mapMas1 = new Master_Map__c();
        mapMas1.Name = 'CR01';
        mapMas1.Type__c = 'Main Work Center';
        insert mapMas1;
        
        EMOC_MasterController.getLookupFncLocation('Functional', 'Notification');
        EMOC_MasterController.getLookupUser(currentuser.Name);
 		EMOC_MasterController.getLookupMasterMap(mapMas1.Id);
        EMOC_MasterController.getLookupPMActivity('CR01');
        EMOC_MasterController.getLookupMainWorkCenterPlan('1200');
        Test.stopTest();
    }
}