force-app/main/default/objects/Functional_Location__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MainWorkCenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MainWorkCenter</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Main Work Center</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Functional Location (MainWorkCenter)</relationshipLabel>
        <relationshipName>Functional_Location5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planning_Plant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Plant</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Functional Location (Planning Plant)</relationshipLabel>
        <relationshipName>Functional_Location2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PlantSection__c</fullName>
        <label>PlantSection</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>mainWorkCenterPlant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>mainWorkCenterPlant</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Functional Location (mainWorkCenterPlant)</relationshipLabel>
        <relationshipName>Functional_Location3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Functional Location</label>
    <nameField>
        <label>Functional Location</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Map__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Master Map Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Functional_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Location</label>
        <referenceTo>Functional_Location__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <formula>IF(ISBLANK(Equipment__c), Functional_Location__r.Location__c, Equipment__r.location__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planning_Plant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Plant</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Notifications (Planning Plant)</relationshipLabel>
        <relationshipName>Notifications3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>mainWorkCenterPlant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>mainWorkCenterPlant</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Notification (mainWorkCenterPlant)</relationshipLabel>
        <relationshipName>Notification</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ORTLAction__c.object
<CustomObject>
    <fields>
        <fullName>APU__c</fullName>
        <description>APU of selected Tag no.</description>
        <inlineHelpText>Default from Risk record</inlineHelpText>
        <label>APU</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CloseDate__c</fullName>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <defaultValue>Today()+30</defaultValue>
        <description>Date to finish task</description>
        <inlineHelpText>Default 30 days after create action record and editable</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InitialDate__c</fullName>
        <description>Create Date</description>
        <inlineHelpText>Format: DD/MM/YYYY</inlineHelpText>
        <label>Initial Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsOwner__c</fullName>
        <formula>$User.Id = Owner:User.Id</formula>
        <label>IsOwner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MitigateCons__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if an action was created to mitigate consequence</description>
        <inlineHelpText>To check if an action was created to mitigate consequence</inlineHelpText>
        <label>Mitigate Consequence</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SAP Notification Number</description>
        <label>Notification</label>
        <referenceTo>Notification__c</referenceTo>
        <relationshipLabel>Action</relationshipLabel>
        <relationshipName>Action1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PlantSection__c</fullName>
        <label>Plant Section</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <description>Display Plant Section of selected Tag no.</description>
        <inlineHelpText>Default from Risk record</inlineHelpText>
        <label>Plant</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReduceLLH__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if an action was created to reduce likelihood</description>
        <inlineHelpText>To check if an action was created to reduce likelihood</inlineHelpText>
        <label>Reduce Likelihood</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RiskScenario__c</fullName>
        <description>Default from Risk record</description>
        <label>Threat Scenario</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Risk__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Threat</label>
        <referenceTo>ORTLRisk__c</referenceTo>
        <relationshipLabel>Action</relationshipLabel>
        <relationshipName>Action</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <description>Task owner section detail</description>
        <label>Section</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ORTLSectionValue</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TagNo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Functional Location</description>
        <inlineHelpText>Default from Risk record</inlineHelpText>
        <label>Tag No.</label>
        <referenceTo>Functional_Location__c</referenceTo>
        <relationshipLabel>Action</relationshipLabel>
        <relationshipName>Action</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaskCopyOwner__c</fullName>
        <formula>Owner:User.FirstName &amp;&quot; &quot;&amp; Owner:User.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Task Copy Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaskDescription__c</fullName>
        <description>Task Description detail</description>
        <label>Task Description</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TaskInitiator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name Risk owner</description>
        <inlineHelpText>Default name as created user</inlineHelpText>
        <label>Task Initiator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Action1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaskOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of assigned action owner</description>
        <label>Task Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Action</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaskStatus__c</fullName>
        <description>Display the current status</description>
        <label>Task Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ORTLTaskStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaskType__c</fullName>
        <description>Display task type</description>
        <label>Task Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assessment</fullName>
                </value>
                <value>
                    <fullName>Awaiting Opportunity</fullName>
                </value>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>Moc</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Action</label>
    <nameField>
        <label>Action No.</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ORTLRelevantUser__c.object
<CustomObject>
    <fields>
        <fullName>ActionNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Display Action Number</description>
        <label>Action Number</label>
        <referenceTo>ORTLAction__c</referenceTo>
        <relationshipLabel>Relevant User (CC to)</relationshipLabel>
        <relationshipName>RelevantUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelevantUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To display Relevant name who related to that particular action</description>
        <label>Relevant User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Relevant_User_CC_to1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TagNo__c</fullName>
        <formula>ActionNumber__r.txtTagNo__c</formula>
        <label>Tag No.</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaskType__c</fullName>
        <formula>TEXT(ActionNumber__r.TaskType__c)</formula>
        <label>Task Type</label>
        <type>Text</type>
    </fields>
    <label>Relevant User (CC to)</label>
    <nameField>
        <displayFormat>CC-{000}</displayFormat>
        <label>CC Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ORTLRisk__c.object
<CustomObject>
    <fields>
        <fullName>APU__c</fullName>
        <label>APU</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AssessmentType__c</fullName>
        <description>To select Assessment type of Risk</description>
        <label>Threat Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PRA (Potential Risk Assessment)</fullName>
                </value>
                <value>
                    <fullName>RRA (Reactive Risk Assessment)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PlantSection__c</fullName>
        <label>Plant Section</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RiskScenario__c</fullName>
        <description>To record Risk Scenario</description>
        <label>Threat Scenario</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TagNo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Display Functional Location</description>
        <label>Tag No.</label>
        <referenceTo>Functional_Location__c</referenceTo>
        <relationshipName>Risk1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Threat</label>
    <nameField>
        <label>Threat No.</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/ORTLSectionValue.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ENRM</fullName>
    </customValue>
    <customValue>
        <fullName>ACCO</fullName>
    </customValue>
    <customValue>
        <fullName>ACCP</fullName>
    </customValue>
    <customValue>
        <fullName>ACCT</fullName>
    </customValue>
    <customValue>
        <fullName>ACFA</fullName>
    </customValue>
    <customValue>
        <fullName>ACFC</fullName>
    </customValue>
    <customValue>
        <fullName>ACFS</fullName>
    </customValue>
    <customValue>
        <fullName>ACSA</fullName>
    </customValue>
    <customValue>
        <fullName>ADOE</fullName>
    </customValue>
    <customValue>
        <fullName>ADPE</fullName>
    </customValue>
    <customValue>
        <fullName>BDOA</fullName>
    </customValue>
    <customValue>
        <fullName>BDOC</fullName>
    </customValue>
    <customValue>
        <fullName>BDOD</fullName>
    </customValue>
    <customValue>
        <fullName>BDOE</fullName>
    </customValue>
    <customValue>
        <fullName>CACA</fullName>
    </customValue>
    <customValue>
        <fullName>CACM</fullName>
    </customValue>
    <customValue>
        <fullName>CAGR</fullName>
    </customValue>
    <customValue>
        <fullName>CAPB</fullName>
    </customValue>
    <customValue>
        <fullName>CARR</fullName>
    </customValue>
    <customValue>
        <fullName>CMBD</fullName>
    </customValue>
    <customValue>
        <fullName>CMCS</fullName>
    </customValue>
    <customValue>
        <fullName>CMDC</fullName>
    </customValue>
    <customValue>
        <fullName>CMDL</fullName>
    </customValue>
    <customValue>
        <fullName>CMDO</fullName>
    </customValue>
    <customValue>
        <fullName>CMDP</fullName>
    </customValue>
    <customValue>
        <fullName>CMLA</fullName>
    </customValue>
    <customValue>
        <fullName>CMPS</fullName>
    </customValue>
    <customValue>
        <fullName>COO1</fullName>
    </customValue>
    <customValue>
        <fullName>COO2</fullName>
    </customValue>
    <customValue>
        <fullName>COO3</fullName>
    </customValue>
    <description>Task owner section detail</description>
    <masterLabel>Section Value</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ORTLTaskStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>In Progress</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>New</fullName>
        <isActive>false</isActive>
        <label>New</label>
    </customValue>
    <description>Display the current status</description>
    <masterLabel>Task Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ORTLActionTest.cls
/**
 * ORTLActionTest used to test each method in ORTLActionCtrl
 * By the way Set up data or make some data like a real case
 * then call each method to test, if any method must have a parameter
 * you can query record and pass to those parameter,but they have to same type
 */
@isTest
public class ORTLActionTest {

	public static String CRON_EXP = '02 0 0 31 12 ? 2024';

	/**Set up data that like a real case */
	@Testsetup
	public static void setupData(){

		System.debug('--setupData--');

		/**User Object */
		User u = [SELECT id,Name,Email FROM User WHERE id =: userInfo.getUserId()];
		System.debug('User=>'+u);

		/**Contact Object */
		Contact cnt = new Contact();
		cnt.FirstName = 'lastnameTest';
		cnt.LastName = 'firstnameTest';
		cnt.Phone = '0000000000';
		cnt.Email = 'setUpData@gmail.com';
		insert cnt;

		/**Functional Location Object */
		Functional_Location__c fl = new Functional_Location__c();
		fl.Name = 'Test FL';
		insert fl;
		System.debug('fl=>'+fl);
		Functional_Location__c flRecords = [ SELECT
													Id,
													Name,
													Description__c,
													Planning_Plant__c,
													MainWorkCenter__c,
													mainWorkCenterPlant__c,
													mainWorkCenterPlant__r.Name,
													MainWorkCenter__r.Name,
													MainWorkCenter__r.Code__c,
													Location__c,
													PlantSection__c
												FROM Functional_Location__c
												WHERE Name = 'Test FL'
												LIMIT 1
											];

		/** Risk Object*/
		ORTLRisk__c risk = new ORTLRisk__c();
		risk.TagNo__c = flRecords.Id;
		risk.AssessmentType__c = 'PRA (Potential Risk Assessment)';
		insert risk;

		ORTLRisk__c riskRecord = [SELECT Id FROM ORTLRisk__c LIMIT 1];

		/**Action Object */
		ORTLAction__c action = new ORTLAction__c();
		//action.TaskDescription__c = 'Test';
		action.TaskType__c = 'Assessment';
		action.TagNo__c = flRecords.Id;
		action.Risk__c = riskRecord.Id;
		action.TaskStatus__c = 'In Progress';
		action.DueDate__c = Date.today() + 1;
		insert action;
		System.debug('action=>'+action);

		/**Action Object */
		ORTLAction__c action2 = new ORTLAction__c();
		//action2.TaskDescription__c = 'action2';
		action2.TaskType__c = 'Assessment';
		action2.TagNo__c = flRecords.Id;
		action2.Risk__c = riskRecord.Id;
		action2.TaskStatus__c = 'In Progress';
		action2.DueDate__c = Date.today() + 7;
		insert action2;

		/**Relavant User Object */
		List<ORTLRelevantUser__c> relavantUserList = new List<ORTLRelevantUser__c>();
		ORTLRelevantUser__c relavantUser = new ORTLRelevantUser__c();
		relavantUser.RelevantUser__c = u.Id;
		relavantUser.ActionNumber__c = action2.Id;
		relavantUserList.add(relavantUser);
		insert relavantUserList;
		System.debug('relavantUserList=>'+relavantUserList);
	}

	/**testSendEmailCreateAction Method used to test sendEmailActionCreated method on ORTLActionCtrl */
	@isTest
	public static void testSendEmailCreateAction(){
		ORTLAction__c action = [SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastActivityDate, LastViewedDate, LastReferencedDate, TaskType__c, Notification__c, Risk__c, ReduceLLH__c, TagNo__c, MitigateCons__c, Plant__c, APU__c, TaskStatus__c,/* RiskScenario__c,*/ TaskOwner__c, TaskInitiator__c, InitialDate__c, DueDate__c, CloseDate__c, TaskCopyOwner__c, IsOwner__c, CancelReason__c, Objective__c, PlantSection__c, Section__c, txtTagNo__c FROM ORTLAction__c LIMIT 1];

		Test.startTest();
		ORTLActionCtrl.sendEmailActionCreated(new List<ORTLAction__c>{ action });
		Test.stopTest();
	}

	/**testCancelAction Method used to test cancelAction and sendEmailActionCanceled method on ORTLActionCtrl */
	@isTest
	public static void testCancelAction(){
		System.debug('--testCancelAction--');
		ORTLAction__c actionId = [SELECT Id,Name FROM ORTLAction__c LIMIT 1 ];

		Test.startTest();
		String actionTest = (String) ORTLActionCtrl.cancelAction(actionId.Id,'Test Reason');
		Test.stopTest();
		System.assert(actionTest != null,'Not Expect Data');
	}

	/** testActionName Method used to test getActionName method on ORTLActionCtrl */
	@isTest
	public static void testActionName(){
		System.debug('--testActionName--');
		ORTLAction__c actionId = [SELECT Id,Name FROM ORTLAction__c LIMIT 1 ];

		Test.startTest();
		ORTLAction__c actionTest = (ORTLAction__c) ORTLActionCtrl.getActionName(actionId.Id);
		Test.stopTest();
		System.assert(actionTest != null,'Not Expect Data');
	}

	/** testActionOwner Method used to test getActionOwner method on ORTLActionCtrl */
	@isTest
	public static void testActionOwner(){
		ORTLAction__c action = [SELECT Id, Name, OwnerId FROM ORTLAction__c LIMIT 1 ];

		Test.startTest();
		String ownerId = ORTLActionCtrl.getActionOwner(action.Id);
		Test.stopTest();
		System.assertEquals(action.OwnerId, ownerId);
	}

	/** testRelevantUsers Method used to test getRelevantUsers method on ORTLActionCtrl */
	@isTest
	public static void testRelevantUsers(){
		System.debug('--testRelevantUsers--');
		ORTLAction__c actionId = [SELECT Id,Name FROM ORTLAction__c LIMIT 1 ];

		Test.startTest();
		List<ORTLRelevantUser__c> actionTest = (List<ORTLRelevantUser__c>) ORTLActionCtrl.getRelevantUsers(actionId.Id);
		Test.stopTest();
		System.assert(actionTest != null,'Not Expect Data');
	}

	/** testUpdateRelevantUsers Method used to test updateRelevantUsers method on ORTLActionCtrl */
	@isTest
	public static void testUpdateRelevantUsers(){
		System.debug('--testUpdateRelevantUsers--');
		ORTLAction__c actionId = [SELECT Id,Name FROM ORTLAction__c LIMIT 1 ];

		List<ORTLRelevantUser__c> relavantUser = [SELECT Id,RelevantUser__c FROM ORTLRelevantUser__c];
		List<ORTLRelevantUser__c> relavantUserId = [SELECT Id FROM ORTLRelevantUser__c];

		Test.startTest();
		List<ORTLRelevantUser__c> actionTestAddRelavantUser = (List<ORTLRelevantUser__c>) ORTLActionCtrl.updateRelevantUsers(actionId.Id,relavantUser,relavantUser);
		Test.stopTest();
		System.assert(actionTestAddRelavantUser != null,'Not Expect Data');
	}

	/** testDueDateChanged Method used to test sendEmailActionDueDateChanged method on ORTLActionCtrl */
	@isTest
	public static void testDueDateChanged(){
		System.debug('--testDueDateChanged--');
		Test.startTest();
		ORTLAction__c actionId = [SELECT Id,Name,Risk__c,TaskStatus__c,TagNo__c,TaskType__c,DueDate__c FROM ORTLAction__c LIMIT 1 ];
		actionId.DueDate__c = Date.today()-1;
		update actionId;
		Test.stopTest();
	}

	/** testStatusIsDone Method used to test sendEmailActionClosed method on ORTLActionCtrl */
	@isTest
	public static void testStatusIsDone(){
		System.debug('--testStatusIsDone--');
		Test.startTest();
		ORTLAction__c actionId = [SELECT Id,Name,Risk__c,TaskStatus__c,TagNo__c,TaskType__c,DueDate__c FROM ORTLAction__c LIMIT 1 ];
		actionId.TaskStatus__c = 'Done';
		update actionId;
		Test.stopTest();
	}

	/** testApplogFailed Method used to test Fail Case */
	@isTest
	public static void testApplogFailed(){
		System.debug('--testStatusIsDoneFailed--');
		Test.startTest();
		ORTLAction__c actionId = [SELECT Id,Name,Risk__c,TaskStatus__c,TagNo__c,TaskType__c,DueDate__c FROM ORTLAction__c LIMIT 1 ];
		actionId.TaskStatus__c = 'Canceled';
		actionId.DueDate__c = Date.today()+5;
		actionId.CancelReason__c = 'test input character more than 255 ';

		update actionId;
		System.debug('actionId =>'+ actionId);
		Test.stopTest();
	}

	/** testDeleteAction Method used to test when delete record */
	@isTest
	public static void testDeleteAction() {
		Test.startTest();
		List<ORTLAction__c> action = [SELECT Id,Name FROM ORTLAction__c];
		delete action;
		List<ORTLAction__c> actionAfterDeleted = [SELECT Id,Name FROM ORTLAction__c];
		System.assertEquals(0, actionAfterDeleted.size());
		Test.stopTest();
	}

	/** testAboutDueDate1DayLeft Method used to test sendEmailActionAboutDueDate 1 day left method on ORTLActionCtrl */
	@isTest
	public static void testAboutDueDate1DayLeft(){
		System.debug('--testAboutDueDate1DayLeft--');
		Test.startTest();
		// ORTLAction__c actionId = [SELECT Id,Name,Risk__c,TaskStatus__c,TagNo__c,TaskType__c,DueDate__c,(SELECT Id, RelevantUser__r.Email FROM RelevantUser__r) FROM ORTLAction__c WHERE TaskDescription__c = 'action2' AND TaskStatus__c = 'In Progress' LIMIT 1 ];
		// actionId.DueDate__c = Date.today()+1;
		// //actionId.RelevantUser__r = 'setUpData@gmail.com';
		// update actionId;

		ORTLActionCtrl.sendEmailActionAboutDueDate(null);
		Test.stopTest();
	}

	// /** testAboutDueDate7DayLeft Method used to test sendEmailActionAboutDueDate 7 day left method on ORTLActionCtrl */
	// @isTest
	// public static void testAboutDueDate7DayLeft(){
	// 	System.debug('--testAboutDueDate7DayLeft--');
	// 	Test.startTest();
	// 	ORTLAction__c actionId = [SELECT Id,Name,Risk__c,TaskStatus__c,TagNo__c,TaskType__c,DueDate__c FROM ORTLAction__c LIMIT 1 ];
	// 	actionId.DueDate__c = Date.today()+7;
	// 	update actionId;

	// 	ORTLActionCtrl.sendEmailActionAboutDueDate(null);
	// 	Test.stopTest();
	// }

	/** testScheduledJob Method used to test when ShceduleJob Run */
	static testmethod void testScheduledJob() {

		Test.startTest();
		String jobId = System.schedule('ORTLActionDueDateJob',CRON_EXP,new ORTLActionDueDateJob());
		System.assert(jobId != '', 'Tasks exist before job has run');
		Test.stopTest();
	}

	/**
	 * Test method used to test canCancelOwner method on ORTLActionCtrl.
	 */
	@isTest
	public static void testCanCancelOwner() {
		Test.startTest();
		ORTLAction__c action = [SELECT Id FROM ORTLAction__c LIMIT 1];
		Boolean canCancelAction = ORTLActionCtrl.canCancelOwner(action);
		System.assertEquals(true, canCancelAction);
		Test.stopTest();
	}

	/**
	 * Test method used to test canEditAction method on ORTLAction.
	 */
	@isTest
	public static void testCanEditAction() {
		Test.startTest();
		ORTLAction__c actionRecord = [SELECT Id FROM ORTLAction__c LIMIT 1];
		Boolean canEditAction = ORTLActionCtrl.canEditAction(actionRecord);
		System.assertEquals(true, canEditAction);
		Test.stopTest();
	}

}