force-app/main/default/objects/Handover__c.object
<CustomObject>
    <fields>
        <fullName>MC__c</fullName>
        <label>MC</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Punch_List_Management_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Punch List Management System</label>
        <referenceTo>Punch_List_Management_System__c</referenceTo>
        <relationshipLabel>Handover</relationshipLabel>
        <relationshipName>Handover</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSFU__c</fullName>
        <label>RFSU</label>
        <type>Date</type>
    </fields>
    <label>Handover</label>
    <nameField>
        <label>Sub System Numbering</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data__c.object
<CustomObject>
    <label>Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Master_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Data</label>
        <referenceTo>Master_Data__c</referenceTo>
        <relationshipLabel>Master Data Detail</relationshipLabel>
        <relationshipName>Master_Data_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SME</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected user is not SME user. Please select SME user.</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>PM</value>
            </filterItems>
            <infoMessage>Please select SME user.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Master_Data_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Process_Group__c</fullName>
        <label>Work Process Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Group</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Process_No__c</fullName>
        <label>Work Process No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Master Data Detail</label>
    <nameField>
        <label>Work Process Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MC_RSFU__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>MC_RSFU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SME</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected User is not SME. Please select SME user.</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>PM</value>
            </filterItems>
            <infoMessage>Please select SME user.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Step_28_MC_RSFU</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Step 28 : MC &amp; RFSU</label>
    <nameField>
        <displayFormat>WP28-{00000}</displayFormat>
        <label>Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Please select only PM user.</errorMessage>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>TOPPMP-AI</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>CPEM Admin</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Project</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Number__c</fullName>
        <label>Project Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Punch_List_Management_System__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Punch_List_Management_System</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SME</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected User is not SME. Please select SME user.</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>PM</value>
            </filterItems>
            <infoMessage>Please select SME user.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Step 27: Punch List Management System</relationshipLabel>
        <relationshipName>Step_27_Punch_List_Management_System</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Step 27 : Punch List Management System</label>
    <nameField>
        <displayFormat>WP27-{00000}</displayFormat>
        <label>Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Group.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Project Scope and Information</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Project Cost Control</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Project Schedule Control</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Procurement Status Report</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Document Management</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Engineering</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Material Control</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Execution</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Project Handover</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Risk Analyst</label>
    </customValue>
    <masterLabel>Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TC_MCRFSUChart.cls
/* Test Class for MCRFSUController Class */
@isTest
public class TC_MCRFSUChart {

    public static void MasterDataInfo() {
        //Master Data
        User SMEUser = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'SME'].Id,
            UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI AD&SME'].Id,
            LastName = 'last',
            Email = 'test@thaioilgroup.com',
            Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
            CompanyName = 'Thaioil',
            Alias = 'test',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
            );
        insert(SMEUser);
        
        System.runAs(SMEUser) {
            Master_Data__c MD = new Master_Data__c();
            MD.Name = 'SME and Guideline';
            insert(MD);
            
            List<Master_Data_Detail__c> MDDs = new List<Master_Data_Detail__c>();
            
            Master_Data_Detail__c MDD1 = new Master_Data_Detail__c();
            MDD1.Work_Process_No__c = 0;
            MDD1.Group__c = 10;
            MDD1.Name = 'Project Risk Assessment';
            MDD1.Work_Process_Group__c = '10';
            MDD1.Master_Data__c = MD.Id;
            MDD1.SME__c = SMEUser.Id;
            MDDs.add(MDD1);
            
            insert(MDDs);
        }
    }
    
    public static testMethod void MCRFSUChart() {
        
        MasterDataInfo();
        
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'PM'].Id,
        UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI PM'].Id,
        LastName = 'last',
        Email = 'test@thaioilgroup.com',
        Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
        CompanyName = 'Thaioil',
        Alias = 'test',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US'
    	);
        insert(u);
        
        System.runAs(u) {
            
            Project__c Proj = new Project__c();
            Proj.Name = 'Test Project';
            Proj.Project_Number__c = 'Test 001';
            Proj.Project_Manager__c = u.Id;
            insert(Proj);
        
            Punch_List_Management_System__c WP27 = [select id, Project__c from Punch_List_Management_System__c where Project__c =: Proj.Id];
            
            MC_RSFU__c MCRFSU = [select id from MC_RSFU__c where Project__c =: Proj.Id];
            
            DateTime dT = System.now();
            Date todayDate = date.newinstance(dT.year(), dT.month(), dT.day());
            
            Handover__c Handover = new Handover__c();
            Handover.MC__c = todayDate;
            Handover.RSFU__c = todayDate;
            Handover.Punch_List_Management_System__c = WP27.Id;
            insert(Handover);
            
            PageReference pageRef = Page.WorkProcess28Chart;
            //pageRef.getParameters().put('WorkProcessNo','1');        
            Test.setCurrentPage(PageRef);
            
            test.startTest();
            
            ApexPages.StandardController sc = new ApexPages.StandardController(MCRFSU);                         
            MCRFSUChart Chart = new MCRFSUChart(sc); 
            
            test.stopTest();
        }
    }
    
    public static testMethod void MCRFSUChartMC() {
        
        MasterDataInfo();
        
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'PM'].Id,
        UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI PM'].Id,
        LastName = 'last',
        Email = 'test@thaioilgroup.com',
        Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
        CompanyName = 'Thaioil',
        Alias = 'test',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US'
    	);
        insert(u);
        
        System.runAs(u) {
            
            Project__c Proj = new Project__c();
            Proj.Name = 'Test Project';
            Proj.Project_Number__c = 'Test 001';
            Proj.Project_Manager__c = u.Id;
            insert(Proj);
        
            Punch_List_Management_System__c WP27 = [select id, Project__c from Punch_List_Management_System__c where Project__c =: Proj.Id];
            
            MC_RSFU__c MCRFSU = [select id from MC_RSFU__c where Project__c =: Proj.Id];
            
            DateTime dT = System.now();
            Date todayDate = date.newinstance(dT.year(), dT.month(), dT.day());
            
            Handover__c Handover = new Handover__c();
            Handover.Punch_List_Management_System__c = WP27.Id;
            insert(Handover);
            
            PageReference pageRef = Page.WorkProcess28Chart;
            //pageRef.getParameters().put('WorkProcessNo','1');        
            Test.setCurrentPage(PageRef);
            
            test.startTest();
            
            ApexPages.StandardController sc = new ApexPages.StandardController(MCRFSU);                         
            MCRFSUChart Chart = new MCRFSUChart(sc); 
            
            test.stopTest();
        }
    }
    
    public static testMethod void MCRFSUChartRSFU() {
        
        MasterDataInfo();
        
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'PM'].Id,
        UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI PM'].Id,
        LastName = 'last',
        Email = 'test@thaioilgroup.com',
        Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
        CompanyName = 'Thaioil',
        Alias = 'test',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US'
    	);
        insert(u);
        
        System.runAs(u) {
            
            Project__c Proj = new Project__c();
            Proj.Name = 'Test Project';
            Proj.Project_Number__c = 'Test 001';
            Proj.Project_Manager__c = u.Id;
            insert(Proj);
        
            Punch_List_Management_System__c WP27 = [select id, Project__c from Punch_List_Management_System__c where Project__c =: Proj.Id];
            
            MC_RSFU__c MCRFSU = [select id from MC_RSFU__c where Project__c =: Proj.Id];
            
            DateTime dT = System.now();
            Date todayDate = date.newinstance(dT.year(), dT.month(), dT.day());
            
            Handover__c Handover = new Handover__c();
            Handover.MC__c = todayDate;
            Handover.Punch_List_Management_System__c = WP27.Id;
            insert(Handover);
            
            PageReference pageRef = Page.WorkProcess28Chart;
            //pageRef.getParameters().put('WorkProcessNo','1');        
            Test.setCurrentPage(PageRef);
            
            test.startTest();
            
            ApexPages.StandardController sc = new ApexPages.StandardController(MCRFSU);                         
            MCRFSUChart Chart = new MCRFSUChart(sc); 
            
            test.stopTest();
        }
    }
    
    public static testMethod void MCRFSUChartNoHandover() {
        
        MasterDataInfo();
        
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'PM'].Id,
        UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI PM'].Id,
        LastName = 'last',
        Email = 'test@thaioilgroup.com',
        Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
        CompanyName = 'Thaioil',
        Alias = 'test',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US'
    	);
        insert(u);
        
        System.runAs(u) {
            
            Project__c Proj = new Project__c();
            Proj.Name = 'Test Project';
            Proj.Project_Number__c = 'Test 001';
            Proj.Project_Manager__c = u.Id;
            insert(Proj);
        
            Punch_List_Management_System__c WP27 = [select id, Project__c from Punch_List_Management_System__c where Project__c =: Proj.Id];
            
            MC_RSFU__c MCRFSU = [select id from MC_RSFU__c where Project__c =: Proj.Id];
            
            PageReference pageRef = Page.WorkProcess28Chart;
            //pageRef.getParameters().put('WorkProcessNo','1');        
            Test.setCurrentPage(PageRef);
            
            test.startTest();
            
            ApexPages.StandardController sc = new ApexPages.StandardController(MCRFSU);                         
            MCRFSUChart Chart = new MCRFSUChart(sc); 
            
            test.stopTest();
        }
    }
}