force-app/main/default/objects/ICR_Approval__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>วันสิ้นสุ</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>วันเริ่มต้น</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Submit</fullName>
                    <default>true</default>
                    <label>Not Submit</label>
                </value>
                <value>
                    <fullName>Waiting Requester Revise</fullName>
                </value>
                <value>
                    <fullName>Waiting Line Manager Approval</fullName>
                </value>
                <value>
                    <fullName>Waiting Submit Approval Type</fullName>
                </value>
                <value>
                    <fullName>Waiting GSCS Approval</fullName>
                </value>
                <value>
                    <fullName>Waiting Requester Update Result</fullName>
                </value>
                <value>
                    <fullName>Waiting EVP Approval</fullName>
                </value>
                <value>
                    <fullName>Waiting Circular No.</fullName>
                </value>
                <value>
                    <fullName>Waiting Signed Circular File</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>Appointed</fullName>
                </value>
                <value>
                    <fullName>Disappointed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ICR Approval</label>
    <nameField>
        <displayFormat>{YYYY}-{000}</displayFormat>
        <label>Document No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ICR_ActiveICRController.cls
/* 
 * Author Softever
 
    ICR_ActiveICRBatchable AutoActiveICR = new ICR_ActiveICRBatchable();
    string cronExp1 = '0 0 12 1 * ? *';  0 45 21 19 1 ? *
    system.schedule('Auto Acitve ICR', cronExp1, AutoActiveICR);
	
	Run on every day
	For Test '0 0 8 * * ? *'
*/
global class ICR_ActiveICRController implements Database.Batchable<sObject>, Database.AllowsCallouts {

    public boolean isActive = false;
    public string status = 'Appointed';
    public date todayDate = date.today();
    public String query = 'select id, name, status__c, start_date__c, end_date__c, active__c from ICR_Approval__c where status__c =: status' ;
    
	global Database.QueryLocator start(Database.BatchableContext BC) {
       return Database.getQueryLocator(query);
    }    
    
    global void execute(Database.BatchableContext BC, List<ICR_Approval__c> ICRApprovals) {
        
        //Auto Active ICR when reach Start Date
        if(ICRApprovals.size() > 0) {
            for(ICR_Approval__c ICR : ICRApprovals) {
                if(ICR.Active__c == isActive && ICR.Start_Date__c == todayDate) {
                    ICR_ChangeStatusController.activeCommittee(ICR.Id);
                }
            }
        }

    }
    
    global void finish(Database.BatchableContext BC){    
    }
}