force-app/main/default/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Damage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Damage</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Notification</label>
        <referenceTo>Notification__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object_Part_Code_Group_Text__c</fullName>
        <label>Object Part Code Group Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Part_Code_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Object Part Code Group</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Items (Object Part Code Group)</relationshipLabel>
        <relationshipName>Items3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object_Part_Code_Text__c</fullName>
        <label>Object Part Code Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Object Part</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Items (Object Part)</relationshipLabel>
        <relationshipName>Items2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Controls whether the Item has been marked as deleted or not. This is because Items cannot be hard deleted in the application.</description>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <label>Item</label>
    <nameField>
        <displayFormat>I-{0000000}</displayFormat>
        <label>Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Map__c.object
<CustomObject>
    <label>Master Map</label>
    <nameField>
        <label>Master Map Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification_Status__c</fullName>
        <label>Notification Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                    <isActive>false</isActive>
                    <label>In Execution</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Order does not integration with SAP System</errorMessage>
            <filterItems>
                <field>Order__c.Order_Number__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>mainWorkCenterPlant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>mainWorkCenterPlant</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Notification (mainWorkCenterPlant)</relationshipLabel>
        <relationshipName>Notification</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_File__c.object
<CustomObject>
    <fields>
        <fullName>File_Id__c</fullName>
        <label>File Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Notification</label>
        <referenceTo>Notification__c</referenceTo>
        <relationshipLabel>Notification File</relationshipLabel>
        <relationshipName>Notification_File</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_File_Id__c</fullName>
        <externalId>true</externalId>
        <label>SAP File Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Notification File</label>
    <nameField>
        <displayFormat>NF-{0000}</displayFormat>
        <label>Notification File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Notification</label>
        <referenceTo>Notification__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Super_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Super Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Sub Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/THOR_NotificationsListRelatedController.cls
/**
 * @author Oktana
 * @description Queries all related Notification Object
 */
public without sharing class THOR_NotificationsListRelatedController {
	/**
	 * @description retrieves all Items, Orders and Files that are related to a specific Notification
	 * @return The Notification plus related Items, Orders and Files from the database
	 * @param notificationIdentifier is the Id of the Notification
	 */
	@AuraEnabled
	public static THOR_NotificationListRelatedDTO getRelatedObjects(String notificationIdentifier) {
		try {
			THOR_NotificationListRelatedDTO dto = new THOR_NotificationListRelatedDTO();

			Notification__c n = [
				SELECT
					Id,
					Order__c,
					Integration_Status__c,
					Notification_Status__c,
					(
						SELECT
							Id,
							Name,
							CreatedDate,
							Start_Date__c,
							End_Date__c,
							Notification__r.Id,
							Object_part__r.Name,
							Object_Part_Code_Group__r.Name,
							Object_Part_Code_Group__r.Description__c,
							Object_Part_Code_Group_Text__c,
							Object_Part_Code_Text__c,
							Integration_Status__c
						FROM Items__r
						WHERE isDeleted__c = FALSE
					),
					(
						SELECT Integration_Status__c, File_Id__c, LastModifiedDate
						FROM Notification_File__r
						ORDER BY CreatedDate DESC
					)
				FROM Notification__c
				WHERE Id = :notificationIdentifier
				WITH SECURITY_ENFORCED
				LIMIT 1
			];

			dto.orderId = n.Order__c;
			dto.relatedItems = THOR_DTOMapper.mapItems(n.Items__r);
			dto.relatedSubOrders = [
				SELECT Id, Name
				FROM Order__c
				WHERE Super_Order__c = :n.Order__c AND Super_Order__c != NULL
				WITH SECURITY_ENFORCED
			];

			List<ContentDocumentLink> documents = getFilesRelatedToNotification(notificationIdentifier);
			dto.files = wrapDocuments(documents);
			dto.notification_files = n.Notification_File__r;
			dto.hasEditAccess = [
				SELECT RecordId, HasEditAccess
				FROM UserRecordAccess
				WHERE RecordId = :notificationIdentifier AND UserId = :UserInfo.getUserId()
			]
			?.HasEditAccess;
			dto.notificationObj = n;
			return dto;
		} catch (Exception e) {
			System.debug(
				System.LoggingLevel.ERROR,
				String.format('{0}\r\n{1}', new List<String>{ e.getMessage(), e.getStackTraceString() })
			);
			throw new AuraHandledException(
				String.format('{0}\r\n{1}', new List<String>{ e.getMessage(), e.getStackTraceString() })
			);
		}
	}

	/**
	 * @description delete a file
	 * @param fileId file identifier to delete
	 */
	@AuraEnabled
	public static void deleteFile(String fileId) {
		try {
			if (Schema.sObjectType.ContentDocument.isDeletable()) {
				// delete [SELECT Id FROM ContentDocument WHERE Id = :fileId];
				Map<Id, Notification_File__c> documentsMap = new Map<Id, Notification_File__c>(
					ContentDocumentHandler.getNotificationFilesByFileId(new Set<Id>{ fileId })
				);

				if (String.isNotEmpty(documentsMap.values().get(0)?.SAP_File_Id__c)) {
					THOR_iRPAIntegration_NotificationFile.sendNotificationFilesToSAP(documentsMap.values(), 'Deleted');
				} else {
					delete [SELECT Id FROM ContentDocument WHERE Id = :fileId];
				}
			} else {
				throw new AuraHandledException('Not sufficient permissions');
			}
		} catch (Exception ex) {
			throw new AuraHandledException(ex.getMessage());
		}
	}

	/**
	 * @description retrieves all files related to a notification
	 * @param notificationId
	 */
	private static List<ContentDocumentLink> getFilesRelatedToNotification(Id notificationId) {
		return [
			SELECT
				ContentDocumentId,
				ContentDocument.Title,
				ContentDocument.FileType,
				ContentDocument.ContentSize,
				ContentDocument.CreatedDate
			FROM ContentDocumentLink
			WHERE LinkedEntityId = :notificationId AND LinkedEntity.Type = 'Notification__c'
			ORDER BY ContentDocument.CreatedDate DESC
		];
	}

	/**
	 * @description wraps a list of documents to add sequential number to each document
	 * @param documents
	 */
	private static List<DocumentWrapper> wrapDocuments(List<ContentDocumentLink> documents) {
		List<DocumentWrapper> wrappedDocuments = new List<DocumentWrapper>();

		Integer sequentialNumber = 1;
		for (ContentDocumentLink document : documents) {
			wrappedDocuments.add(new DocumentWrapper(getSequentialNumber(sequentialNumber), document));

			sequentialNumber++;
		}

		return wrappedDocuments;
	}

	/**
	 * @description builds a left padded string from a number
	 * @param sequentialNumber
	 */
	private static String getSequentialNumber(Integer sequentialNumber) {
		return String.valueOf(sequentialNumber).leftPad(3, '0');
	}

	@AuraEnabled
	public static void resendIntegrationNotificationFile(String fileId, String flag) {
		try {
			Map<Id, Notification_File__c> notiFiles = new Map<Id, Notification_File__c>(
				ContentDocumentHandler.getNotificationFilesByFileId(new Set<Id>{ fileId })
			);
			update notiFiles.values();

			THOR_iRPAIntegration_NotificationFile.sendNotificationFilesToSAP(notiFiles.values(), flag);
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}
}