force-app/main/default/objects/Master_Map__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Map_Set__c</fullName>
        <label>Master Map Set</label>
        <referenceTo>Master_Map_Set__c</referenceTo>
        <relationshipLabel>Master Maps</relationshipLabel>
        <relationshipName>Master_Maps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Master Map Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Map_Set__c.object
<CustomObject>
    <label>Master Map Set</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Master Map Set Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>AssignedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center_Text__c</fullName>
        <label>Main Work Center Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Work Center</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notification_Status__c</fullName>
        <label>Notification Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                    <isActive>false</isActive>
                    <label>In Execution</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Order does not integration with SAP System</errorMessage>
            <filterItems>
                <field>Order__c.Order_Number__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CM</fullName>
                    <default>true</default>
                    <label>CM</label>
                </value>
                <value>
                    <fullName>PM</fullName>
                </value>
                <value>
                    <fullName>SH</fullName>
                </value>
                <value>
                    <fullName>OP</fullName>
                </value>
                <value>
                    <fullName>CR</fullName>
                </value>
                <value>
                    <fullName>FN</fullName>
                </value>
                <value>
                    <fullName>PJ</fullName>
                    <isActive>false</isActive>
                    <label>PJ</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center_Text__c</fullName>
        <label>Main Work Center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Work Center</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Orders (Main Work Center)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Notification</label>
        <referenceTo>Notification__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NotificationProcessTest.cls
/**
 * @author Oktana
 * @description test class for PB 'Notification_Process'
 */
@isTest
public class NotificationProcessTest {
    /**
     * @given PB Notification_Process
     * @when a Notification is updated and assigned to another User
     * @then the User becomes the Notification's Owner
     */
    @IsTest
    private static void testUpdateOwnerAfterReassigningNotification() {
        User testUser = createUser();
        Notification__c notification = buildNotification();
        insert notification;
        Test.startTest();
        System.runAs(testUser) {
            notification.AssignedTo__c = testUser.Id;
            update notification;
        }
        Test.stopTest();

        Notification__c updatedNotification = getNotification();
        System.assertEquals(
            updatedNotification.OwnerId,
            testUser.Id,
            'Notification Owner should have been updated to the User it was assigned to'
        );
    }

    /**
     * @given PB Notification_Process
     * @when a Notification is updated and not reassigned
     * @then Notification's Owner is not updated
     */
    @IsTest
    private static void testOwnerNotUpdateWhenNotReassigningNotification() {
        User testUser = createUser();
        Notification__c notification = buildNotification();
        insert notification;
        Test.startTest();
        System.runAs(testUser) {
            notification.Description__c = 'Another description';
            update notification;
        }
        Test.stopTest();

        Notification__c updatedNotification = getNotification();
        System.assertEquals(
            UserInfo.getUserId(),
            updatedNotification.OwnerId,
            'Notification Owner should not have been updated'
        );
    }

    /**
     * @given PB Notification_Process
     * @when a Notification is created
     * @then Notification's Main Work Center Text is updated
     */
    @IsTest
    private static void testMWCTextNameUpdateWhenCreatingNotification() {
        Master_Map_Set__c masterMapSet = new Master_Map_Set__c();
        insert masterMapSet;

        Master_Map__c masterMapMWC = new Master_Map__c(
            Name = 'ENMA-E',
            Code__c = 'ENMA-E',
            Type__c = 'Main Work Center',
            Master_Map_Set__c = masterMapSet.Id
        );
        insert masterMapMWC;

        Notification__c notification = buildNotification();

        notification.Main_Work_Center__c = masterMapMWC.Id;

        Test.startTest();
        insert notification;
        Test.stopTest();

        Notification__c updatedNotification = getNotification();

        System.assertEquals(
            masterMapMWC.Name,
            updatedNotification.Main_Work_Center_Text__c,
            'Main Work Center Name was not updated'
        );
    }

    /**
     * @given PB Notification_Process
     * @when a Notification is updated
     * @then Notification's Main Work Center Text is updated
     */
    @IsTest
    private static void testMWCTextNameUpdateWhenUpdatingNotification() {
        Master_Map_Set__c masterMapSet = new Master_Map_Set__c();
        insert masterMapSet;

        Master_Map__c masterMapMWC = new Master_Map__c(
            Name = 'ENMA-E',
            Code__c = 'ENMA-E',
            Type__c = 'Main Work Center',
            Master_Map_Set__c = masterMapSet.Id
        );
        insert masterMapMWC;

        Notification__c notification = buildNotification();

        insert notification;

        notification.Main_Work_Center__c = masterMapMWC.Id;

        Test.startTest();
        update notification;
        Test.stopTest();

        Notification__c updatedNotification = getNotification();

        System.assertEquals(
            masterMapMWC.Name,
            updatedNotification.Main_Work_Center_Text__c,
            'Main Work Center Name was not updated'
        );
    }

    private static Notification__c getNotification() {
        return [
            SELECT
                Id,
                OwnerId,
                AssignedTo__c,
                Notification_Status__c,
                Main_Work_Center_Text__c,
                Main_Work_Center__r.Name
            FROM Notification__c
            LIMIT 1
        ];
    }

    private static Notification__c buildNotification() {
        Notification__c notification = new Notification__c(
            Name = 'Test Notification',
            Description__c = 'Test Description',
            AssignedTo__c = UserInfo.getUserId()
        );

        return notification;
    }

    private static Notification__c buildNewNotificationWithOutUser() {
        Notification__c notification = new Notification__c(
            Name = 'Test Notification',
            Description__c = 'Test Description',
            Notification_Status__c = 'New'
        );

        return notification;
    }

    private static User createUser() {
        //using System Administrator Profile since this is the only one available
        //works with any profile with permissions to access Notification__c and Order__c
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueOf(Datetime.now()).replace(' ', '').replace(':', '').replace('-', '');
        Integer randomInt = Integer.valueOf(Math.rint(Math.random() * 1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(
            FirstName = 'test',
            LastName = 'user',
            Email = uniqueName + '@test' + orgId + '.org',
            Username = uniqueName + '@test' + orgId + '.org',
            EmailEncodingKey = 'ISO-8859-1',
            Alias = uniqueName.substring(18, 23),
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator']
            .Id
        );
        insert tuser;
        return tuser;
    }

    /**
     * @given PB Notification_Process
     * @when a Notification is updated and assigned to another User
     * @then the Status becomes In Progress
     */
    @IsTest
    private static void testUpdateStatusAfterReassigningNotification() {
        User testUser = createUser();
        Notification__c notification = buildNewNotificationWithOutUser();
        insert notification;
        Test.startTest();
        System.runAs(testUser) {
            notification.AssignedTo__c = testUser.Id;
            update notification;
        }
        Test.stopTest();

        Notification__c updatedNotification = getNotification();
        System.assertEquals(
            updatedNotification.Notification_Status__c,
            'In Progress',
            'Notification Status should have been updated to In Progress'
        );
    }
}