force-app/main/default/objects/Master_Map__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedMasterMap1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedMasterMap1</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Master Maps</relationshipLabel>
        <relationshipName>Master_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedMasterMap2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RelatedMasterMap2</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Master Maps (RelatedMasterMap2)</relationshipLabel>
        <relationshipName>Master_Maps2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_Number__c</fullName>
        <label>Status Number</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Master Map Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/THOR_SetUserStatusController.cls
/**
 * @author Oktana
 * @description controller for THOR_SetUserStatus Component
 */
public with sharing class THOR_SetUserStatusController {
    /**
     * @description retrieves availabel user status for notifications
     * @return List<UserStatusDTO>
     */
    @AuraEnabled
    public static List<UserStatusDTO> retrieveUserStatusForNotification(String notificationType) {
        List<UserStatusDTO> res = new List<UserStatusDTO>();

        Master_Map__c mmTemp = null;

        List<Master_Map__c> masterMapListTemp = [
            SELECT Id, RelatedMasterMap2__r.Name
            FROM Master_Map__c
            WHERE Type__c = 'NotificationTypewithStatusProfile' AND RelatedMasterMap1__r.Name = :notificationType
            LIMIT 1
        ];

        if (masterMapListTemp.size() > 0) {
            mmTemp = masterMapListTemp[0];

            masterMapListTemp = [
                SELECT
                    Id,
                    RelatedMasterMap2__r.Name,
                    RelatedMasterMap2__r.Description__c,
                    RelatedMasterMap2__r.Type__c
                FROM Master_Map__c
                WHERE
                    Type__c = 'NotificationStatusProfileWithUserStatus'
                    AND RelatedMasterMap1__r.Name = :mmTemp.RelatedMasterMap2__r.Name
            ];

            for (Master_Map__c mm : masterMapListTemp) {
                if (mm.RelatedMasterMap2__r.Type__c.equals('NotificationUserStatus')) {
                    UserStatusDTO userStatusDTO = new UserStatusDTO();
                    userStatusDTO.name = mm.RelatedMasterMap2__r.Name;
                    userStatusDTO.description = mm.RelatedMasterMap2__r.Description__c;

                    res.add(userStatusDTO);
                }
            }
        }

        return res;
    }

    /**
     * @description retrieves availabel user status for orders
     * @return List<UserStatusDTO>
     */
    @AuraEnabled
    public static List<UserStatusDTO> retrieveUserStatusForOrder(String orderType) {
        List<UserStatusDTO> res = new List<UserStatusDTO>();

        Master_Map__c mmTemp = null;

        List<Master_Map__c> masterMapListTemp = [
            SELECT Id, RelatedMasterMap2__r.Name
            FROM Master_Map__c
            WHERE Type__c = 'OrderTypewithStatusProfile' AND RelatedMasterMap1__r.Name = :orderType
            LIMIT 1
        ];

        System.debug('masterMapListTemp1');
        System.debug(masterMapListTemp);

        if (masterMapListTemp.size() > 0) {
            mmTemp = masterMapListTemp[0];

            masterMapListTemp = [
                SELECT Id, RelatedMasterMap2__r.Name, RelatedMasterMap2__r.Description__c, RelatedMasterMap2__r.Type__c
                FROM Master_Map__c
                WHERE
                    Type__c = 'OrderStatusProfileWithUserStatus'
                    AND RelatedMasterMap1__r.Name = :mmTemp.RelatedMasterMap2__r.Name
                    AND Status_Number__c = ''
            ];

            System.debug('masterMapListTemp2');
            System.debug(masterMapListTemp);

            for (Master_Map__c mm : masterMapListTemp) {
                System.debug('mm');
                System.debug(mm);
                if (mm.RelatedMasterMap2__r.Type__c.equals('OrderUserStatus')) {
                    UserStatusDTO userStatusDTO = new UserStatusDTO();
                    userStatusDTO.name = mm.RelatedMasterMap2__r.Name;
                    userStatusDTO.description = mm.RelatedMasterMap2__r.Description__c;

                    res.add(userStatusDTO);
                }
            }
        }
        return res;
    }

    /**
     * @author Oktana
     * @description user status name and description DTO
     */
    public class UserStatusDTO {
        @AuraEnabled
        public String name { get; set; }

        @AuraEnabled
        public String description { get; set; }
    }
}