force-app/main/default/objects/Master_Data__c.object
<CustomObject>
    <label>Master Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Data_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Master_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Data</label>
        <referenceTo>Master_Data__c</referenceTo>
        <relationshipLabel>Master Data Detail</relationshipLabel>
        <relationshipName>Master_Data_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SME</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected user is not SME user. Please select SME user.</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>PM</value>
            </filterItems>
            <infoMessage>Please select SME user.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Master_Data_Detail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Process_Group__c</fullName>
        <label>Work Process Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Group</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Process_No__c</fullName>
        <label>Work Process No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Master Data Detail</label>
    <nameField>
        <label>Work Process Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Please select only PM user.</errorMessage>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>TOPPMP-AI</value>
            </filterItems>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>CPEM Admin</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Project</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Number__c</fullName>
        <label>Project Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Execution_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Project_Execution_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SME</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected User is not SME. Please select SME user.</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>PM</value>
            </filterItems>
            <infoMessage>Please select SME user.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Step_4_Project_Execution_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Process_Status__c</fullName>
        <label>Work Process Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Work_Process_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Step 4:Project Execution Plan and Permit</label>
    <nameField>
        <displayFormat>WP4-{00000}</displayFormat>
        <label>Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Procurement_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Project_Procurement_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SME__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SME</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected User is not SME. Please select SME user.</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>PM</value>
            </filterItems>
            <infoMessage>Please select SME user.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Step 5: Project Procurement Plan</relationshipLabel>
        <relationshipName>Step_5_Project_Procurement_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Process_Status__c</fullName>
        <label>Work Process Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Work_Process_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Step 5 : Project Procurement Plan</label>
    <nameField>
        <displayFormat>WP5-{00000}</displayFormat>
        <label>Process ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Group.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Project Scope and Information</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Project Cost Control</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Project Schedule Control</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Procurement Status Report</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Document Management</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Engineering</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Material Control</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Execution</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Project Handover</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Risk Analyst</label>
    </customValue>
    <masterLabel>Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Work_Process_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Not Start</fullName>
        <default>true</default>
        <label>Not Start</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting for Previous Step</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Work Process Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TC_WP4Controller.cls
/* Test class for WorkProcess 4 */
@isTest
public class TC_WP4Controller {

    public static void MasterDataInfo() {
        //Master Data
        User SMEUser = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'SME'].Id,
            UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI AD&SME'].Id,
            LastName = 'last',
            Email = 'test@thaioilgroup.com',
            Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
            CompanyName = 'Thaioil',
            Alias = 'test',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
            );
        insert(SMEUser);
        
        System.runAs(SMEUser) {
            Master_Data__c MD = new Master_Data__c();
            MD.Name = 'SME and Guideline';
            insert(MD);
            
            List<Master_Data_Detail__c> MDDs = new List<Master_Data_Detail__c>();
            
            Master_Data_Detail__c MDD1 = new Master_Data_Detail__c();
            MDD1.Work_Process_No__c = 1;
            MDD1.Group__c = 10;
            MDD1.Name = 'Project Charter';
            MDD1.Work_Process_Group__c = '1';
            MDD1.Master_Data__c = MD.Id;
            MDD1.SME__c = SMEUser.Id;
            MDDs.add(MDD1);
            
            Master_Data_Detail__c MDD4 = new Master_Data_Detail__c();
            MDD4.Work_Process_No__c = 4;
            MDD4.Group__c = 10;
            MDD4.Name = 'Project Execution';
            MDD4.Work_Process_Group__c = '1';
            MDD4.Master_Data__c = MD.Id;
            MDD4.SME__c = SMEUser.Id;
            MDDs.add(MDD4);
            
            Master_Data_Detail__c MDD5 = new Master_Data_Detail__c();
            MDD5.Work_Process_No__c = 5;
            MDD5.Group__c = 10;
            MDD5.Name = 'Project Procurement Plan';
            MDD5.Work_Process_Group__c = '1';
            MDD5.Master_Data__c = MD.Id;
            MDD5.SME__c = SMEUser.Id;
            MDDs.add(MDD5);
            
            Master_Data_Detail__c MDD10 = new Master_Data_Detail__c();
            MDD10.Work_Process_No__c = 10;
            MDD10.Group__c = 10;
            MDD10.Name = 'ITB Standard';
            MDD10.Work_Process_Group__c = '1';
            MDD10.Master_Data__c = MD.Id;
            MDD10.SME__c = SMEUser.Id;
            MDDs.add(MDD10);
            
            Master_Data_Detail__c MDD11 = new Master_Data_Detail__c();
            MDD11.Work_Process_No__c = 11;
            MDD11.Group__c = 10;
            MDD11.Name = 'CCE Approval Process';
            MDD11.Work_Process_Group__c = '1';
            MDD11.Master_Data__c = MD.Id;
            MDD11.SME__c = SMEUser.Id;
            MDDs.add(MDD11);
            
            insert(MDDs);
        }
    }
    
    public static TestMethod void WP4Controller() {
        
        MasterDataInfo();
        
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'PM'].Id,
        UserRoleId = [select id From UserRole where Name = 'TOPPMP-AI PM'].Id,
        LastName = 'last',
        Email = 'test@thaioilgroup.com',
        Username = 'test@thaioilgroup.com' + System.currentTimeMillis(),
        CompanyName = 'Thaioil',
        Alias = 'test',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US'
    	);
        insert(u);
        
        System.runAs(u) {
            
            Project__c Proj = new Project__c();
            Proj.Name = 'Test Project';
            Proj.Project_Number__c = 'Test WP4';
            Proj.Project_Manager__c = u.Id;
            insert(Proj);
            
            List<Id> ProjIds = new List<Id>();
            ProjIds.add(Proj.Id);
            
            string completedStatus = 'Completed';
            string waitingStatus = 'Waiting for Previous Step';
            
            Project_Execution_Plan__c currentWP = [select id, Project__c, Work_Process_Status__c from Project_Execution_Plan__c where Project__c =: Proj.Id];
            currentWP.Work_Process_Status__c = completedStatus;
            update(currentWP);
            
            Project_Procurement_Plan__c previousWP = [select id, Project__c, Work_Process_Status__c from Project_Procurement_Plan__c where Project__c =: Proj.Id];
            previousWP.Work_Process_Status__c = waitingStatus;
            update(previousWP);
            
        	WP4Controller.UpdateWorkProcess5FromWaitingForPreviousStep(ProjIds);
        }
    }
    
}