force-app/main/default/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_File__c.object
<CustomObject>
    <fields>
        <fullName>File_Id__c</fullName>
        <label>File Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification_Number_Formular__c</fullName>
        <formula>IF(NOT(ISBLANK(Notification__r.Notification_Number__c)), Notification__r.Notification_Number__c, Notification__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Notification Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Notification</label>
        <referenceTo>Notification__c</referenceTo>
        <relationshipLabel>Notification File</relationshipLabel>
        <relationshipName>Notification_File</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_File_Id__c</fullName>
        <externalId>true</externalId>
        <label>SAP File Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Url_Link__c</fullName>
        <formula>LEFT($Api.Partner_Server_URL_530, FIND( &apos;/services&apos;, $Api.Partner_Server_URL_530)) + File_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Url Link</label>
        <type>Text</type>
    </fields>
    <label>Notification File</label>
    <nameField>
        <displayFormat>NF-{0000}</displayFormat>
        <label>Notification File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContentDocumentHandler.cls
/**
 * @author Oktana
 */
public with sharing class ContentDocumentHandler {
	public static void handleNotificationFilesRenamed(Map<Id, sObject> newItems, Map<Id, sObject> oldItems) {
		// Map<Id, ContentDocument> renamedDocumentsById = new Map<Id, ContentDocument>();

		// for (ContentDocument newDocument : (List<ContentDocument>) newItems.values()) {
		// 	ContentDocument oldDocument = (ContentDocument) oldItems.get(newDocument.Id);

		// 	if (isDocumentRenamed(newDocument, oldDocument)) {
		// 		renamedDocumentsById.put(newDocument.Id, newDocument);
		// 	}
		// }

		if (newItems.size() > 0) {
			List<Notification_File__c> nFilesToUpdate = new List<Notification_File__c>();

			for (Notification_File__c nFile : getNotificationFilesByFileId(newItems.keySet())) {
				ContentDocument contentDocument = (ContentDocument) newItems.get(nFile.File_Id__c);
				if (nFile.File_Name__c != contentDocument.Title) {
					nFile.File_Name__c = contentDocument.Title;

					nFilesToUpdate.add(nFile);
				}
			}

			if (Schema.SObjectType.Notification_File__c.isUpdateable() && nFilesToUpdate.size() > 0) {
				update nFilesToUpdate;
			}
		}
	}

	public static void handleNotificationFilesDeleted(Map<Id, sObject> oldDocuments) {
		List<Notification_File__c> nFilesToDelete = getNotificationFilesByFileId(oldDocuments.keySet());

		if (Schema.SObjectType.Notification_File__c.isDeletable()) {
			delete nFilesToDelete;
			// THOR_iRPAIntegration_NotificationFile.sendNotificationFilesToSAP(nFilesToDelete, 'Deleted');
		}
	}

	// private static Boolean isDocumentRenamed(ContentDocument newDocument, ContentDocument oldDocument) {
	// 	return newDocument.Title != oldDocument.Title;
	// }

	public static List<Notification_File__c> getNotificationFilesByFileId(Set<Id> documentIds) {
		return [
			SELECT
				Id,
				File_Name__c,
				File_Id__c,
				Url_Link__c,
				Integration_Status__c,
				Notification__c,
				SAP_File_Id__c,
				Notification_Number_Formular__c
			FROM Notification_File__c
			WHERE File_Id__c IN :documentIds
		];
			// WITH SECURITY_ENFORCED
	}
}