force-app/main/default/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Application__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>People Connect</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Finance and Accounting</fullName>
                </value>
                <value>
                    <fullName>Strategy</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>SSHE</fullName>
                </value>
                <value>
                    <fullName>Procurement &amp; Contract</fullName>
                </value>
                <value>
                    <fullName>Operation</fullName>
                </value>
                <value>
                    <fullName>Governance and Compliance</fullName>
                </value>
                <value>
                    <fullName>Notification</fullName>
                    <isActive>false</isActive>
                    <label>Notification</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <label>Icon</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>URL_Android__c</fullName>
        <label>URL Android</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_IOS__c</fullName>
        <label>URL IOS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_Web__c</fullName>
        <label>URL Web</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Favorite_Application__c.object
<CustomObject>
    <fields>
        <fullName>No__c</fullName>
        <label>No</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OPP_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OPP Application</label>
        <referenceTo>OPP_Application__c</referenceTo>
        <relationshipLabel>OPP Favorite Application</relationshipLabel>
        <relationshipName>OPP_Favorite_Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OPP_Favorite_Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Favorite Applications</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>OPP Favorite Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Notification__c.object
<CustomObject>
    <fields>
        <fullName>ApplicationName__c</fullName>
        <label>ApplicationName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>OPP_Application__c</referenceTo>
        <relationshipLabel>OPP Notification</relationshipLabel>
        <relationshipName>OPP_Notification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReferenceID__c</fullName>
        <label>ReferenceID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OPP_Notification</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Top Space Notifications</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Notification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OPP_ApplicationController.cls
public class OPP_ApplicationController {

    @AuraEnabled
    public static List<String> getCategoryPicklistValuesIntoList() {
        List<String> categoryPicklistValueList = new List<String>();
        Schema.DescribeFieldResult fieldResult = OPP_Application__c.Category__c.getDescribe();
        List<Schema.PicklistEntry> picklistEntryList = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry picklistEntry : picklistEntryList) {
            categoryPicklistValueList.add(picklistEntry.getLabel());
        }
        return categoryPicklistValueList;
    }
    
    @AuraEnabled
    public static List<OPP_Application__c> getActiveApplications() {
        return [SELECT Id,Name,Icon__c,Description__c,Category__c,URL_Web__c,URL_Android__c,URL_IOS__c,Default__c,(SELECT ContentDocumentId,SystemModstamp FROM ContentDocumentLinks ORDER BY SystemModstamp DESC),
                (SELECT Id,OPP_Application__c FROM OPP_Favorite_Application__r WHERE User__c =:UserInfo.getUserId()) FROM OPP_Application__c WHERE Is_Deleted__c = false ORDER BY Name	];
    }
    
    @AuraEnabled
    public static List<OPP_Application__c> getActiveApplicationInCategory(String category) {
        return [SELECT Id,Name,Icon__c,Description__c,Category__c FROM OPP_Application__c WHERE Category__c = :category AND Is_Deleted__c = false ORDER BY Name];
    }

    @AuraEnabled
    public static List<OPP_Application__c> getNotificationApplications() {
        return [ SELECT Id,Name,Icon__c,Description__c,Category__c,URL_Web__c,(SELECT Id,OPP_Application__c FROM OPP_Favorite_Application__r WHERE User__c =: UserInfo.getUserId()) FROM OPP_Application__c WHERE Is_Deleted__c = false AND Notification__c = true];
    }
    
    @AuraEnabled
    public static List<OPP_Application__c> getOtherApplications() {
        return [SELECT Id,Name,Icon__c,Description__c,Category__c,URL_Web__c,(SELECT Id, OPP_Application__c FROM OPP_Favorite_Application__r WHERE User__c =: UserInfo.getUserId()) FROM OPP_Application__c WHERE Is_Deleted__c = false AND Category__c = null];
    }

    @AuraEnabled
    public static List<OPP_Notification__c> getListofNotifications(String AppId)
    {
        List<OPP_Notification__c> Notifications=([Select ApplicationName__c,Application__c,Subject__c,Description__c,URL__c,ReferenceID__c,CreatedDate from OPP_Notification__c where Application__c=:AppId AND User__c =:UserInfo.getUserId()]);    
        return Notifications;
    }
    
    @AuraEnabled
    public static AggregateResult[] countNotificationGroupByApplication() {
        Id userId = UserInfo.getUserId();
    	AggregateResult[] aggregateResults = [SELECT Application__c, COUNT(Id) Count__c FROM OPP_Notification__c WHERE User__c =:userId GROUP BY Application__c];
        return aggregateResults;
    }

    @AuraEnabled
    public static List<OPP_Application__c> getApplications(){
        try {
            List<OPP_Application__c> applications = [SELECT Id, Name, Icon__c, URL_Web__c, Category__c,URL_Android__c, URL_IOS__c, (SELECT ContentDocumentId FROM ContentDocumentLinks ORDER BY SystemModstamp DESC LIMIT 1),
                                                     (SELECT Id, OPP_Application__c FROM OPP_Favorite_Application__r WHERE User__c =: UserInfo.getUserId()) FROM OPP_Application__c];
            return applications;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Integer getCountApplications(){
        try {
            Integer count =[SELECT COUNT() FROM OPP_Favorite_Application__c WHERE User__c =: UserInfo.getUserId() AND OPP_Application__c != NULL];
            return count;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<OPP_Favorite_Application__c> getDefaultApplications(){
        try {
            List<OPP_Favorite_Application__c> applications =[SELECT Id, OPP_Application__c FROM OPP_Favorite_Application__c WHERE User__c =: UserInfo.getUserId()];
            return applications;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Boolean updateFavApps(String jsonString){
        try {
            Set<Id> setFavAppIds = (Set<Id>)JSON.deserialize(jsonString, Set<Id>.class);
            List<OPP_Favorite_Application__c> oppFavApps = new List<OPP_Favorite_Application__c>();
            Map<String, OPP_Favorite_Application__c> mapOPPFavApps = new Map<String, OPP_Favorite_Application__c>();
            if (setFavAppIds.size() > 0)
            {
                Integer i;
                Integer count = 6 - setFavAppIds.size();
             
                List<OPP_Favorite_Application__c> favApps = [SELECT Id, OPP_Application__c, No__c FROM OPP_Favorite_Application__c WHERE User__c =: UserInfo.getUserId() AND OPP_Application__c NOT IN: setFavAppIds];
                List<OPP_Favorite_Application__c> allFavApps = [SELECT Id, OPP_Application__c, No__c FROM OPP_Favorite_Application__c WHERE User__c =: UserInfo.getUserId()];
                for(OPP_Favorite_Application__c allFavApp : allFavApps) {
                    for(Id setFavAppId : setFavAppIds) {
                        if(allFavApp.OPP_Application__c == setFavAppId) {
                            setFavAppIds.remove(allFavApp.OPP_Application__c);
                        }
                    }
                }
                if(setFavAppIds.size() > 0) {
                    List<Id> favAppIds = new List<Id>(setFavAppIds);
                    for(i=0; i<favAppIds.size(); i++) {
                        OPP_Favorite_Application__c favApp = favApps.get(i);
                        favApp.OPP_Application__c = favAppIds.get(i);
                        oppFavApps.add(favApp);
                    }   
                }
                else {
                    for(i=0; i<count; i++) {
                        OPP_Favorite_Application__c favApp = favApps.get(i);
                        favApp.OPP_Application__c = null;
                        oppFavApps.add(favApp);
                    }
                }
                update oppFavApps;
                return true;
            }
            return false;
       } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}