force-app/main/default/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Functional_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Location</label>
        <referenceTo>Functional_Location__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Work Center</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Notification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Clearance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Clearance</label>
        <referenceTo>Work_Clearance__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Functional_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Location</label>
        <referenceTo>Functional_Location__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Work Center</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Orders (Main Work Center)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Clearance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Clearance</label>
        <referenceTo>Work_Clearance__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PISUsers__c.object
<CustomObject>
    <fields>
        <fullName>EMPLOYEEID__c</fullName>
        <externalId>true</externalId>
        <label>EMPLOYEEID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PISUsers</label>
    <nameField>
        <label>UserID</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PTW_Header__c.object
<CustomObject>
    <fields>
        <fullName>Main_Work_Center__c</fullName>
        <formula>Auditor_Name__r.User__r.Main_Work_Center__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Main Work Center</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Agree</fullName>
                </value>
                <value>
                    <fullName>Disagree</fullName>
                </value>
                <value>
                    <fullName>ดำเนินการได้</fullName>
                </value>
                <value>
                    <fullName>หยุดงานชั่วคราว</fullName>
                </value>
                <value>
                    <fullName>หยุดงานถาวร</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Clearance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Clearance</label>
        <referenceTo>Work_Clearance__c</referenceTo>
        <relationshipLabel>PTW Header</relationshipLabel>
        <relationshipName>PTW_Header</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PTW Header</label>
    <nameField>
        <displayFormat>PTWH - {0000}</displayFormat>
        <label>PTW Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <recordTypes>
        <fullName>Inspection</fullName>
        <active>true</active>
        <label>Inspection</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/THOR_Filter__c.object
<CustomObject>
    <fields>
        <fullName>Clearance_Number__c</fullName>
        <label>Clearance Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_Date_From__c</fullName>
        <label>Create Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Create_Date_To__c</fullName>
        <label>Create Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_By__c</fullName>
        <label>Created By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Functional_Location__c</fullName>
        <label>Functional Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center__c</fullName>
        <label>Main Work Center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_Date_Form__c</fullName>
        <label>Requested Date Form</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requested_Date_To__c</fullName>
        <label>Requested Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <label>Requester</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Need Revision</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Clearance_Status__c</fullName>
        <label>Work Clearance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Delete Flag</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>EXTD</fullName>
                    <isActive>false</isActive>
                    <label>EXTD</label>
                </value>
                <value>
                    <fullName>EXTH</fullName>
                    <isActive>false</isActive>
                    <label>EXTH</label>
                </value>
                <value>
                    <fullName>WCCL</fullName>
                    <isActive>false</isActive>
                    <label>WCCL</label>
                </value>
                <value>
                    <fullName>WIP1</fullName>
                    <isActive>false</isActive>
                    <label>WIP1</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>THOR Filter</label>
    <nameField>
        <label>THOR Filter Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Clearance__c.object
<CustomObject>
    <fields>
        <fullName>Authorized_Date_UI__c</fullName>
        <label>Authorized Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Work Center</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>It must be a valid Main Work Center from Master Map</errorMessage>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Main Work Center</value>
            </filterItems>
            <infoMessage>Choose a Main Work Center from Master Map</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Work Clearances</relationshipLabel>
        <relationshipName>Work_Clearances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requester_UI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>PISUsers__c</referenceTo>
        <relationshipLabel>Work Clearance (Requester)</relationshipLabel>
        <relationshipName>Work_Clearance1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <label>Requester</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Clearance_Status__c</fullName>
        <formula>IF(CONTAINS(System_Status__c, &quot;DLFL&quot;), &quot;Delete Flag&quot;,
    IF(CONTAINS(System_Status__c, &quot;REJC&quot;), &quot;Rejected&quot;,
        IF(CONTAINS(System_Status__c, &quot;CLSD&quot;), &quot;Closed&quot;,
            IF(CONTAINS(System_Status__c, &quot;CLSE&quot;), &quot;Closed&quot;,
                IF(CONTAINS(System_Status__c, &quot;INAC&quot;), &quot;Inactive&quot;,
                    IF(CONTAINS(System_Status__c, &quot;INC&quot;), &quot;Inactive&quot;,
                        IF(CONTAINS(System_Status__c, &quot;CRTE&quot;), &quot;Created&quot;,
                            IF(CONTAINS(System_Status__c, &quot;CRET&quot;), &quot;Created&quot;,
                                IF(CONTAINS(System_Status__c, &quot;PREP&quot;), &quot;In Progress&quot;,
                                    IF(CONTAINS(System_Status__c, &quot;CHNG&quot;), &quot;In Progress&quot;, &quot;&quot;)
                                )
                            )
                        )
                    )
                )
            )
        )
    )
)</formula>
        <label>Work Clearance Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Clearance__c</fullName>
        <externalId>true</externalId>
        <label>Work Clearance</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Work Clearance</label>
    <nameField>
        <label>Work Clearance Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ODM_WorkClearanceController.cls
/**
 * @description       :
 * @author            : narathip.s@roundtwosolutions.com
 * @group             :
 * @last modified on  : 06-29-2022
 * @last modified by  : narathip.s@roundtwosolutions.com
 **/
public with sharing class ODM_WorkClearanceController {
    @AuraEnabled
    public static Object getUser() {
        User user = [SELECT Id, Name ,FirstName, LastName, Main_Work_Center__c
                     FROM User WHERE Id =: userInfo.getUserId()];
        return user;
    }

	public static String conditionQuery(String apiField, String operator, String val) {
		if (operator.equalsIgnoreCase('LIKE')) {
			val = String.valueOf(val).replace('*', '%');
			if (!val.contains('%')) {
				val = '%' + val + '%';
			}
		}
		return String.format('{0} {1} {2}', new List<String>{ apiField, operator, '\'' + val + '\'' });
	}

	private static List<String> parseWcFilterObject(Map<String, Object> filter) {
		Map<String, String> filterMapping = new Map<String, String>();
		if (filter.containsKey('Create_Date_From__c')) {
			filterMapping.put(
				'CreatedDate_from',
				'CreatedDate >= ' + String.valueOf(filter.get('Create_Date_From__c') + 'T00:00:00.000+0700')
			);
		}
		if (filter.containsKey('Create_Date_To__c')) {
			filterMapping.put(
				'CreatedDate_to',
				'CreatedDate <= ' + String.valueOf(filter.get('Create_Date_To__c') + 'T23:59:59.000+0700')
			);
		}
		if (filter.containsKey('Requested_Date_Form__c')) {
			filterMapping.put(
				'AuthorizedDate_from',
				'Authorized_Date_UI__c >= ' + String.valueOf(filter.get('Requested_Date_Form__c'))
			);
		}
		if (filter.containsKey('Requested_Date_To__c')) {
			filterMapping.put(
				'AuthorizedDate_to',
				'Authorized_Date_UI__c <= ' + String.valueOf(filter.get('Requested_Date_To__c'))
			);
		}

		/**
		 * @description: Add filter condition for query
		 */
		if (filter.containsKey('Requester__c')) {
			filter.put('Requester_UI__r.EMPLOYEEID__c', filter.get('Requester__c'));
		}
		if (filter.containsKey('Created_By__c')) {
			filter.put('Requester_UI__r.EMPLOYEEID__c', filter.get('Created_By__c'));
		}

		// Thor_filter__c => Work_Clearance__c
		Map<String, String> convertFieldName = new Map<String, String>{
			'Clearance_Number__c' => 'Work_Clearance__c',
			// 'Work_Clearance_Status__c' => 'Work_Clearance_Status__c',
			'Functional_Location__c' => 'FunctionalLocation__r.Name',
			'Notification_Number__c' => 'Notification__r.Name',
			'Notification_Type__c' => 'Notification__r.type__c',
			'Order_Number__c' => 'Order__r.Name',
			'Order_Type__c' => 'Order__r.Order_Type__c',
			// 'Priority__c' => 'Priority__c',
			'Requester__c' => 'Requester_UI__r.EN_Fullname__c',
			// 'Main_Work_Center__c' => 'Main_Work_Center__c',
			// 'Location__c' => 'Location__c'

			// Historical Search
			'Status__c' => 'Work_Clearance_Status__c',
			'Main_Work_Center__c' => 'Main_Work_Center__r.Name',
			'Created_By__c' => 'Requester_UI__r.EN_Fullname__c'
		};

		for (String oldKey : convertFieldName.keySet()) {
			if (filter.containsKey(oldKey)) {
				String newKey = convertFieldName.get(oldKey);
				filter.put(newKey, filter.remove(oldKey));
			}
		}

		Map<String, Schema.SObjectField> sObjectField = Schema.getGlobalDescribe().get('Work_Clearance__c'.toLowerCase()).getDescribe().fields.getMap();
		//System.debug(JSON.serializePretty(sObjectField.get('Priority__c').getDescribe().getPicklistValues()));
		for (String f : filter.keySet()) {
			if (!sObjectField.containsKey(f) && !f.contains('__r')) {
				filter.remove(f);
			}

			if (f?.equalsIgnoreCase('Priority__c')) {
				Schema.DescribeFieldResult dfr = sObjectField.get(f)?.getDescribe();
				List<Schema.PicklistEntry> picklistValueInfo = dfr.getPicklistValues();
				for (Schema.PicklistEntry p : picklistValueInfo) {
					filter.put(f, String.valueOf(filter.get(f))?.replace(p.getLabel(), p.getValue()));
				}
			}

			if (f?.equalsIgnoreCase('Area__c')) {
				filterMapping.put('Area__c', 'Area__c IN (\'' + filter.get(f) + '\')');
				filter.remove(f);
			}

			if (f?.equalsIgnoreCase('Main_Work_Center__r.Name')) {
				Object mainWorkCenter = filter.get(f);
				if (String.valueOf(mainWorkCenter).containsIgnoreCase('OPS-')) {
					filterMapping.put('OPSMainWorkCenter__c', 'OPSMainWorkCenter__c LIKE \'%' + String.valueOf(mainWorkCenter).trim() + '%\'');
					filter.remove(f);
				} else {
					filterMapping.put('Main_Work_Center__r.Name', 'Main_Work_Center__r.Name IN (\'' + String.valueOf(mainWorkCenter).trim() + '\')');
					filter.remove(f);
				}
			}
		}

		for (String apiField : filter.keySet()) {
			Object value = filter.get(apiField);

			Schema.DisplayType fieldType = sObjectField.get(apiField)?.getDescribe()?.getType();
			if (String.valueOf(value)?.contains(';')) {
				List<String> tempVal = new List<String>();
				for (String f : String.valueOf(value).split(';')) {
					tempVal.add(String.format('{0}', new List<String>{ '\'' + f + '\'' }));
				}
				filterMapping.put(apiField,String.format('{0} IN ({1})', new List<String>{ apiField, String.join(tempVal, ',') }));
			} else if (fieldType === Schema.DisplayType.BOOLEAN) {
				filterMapping.put(apiField,String.format('{0} {1} {2}', new List<Object>{ apiField, '=', Boolean.valueOf(value) }));
			} else if (fieldType == Schema.DisplayType.REFERENCE || fieldType == Schema.DisplayType.PICKLIST) {
				filterMapping.put(apiField, conditionQuery(apiField, ' = ', String.valueOf(value)));
			} else if (fieldType == Schema.DisplayType.DATE) {
				filterMapping.put(apiField,String.format('{0} = {1}', new List<String>{ apiField, String.valueOf(value) }));
			} else {
				filterMapping.put(apiField, conditionQuery(apiField, 'LIKE', String.valueOf(value)));
			}
		}

		/**
		 * @description: union condition when are same field
		 *
		 */
		if (
			filterMapping.containsKey('Requester_UI__r.EN_Fullname__c') ||
			filterMapping.containsKey('Requester_UI__r.EMPLOYEEID__c')
		) {
			filterMapping.put(
				'Requester_UI__r',
				String.format(
					'({0} OR {1})',
					new List<String>{
						filterMapping.remove('Requester_UI__r.EN_Fullname__c'),
						filterMapping.remove('Requester_UI__r.EMPLOYEEID__c')
					}
				)
			);
		}
		return filterMapping.values();
	}

	/**
	 * @description
	 * @author narathip.s@roundtwosolutions.com | 05-30-2022
	 * @param filter
	 * @param offset
	 * @param rowlimit
	 * @param isSharingSettings
	 * @return Object
	 **/
	@AuraEnabled
	public static Object getWcList(
		Map<String, String> filter,
		Integer offset,
		Integer rowlimit,
		Boolean isSharingSettings
	) {
		String query;
		try {
			List<String> filterMapping = parseWcFilterObject(filter);

			String condition = '';
			if (isSharingSettings) {
				condition = String.format(
					'WHERE CreatedDate > 2021-01-01T00:00:00.000+0700 AND {0}',
					//'WHERE Authorized_Date_UI__c > 2022-01-01 AND Area__c != null AND {0}',
					new List<String>{
						filterMapping.size() > 0 // condition (optional)
							? String.format('{0}', new List<Object>{ String.join(filterMapping, ' AND ') })
							: ''
					}
				);
			} else {
				condition = String.format(
					'WHERE {0}',
					new List<String>{
						filterMapping.size() > 0 // condition (optional)
							? String.format('{0}', new List<Object>{ String.join(filterMapping, ' AND ') })
							: ''
					}
				);
			}

			condition = condition.trim().endsWith('AND') ? condition.trim().removeEnd('AND') : condition;

			query = String.format(
				'SELECT {0} FROM Work_Clearance__c {1} ORDER BY Authorized_Date__c DESC LIMIT 25000',
				new List<String>{ String.join( new List<String>{ 'Id', 'Name', 'Area__c', 'CreatedDate', 'Authorized_Date_UI__c', 'Work_Clearance__c', 'Work_Clearance_Status__c', 'Functional_Location__c', 'FunctionalLocation__r.Description__c', 'Main_Work_Center__r.Name', 'Notification__r.Name', 'Order__r.Name', 'Verification_Status__c', 'UserRecordAccess.HasEditAccess' }, ',' ), // fields
					condition
				}
			);

			List<Object> wcAsObjectList = Database.query(query);
			List<Object> wcResultAsObjectList;

			if (isSharingSettings) {
				wcResultAsObjectList = new List<Object>();
				for (Object wcAsObject : wcAsObjectList) {
					Work_Clearance__c wc = (Work_Clearance__c) wcAsObject;
					if (wc.UserRecordAccess.HasEditAccess) {
						wcResultAsObjectList.add(wc);
					}
				}
			} else {
				wcResultAsObjectList = wcAsObjectList;
			}

			List<Object> wcPagingResultAsObjectList = new List<Object>();
			for (Integer i = offset; (i < offset + rowlimit) && (i < wcResultAsObjectList.size()); i++) {
				wcPagingResultAsObjectList.add(wcResultAsObjectList[i]);
			}

			return new Map<String, Object>{
				'data' => wcPagingResultAsObjectList,
				'count' => wcResultAsObjectList.size()
			};
		} catch (Exception e) {
			//System.debug(System.LoggingLevel.DEBUG, e.getStackTraceString());
			throw new AuraHandledException(query);
		}
	}

	@AuraEnabled
	public static Object getWcVerificationList(
		Map<String, String> filter,
		Integer offset,
		Integer rowlimit,
		Boolean isSharingSettings
	) {
		String query;
		try {
			List<String> filterMapping = parseWcFilterObject(filter);

			String condition = '';
			if (isSharingSettings) {
				condition = String.format(
					'WHERE CreatedDate > 2021-01-01T00:00:00.000+07:00 AND Work_Clearance_Status__c = \'In Progress\' AND (Authorized_Signature_UI__c != null AND Authorized_Signatory_UI__c != null) AND (Verification_Status__c = null OR Verification_Status__c = \'Draft\') AND {0}',
					//'WHERE Authorized_Date_UI__c > 2022-01-01 AND Work_Clearance_Status__c = \'In Progress\' AND Area__c != null AND (Authorized_Signature_UI__c != null AND Authorized_Signatory_UI__c != null) AND (Verification_Status__c = null OR Verification_Status__c = \'Draft\') AND {0}',
					new List<String>{
						filterMapping.size() > 0 // condition (optional)
							? String.format('{0}', new List<Object>{ String.join(filterMapping, ' AND ') })
							: ''
					}
				);
			} else {
				condition = String.format(
					'WHERE Work_Clearance_Status__c = \'In Progress\' AND (Authorized_Signature_UI__c != null AND Authorized_Signatory_UI__c != null) AND (Verification_Status__c = null OR Verification_Status__c = \'Draft\') AND {0}',
					new List<String>{
						filterMapping.size() > 0 // condition (optional)
							? String.format('{0}', new List<Object>{ String.join(filterMapping, ' AND ') })
							: ''
					}
				);
			}
			condition = condition.trim().endsWith('AND') ? condition.trim().removeEnd('AND') : condition;

			query = String.format(
				'SELECT {0} FROM Work_Clearance__c {1} ORDER BY Authorized_Date__c DESC LIMIT 25000',
				new List<String>{ String.join( new List<String>{ 'Id', 'Name', 'Area__c', 'CreatedDate', 'Authorized_Date_UI__c', 'Work_Clearance__c', 'Work_Clearance_Status__c', 'Functional_Location__c', 'FunctionalLocation__r.Description__c', 'Main_Work_Center__r.Name', 'Notification__r.Name', 'Order__r.Name', 'Verification_Status__c', 'UserRecordAccess.HasEditAccess' }, ',' ), // fields
					condition
				}
			);

			List<Object> wcAsObjectList = Database.query(query);
			List<Object> wcResultAsObjectList;

			if (isSharingSettings) {
				wcResultAsObjectList = new List<Object>();
				for (Object wcAsObject : wcAsObjectList) {
					Work_Clearance__c wc = (Work_Clearance__c) wcAsObject;
					if (wc.UserRecordAccess.HasEditAccess) {
						wcResultAsObjectList.add(wc);
					}
				}
			} else {
				wcResultAsObjectList = wcAsObjectList;
			}

			List<Object> wcPagingResultAsObjectList = new List<Object>();
			for (Integer i = offset; (i < offset + rowlimit) && (i < wcResultAsObjectList.size()); i++) {
				wcPagingResultAsObjectList.add(wcResultAsObjectList[i]);
			}

			return new Map<String, Object>{
				'data' => wcPagingResultAsObjectList,
				'count' => wcResultAsObjectList.size()
			};
		} catch (Exception e) {
//System.debug(System.LoggingLevel.DEBUG, e.getStackTraceString());
			throw new AuraHandledException(query);
		}
	}

	@AuraEnabled
	public static Object getWcVerificationAllList(
		Map<String, String> filter,
		Integer offset,
		Integer rowlimit,
		Boolean isSharingSettings
	) {
		String query;
		try {
			List<String> filterMapping = parseWcFilterObject(filter);

			String condition = '';
			if (isSharingSettings) {
				condition = String.format(
					'WHERE CreatedDate > 2021-01-01T00:00:00.000+07:00 AND Work_Clearance_Status__c = \'In Progress\' AND (Authorized_Signature_UI__c != null AND Authorized_Signatory_UI__c != null) AND {0}',
					//'WHERE Authorized_Date_UI__c > 2022-01-01 AND Work_Clearance_Status__c = \'In Progress\' AND Area__c != null AND (Authorized_Signature_UI__c != null AND Authorized_Signatory_UI__c != null) AND (Verification_Status__c = null OR Verification_Status__c = \'Draft\') AND {0}',
					new List<String>{
						filterMapping.size() > 0 // condition (optional)
							? String.format('{0}', new List<Object>{ String.join(filterMapping, ' AND ') })
							: ''
					}
				);
			} else {
				condition = String.format(
					'WHERE Work_Clearance_Status__c = \'In Progress\' AND (Authorized_Signature_UI__c != null AND Authorized_Signatory_UI__c != null) AND {0}',
					new List<String>{
						filterMapping.size() > 0 // condition (optional)
							? String.format('{0}', new List<Object>{ String.join(filterMapping, ' AND ') })
							: ''
					}
				);
			}
			condition = condition.trim().endsWith('AND') ? condition.trim().removeEnd('AND') : condition;

			query = String.format(
				'SELECT {0} FROM Work_Clearance__c {1} ORDER BY Authorized_Date__c DESC LIMIT 25000',
				new List<String>{ String.join( new List<String>{ 'Id', 'Name', 'Area__c', 'CreatedDate', 'Authorized_Date_UI__c', 'Work_Clearance__c', 'Work_Clearance_Status__c', 'Functional_Location__c', 'FunctionalLocation__r.Description__c', 'Main_Work_Center__r.Name', 'Notification__r.Name', 'Order__r.Name', 'Verification_Status__c', 'UserRecordAccess.HasEditAccess' }, ',' ), // fields
					condition
				}
			);

			List<Object> wcAsObjectList = Database.query(query);
			List<Object> wcResultAsObjectList;

			if (isSharingSettings) {
				wcResultAsObjectList = new List<Object>();
				for (Object wcAsObject : wcAsObjectList) {
					Work_Clearance__c wc = (Work_Clearance__c) wcAsObject;
					if (wc.UserRecordAccess.HasEditAccess) {
						wcResultAsObjectList.add(wc);
					}
				}
			} else {
				wcResultAsObjectList = wcAsObjectList;
			}

			List<Object> wcPagingResultAsObjectList = new List<Object>();
			for (Integer i = offset; (i < offset + rowlimit) && (i < wcResultAsObjectList.size()); i++) {
				wcPagingResultAsObjectList.add(wcResultAsObjectList[i]);
			}

			return new Map<String, Object>{
				'data' => wcPagingResultAsObjectList,
				'count' => wcResultAsObjectList.size()
			};
		} catch (Exception e) {
//System.debug(System.LoggingLevel.DEBUG, e.getStackTraceString());
			throw new AuraHandledException(query);
		}
	}

	@AuraEnabled
	public static Object getWcInspectionList(
		Map<String, String> filter,
		Integer offset,
		Integer rowlimit,
		Boolean isSharingSettings
	) {
		String query;
		try {
			List<String> filterMapping = parseWcFilterObject(filter);

			String condition = '';
			if (isSharingSettings) {
				condition = String.format(
					'WHERE CreatedDate > 2022-01-01T00:00:00.000+0700 AND Work_Clearance_Status__c = \'In Progress\' AND (Authorized_Signature_UI__c != null AND Authorized_Signatory_UI__c != null) AND Verification_Status__c = \'Agree\' AND {0}',
					//'WHERE Authorized_Date_UI__c > 2022-01-01 AND Work_Clearance_Status__c = \'In Progress\' AND Area__c != null AND (Authorized_Signature_UI__c != null AND Authorized_Signatory_UI__c != null) AND Verification_Status__c = \'Agree\' AND {0}',
					new List<String>{
						filterMapping.size() > 0 // condition (optional)
							? String.format('{0}', new List<Object>{ String.join(filterMapping, ' AND ') })
							: ''
					}
				);
			} else {
				condition = String.format(
					'WHERE Work_Clearance_Status__c = \'In Progress\' AND (Authorized_Signature_UI__c != null AND Authorized_Signatory_UI__c != null) AND Verification_Status__c = \'Agree\' AND {0}',
					new List<String>{
						filterMapping.size() > 0 // condition (optional)
							? String.format('{0}', new List<Object>{ String.join(filterMapping, ' AND ') })
							: ''
					}
				);
			}
			condition = condition.trim().endsWith('AND') ? condition.trim().removeEnd('AND') : condition;

			query = String.format(
				'SELECT {0} FROM Work_Clearance__c {1} ORDER BY Authorized_Date__c DESC LIMIT 25000',
				new List<String>{ String.join( new List<String>{ 'Id', 'Name', 'Area__c', 'CreatedDate', 'Authorized_Date_UI__c', 'Work_Clearance__c', 'Work_Clearance_Status__c', 'Functional_Location__c', 'FunctionalLocation__r.Description__c', 'Main_Work_Center__r.Name', 'Notification__r.Name', 'Order__r.Name', 'Verification_Status__c', 'UserRecordAccess.HasEditAccess', '(SELECT Id FROM PTW_Header__r WHERE FormName__c = \'Inspection\' AND Status__c = \'ดำเนินการได้\')' }, ',' ), // fields
					condition
				}
			);

			List<Object> wcAsObjectList = Database.query(query);
			List<Object> wcResultAsObjectList;

			if (isSharingSettings) {
				wcResultAsObjectList = new List<Object>();
				for (Object wcAsObject : wcAsObjectList) {
					Work_Clearance__c wc = (Work_Clearance__c) wcAsObject;
					if (wc.UserRecordAccess.HasEditAccess) {
						wcResultAsObjectList.add(wc);
					}
				}
			} else {
				wcResultAsObjectList = wcAsObjectList;
			}

			List<Object> wcPagingResultAsObjectList = new List<Object>();
			for (Integer i = offset; (i < offset + rowlimit) && (i < wcResultAsObjectList.size()); i++) {
				wcPagingResultAsObjectList.add(wcResultAsObjectList[i]);
			}

			return new Map<String, Object>{
				'data' => wcPagingResultAsObjectList,
				'count' => wcResultAsObjectList.size()
			};
		} catch (Exception e) {
			//System.debug(System.LoggingLevel.DEBUG, e.getStackTraceString());
			throw new AuraHandledException(query);
		}
	}

	@AuraEnabled
	public static Object getWcInspectionDoneList(
		Map<String, String> filter,
		Integer offset,
		Integer rowlimit,
		Boolean isSharingSettings
	) {
		String query;
		try {
			List<String> filterMapping = parseWcFilterObject(filter);

			String condition = '';
			if (isSharingSettings) {
				condition = String.format(
					'WHERE CreatedDate > 2022-01-01T00:00:00.000+0700 AND Work_Clearance_Status__c = \'In Progress\' AND (Authorized_Signature_UI__c != null AND Authorized_Signatory_UI__c != null) AND Verification_Status__c = \'Agree\' AND {0}',
					//'WHERE Authorized_Date_UI__c > 2022-01-01 AND Work_Clearance_Status__c = \'In Progress\' AND Area__c != null AND (Authorized_Signature_UI__c != null AND Authorized_Signatory_UI__c != null) AND Verification_Status__c = \'Agree\' AND {0}',
					new List<String>{
						filterMapping.size() > 0 // condition (optional)
							? String.format('{0}', new List<Object>{ String.join(filterMapping, ' AND ') })
							: ''
					}
				);
			} else {
				condition = String.format(
					'WHERE Work_Clearance_Status__c = \'In Progress\' AND (Authorized_Signature_UI__c != null AND Authorized_Signatory_UI__c != null) AND Verification_Status__c = \'Agree\' AND {0}',
					new List<String>{
						filterMapping.size() > 0 // condition (optional)
							? String.format('{0}', new List<Object>{ String.join(filterMapping, ' AND ') })
							: ''
					}
				);
			}
			condition = condition.trim().endsWith('AND') ? condition.trim().removeEnd('AND') : condition;

			query = String.format(
				'SELECT {0} FROM Work_Clearance__c {1} ORDER BY Authorized_Date__c DESC LIMIT 25000',
				new List<String>{ String.join( new List<String>{ 'Id', 'Name', 'Area__c', 'CreatedDate', 'Authorized_Date_UI__c', 'Work_Clearance__c', 'Work_Clearance_Status__c', 'Functional_Location__c', 'FunctionalLocation__r.Description__c', 'Main_Work_Center__r.Name', 'Notification__r.Name', 'Order__r.Name', 'Verification_Status__c', 'UserRecordAccess.HasEditAccess', '(SELECT Id FROM PTW_Header__r WHERE FormName__c = \'Inspection\' AND Status__c = \'ดำเนินการได้\')' }, ',' ), // fields
					condition
				}
			);

			List<Object> wcAsObjectList = Database.query(query);
			List<Object> wcResultAsObjectList;

			if (isSharingSettings) {
				wcResultAsObjectList = new List<Object>();
				for (Object wcAsObject : wcAsObjectList) {
					Work_Clearance__c wc = (Work_Clearance__c) wcAsObject;
					if (wc.UserRecordAccess.HasEditAccess && !wc.PTW_Header__r.isEmpty()) {
						wcResultAsObjectList.add(wc);
					}
				}
			} else {
				wcResultAsObjectList = new List<Object>();
				for (Object wcAsObject : wcAsObjectList) {
					Work_Clearance__c wc = (Work_Clearance__c) wcAsObject;
					if (!wc.PTW_Header__r.isEmpty()) {
						wcResultAsObjectList = wcAsObjectList;
					}
				}
			}

			List<Object> wcPagingResultAsObjectList = new List<Object>();
			for (Integer i = offset; (i < offset + rowlimit) && (i < wcResultAsObjectList.size()); i++) {
				wcPagingResultAsObjectList.add(wcResultAsObjectList[i]);
			}

			return new Map<String, Object>{
				'data' => wcPagingResultAsObjectList,
				'count' => wcResultAsObjectList.size()
			};
		} catch (Exception e) {
			//System.debug(System.LoggingLevel.DEBUG, e.getStackTraceString());
			throw new AuraHandledException(query);
		}
	}
}