force-app/main/default/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Breakdown__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Breakdown</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Number__c</fullName>
        <externalId>true</externalId>
        <label>Notification Number</label>
        <length>16</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Notification_Status__c</fullName>
        <label>Notification Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>In Execution</fullName>
                    <isActive>false</isActive>
                    <label>In Execution</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Date__c</fullName>
        <label>Requested Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Notification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required_Start__c</fullName>
        <label>Required Start</label>
        <type>Date</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <label>Notification Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ODM_NotificationSwitchOverCtrlTest.cls
@isTest
public class ODM_NotificationSwitchOverCtrlTest {

    @TestSetup
    static void makeData(){
        insert new Notification__c(
			Name = '00000001',
            Notification_Number__c = '00000001',
			Description__c = 'SWITCH OVER - Test Notification',
			Requested_Date__c = Date.today(),
			Required_Start__c = Date.today()
		);
    }
    
    @isTest
    public static void testGetNotificationList() {
		Test.startTest();

		Object objNotis = ODM_NotificationSwtchOverCtrl.getNotificationList(
			new Map<String, String>{
				'Type' => 'OP',
				'Notification_Number__c' => '00000001',
				'Notification_Status__c' => 'New;In Progress',
				'Requested_Date__c' => '2022-06-19',
				'Create_Date_From__c' => '2022-06-19',
				'Create_Date_To__c' => '2022-06-19',
				'Requester__c' => '12341234',
				'Breakdown__c' => 'false',
				'Test__c' => 'Test'
			}, 0, 20, true
		);

        Map<String, Object> wrapper = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(objNotis));

        System.assertEquals(0, Integer.valueOf(wrapper.get('count')));
        
		Test.stopTest();
    }
}