force-app/main/default/objects/OPP_Application__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Notification__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>OPP_Application__c</referenceTo>
        <relationshipLabel>OPP Notification</relationshipLabel>
        <relationshipName>OPP_Notification</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReferenceID__c</fullName>
        <label>ReferenceID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <label>Requester</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reassigned</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Send back</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OPP_Notification</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Top Space Notifications</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Notification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CG_NotiController.cls
/* 
 * Author Softever
 */

public with sharing class CG_NotiController {

    public static void SendBellNoti(CG_DTO.BellNotiDTO BellNoti) {
        
        //Send Bell Noti
        CustomNotificationType notificationType = [SELECT Id, DeveloperName FROM CustomNotificationType 
                               			 			WHERE DeveloperName =: BellNoti.NotificationName];
        
        // Create a new custom notification
        Messaging.CustomNotification customNoti = new Messaging.CustomNotification();
        
        string title = BellNoti.Title;
        string body = BellNoti.Body;
        
        // Set the contents for the notification
        customNoti.setTitle(title);
        customNoti.setBody(body);
        
        // Set the notification type and target
        customNoti.setNotificationTypeId(notificationType.Id);
        //customNoti.setTargetId(BellNoti.RecordId);
        customNoti.setTargetPageRef(BellNoti.PageRef);
              
        Set<String> receivers = new Set<String>();
        
        //Owner
        //receivers.add(CGReport.OwnerId);
        receivers = BellNoti.Receivers;
                    
        // Actually send the notification
        try {
            customNoti.send(receivers);
        }
        catch (Exception e) {
            System.debug('Problem sending notification: ' + e.getMessage());
        }
    } 
    
    public static void SendBellNoti(CG_DTO.BellNotiDTO BellNoti, CustomNotificationType notificationType) {
        
        //Send Bell Noti
        //CustomNotificationType notificationType = [SELECT Id, DeveloperName FROM CustomNotificationType 
        //                       			 			WHERE DeveloperName =: BellNoti.NotificationName];
        
        // Create a new custom notification
        Messaging.CustomNotification customNoti = new Messaging.CustomNotification();
        
        string title = BellNoti.Title;
        string body = BellNoti.Body;
        
        // Set the contents for the notification
        customNoti.setTitle(title);
        customNoti.setBody(body);
        
        // Set the notification type and target
        customNoti.setNotificationTypeId(notificationType.Id);
        //customNoti.setTargetId(BellNoti.RecordId);
        customNoti.setTargetPageRef(BellNoti.PageRef);
              
        Set<String> receivers = new Set<String>();
        
        //Owner
        //receivers.add(CGReport.OwnerId);
        receivers = BellNoti.Receivers;
                    
        // Actually send the notification
        try {
            customNoti.send(receivers);
        }
        catch (Exception e) {
            System.debug('Problem sending notification: ' + e.getMessage());
        }
    } 
    
    public static void SendOppNoti(CG_DTO.OppNotiDTO OppNoti) {
        
        //Send to Opp Notification
        OPP_Application__c CGApp = [select id, name from OPP_Application__c where Name =: 'CG Reporting'];
        
        Opp_Notification__c CGOpp = new Opp_Notification__c();
        CGOpp.Application__c = CGApp.Id;
        CGOpp.User__c = OppNoti.ApproverId;
        CGOpp.Subject__c = OppNoti.Subject;
        CGOpp.Description__c = OppNoti.Description;
        CGOpp.Requester__c = OppNoti.RequesterName;
        CGOpp.Status__c = OppNoti.Status;
        CGOpp.URL__c = OppNoti.URL;
        CGOpp.ReferenceID__c = OppNoti.ReferenceId;
        insert(CGOpp);
        
        /* CGOpp.Application__c = TOPPMPApp.Id;
        CGOpp.User__c = approveUserId;
        CGOpp.Subject__c = 'Following Step ' + stepName + ' for Project ' + projectName + ' has submitted for approve.';
        CGOpp.Description__c = '';
        CGOpp.Requester__c = requesterName;
        CGOpp.Status__c = 'New';
        CGOpp.URL__c = baseUrl + '/lightning/r/' + recordId + '/view';
        CGOpp.ReferenceID__c = recordId;
        insert(CGApp); */
        
    }
    
    public static Opp_Notification__c SaveOppNoti(CG_DTO.OppNotiDTO OppNoti) {
        
        Opp_Notification__c CGOpp = new Opp_Notification__c();
        CGOpp.Application__c = OppNoti.ApplicationId;
        CGOpp.User__c = OppNoti.ApproverId;
        CGOpp.Subject__c = OppNoti.Subject;
        CGOpp.Description__c = OppNoti.Description;
        CGOpp.Requester__c = OppNoti.RequesterName;
        CGOpp.Status__c = OppNoti.Status;
        CGOpp.URL__c = OppNoti.URL;
        CGOpp.ReferenceID__c = OppNoti.ReferenceId;
        
        return CGOpp;
    }
    
    public static void UpdateOppNoti(Id recordId) {
        
        string baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        
        List<Opp_Notification__c> CGApps = [select id, name, ReferenceID__c from Opp_Notification__c where ReferenceID__c =: recordId];
        
        if(CGApps.size() > 0) {
            for(Opp_Notification__c OppNoti : CGApps) {
                OppNoti.Status__c = 'Approved';
        		update(OppNoti);
            }
        }
        
    }
    
    public static void UpdateOppNotiWhenUserAction(Id recordId, Id userId, string status) {
        
        string baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        
        List<Opp_Notification__c> CGApps = [select id, name, ReferenceID__c, User__c, Status__c from Opp_Notification__c where ReferenceID__c =: recordId AND User__c = :userId];
        
        if(CGApps.size() > 0) {
            for(Opp_Notification__c OppNoti : CGApps) {
                OppNoti.Status__c = status;
        		database.update(OppNoti, true);
            }
        }
        
    }
}