force-app/main/default/objects/OPP_Application__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>People Connect</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>Finance and Accounting</fullName>
                </value>
                <value>
                    <fullName>Strategy</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>SSHE</fullName>
                </value>
                <value>
                    <fullName>Procurement &amp; Contract</fullName>
                </value>
                <value>
                    <fullName>Operation</fullName>
                </value>
                <value>
                    <fullName>Governance and Compliance</fullName>
                </value>
                <value>
                    <fullName>Notification</fullName>
                    <isActive>false</isActive>
                    <label>Notification</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <label>Icon</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_Android__c</fullName>
        <label>URL Android</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_IOS__c</fullName>
        <label>URL IOS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_Web__c</fullName>
        <label>URL Web</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Applications</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Favorite_Application__c.object
<CustomObject>
    <fields>
        <fullName>No__c</fullName>
        <label>No</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OPP_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OPP Application</label>
        <referenceTo>OPP_Application__c</referenceTo>
        <relationshipLabel>OPP Favorite Application</relationshipLabel>
        <relationshipName>OPP_Favorite_Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OPP_Favorite_Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Favorite Applications</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>OPP Favorite Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_News__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Operation</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Digital</fullName>
                </value>
                <value>
                    <fullName>PM4U</fullName>
                </value>
                <value>
                    <fullName>KM</fullName>
                </value>
                <value>
                    <fullName>QSHE</fullName>
                </value>
                <value>
                    <fullName>Club</fullName>
                </value>
                <value>
                    <fullName>Akanee</fullName>
                </value>
                <value>
                    <fullName>Special Issues</fullName>
                </value>
                <value>
                    <fullName>People</fullName>
                    <isActive>false</isActive>
                    <label>People</label>
                </value>
                <value>
                    <fullName>TOP Shop</fullName>
                    <isActive>false</isActive>
                    <label>TOP Shop</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Coin__c</fullName>
        <label>Coin</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Thumbnail__c</fullName>
        <label>Thumbnail</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>News</label>
    <nameField>
        <displayFormat>NEWS# {YYYY}.{MM}.{DD}.{000}</displayFormat>
        <label>News Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OPP_HomeController.cls
public with sharing class OPP_HomeController {
    
    @AuraEnabled
    public static List<OPP_News__c> getNews(String size, Boolean showAll){
        try {
             string rdLimit = '';
           	 string wheCat = '';
             rdLimit = size == '3'?'LIMIT 3':'LIMIT 6';
             if(showAll){ wheCat =' And Category__c !=\'Operation\' ';  }
             String query ='Select Id,Name,Thumbnail__c,Coin__c,Title__c,Category__c,(SELECT ContentDocumentId FROM ContentDocumentLinks ORDER BY SystemModstamp DESC LIMIT 1) FROM OPP_News__c WHERE Status__c =\'Published\' '+wheCat+'  ORDER BY LastModifiedDate DESC '+rdLimit;
             List<sObject> news = Database.query(query); 
            return news;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<OPP_News__c> getOperationNews(String size){
        try {
             string rdLimit = '';
             rdLimit = size == '3'? 'LIMIT 3':'LIMIT 6';
             String query ='SELECT Id,Name,Thumbnail__c,Coin__c,Title__c,Category__c,(SELECT ContentDocumentId FROM ContentDocumentLinks ORDER BY SystemModstamp DESC LIMIT 1)FROM OPP_News__c WHERE Category__c =\'Operation\' AND Status__c =\'Published\' ORDER BY LastModifiedDate DESC '+rdLimit;
             List<sObject> news = Database.query(query);
            return news;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<OPP_FavAppWrap> getApplications(){
        try {
            List<OPP_FavAppWrap> oppFavAppWraps = new List<OPP_FavAppWrap>();
            List<OPP_Favorite_Application__c> applications = [SELECT Id, OPP_Application__c, OPP_Application__r.Name, OPP_Application__r.URL_Web__c,OPP_Application__r.Icon__c, User__c, No__c, OPP_Application__r.URL_IOS__c, OPP_Application__r.URL_Android__c FROM OPP_Favorite_Application__c WHERE User__c =: UserInfo.getUserId() ORDER BY NO__c ASC LIMIT 6];
            if(applications.size() > 0){
                Set<Id> setAppIds = new Set<Id>();
                Map<Id, Id> mapFileApplication = new Map<Id, Id>();
				for(OPP_Favorite_Application__c application : applications){
                    setAppIds.add(application.OPP_Application__c);
                }
                List<OPP_Application__c> apps = [SELECT Id, (SELECT ContentDocumentId FROM ContentDocumentLinks ORDER BY SystemModstamp DESC LIMIT 1) FROM OPP_Application__c WHERE Id IN: setAppIds];
                for(OPP_Application__c app : apps) {
                    for(ContentDocumentLink content : app.ContentDocumentLinks){
                        mapFileApplication.put(app.Id, content.ContentDocumentId);
                    }
                }
                for(OPP_Favorite_Application__c application : applications){
                    OPP_FavAppWrap oppFavAppWrap = new OPP_FavAppWrap();
                    oppFavAppWrap.favAppId = application.Id;
                    oppFavAppWrap.appName = application.OPP_Application__r.Name;
                    oppFavAppWrap.url = application.OPP_Application__r.URL_Web__c;
                    oppFavAppWrap.ios = application.OPP_Application__r.URL_IOS__c;
                    oppFavAppWrap.android = application.OPP_Application__r.URL_Android__c;
                    if(mapFileApplication.containsKey(application.OPP_Application__c)) {
                        oppFavAppWrap.fileId = mapFileApplication.get(application.OPP_Application__c);
                    }  
                    oppFavAppWraps.add(oppFavAppWrap);
                }
                return oppFavAppWraps;
            }
            else {
                // First time user login on SF
                OPP_Favorite_Application__c app_1 = new OPP_Favorite_Application__c();
                app_1.OPP_Application__c = [SELECT Id FROM OPP_Application__c WHERE Name = 'Intranet' LIMIT 1].Id;
                app_1.User__c = UserInfo.getUserId();
                app_1.No__c = 1;
                insert app_1;

                OPP_Favorite_Application__c app_2 = new OPP_Favorite_Application__c();
                app_2.OPP_Application__c = [SELECT Id FROM OPP_Application__c WHERE Name = 'Employee Online' LIMIT 1].Id;
                app_2.User__c = UserInfo.getUserId();
                app_2.No__c = 2;
                insert app_2;

                OPP_Favorite_Application__c app_3 = new OPP_Favorite_Application__c();
                app_3.OPP_Application__c = [SELECT Id FROM OPP_Application__c WHERE Name = 'Top Search' LIMIT 1].Id;
                app_3.User__c = UserInfo.getUserId();
                app_3.No__c = 3;
                insert app_3;

                Integer i;
                for(i=0; i<3; i++) {
                    OPP_Favorite_Application__c app = new OPP_Favorite_Application__c();
                    app.User__c = UserInfo.getUserId();
                    app.No__c = 4 + i;
                    insert app;
                }

                Set<Id> setAppIds = new Set<Id>();
                Map<Id, Id> mapFileApplication = new Map<Id, Id>();

                List<OPP_Favorite_Application__c> fapApps = [SELECT Id,OPP_Application__c,OPP_Application__r.Name,OPP_Application__r.URL_Web__c,OPP_Application__r.URL_IOS__c,OPP_Application__r.URL_Android__c,OPP_Application__r.Icon__c,User__c FROM OPP_Favorite_Application__c WHERE User__c =: UserInfo.getUserId() ORDER BY NO__c ASC];

                for(OPP_Favorite_Application__c application : fapApps){
                    setAppIds.add(application.OPP_Application__c);
                }
                List<OPP_Application__c> apps = [SELECT Id, (SELECT ContentDocumentId FROM ContentDocumentLinks ORDER BY SystemModstamp DESC LIMIT 1) FROM OPP_Application__c WHERE Id IN: setAppIds];
                for(OPP_Application__c app : apps){
                    for(ContentDocumentLink content : app.ContentDocumentLinks){
                        mapFileApplication.put(app.Id, content.ContentDocumentId);
                    }
                }
                List<OPP_Favorite_Application__c> getApplications = [SELECT Id,OPP_Application__c,OPP_Application__r.Name, OPP_Application__r.URL_Web__c,OPP_Application__r.Icon__c,User__c, No__c,OPP_Application__r.URL_IOS__c,OPP_Application__r.URL_Android__c FROM OPP_Favorite_Application__c WHERE User__c =: UserInfo.getUserId() ORDER BY NO__c ASC LIMIT 6];
                for(OPP_Favorite_Application__c application : getApplications){
                    OPP_FavAppWrap oppFavAppWrap = new OPP_FavAppWrap();
                    oppFavAppWrap.favAppId = application.Id;
                    oppFavAppWrap.appName = application.OPP_Application__r.Name;
                    oppFavAppWrap.url = application.OPP_Application__r.URL_Web__c;
                    oppFavAppWrap.ios = application.OPP_Application__r.URL_IOS__c;
                    oppFavAppWrap.android = application.OPP_Application__r.URL_Android__c;
                    if(mapFileApplication.containsKey(application.OPP_Application__c)) {
                        oppFavAppWrap.fileId = mapFileApplication.get(application.OPP_Application__c);
                    }  
                    oppFavAppWraps.add(oppFavAppWrap);
                }
                return oppFavAppWraps;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}