force-app/main/default/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
                <value>
                    <fullName>Urgent</fullName>
                </value>
                <value>
                    <fullName>Immediately</fullName>
                </value>
                <value>
                    <fullName>Float Time - 1M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 3M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 6M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 9M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 12M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 15M</fullName>
                </value>
                <value>
                    <fullName>Float Time - 18M</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <isActive>false</isActive>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <isActive>false</isActive>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <isActive>false</isActive>
                    <label>3</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Clearance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Clearance</label>
        <referenceTo>Work_Clearance__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Clearance__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Work Clearances</relationshipLabel>
        <relationshipName>Work_Clearances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Immediately</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Urgent</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Normal</label>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                    <label>Float Time - 1M</label>
                </value>
                <value>
                    <fullName>C</fullName>
                    <label>Float Time - 3M</label>
                </value>
                <value>
                    <fullName>F</fullName>
                    <label>Float Time - 6M</label>
                </value>
                <value>
                    <fullName>I</fullName>
                    <label>Float Time - 9M</label>
                </value>
                <value>
                    <fullName>L</fullName>
                    <label>Float Time - 12M</label>
                </value>
                <value>
                    <fullName>O</fullName>
                    <label>Float Time - 15M</label>
                </value>
                <value>
                    <fullName>R</fullName>
                    <label>Float Time - 18M</label>
                </value>
                <value>
                    <fullName>Immediately</fullName>
                    <isActive>false</isActive>
                    <label>Immediately</label>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <isActive>false</isActive>
                    <label>Normal</label>
                </value>
                <value>
                    <fullName>Urgent</fullName>
                    <isActive>false</isActive>
                    <label>Urgent</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Clearance__c</fullName>
        <externalId>true</externalId>
        <label>Work Clearance</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Work Clearance</label>
    <nameField>
        <label>Work Clearance Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/THOR_OrderRelatedWorkClearanceCtr_Test.cls
@isTest
public class THOR_OrderRelatedWorkClearanceCtr_Test {
    @isTest
    static void testRelatedWorkClearances() {
        Order__c exampleOrder = new Order__c();
        exampleOrder.Name = 'Example Order Name';
        insert exampleOrder;

        Work_Clearance__c clearance = new Work_Clearance__c();
        clearance.Name = 'Example';
        clearance.Work_Clearance__c = 'Example';
        clearance.Description__c = 'Example Description';
        clearance.Priority__c = '5';
        clearance.order__c = exampleOrder.Id;
        insert clearance;

        Test.startTest();
        /*Map<Id, THOR_RelatedWorkClearanceDTO> result = THOR_OrderRelatedWorkClearanceCtr.getRelatedObjects(
            exampleOrder.Id
        );*/
        Work_Clearance__c result = THOR_OrderRelatedWorkClearanceCtr.getRelatedObjects(
            exampleOrder.Id
        );
        Test.stopTest();

        //System.assertEquals(1, result.size());
    }
}