force-app/main/default/objects/Order__c.object
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Operation__c.object
<CustomObject>
    <fields>
        <fullName>Operation_Text__c</fullName>
        <label>Operation Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Operations</relationshipLabel>
        <relationshipName>Order_Operations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Operation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Order Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Spare_Part__c.object
<CustomObject>
    <fields>
        <fullName>Material_Number__c</fullName>
        <label>Material Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Spare Part</label>
    <nameField>
        <label>Spare Part Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Spare_Part_Request__c.object
<CustomObject>
    <fields>
        <fullName>IC__c</fullName>
        <description>Item Category</description>
        <label>IC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Operation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Operation</label>
        <referenceTo>Order_Operation__c</referenceTo>
        <relationshipLabel>Spare Part Requests</relationshipLabel>
        <relationshipName>Spare_Part_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Spare Part Requests</relationshipLabel>
        <relationshipName>Spare_Part_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spare_Part_Stock__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Spare Part Stock</label>
        <referenceTo>Spare_Part_Stock__c</referenceTo>
        <relationshipLabel>Spare Part Requests</relationshipLabel>
        <relationshipName>Spare_Part_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spare_Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Spare Part</label>
        <referenceTo>Spare_Part__c</referenceTo>
        <relationshipLabel>Spare Part Requests</relationshipLabel>
        <relationshipName>Spare_Part_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Spare Part Request</label>
    <nameField>
        <label>Spare Part Request Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Spare_Part_Stock__c.object
<CustomObject>
    <fields>
        <fullName>Spare_Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Spare Part</label>
        <referenceTo>Spare_Part__c</referenceTo>
        <relationshipLabel>Spare Part Stocks</relationshipLabel>
        <relationshipName>Spare_Part_Stocks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Spare Part Stock</label>
    <nameField>
        <label>Spare Part Stock Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/THOR_CmpReqRecordDisplayControllerTest.cls
/**
 * @author Oktana
 * @description test class for THOR_CmpReqRecordDisplayController
 */
@isTest
public with sharing class THOR_CmpReqRecordDisplayControllerTest {
    @testSetup
    static void setup() {
        Spare_Part__c part = new Spare_Part__c();
        part.Material_Number__c = '1234';
        insert part;

        Spare_Part_Stock__c stock = new Spare_Part_Stock__c();
        stock.Spare_Part__c = part.Id;
        insert stock;

        Order__c order = new Order__c(Name = 'orderTest');
        insert order;

        Order_Operation__c orderOperation = new Order_Operation__c(
            Operation_Text__c = 'orderOpTest',
            Order__c = order.Id
        );
        insert orderOperation;

        Spare_Part_Request__c componentRequest = new Spare_Part_Request__c();
        componentRequest.IC__c = 'M';
        componentRequest.Spare_Part_Stock__c = stock.Id;
        componentRequest.Order__c = order.Id;
        componentRequest.Order_Operation__c = orderOperation.Id;
        componentRequest.Spare_Part__c = part.Id;

        insert componentRequest;
    }

    /**
     * @given a Spare Part Request
     * @when method THOR_CmpReqRecordDisplayController.retrieveComponentRequest is invoked with
     *       the Spare Part Request Id
     * @then the Spare Part Request is passed to the Aura Component
     */
    @isTest
    static void retrieveComponentRequestTest() {
        Spare_Part_Request__c componentRequest = getComponentRequest();

        Test.startTest();
        Spare_Part_Request__c retrievedComponent = THOR_CmpReqRecordDisplayController.retrieveComponentRequest(
            componentRequest.Id
        );
        Test.stopTest();

        System.assertNotEquals(null, retrievedComponent, 'A Spare Part Request should have been retrieved');
        System.assertEquals('M', retrievedComponent.IC__c, 'IC does not match');
        System.assertEquals(
            '1234',
            retrievedComponent.Spare_Part_Stock__r.Spare_Part__r.Material_Number__c,
            'Material_Number__c does not match'
        );
    }

    /**
     * @given a Spare Part Request
     * @when method THOR_CmpReqRecordDisplayController.retrieveComponentRequest is invoked with
     *       a nonexistent Id
     * @then an Exception is thrown
     * @and no Spare Part Request is passed to the Aura Component
     */
    @isTest
    static void retrieveComponentRequestWithBadIdTest() {
        Spare_Part_Request__c componentRequest = getComponentRequest();

        Test.startTest();
        try {
            Spare_Part_Request__c retrievedComponent = THOR_CmpReqRecordDisplayController.retrieveComponentRequest(
                null
            );
            System.assert(false, 'An exception should have been thrown');
        } catch (Exception ex) {
            System.assertEquals(
                'System.AuraHandledException',
                ex.getTypeName(),
                'AuraHandledException should have been thrown'
            );
        }
        Test.stopTest();
    }

    private static Spare_Part_Request__c getComponentRequest() {
        return [
            SELECT Id, IC__c, Spare_Part_Stock__r.Spare_Part__r.Material_Number__c
            FROM Spare_Part_Request__c
            LIMIT 1
        ];
    }
}