force-app/main/default/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Number__c</fullName>
        <externalId>true</externalId>
        <label>Order Number</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Spare_Part__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit__c</fullName>
        <label>Base Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PC</fullName>
                </value>
                <value>
                    <fullName>SET</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Material_Description__c</fullName>
        <label>Material Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Material_Number__c</fullName>
        <label>Material Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Spare Part</label>
    <nameField>
        <label>Spare Part Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Spare_Part_Request__c.object
<CustomObject>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Spare Part Requests</relationshipLabel>
        <relationshipName>Spare_Part_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Material_Quantity__c</fullName>
        <label>Request Material Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Pending for Approved</fullName>
                    <isActive>false</isActive>
                    <label>Pending for Approved</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Spare_Part_Stock__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Spare Part Stock</label>
        <referenceTo>Spare_Part_Stock__c</referenceTo>
        <relationshipLabel>Spare Part Requests</relationshipLabel>
        <relationshipName>Spare_Part_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spare_Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Spare Part</label>
        <referenceTo>Spare_Part__c</referenceTo>
        <relationshipLabel>Spare Part Requests</relationshipLabel>
        <relationshipName>Spare_Part_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Spare Part Request</label>
    <nameField>
        <label>Spare Part Request Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Spare_Part_Stock__c.object
<CustomObject>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spare_Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Spare Part</label>
        <referenceTo>Spare_Part__c</referenceTo>
        <relationshipLabel>Spare Part Stocks</relationshipLabel>
        <relationshipName>Spare_Part_Stocks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Spare Part Stock</label>
    <nameField>
        <label>Spare Part Stock Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/THOR_OrderRelCmpReqController.cls
/**
 * @author Sebastian Bucalo
 * @description Controller class for THOR_OrderRelatedComponentRequest aura component
 */
public with sharing class THOR_OrderRelCmpReqController {
    /**
     * @description retrieves the order component request for a specific order
     * @return Related components requests
     * @param orderId
     */
    @AuraEnabled
    public static List<THOR_ObjectCardDTO> retrieveComponentsRequests(Id orderId) {
        try {
            return THOR_DTOMapper.mapComponentsRequests(
                [
                    SELECT
                        Id,
                        Name,
                        Order__c,
                        Order__r.Order_Number__c,
                        Request_Material_Quantity__c,
                        Request_Status__c,
                        Spare_Part_Stock__r.Available_Quantity__c,
                        Spare_Part_Stock__r.Spare_Part__r.Material_Number__c,
                        Spare_Part_Stock__r.Spare_Part__r.Material_Description__c,
                        Spare_Part_Stock__r.Spare_Part__r.Base_Unit__c,
                    	Spare_Part__r.Material_Number__c,
                    	Spare_Part__r.Material_Description__c
                    FROM Spare_Part_Request__c
                    WHERE
                        Order__c = :orderId
                        AND Deleted__c = FALSE
                        AND Request_Status__c IN ('Pending for Approval', 'Approved', 'Rejected')
                    WITH SECURITY_ENFORCED
                ]
            );
        } catch (Exception e) {
            throw new AuraHandledException('Something went wrong...');
        }
    }
    /**
     * @description retrieves the cart count for a specific order
     * @return Related components cart count
     * @param orderId
     */
    @AuraEnabled
    public static Integer getCartCount(String orderId) {
        try {
            return [
                SELECT COUNT()
                FROM Spare_Part_Request__c
                WHERE Order__c = :orderId AND Request_Status__c = 'Draft' AND Deleted__c = FALSE
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}