force-app/main/default/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Requested Date</label>
        <type>Date</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Operation__c.object
<CustomObject>
    <fields>
        <fullName>Operation_Text__c</fullName>
        <label>Operation Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Operations</relationshipLabel>
        <relationshipName>Order_Operations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Operation</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Order Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Spare_Part__c.object
<CustomObject>
    <fields>
        <fullName>Base_Unit__c</fullName>
        <label>Base Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PC</fullName>
                </value>
                <value>
                    <fullName>SET</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Material_Description__c</fullName>
        <label>Material Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Material_Number__c</fullName>
        <label>Material Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Spare Part</label>
    <nameField>
        <label>Spare Part Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Spare_Part_Request__c.object
<CustomObject>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Order_Operation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Operation</label>
        <referenceTo>Order_Operation__c</referenceTo>
        <relationshipLabel>Spare Part Requests</relationshipLabel>
        <relationshipName>Spare_Part_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Spare Part Requests</relationshipLabel>
        <relationshipName>Spare_Part_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Material_Quantity__c</fullName>
        <label>Request Material Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending for Approval</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <isActive>false</isActive>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Pending for Approved</fullName>
                    <isActive>false</isActive>
                    <label>Pending for Approved</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Spare_Part_Stock__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Spare Part Stock</label>
        <referenceTo>Spare_Part_Stock__c</referenceTo>
        <relationshipLabel>Spare Part Requests</relationshipLabel>
        <relationshipName>Spare_Part_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spare_Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Spare Part</label>
        <referenceTo>Spare_Part__c</referenceTo>
        <relationshipLabel>Spare Part Requests</relationshipLabel>
        <relationshipName>Spare_Part_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Spare Part Request</label>
    <nameField>
        <label>Spare Part Request Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Spare_Part_Stock__c.object
<CustomObject>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spare_Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Spare Part</label>
        <referenceTo>Spare_Part__c</referenceTo>
        <relationshipLabel>Spare Part Stocks</relationshipLabel>
        <relationshipName>Spare_Part_Stocks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Spare Part Stock</label>
    <nameField>
        <label>Spare Part Stock Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/THOR_OrderRelCmpReqController_Test.cls
@isTest
public with sharing class THOR_OrderRelCmpReqController_Test{
	@isTest
	public static void givenOrderIdWhenCalledRetrieveComponentsRequestsExpectedArrayOfDTOS(){
		Profile userProfile = [SELECT Id FROM Profile WHERE Name='Read Only'];
        User readOnlyUser = new User(
            Alias = 'standt',
            Email = 'ReadOnlyUser@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = userProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'ReadOnlyUser' + DateTime.now().getTime() + '@testorg.com'
        );

		Order__c order = new Order__c();
		order.Description__c = 'Order Test';
		order.Requested_Date__c = Date.today();
		insert order;

		Spare_Part__c sp = new Spare_Part__c();
		sp.Name = 'SP Test';
		sp.Material_Number__c = '238';
		sp.Material_Description__c = 'Desc 238';
		sp.Base_Unit__c = 'PC';
		insert sp;

		Spare_Part_Stock__c stock = new Spare_Part_Stock__c();
		stock.Name = 'Stock Test';
		stock.Available_Quantity__c = 14;
		stock.Spare_Part__c = sp.Id;
		insert stock;

		Order_Operation__c orderOperation = new Order_Operation__c(
            Operation_Text__c = 'orderOpTest',
            Order__c = order.Id
        );
        insert orderOperation;

		Spare_Part_Request__c request = New Spare_Part_Request__c();
		request.Name = 'Request Test';
		request.Order__c = order.Id;
		request.Request_Material_Quantity__c = 180;
		request.Request_Status__c = 'Pending for Approval';
		request.Spare_Part_Stock__c = stock.Id;
		request.Spare_Part__c = sp.Id;
		request.Order_Operation__c = orderOperation.Id;
		insert request;


		List<THOR_ObjectCardDTO> dtos = THOR_OrderRelCmpReqController.retrieveComponentsRequests(order.Id);
		System.assert(dtos.size() == 1, 'Controller did not returned elements');
		System.runAs(readOnlyUser) {
			try{
				List<THOR_ObjectCardDTO> dtosFail = THOR_OrderRelCmpReqController.retrieveComponentsRequests(order.Id);
			}catch(Exception e){
				System.assertEquals(
					'System.AuraHandledException',
					e.getTypeName(),
					'Aura Exception should be thrown when user access is restricted or bad query'
				);
			}
		}
	}
    
    @isTest
    static void testGetCartCount() {
        Order__c order = new Order__c();
		order.Description__c = 'Order Test';
		order.Requested_Date__c = Date.today();
		insert order;

		Spare_Part__c sp = new Spare_Part__c();
		sp.Name = 'SP Test';
		sp.Material_Number__c = '238';
		sp.Material_Description__c = 'Desc 238';
		sp.Base_Unit__c = 'PC';
		insert sp;

		Spare_Part_Stock__c stock = new Spare_Part_Stock__c();
		stock.Name = 'Stock Test';
		stock.Available_Quantity__c = 14;
		stock.Spare_Part__c = sp.Id;
		insert stock;

		Order_Operation__c orderOperation = new Order_Operation__c(
            Operation_Text__c = 'orderOpTest',
            Order__c = order.Id
        );
        insert orderOperation;

		Spare_Part_Request__c request = New Spare_Part_Request__c();
		request.Name = 'Request Test';
		request.Order__c = order.Id;
		request.Request_Material_Quantity__c = 180;
		request.Request_Status__c = 'Draft';
		request.Spare_Part_Stock__c = stock.Id;
		request.Spare_Part__c = sp.Id;
		request.Order_Operation__c = orderOperation.Id;
		insert request;
        
        Integer cartCount;
        Test.startTest();
        cartCount = THOR_OrderRelCmpReqController.getCartCount(order.Id);
        Test.stopTest();
        
        System.assertEquals(1, cartCount);
    }
    
    @isTest
    static void testGetCartCountException() {
        Profile userProfile = [SELECT Id FROM Profile WHERE Name='Read Only'];
        User readOnlyUser = new User(
            Alias = 'standt',
            Email = 'ReadOnlyUser@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Testing',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = userProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'ReadOnlyUser' + DateTime.now().getTime() + '@testorg.com'
        );
        
        Order__c order = new Order__c();
		order.Description__c = 'Order Test';
		order.Requested_Date__c = Date.today();
		insert order;

		Spare_Part__c sp = new Spare_Part__c();
		sp.Name = 'SP Test';
		sp.Material_Number__c = '238';
		sp.Material_Description__c = 'Desc 238';
		sp.Base_Unit__c = 'PC';
		insert sp;

		Spare_Part_Stock__c stock = new Spare_Part_Stock__c();
		stock.Name = 'Stock Test';
		stock.Available_Quantity__c = 14;
		stock.Spare_Part__c = sp.Id;
		insert stock;

		Order_Operation__c orderOperation = new Order_Operation__c(
            Operation_Text__c = 'orderOpTest',
            Order__c = order.Id
        );
        insert orderOperation;

		Spare_Part_Request__c request = New Spare_Part_Request__c();
		request.Name = 'Request Test';
		request.Order__c = order.Id;
		request.Request_Material_Quantity__c = 180;
		request.Request_Status__c = 'Draft';
		request.Spare_Part_Stock__c = stock.Id;
		request.Spare_Part__c = sp.Id;
		request.Order_Operation__c = orderOperation.Id;
		insert request;
        
        Integer cartCount;
        Test.startTest();
        System.runAs(readOnlyUser) {
            try {
                cartCount = THOR_OrderRelCmpReqController.getCartCount(orderOperation.Id);
            } catch (Exception e) {
                System.assertEquals(
					'System.AuraHandledException',
					e.getTypeName(),
					'Aura Exception should be thrown when user access is restricted or bad query'
				);
            }
        }
        Test.stopTest();
    }
}