force-app/main/default/objects/Permit__c.object
<CustomObject>
    <fields>
        <fullName>Permit_Department__c</fullName>
        <label>หน่วยงานออกใบอนุญาต</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Permit_Department</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permit_Topic__c</fullName>
        <label>เรื่องที่ขออนุญาต</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Permit</label>
    <nameField>
        <displayFormat>PL-{00000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Permit_Department.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>กรมการอุตสาหกรรมทหาร</fullName>
    </customValue>
    <customValue>
        <fullName>กรมเจ้าท่า</fullName>
    </customValue>
    <customValue>
        <fullName>กรมทางหลวง</fullName>
    </customValue>
    <customValue>
        <fullName>กรมที่ดิน</fullName>
    </customValue>
    <customValue>
        <fullName>กรมธนารักษ์</fullName>
    </customValue>
    <customValue>
        <fullName>กรมธุรกิจพลังงาน</fullName>
    </customValue>
    <customValue>
        <fullName>กรมธุรกิจพลังงาน (สำนักปลอดภัย)</fullName>
    </customValue>
    <customValue>
        <fullName>กรมธุรกิจพลังงาน (สำนักสำรอง)</fullName>
    </customValue>
    <customValue>
        <fullName>กรมพัฒนาพลังงานทดแทนและอนุรักษ์พลังงาน (พพ.)</fullName>
    </customValue>
    <customValue>
        <fullName>กรมโรงงานอุตสาหกรรม</fullName>
    </customValue>
    <customValue>
        <fullName>กรมสรรพสามิต</fullName>
    </customValue>
    <customValue>
        <fullName>กรมสรรพากร</fullName>
    </customValue>
    <customValue>
        <fullName>การนิคมอุตสาหกรรมแห่งประเทศไทย (กนอ.)</fullName>
    </customValue>
    <customValue>
        <fullName>การไฟฟ้า/ปะปา/เทศบาล</fullName>
    </customValue>
    <customValue>
        <fullName>เทศบาล</fullName>
    </customValue>
    <customValue>
        <fullName>เทศบาล/อื่นๆ</fullName>
    </customValue>
    <customValue>
        <fullName>สำนักงานคณะกรรมการส่งเสริมการลงทุน BOI</fullName>
    </customValue>
    <customValue>
        <fullName>สำนักงานนโยบายแผนและสิ่งแวดล้อม</fullName>
    </customValue>
    <customValue>
        <fullName>สำนักงานพลังงานปรมาณูเพื่อสันติ</fullName>
    </customValue>
    <customValue>
        <fullName>สำนักงานมาตรฐานผลิตภัณฑ์อุตสาหกรรม(สมอ.)</fullName>
    </customValue>
    <customValue>
        <fullName>สำนักงานโยธาธิการและผังเมือง</fullName>
    </customValue>
    <masterLabel>หน่วยงานออกใบอนุญาต</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TC_TRG_CheckPermit.cls
/* Test class for CheckPermit */
@isTest
public class TC_TRG_CheckPermit {

    public static TestMethod void CheckPermit() {
        
        Permit__c Permit = new Permit__c();
        Permit.Permit_Topic__c = 'เทสเรื่องขออนุญาต';
        Permit.Permit_Department__c = 'กรมเจ้าท่า';
        insert(Permit);
        
    }
    
    public static TestMethod void CheckUpdatePermit() {
        
        Permit__c Permit = new Permit__c();
        Permit.Permit_Topic__c = 'วัด';
        Permit.Permit_Department__c = 'กรมเจ้าท่า';
        insert(Permit);
        
        Permit__c existPermit = [select id, Permit_Topic__c from Permit__c where Permit_Topic__c = 'วัด'];

        Test.startTest();
        
        try {
            
            existPermit.Permit_Topic__c = 'วัด';
            existPermit.Permit_Department__c = 'กรมเจ้าท่า';
            
            update(existPermit);
        }
        catch(Exception e) {
        	Boolean expectedExceptionThrown =  e.getMessage().contains('กรุณาเช็ค ' + '**เรื่องที่ขออนุญาติ**' + ' เนื่องจากไม่อนุญาติให้ใข้ ชื่อเรื่องที่ขออนุญาติ ซ้ำกันได') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);        
        }
        
        Test.stopTest();
        
    }
    
}