force-app/main/default/objects/PISUsers__c.object
<CustomObject>
    <fields>
        <fullName>SECTIONS__c</fullName>
        <label>SECTIONS</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PISUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PISUsers</label>
    <nameField>
        <label>UserID</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PTW_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Key__c</fullName>
        <description>Format : Header.Id + Question</description>
        <externalId>true</externalId>
        <label>Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Main_Work_Center__c</fullName>
        <formula>CreatedBy.Main_Work_Center__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Main Work Center</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTW_Header__c</fullName>
        <label>PTW Header</label>
        <referenceTo>PTW_Header__c</referenceTo>
        <relationshipLabel>PTW Answer</relationshipLabel>
        <relationshipName>PTW_Answer</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>PTW_Question_Master__c</referenceTo>
        <relationshipLabel>PTW Answer</relationshipLabel>
        <relationshipName>PTW_Answer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PTW Answer</label>
    <nameField>
        <displayFormat>PTWA-{0000}</displayFormat>
        <label>PTW Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PTW_Header__c.object
<CustomObject>
    <fields>
        <fullName>FormName__c</fullName>
        <label>FormName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Work_Center__c</fullName>
        <formula>Auditor_Name__r.User__r.Main_Work_Center__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Main Work Center</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Agree</fullName>
                </value>
                <value>
                    <fullName>Disagree</fullName>
                </value>
                <value>
                    <fullName>ดำเนินการได้</fullName>
                </value>
                <value>
                    <fullName>หยุดงานชั่วคราว</fullName>
                </value>
                <value>
                    <fullName>หยุดงานถาวร</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PTW_Header</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Clearance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Clearance</label>
        <referenceTo>Work_Clearance__c</referenceTo>
        <relationshipLabel>PTW Header</relationshipLabel>
        <relationshipName>PTW_Header</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PTW Header</label>
    <nameField>
        <displayFormat>PTWH - {0000}</displayFormat>
        <label>PTW Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <recordTypes>
        <fullName>Inspection</fullName>
        <active>true</active>
        <label>Inspection</label>
    </recordTypes>
    <recordTypes>
        <fullName>Verification</fullName>
        <active>true</active>
        <label>Verification</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PTW_Inspection_Report__c.object
<CustomObject>
    <fields>
        <fullName>SECTIONS__c</fullName>
        <formula>IF( OR(Section__c = &quot;QMOS&quot; ,Section__c = &quot;MFOP&quot;),Section__c ,&quot;OPS&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SECTIONS</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>PTW Inspection Report</label>
    <nameField>
        <label>Report Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PTW_Question_Master__c.object
<CustomObject>
    <fields>
        <fullName>Answer_type__c</fullName>
        <label>Answer type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Text Area</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FormName__c</fullName>
        <label>FormName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive_Report__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive Report</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Question__c</fullName>
        <label>Order Question</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>PTW Question Master</label>
    <nameField>
        <displayFormat>PTWQ-{0000}</displayFormat>
        <label>PTW Question Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Clearance__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorized_Signature_UI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Authorized Signature</label>
        <referenceTo>PISUsers__c</referenceTo>
        <relationshipLabel>Work Clearance (Authorized Signature)</relationshipLabel>
        <relationshipName>Work_Clearance7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Authorized_Signature__c</fullName>
        <label>Authorized Signature</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>High_Risk_Work__c</fullName>
        <label>High risk work Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>งานทั่วไป</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>Hot work</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Confined Space</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Crane/Lifting</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Radiation</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Jack Hammer</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>High Pressure Water Jet</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>Digging</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>Work at Height</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <label>Online Stop Leak</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>Non Type Of Work</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Main_Work_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Work Center</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>It must be a valid Main Work Center from Master Map</errorMessage>
            <filterItems>
                <field>Master_Map__c.Type__c</field>
                <operation>equals</operation>
                <value>Main Work Center</value>
            </filterItems>
            <infoMessage>Choose a Main Work Center from Master Map</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Work Clearances</relationshipLabel>
        <relationshipName>Work_Clearances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Safety_Permit1__c</fullName>
        <label>Safety Permit1</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Safety_Permit2__c</fullName>
        <label>Safety Permit2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Safety_Permit3__c</fullName>
        <label>Safety Permit3</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Status__c</fullName>
        <label>System Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Status__c</fullName>
        <label>User Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Clearance_Status__c</fullName>
        <formula>IF(CONTAINS(System_Status__c, &quot;DLFL&quot;), &quot;Delete Flag&quot;,
    IF(CONTAINS(System_Status__c, &quot;REJC&quot;), &quot;Rejected&quot;,
        IF(CONTAINS(System_Status__c, &quot;CLSD&quot;), &quot;Closed&quot;,
            IF(CONTAINS(System_Status__c, &quot;CLSE&quot;), &quot;Closed&quot;,
                IF(CONTAINS(System_Status__c, &quot;INAC&quot;), &quot;Inactive&quot;,
                    IF(CONTAINS(System_Status__c, &quot;INC&quot;), &quot;Inactive&quot;,
                        IF(CONTAINS(System_Status__c, &quot;CRTE&quot;), &quot;Created&quot;,
                            IF(CONTAINS(System_Status__c, &quot;CRET&quot;), &quot;Created&quot;,
                                IF(CONTAINS(System_Status__c, &quot;PREP&quot;), &quot;In Progress&quot;,
                                    IF(CONTAINS(System_Status__c, &quot;CHNG&quot;), &quot;In Progress&quot;, &quot;&quot;)
                                )
                            )
                        )
                    )
                )
            )
        )
    )
)</formula>
        <label>Work Clearance Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Clearance__c</fullName>
        <externalId>true</externalId>
        <label>Work Clearance</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Detail__c</fullName>
        <label>Work Detail</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Work Clearance</label>
    <nameField>
        <label>Work Clearance Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ODM_JobScheduleForReportTest.cls
@isTest
public class ODM_JobScheduleForReportTest {

    public static String CRON_EXP = '0 0 0 31 12 ? 2024';

    @testSetup
    static void makeData(){
        Id RecordTypeIdVeri = Schema.SObjectType.PTW_Header__c.getRecordTypeInfosByName().get('Verification').getRecordTypeId();
        Id RecordTypeIdIns = Schema.SObjectType.PTW_Header__c.getRecordTypeInfosByName().get('Inspection').getRecordTypeId();
        // Id idReport = [SELECT Id FROM RecordType WHERE sObjectType='Report__c '].Id;

        Datetime yesterday = Datetime.now().addDays(-1);

        //User
        User user1 = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Non Operation'].Id,
            LastName = 'thaninthon',
            Email = 'thaninthon@thaioilgroup.com',
            Username = 'thaninthon@thaioilgroup.com.icr',
            CompanyName = 'Thaioil',
            Alias = 'test',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Main_Work_Center__c = 'OPS-TOC5'
        );
        insert user1;

        //PISUsers
        PISUsers__c pisUser1 = new PISUsers__c(
            User__c = user1.id,
            SECTIONS__c = 'MFOC'
        );
        insert pisUser1;
        
        //User
        User user2 = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Non Operation'].Id,
            LastName = 'thaninthonnn',
            Email = 'thaninthonnn@thaioilgroup.com',
            Username = 'thaninthonnn@thaioilgroup.com.icr',
            CompanyName = 'Thaioil',
            Alias = 'test',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Main_Work_Center__c = 'OPS-TOC3'
        );
        insert user2;

        //PISUsers
        PISUsers__c pisUser2 = new PISUsers__c(
            User__c = user2.id,
            SECTIONS__c = 'MFOC'
        );
        insert pisUser2;

        Work_Clearance__c wc1 = new Work_Clearance__c(
            Name = '9012341234',
            Integration_Status__c = 'Success',
            System_Status__c = 'CRTE',
            User_Status__c = 'WCCL',
            Area__c = 'P1',
            Work_Detail__c = 'Test',
            Safety_Permit1__c = 'Test',
            Safety_Permit2__c = 'Test',
            Safety_Permit3__c = 'Test',
            High_risk_work__c = '1',
            Authorized_Signature_UI__c = pisUser1.id,
            Authorized_Signature__c = '00001185' //Authorized_Signature__c
            // Work_Clearance_Status__c = 'Created;In Progress'
            // CreatedDate = TODAY
        );
        insert wc1;
        // Test.setCreatedDate(wc1.Id, yesterday);

        Work_Clearance__c wc2 = new Work_Clearance__c(
        	Name = '9012341236',
			Integration_Status__c = 'Success',
			System_Status__c = 'PREP',
			User_Status__c = 'WCCL',
            Area__c = 'P1',
            Work_Detail__c = 'Test',
            Safety_Permit1__c = 'Test',
            Safety_Permit2__c = 'Test',
            Safety_Permit3__c = 'Test',
            High_risk_work__c = '1',
            Authorized_Signature_UI__c = pisUser2.id,
            Authorized_Signature__c = '00001186'
        );
        insert wc2;
        // Test.setCreatedDate(wc2.Id, yesterday);

		PTW_Question_Master__c ptwMaster = new PTW_Question_Master__c(
        	FormName__c = 'Inspection',
            Version__c = '1',
            Question__c = 'Status',
            Section__c = '1',
            Order_Question__c = 1,
            Answer_type__c = 'Text',
            Value__c = '',
 			Description__c = 'Test',
            IsActive_Report__c = true
        );
        insert ptwMaster;

        PTW_Header__c ptwHeader = new PTW_Header__c(
            RecordTypeId = RecordTypeIdIns,
        	FormName__c = 'Inspection',
            Version__c = '1',
            Key__c = 'Key',
            Work_Clearance__c = wc1.id,
            Status__c = 'หยุดงานถาวร	'
        );
        insert ptwHeader;

        PTW_Header__c ptwHeader2 = new PTW_Header__c(
            RecordTypeId = RecordTypeIdVeri,
        	FormName__c = 'Verification',
            Version__c = '1',
            Key__c = 'Keyyy',
            Work_Clearance__c = wc2.id,
            Status__c = 'Agree	'
        );
        insert ptwHeader2;
        
        // insert new PTW_Answer__c(
        //     PTW_Header__c = ptwHeader.id,
        //     Key__c = 'Key',
        //     Question_Text__c = 'Area'
        // );   
        
        // /** Setup format date */
        // Integer year = 2022;
        // Integer month = 9;
        // Integer day = 1;
        // Date dt = Date.newInstance(year, month, day); 

        // PTW_Inspection_Report__c reportWC1 = new PTW_Inspection_Report__c(
        //     WC_Created_Date__c = Date.valueOf(dt),
        //     // Main_Work_Center_Work_Clearances__c = 'MFOP',
        //     Number_of_Work_Clearances__c = 15
        // );
        // insert reportWC1;
        // PTW_Inspection_Report__c reportINS1 = new PTW_Inspection_Report__c(
        //     WC_Created_Date__c = Date.valueOf(dt).addDays(+40),
        //     Main_Work_Center_Permit_to_work__c = 'OPS-TOC3' ,                         /*OPS-TOC3*/
        //     Type_of_Permit_to_Work__c =  'Inspection',   /*inspection*/
        //     Status_of_Permit_to_Work__c = 'หยุดงานถาวร',                               /*หยุดงานถาวร*/
        //     Section__c = 'MFOP',                                                    /*MFOP*/
        //     Number_of_Work_Clearances__c = 15                         /*4*/   
        // );
        // insert reportINS1;
    }


    static testmethod void testScheduledJob() {
        System.debug('Query >'+ [SELECT  
                Authorized_Signature_UI__r.User__r.Main_Work_Center__c , 
                CreatedDate, Work_Clearance_Status__c,Authorized_Signature__c
                FROM Work_Clearance__c ]);

        Test.startTest();
        String jobId = System.schedule('ODM_JobScheduleForReport',CRON_EXP,new ODM_JobScheduleForReport());
        System.assert(jobId != '', 'Tasks exist before job has run');
        Test.stopTest();
    }
}