force-app/main/default/objects/Safety_Permit__c.object
<CustomObject>
    <fields>
        <fullName>Expired_Date_1__c</fullName>
        <label>Expired Date 1</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expired_Date_2__c</fullName>
        <label>Expired Date 2</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expired_Date_3__c</fullName>
        <label>Expired Date 3</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Permit_to_Work_Date__c</fullName>
        <label>Permit to Work Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plant_Section__c</fullName>
        <label>Plant Section</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Detail__c</fullName>
        <label>Work Detail</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Safety Permit</label>
    <nameField>
        <label>Safety Permit Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Clearance__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorized_Date_UI__c</fullName>
        <label>Authorized Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Authorized_Time_UI__c</fullName>
        <label>Authorized Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Extend_Date__c</fullName>
        <label>Extend Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Extend_Time_Flag_Formula__c</fullName>
        <formula>IF( Extend_Time_Flag__c == &apos;X&apos;, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Extend Time Flag Formula</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Extend_Time_To_UI__c</fullName>
        <label>Extend Time To</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Extend_Time__c</fullName>
        <label>Extend Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>High_Risk_Work__c</fullName>
        <label>High risk work Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>งานทั่วไป</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>Hot work</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Confined Space</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Crane/Lifting</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Radiation</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>Jack Hammer</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>High Pressure Water Jet</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>Digging</label>
                </value>
                <value>
                    <fullName>8</fullName>
                    <label>Work at Height</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <label>Online Stop Leak</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>Non Type Of Work</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plant_Section__c</fullName>
        <formula>IF(ISBLANK(Order__r.Plant_Section__c), Notification__r.Plant_Section__c, Order__r.Plant_Section__c)</formula>
        <label>Plant Section</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Clearance_Status__c</fullName>
        <formula>IF(CONTAINS(System_Status__c, &quot;DLFL&quot;), &quot;Delete Flag&quot;,
    IF(CONTAINS(System_Status__c, &quot;REJC&quot;), &quot;Rejected&quot;,
        IF(CONTAINS(System_Status__c, &quot;CLSD&quot;), &quot;Closed&quot;,
            IF(CONTAINS(System_Status__c, &quot;CLSE&quot;), &quot;Closed&quot;,
                IF(CONTAINS(System_Status__c, &quot;INAC&quot;), &quot;Inactive&quot;,
                    IF(CONTAINS(System_Status__c, &quot;INC&quot;), &quot;Inactive&quot;,
                        IF(CONTAINS(System_Status__c, &quot;CRTE&quot;), &quot;Created&quot;,
                            IF(CONTAINS(System_Status__c, &quot;CRET&quot;), &quot;Created&quot;,
                                IF(CONTAINS(System_Status__c, &quot;PREP&quot;), &quot;In Progress&quot;,
                                    IF(CONTAINS(System_Status__c, &quot;CHNG&quot;), &quot;In Progress&quot;, &quot;&quot;)
                                )
                            )
                        )
                    )
                )
            )
        )
    )
)</formula>
        <label>Work Clearance Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Clearance__c</fullName>
        <externalId>true</externalId>
        <label>Work Clearance</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Detail__c</fullName>
        <label>Work Detail</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Work Clearance</label>
    <nameField>
        <label>Work Clearance Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/WAP_ClearanceDashboardExcelController.cls
/* 
 * Author Softever
 */

public with sharing class WAP_ClearanceDashboardExcelController {

    public string excelName {get;set;}
    public string year {get;set;}
    public string area {get;set;}
    public date startDate {get;set;}
    public date endDate {get;set;}
    public date todayDate {get;set;}
    
    public List<WAPClearanceDashboardWrapper> CDWs {get;set;}

    public class WAPClearanceDashboardWrapper {
        public string clearanceNo {get;set;}
        public date workingDate {get;set;}
        public time workingTime {get;set;}
        public string typeOfWork {get;set;}
        public string area {get;set;}
        public string requestExtended {get;set;}
        public date extendedDate {get;set;}
        public time extendedTime {get;set;}
        public time extendingTime {get;set;}
        public string status {get;set;}
    }

    public void OnloadExcel() {
    
        excelName = ApexPages.currentPage().getParameters().get('excelName');
        year = ApexPages.currentPage().getParameters().get('year');
        area = ApexPages.currentPage().getParameters().get('area');
        startDate = Date.ValueOf(ApexPages.currentPage().getParameters().get('startDate'));
        endDate = Date.ValueOf(ApexPages.currentPage().getParameters().get('endDate'));
        
        todayDate = date.today();
        
        Set<string> areas = new Set<string>();
        List<Work_Clearance__c> WorkClearances = new List<Work_Clearance__c>();
        
        CDWs = new List<WAPClearanceDashboardWrapper>();
        
        if(excelName == 'daily') {
        
            string query = 'select id, name, Area__c, Authorized_Date_UI__c, Authorized_Time_UI__c, High_Risk_Work__c, Extend_Time_Flag_Formula__c, Extend_Date__c, Extend_Time__c, ' + 
                        'Extend_Time_To_UI__c, Work_Clearance_Status__c from Work_Clearance__c';
        
            //filter.startDate
            query = query + ' WHERE Authorized_Date_UI__c >=: startDate';
            
            //filter.endDate
            query = query + ' AND Authorized_Date_UI__c <=: endDate';
            
            if(area.toLowerCase() != 'all') {
                query = query + ' AND Area__c =: area';
            }
            else {
                query = query + ' AND Area__c != null';
            }
            
            WorkClearances = database.query(query + ' order by area__c asc');
            
            if(WorkClearances.size() > 0) {
                for(Work_Clearance__c WC : WorkClearances) {
                    
                    WAPClearanceDashboardWrapper CDW = new WAPClearanceDashboardWrapper();
                    CDW.clearanceNo = WC.Name;
                    CDW.workingDate = WC.Authorized_Date_UI__c;
                    CDW.workingTime = WC.Authorized_Time_UI__c;
                    CDW.typeOfWork = WC.High_Risk_Work__c;
                    CDW.area = WC.Area__c;
                    
                    if(WC.Extend_Time_Flag_Formula__c) {
                        CDW.requestExtended = 'มี';
                    }
                    else if(!WC.Extend_Time_Flag_Formula__c) {
                        CDW.requestExtended = 'ไม่มี';
                    }
                    
                    CDW.extendedDate = WC.Extend_Date__c;
                    CDW.extendedTime = WC.Extend_Time_To_UI__c;
                    CDW.extendingTime = WC.Extend_Time_To_UI__c;
                    CDW.status = WC.Work_Clearance_Status__c;
                    CDWs.add(CDW);
                    
                }
            }
            
        }
        else if(excelName == 'detail') {
        
            string query = 'select id, name, Area__c, Authorized_Date_UI__c, Authorized_Time_UI__c, High_Risk_Work__c, Extend_Time_Flag_Formula__c, Extend_Date__c, Extend_Time__c, ' + 
                        'Extend_Time_To_UI__c, Work_Clearance_Status__c from Work_Clearance__c';
        
            //filter.startDate
            query = query + ' WHERE Authorized_Date_UI__c >=: startDate';
            
            //filter.endDate
            query = query + ' AND Authorized_Date_UI__c <=: endDate';
            
            query = query + ' AND Area__c != null';
            
            WorkClearances = database.query(query + ' order by area__c asc');
            
            if(WorkClearances.size() > 0) {
                for(Work_Clearance__c WC : WorkClearances) {
                    
                    WAPClearanceDashboardWrapper CDW = new WAPClearanceDashboardWrapper();
                    CDW.clearanceNo = WC.Name;
                    CDW.workingDate = WC.Authorized_Date_UI__c;
                    CDW.workingTime = WC.Authorized_Time_UI__c;
                    CDW.typeOfWork = WC.High_Risk_Work__c;
                    CDW.area = WC.Area__c;
                    
                    if(WC.Extend_Time_Flag_Formula__c) {
                        CDW.requestExtended = 'มี';
                    }
                    else if(!WC.Extend_Time_Flag_Formula__c) {
                        CDW.requestExtended = 'ไม่มี';
                    }
                    
                    CDW.extendedDate = WC.Extend_Date__c;
                    CDW.extendedTime = WC.Extend_Time_To_UI__c;
                    CDW.extendingTime = WC.Extend_Time_To_UI__c;
                    CDW.status = WC.Work_Clearance_Status__c;
                    CDWs.add(CDW);
                    
                }
            }
            
        }
        else if(excelName == 'clearance') {
        
            string query = 'select id, name, Area__c, Authorized_Date_UI__c, Authorized_Time_UI__c, High_Risk_Work__c, Extend_Time_Flag_Formula__c, Extend_Date__c, Extend_Time__c, ' + 
                        'Extend_Time_To_UI__c, Work_Clearance_Status__c from Work_Clearance__c';
        
            integer filterYear = Integer.ValueOF(year);
            
            query = query + ' WHERE Authorized_Date_UI__c != null AND CALENDAR_YEAR(Authorized_Date_UI__c) =: filterYear';
            
            query = query + ' AND Area__c != null';
            system.debug(query);
            WorkClearances = database.query(query + ' order by area__c asc');
            
            if(WorkClearances.size() > 0) {
                for(Work_Clearance__c WC : WorkClearances) {
                    
                    WAPClearanceDashboardWrapper CDW = new WAPClearanceDashboardWrapper();
                    CDW.clearanceNo = WC.Name;
                    CDW.workingDate = WC.Authorized_Date_UI__c;
                    CDW.workingTime = WC.Authorized_Time_UI__c;
                    CDW.typeOfWork = WC.High_Risk_Work__c;
                    CDW.area = WC.Area__c;
                    
                    if(WC.Extend_Time_Flag_Formula__c) {
                        CDW.requestExtended = 'มี';
                    }
                    else if(!WC.Extend_Time_Flag_Formula__c) {
                        CDW.requestExtended = 'ไม่มี';
                    }
                    
                    CDW.extendedDate = WC.Extend_Date__c;
                    CDW.extendedTime = WC.Extend_Time_To_UI__c;
                    CDW.extendingTime = WC.Extend_Time_To_UI__c;
                    CDW.status = WC.Work_Clearance_Status__c;
                    CDWs.add(CDW);
                    
                }
            }
            
        }
    
    }
    
    //assign DTO
    private static WAP_DTO.SafetyPermitReportDTO assignToSafetyPermitReportDTO(Safety_Permit__c SP) {
        
        WAP_DTO.SafetyPermitReportDTO SafetyPermit = new WAP_DTO.SafetyPermitReportDTO();
        SafetyPermit.Id = SP.Id;
        SafetyPermit.no = SP.name;
        SafetyPermit.detail = SP.Work_Detail__c;
        SafetyPermit.workingArea = SP.Plant_Section__c;
        SafetyPermit.startDate = SP.Permit_to_Work_Date__c;
        SafetyPermit.endDate = SP.Expired_Date_1__c;
        SafetyPermit.firstExtendDate = SP.Expired_Date_1__c;
        SafetyPermit.secondExtendDate = SP.Expired_Date_2__c;
        SafetyPermit.thirdExtendDate = SP.Expired_Date_3__c;
            
        return SafetyPermit;
        
    }

}