force-app/main/default/objects/THOR_Form_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eqcc_Step_Id__c</fullName>
        <label>Eqcc Step Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Code__c</fullName>
        <label>Form Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Json_String__c</fullName>
        <label>Json String</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Step__c</fullName>
        <label>Step</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>THOR Form Mapping</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>THOR Form Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/THOR_FormMappingLabelController.cls
public with sharing class THOR_FormMappingLabelController {
    @AuraEnabled
    public static void updateFormMapping(String jsonString, String formCode, String stepId, String count) {
        List<THOR_Form_Mapping__c> formMappings = [SELECT Id, Json_String__c, Count__c, Step__c FROM THOR_Form_Mapping__c WHERE Eqcc_Step_Id__c =: stepId LIMIT 1];
        if(formMappings.size() > 0) {
            formMappings.get(0).Json_String__c = jsonString;
            formMappings.get(0).Count__c = count;
            formMappings.get(0).Step__c = '1';
            update formMappings;
        }
        else {
            THOR_Form_Mapping__c mapping = new THOR_Form_Mapping__c();
            mapping.Form_Code__c = formCode;
            mapping.Json_String__c = jsonString;
            mapping.Eqcc_Step_Id__c = stepId;
            mapping.Count__c = count;
            mapping.Step__c = '1';
            insert mapping;
        }
        
    }

    @AuraEnabled
    public static string getCount(String stepId){
        List<THOR_Form_Mapping__c> formMappings = [SELECT Id, Json_String__c, Count__c FROM THOR_Form_Mapping__c WHERE Eqcc_Step_Id__c =: stepId LIMIT 1];
        if(formMappings.size() > 0) {
            return formMappings.get(0).Count__c;
        }
        return '';
    }
}